### ISSUE TITLE
Duplicate method createCopy() in type ChatComponentScore and ChatComponentSelector

### ISSUE THREAD

**Issue by tambry** [ModCoderPack/MCPBot-Issues#10]
As of 16. February 7PM GMT decompiled Minecraft on the latest (Semi-Live) mappings doesn't recompile.

**Issue affects:** Client and Server
**Affected class(es):** ChatComponentScore and ChatComponentSelector
**Affected method(s):** _createCopy()_
**Affected Searge name(s):** _func_179991_h_ and _func_179996_i_
**Eclipse error message(s):** "Duplicate method _createCopy()_ in type ChatComponentScore",
                                        "Duplicate method _createCopy()_ in type ChatComponentSelector"
**Person(s) who seem(s) to have caused it:** minecrell

**Comment by bspkrs** [comment]
This is due to a limitation in the scope check for naming methods... there isn't an easy way to determine if a name change would cause an issue due to methods that return different types in the same hierarchy.  I'll rename the affected methods.

**Comment by bspkrs** [comment]
Actually, this is really due to checking against method descriptors in the naming dupe check rather than method signatures. I'll fix the names AND the dupe check.

**Comment by bspkrs** [comment]
Names are undone.

**Comment by tambry** [comment]
Since this seems to be fixed I'll close the issue.
