### ISSUE TITLE
ServerConfigurationManager#sendMessageToTeamOrEvryPlayer

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#100]
This method (`func_177452_b`) is currently `sendMessageToTeamOrEvryPlayer`, but has a typo. I suggest `sendMessageToTeamOrAllPlayers`

**Comment by matthewprenger** [comment]
Fixed:
sendMessageToTeamOrEvryPlayer -> sendMessageToTeamOrAllPlayers
