### ISSUE TITLE
net.minecraft.block.properties.PropertyHelper -> AbstractProperty

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#102]
Similar to https://github.com/ModCoderPack/MCPBot-Issues/issues/76 - this isn't a a helper, it's an abstract implementation.

**Comment by gabizou** [comment]
To keep in practice, probably better to name it `PropertyBase`.

**Comment by kashike** [comment]
@gabizou https://github.com/ModCoderPack/MCPBot-Issues/issues/46#issuecomment-188435102
