### ISSUE TITLE
MobSpawnerBaseLogic$WeightedRandomMinecart

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#105]
Not sure how that ever got its name, but inner class `MobSpawnerBaseLogic$WeightedRandomMinecart` (obf 1.8.9: `add$a`) is the weighted entries describing what sorts of entity the mob spawner can spawn. It has nothing to do with minecarts and can describe any sort of entity. I suggested `WeightedRandomSpawnerEntry` or `WeightedRandomMob`

**Comment by diesieben07** [comment]
https://github.com/ModCoderPack/MCPBot-Issues/issues/49
