### ISSUE TITLE
 net.minecraft.util.MovingObjectPosition

### ISSUE THREAD

**Issue by grondag** [ModCoderPack/MCPBot-Issues#106]
MovingObjectPosition seems to do a mix of things not consistent with the name.  Haven't got an idea that seems much better yet.

Maybe MovingObjectAccess?  Nah... still bad.

**Comment by simon816** [comment]
It was renamed to `RayTraceResult` https://github.com/ModCoderPack/MCPBot-Issues/issues/87

**Comment by kashike** [comment]
This is a duplicate, forgot to close it?

**Comment by grondag** [comment]
Sorry, didn't think to check.  RayTraceResult works. Closing.
