### ISSUE TITLE
Rename C07PacketPlayerDigging.getStatus() to getAction()

### ISSUE THREAD

**Issue by gabizou** [ModCoderPack/MCPBot-Issues#107]
A lot of the packet getters for their `Action` enum states are called `getStatus()` and it's rather awkward that you're calling `getStatus()` but getting an `Action` back. I would suggest renaming either the method to be `getAction()` or renaming the enums to `Status` to mesh properly.

Mostly opening this to have them potentially renamed for 1.9's update/release instead of renaming them in 1.8.9.

**Comment by LexManos** [comment]
Action will stay Action, rename the functions.

**Comment by matthewprenger** [comment]
Fixed:
func_180762_c: getStatus -> getAction
field_149508_e: status -> action
field_179719_b: status -> action
