### ISSUE TITLE
StructureBoundingBox

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#109]
The name for this class is misleading - it's used in more places than just structures, while structures are the primary user.

I suggest `MutableBoundingBox`, or similar.

**Comment by LexManos** [comment]
It's only used in structures... What are you referring to?
I'm going to keep it as is for 1.9, We may revisit it for 1.10

**Comment by kashike** [comment]
`net.minecraft.world.WorldServer#getPendingBlockUpdates`
`net.minecraft.world.WorldServer#func_175712_a`

**Comment by kashike** [comment]
`func_175711_a` (`isAreaLoaded`)
`func_175639_b` (`isAreaLoaded`)

**Comment by kashike** [comment]
- [x] `net/minecraft/world/gen/structure/StructureBoundingBox` → `net/minecraft/util/math/MutableBoundingBox`
