### ISSUE TITLE
Compression threshold

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#111]
`threshold` is typo'd as `treshold`:
- `func_179303_a`: `setCompressionTreshold` -> `setCompressionThreshold`
- `func_179289_a`: `setCompressionTreshold` -> `setCompressionThreshold`
- `func_179299_a`: `setCompressionTreshold` -> `setCompressionThreshold`
- `field_179304_b`: `treshold` -> `threshold`
- `field_179301_c`: `treshold` -> `threshold`
- `p_i46006_1_`: `treshold` -> `threshold`
- `p_179303_1_`: `treshold` -> `threshold`
- `p_179289_1_`: `treshold` -> `threshold`
- `p_i46005_1_`: `treshold` -> `threshold`
- `p_179299_1_`: `treshold` -> `threshold`

**Comment by matthewprenger** [comment]
Fixed:
`func_179303_a`: `setCompressionTreshold` -> `setCompressionThreshold`
`func_179289_a`: `setCompressionTreshold` -> `setCompressionThreshold`
`func_179299_a`: `setCompressionTreshold` -> `setCompressionThreshold`
`field_179304_b`: `treshold` -> `threshold`
`field_179301_c`: `treshold` -> `threshold`
`p_i46006_1_`: `treshold` -> `thresholdIn`
`p_179303_1_`: `treshold` -> `thresholdIn`
`p_179289_1_`: `treshold` -> `threshold`
`p_i46005_1_`: `treshold` -> `thresholdIn`
`p_179299_1_`: `treshold` -> `thresholdIn`
