### ISSUE TITLE
Organize net.minecraft.util package

### ISSUE THREAD

**Issue by Minecrell** [ModCoderPack/MCPBot-Issues#113]
The `util` package contains a lot of classes that don't really fit into another one. However, when looking closer a lot of them could be grouped together in separate packages for better organization:

- chat related classes -> #110?
- `util.FoodStats` -> `entity.player.FoodStats` (or `entity.FoodStats` although it is really only used for players, maybe `PlayerFoodStats`?)
- `util.EntitySelectors` -> `entity.EntitySelectors` (also see #97)
- `entity.damage`:
  - `DamageSource`
  - `EntityDamageSource`
  - `EntityDamageSourceIndirect`
  - `CombatTracker`
  - `CombatEntry`
- `math` or `util.math`:
  - `AxisAlignedBB`
  - `BlockPos`
  - `Cartesian`
  - `MathHelper`
  - `Vec3` (also see #114)
  - `Vec3i`
  - `Vec4b`
  - `Rotations` (also see #114)
  - `MovingObjectPosition`?
- `client.math` or `client.util.math` (could also put them into `math` or `util.math` but they're really just available on the client so that would be probably clearer, similar like there is already a `client.util` package):
  - `Vector3d` (also see #114)
  - `Matrix4f`
- `CryptManager` -> `network`? Would be probably better together with `NettyEncryptingDecoder` etc.
- `registry`
  - `IRegistry`
  - `RegistryDefaulted`
  - `RegistryNamespaced`
  - `RegistryNameSpacedDefaultedByKey`
  - `RegistrySimple`
  - `ResourceLocation`
  - `init.Blocks`, `init.Items` and `init.Bootstrap` may also fit into that package
- `crash`
  - `ReportedException` - Only used together with crash reports (takes a crash report parameter)
- `util.json`
  - `EnumTypeAdapterFactory`
  - `IJsonSerializable`
  - `JsonSerializableSet`
  - `JsonUtils`
  - `TupleIntJsonSerializable`
- `StatCollector`, `StringTranslate`, see #116 

This is just a suggestion to make everything more organized. It would break a lot of things, but maybe a major update is a good chance to clean everything a bit up.

**Comment by grondag** [comment]
Why put Vector3d and Matrix4f in a client package?  Yes, that is current usage and potential use cases on the server may be less common, but is there any reason that can't be used server-side?

**Comment by kashike** [comment]
They aren't available on the server.

**Comment by LexManos** [comment]
1.9:
net/minecraft/util/Rotations -> net/minecraft/util/math/Rotations
net/minecraft/util/Vec3i -> net/minecraft/util/Vec3i
net/minecraft/util/Vec3d -> net/minecraft/util/Vec3d
net/minecraft/util/Vec4b -> net/minecraft/util/Vec4b
net/minecraft/util/AxisAlignedBB -> net/minecraft/util/math/AxisAlignedBB
net/minecraft/util/RayTraceResult -> net/minecraft/util/math/RayTraceResult
net/minecraft/util/BlockPos -> net/minecraft/util/math/BlockPos
net/minecraft/util/Cartesian -> net/minecraft/util/math/Cartesian
net/minecraft/util/MathHelper -> net/minecraft/util/math/MathHelper

net/minecraft/util/IRegistry -> net/minecraft/util/registry/IRegistry
net/minecraft/util/RegistrySimple -> net/minecraft/util/registry/RegistrySimple
net/minecraft/util/RegistryNamespaced -> net/minecraft/util/registry/RegistryNamespaced
net/minecraft/util/RegistryNamespacedDefaultedByKey -> net/minecraft/util/registry/RegistryNamespacedDefaultedByKey
net/minecraft/util/RegistryDefaulted -> net/minecraft/util/registry/RegistryDefaulted

The rest of them need to be thought through more Maybe better names/packages. For 1.10.

**Comment by kashike** [comment]
@LexManos Were the `Vec` classes moved to `math`, or did they stay? There's no difference in your above comment.

**Comment by LexManos** [comment]
Vec3 -> Vec3d
