### ISSUE TITLE
Vector class names

### ISSUE THREAD

**Issue by Minecrell** [ModCoderPack/MCPBot-Issues#114]
There are a few confusingly named vector classes in the `util` package (also see #113):
- `Vec3` should be probably `Vec3d` for consistence with the other vectors (`Vec3i` and `Vec4b`)
- `Vector3d` should be something like `MutableVec3d` (basically a mutable version of `Vec3`, client-only)
- `Rotations` is essentially a `Vec3f`. While it is primarily used for rotations, the class itself is not related to rotations at all.

**Comment by LexManos** [comment]
1.9:
net/minecraft/util/Vec3 -> Vec3d
net/minecraft/util/Matrix4f -> net/minecraft/client/renderer/Matrix4f
net/minecraft/util/Vector3d -> net/minecraft/client/renderer/Vector3d

Going to keep Rotations named that for now.
