### ISSUE TITLE
theReportedExceptionCrashReport -> crashReport

### ISSUE THREAD

**Issue by Minecrell** [ModCoderPack/MCPBot-Issues#115]
I suggest renaming the field `ReportedException.theReportedExceptionCrashReport` (`field_71576_a`) to something like `crashReport` because the other parts are pretty much redundant and clear because it is part of the `ReportedException` class.

**Comment by matthewprenger** [comment]
Fixed:
`field_71576_a`: `theReportedExceptionCrashReport` -> `crashReport`

It's a private field, so no damage in renaming it.
