### ISSUE TITLE
StatCollector -> Translations

### ISSUE THREAD

**Issue by Minecrell** [ModCoderPack/MCPBot-Issues#116]
`StatCollector` is more like an utility class for accessing the default translations, so it would be better called as something like `Translations`.

Together with #110 it would probably also make sense to move it together with `StringTranslate` to `text` or `text.translation`

**Comment by LexManos** [comment]
1.9:
net/minecraft/util/StatCollector -> net/minecraft/util/text/translation/I18n
net/minecraft/util/StringTranslate -> net/minecraft/util/text/translation/LanguageMap
