### ISSUE TITLE
PingResponseHandler -> LegacyPingHandler

### ISSUE THREAD

**Issue by Minecrell** [ModCoderPack/MCPBot-Issues#117]
`PingResponseHandler` is only used for sending responses for clients using the older Minecraft protocols (before 1.7). The actual code handling the server ping code for all modern clients is `NetHandlerStatusServer` so this can easily cause confusion.

Therefore I suggest calling it something like `LegacyPingHandler` which is similar to the name on the Netty pipeline (`legacy_query`).

**Comment by LexManos** [comment]
net/minecraft/network/PingResponseHandler -> LegacyPingHandler
