### ISSUE TITLE
ServerStatusResponse field/method names

### ISSUE THREAD

**Issue by Minecrell** [ModCoderPack/MCPBot-Issues#118]
##### Updated method/field renames:

**Changes for class names:**
- `field_151324_b` (`playerCount`) -> `players`
- `func_151318_b` (`getPlayerCountData`) -> `getPlayers`
- `func_151319_a` (`setPlayerCountData`) -> `setPlayers`
- `p_151319_1_` (`countData`) -> `playersIn`
- `field_151325_c` (`protocolVersion`) -> `version`
- `func_151322_c` (`getProtocolVersionInfo`) -> `getVersion`
- `func_151321_a` (`setProtocolVersionInfo`) -> `setVersion`
- `p_151321_1_` (`protocolVersionData`) -> `versionIn`

**Other suggested changes:**
- `func_151317_a` (`getServerDescription`) -> `getDescription` (`Server` is redundant, already included in class name)
- `func_151315_a` (`setServerDescription`) -> `setDescription`
- `field_151326_a` (`serverMotd`) -> `description` (Consistency with getter/setter)
- `p_151315_1_` (`motd`) -> `descriptionIn`
- `field_151334_b` (`onlinePlayerCount`) -> `onlinePlayers` (Consistency with `maxPlayers`, other option would be changing `maxPlayers`)
- `func_151333_b` (`getOnlinePlayerCount`) -> `getOnlinePlayers`

---

The inner classes in `ServerStatusResponse` use unnecessary long class names which could be shortened a lot because of the context that is already implied by the enclosing class. I suggest the following new names:

- `PlayerCountData` -> `ServerStatusResponse.Players`: Does also contain a player list, so not only related to the player count.
  - field `playerCount` -> `players`
  - `getPlayerCountData` -> `getPlayers`
  - `setPlayerCountData` -> `setPlayers`
  - `PlayerCountData.getOnlineCount` -> `getOnlinePlayers()` similar to `getMaxPlayers` (or rename `getMaxPlayers`)
    - field `PlayerCountData.onlineCount` -> `onlinePlayers`
- `MinecraftProtocolVersionIdentifier` -> `Version` or `Protocol` (keep in mind at the end it will be `ServerStatusResponse.Version`):
  - eventually field `protocolVersion` -> `version`
- `serverDescription` / `motd` -> `description`: Description is the internal name that is used for this part of the status response, `motd` is old and `serverMotd` is redundant because that is included in the class name, it is always coming from the server.
  - field `serverMotd` -> `description`
  - `getServerDescription` -> `getDescription`
  - `setServerDescription` -> `setDescription`
    - parameter `motd` -> `descriptionIn`

**Comment by LexManos** [comment]
PlayerCountData -> Players
MinecraftProtocolVersionIdentifier -> Version

**Comment by Minecrell** [comment]
Any chance to get the other mapping changes of this in? The class names were changed but the method names still use the older class names:

**Changes for class names:**
- `field_151324_b` (`playerCount`) -> `players`
- `func_151318_b` (`getPlayerCountData`) -> `getPlayers`
- `func_151319_a` (`setPlayerCountData`) -> `setPlayers`
- `p_151319_1_` (`countData`) -> `playersIn`
- `field_151325_c` (`protocolVersion`) -> `version`
- `func_151322_c` (`getProtocolVersionInfo`) -> `getVersion`
- `func_151321_a` (`setProtocolVersionInfo`) -> `setVersion`
- `p_151321_1_` (`protocolVersionData`) -> `versionIn`

**Other suggested changes:**
- `func_151317_a` (`getServerDescription`) -> `getDescription` (`Server` is redundant, already included in class name)
- `func_151315_a` (`setServerDescription`) -> `setDescription`
- `field_151326_a` (`serverMotd`) -> `description` (Consistency with getter/setter)
- `p_151315_1_` (`motd`) -> `descriptionIn`
- `field_151334_b` (`onlinePlayerCount`) -> `onlinePlayers` (Consistency with `maxPlayers`, other option would be changing `maxPlayers`)
- `func_151333_b` (`getOnlinePlayerCount`) -> `getOnlinePlayers`

**Comment by matthewprenger** [comment]
`field_151324_b`: `playerCount` -> `players`
`func_151318_b`: `getPlayerCountData` -> `getPlayers`
`func_151319_a`: `setPlayerCountData` -> `setPlayers`
`p_151319_1_`: `countData` -> `playersIn`
`field_151325_c`: `protocolVersion` -> `version`
`func_151322_c`: `getProtocolVersionInfo` -> `getVersion`
`func_151321_a`: `setProtocolVersionInfo` -> `setVersion`
`p_151321_1_`: `protocolVersionData` -> `versionIn`
`field_151326_a`: `serverMotd` -> `description`
`p_151315_1_`: `motd` -> `descriptionIn`

Don't really see a strong reason to make changing the other 4 worth it.

**Comment by Minecrell** [comment]
@matthewprenger IMO, consistency is important, so if you change the field from `serverMotd` to `description`, you should also change the getter from `getServerDescription` to `getDescription`
