### ISSUE TITLE
server.management.LowerStringMap -> util.LowerStringMap

### ISSUE THREAD

**Issue by Minecrell** [ModCoderPack/MCPBot-Issues#120]
Not sure how this has found its way into the `server.management` package. It's just a custom map implementation and should be in `util` like the others. It's only used inside the `ai` package:

![](http://i.imgur.com/0R1xIKj.png)

**Comment by LexManos** [comment]
1.9:
net/minecraft/server/management/LowerStringMap -> net/minecraft/util/LowerStringMap
