### ISSUE TITLE
Inconsistent field names in EntitySelectors

### ISSUE THREAD

**Issue by Minecrell** [ModCoderPack/MCPBot-Issues#121]
`EntitySelectors` uses inconsistent field names, some of the fields named like `IS_STANDALONE` and others like `selectAnything`.

I suggest renaming:
- `selectAnything` -> `IS_ALIVE`, or `ANYTHING` (it checks for `isEntityAlive`)
- `selectInventories` -> maybe `HAS_INVENTORY`?

**Comment by matthewprenger** [comment]
Fixed:
selectAnything -> IS_ALIVE
selectInventories -> HAS_INVENTORY
