### ISSUE TITLE
TileEntity should be renamed to BlockEntity

### ISSUE THREAD

**Issue by iLexiconn** [ModCoderPack/MCPBot-Issues#122]
In 1.7 or 1.8 (I don't remember) Mojang made the change from Tile to Block, but TileEntity never got changed.

**Comment by kashike** [comment]
I agree with this, as well as the `BlockEntity` name. +1

**Comment by gegy1000** [comment]
I also agree with this, +1

**Comment by Minecrell** [comment]
Will break a lot, but sounds worth to change now for the future. +1

**Comment by LexManos** [comment]
No. If anything Blocks would be renamed to Tiles.
However this is legacy stuff that is just fine. This will not be changed.

**Comment by UpcraftLP** [comment]
May we get a new attempt on renaming it, now that 1.13 finally arrived?

**Comment by phase** [comment]
I believe class names for 1.13 are closed, but in 1.14 they will be reevaluated.
