### ISSUE TITLE
command.server.CommandBlockLogic -> tileentity.CommandBlockLogic

### ISSUE THREAD

**Issue by Minecrell** [ModCoderPack/MCPBot-Issues#123]
`CommandBlockLogic` is kind of lonely in the `command.server` package with all the server commands, I would suggest moving it to `tileentity` where `MobSpawnerBaseLogic` already is (as well as the command block tile entity).

**Comment by gabizou** [comment]
But `CommandBlockLogic` is shared by `EntityMinecartCommandBlock` as well? so it's not limited to tile entities. If anything, the mob spawner base logic would be moved as well for a shared use.

**Comment by Minecrell** [comment]
Then `CommandBlockLogic` should be still in the `command` package, not in the `command.server` package.

**Comment by LexManos** [comment]
Since when it comes to minecarts those are essentially just cart + Tile entity, i'll move this to the TE package and keep things standard:

1.9:
net/minecraft/command/server/CommandBlockLogic -> net/minecraft/tileentity/CommandBlockBaseLogic
