### ISSUE TITLE
net.minecraft.pathfinding and world.pathfinder

### ISSUE THREAD

**Issue by Minecrell** [ModCoderPack/MCPBot-Issues#124]
In my opinion `net.minecraft.pathfinding` and `net.minecraft.world.pathfinder` should be either merged or the latter moved into `pathfinding.processor` or something like that, because they're closely related to each other and should therefore reside in a shared package.

An additional option would be doing the above and additionally moving `net.minecraft.pathfinding` to `net.minecraft.entity.ai.pathfinding` because I'm not sure if it's really used anywhere else than there.

**Comment by LexManos** [comment]
Ya, I've merged world.pathfinder to pathfinding.
