### ISSUE TITLE
What is the reason for all the theX field names?

### ISSUE THREAD

**Issue by Minecrell** [ModCoderPack/MCPBot-Issues#125]
There are quite a lot of fields named like `theX`, e.g. `theEntity`, or `thePlayerMP` which sounds kind of weird to me. Where is the point of doing that if you could just name them `entity` or `player` which would be not less descriptive than with the `the` prefix. Was this started because of problems with decompiling or is this just a weird convention that was started once for no real reason?

I would personally suggest removing the `the` prefixes because I don't really see a point in them.

First I thought this was related to #54 but at the end a lot of parameter names are still called like `theScoreboardIn` so that's probably not the reason for this.

**Comment by Kobata** [comment]
At least historically, the bot wouldn't let you name things the same as a class (even with different capitalization).

So 'entity' or 'playerMP' weren't valid names, but the ones that ended up named with 'theClass' weren't used in a context that gave them anything more obvious.

**Comment by Minecrell** [comment]
Is that still the case though? Never noticed this problem when naming something. Otherwise we could just rename them if that is no longer a problem.

**Comment by tterrag1098** [comment]
Yes this is still a restriction. Try to name a parameter "world" and you will get an error.

**Comment by LexManos** [comment]
There is a list of approved people who can bypass these naming restrictions.
This is to prevent stupid people from creating mappings that are likely to make the compile fail.

**Comment by tterrag1098** [comment]
I understand this. What I'm saying is, that restriction was put in place for a reason no? The standard is CONSTANT_CASE for static final fields. So we should take this chance to standardize, no?

**Comment by bspkrs** [comment]
Please add any further comments on this subject to #54
