### ISSUE TITLE
Render.doRender Javadoc

### ISSUE THREAD

**Issue by ljfa-ag** [ModCoderPack/MCPBot-Issues#126]
Since generics are now decompiled as well, the Javadoc on Render.doRender doesn't need to mention generics or bridge methods anymore. Seeing this javadoc in a subclass was already a bit confusing anyway.

**Comment by Minecrell** [comment]
See https://github.com/ModCoderPack/MCPBot-Issues/issues/67

**Comment by ljfa-ag** [comment]
Ah I see, thanks
