### ISSUE TITLE
BlockState and IBlockState confusion

### ISSUE THREAD

**Issue by ljfa-ag** [ModCoderPack/MCPBot-Issues#127]
It is confusing that these two types have almost the same name even though they are not directly related. Contrary to expectation, BlockState is not implementing IBlockState. Rather, it serves as something like a collection of all possible valid states.

Maybe BlockState should be renamed to something like BlockStateList (And then Block.blockstate, .createBlockState and .getBlockState should also be renamed accordingly).

**Comment by gabizou** [comment]
I'd probably rename it to `BlockStateContainer` of sorts due to it not really being a list but more of a container/table of states with properties.

**Comment by diesieben07** [comment]
Or `BlockStateManager`, maybe.

**Comment by AtomicBlom** [comment]
Given that it's sole responsibility seems to be storing states and properties, I would advocate for BlockStateContainer. Given that it doesn't have any logic for processing IBlockStates, I wouldn't be calling it a manager. It's pretty dumb.

**Comment by LexManos** [comment]
1.9:
net/minecraft/block/state/BlockState -> BlockStateContainer
