### ISSUE TITLE
Block.onEntityCollidedWithBlock overloads

### ISSUE THREAD

**Issue by ljfa-ag** [ModCoderPack/MCPBot-Issues#128]
There are actually two different overloads of Entity.onEntityCollidedWithBlock:
`onEntityCollidedWithBlock(World, BlockPos, Entity)` and `onEntityCollidedWithBlock(World, BlockPos, IBlockState, Entity)`.
The first one is actually a misnomer as it is only called when an entity walks on top of the block (and the javadoc is also wrong here). So it should probably be renamed to onEntityWalk.

**Comment by kashike** [comment]
https://github.com/ModCoderPack/MCPBot-Issues/issues/64
