### ISSUE TITLE
[mcpbot.bspk.rs] MCP News button has broken link

### ISSUE THREAD

**Issue by ErrorCraftLP** [ModCoderPack/MCPBot-Issues#13]
If you click on "MCP News" on http://mcpbot.bspk.rs/ you get a HTTP 404 error because the Mod Coder Pack now has a new site. The button should open the website http://www.modcoderpack.com/website/.

**Comment by ErrorCraftLP** [comment]
Note: This issue is still valid ;)

**Comment by bspkrs** [comment]
Done.

**Comment by ErrorCraftLP** [comment]
Thanks :)

**Comment by ErrorCraftLP** [comment]
Oh, I just noticed that the link which leads to more information about the bot is broken, too.
