### ISSUE TITLE
Locale

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#130]
This is a rather odd name for this class.

`net.minecraft.client.resources.Locale` -> `LanguageMap` (https://github.com/ModCoderPack/MCPBot-Issues/issues/116#event-570090953)?

**Comment by LexManos** [comment]
My Logic: Amungst other things, it is the Locale instance, the one that holds the mappings for a specifc localization. LanguageMap implies multiple, or something like that.
This is a no to the rename in the 1.9 life cycle.
