### ISSUE TITLE
WorldProvider members

### ISSUE THREAD

**Issue by caseif** [ModCoderPack/MCPBot-Issues#131]
There are some issues I've noticed in `WorldProvider` and `WorldType` where members have inaccurate or incorrect names. Below are ones I believe need to be changed:
### In `WorldProvider`
- `isHellWorld` -> `doesWaterVaporize`
  - Exposes its true functionality as well as provides consistency with its accessor
- `getHasNoSky()` -> `hasNoSky()`
### In `WorldType`
- `getWorldTypeName()` -> `getName()`
  - The current name is redundant
- `func_151359()` -> `getTranslateInfo()`'
  - This is obviously the name assigned in 1.8 - I'm not familiar with how deobfuscation IDs work so I don't know whether it's the same in 1.9
- `getCanBeCreated()` -> `canBeCreated()`
- `voidFadeMagnitude()` -> `getVoidFadeMagnitude()`
  - This method doesn't appear to exist anymore in 1.9, although it may have moved and I just haven't found it yet

**Comment by matthewprenger** [comment]
Done:
`field_76575_d`: `isHellWorld` -> `doesWaterVaporize`
`func_177495_o`: `getHasNoSky` -> `hasNoSky`
`func_77127_a`: `getWorldTypeName` -> `getName`
`func_77126_d`: `getCanBeCreated` -> `canBeCreated`
