### ISSUE TITLE
EntityPlayerSP.getClientBrand / setClientBrand should be getServerBrand / setServerBrand

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#132]
EntityPlayerSP's getClientBrand and setClientBrand are incorrectly named.  What they actually do are get/set the brand of the currently connected _server_.

`setClientBrand` is called in `NetHandlerPlayClient.handleCustomPayload`, which receives [`MC|Brand`](http://wiki.vg/Plugin_channel#MC.7CBrand) data _sent from the server_.  `getClientBrand` is called, among other places, in `WorldClient.addWorldInfoToCrashReport`, like this:

```java
var2.addCrashSectionCallable("Server brand", new Callable() {
  @Override
  public String call() {
    return WorldClient.this.mc.thePlayer.getClientBrand();
  }
});
```

These methods have nothing to do with the client brand, and instead work with the server brand.  (To get the client brand, `ClientBrandRetriever.getClientModName` is used).

Here's the recommended changes:

<table>
<tr>
<th>SRG name</th>
<th>Old name</th>
<th>New name</th>
<th>Comment</th>
</tr>
<tr>
<td><code>func_142021_k</code></td>
<td><code>getClientBrand</code></td>
<td><code>getServerBrand</code></td>
<td>Gets the brand of the currently connected server.  May be null if the server hasn't yet sent brand information.  Server brand information is sent over the MC|Brand plugin channel, and is used to identify modded servers in crash reports.</td>
</tr>
<tr>
<td><code>func_175158_f</code></td>
<td><code>getClientBrand</code></td>
<td><code>setServerBrand</code></td>
<td>Sets the brand of the currently connected server.  Server brand information is sent over the MC|Brand plugin channel, and is used to identify modded servers in crash reports.</td>
</tr>
</table>

```
!sm func_142021_k getServerBrand Gets the brand of the currently connected server.  May be null if the server hasn't yet sent brand information.  Server brand information is sent over the MC|Brand plugin channel, and is used to identify modded servers in crash reports.
!sm func_175158_f setServerBrand Sets the brand of the currently connected server.  Server brand information is sent over the MC|Brand plugin channel, and is used to identify modded servers in crash reports.

**Comment by matthewprenger** [comment]
Fixed:
getClientBrand -> getServerBrand
setClientBrand -> setServerBrand
