### ISSUE TITLE
Static final fields should be renamed to CONSTANT_CASE

### ISSUE THREAD

**Issue by tterrag1098** [ModCoderPack/MCPBot-Issues#134]
This includes most registries, which are currently in camelCase, like Item.itemRegistry, Block.blockRegistry, etc. MCPBot requires a forced override to name fields like this, so why keep it around if it breaks the rules?

**Comment by darkhax** [comment]
I agree, now is the perfect time to update these. We should compile a list of all registry fields so we can be sure not to miss anything.

**Comment by kashike** [comment]
I'm +1 for `CONSTANT_CASE`. The existing registries/etc are a mixture of `snake_case`, `camelCase` and `CONSTANT_CASE` - it would be nice to switch to `CONSTANT_CASE` for everything, especially since that's what MCPBot tells you to use.

**Comment by liach** [comment]
Only for primitives and Strings. Other types may be mutable.

**Comment by tterrag1098** [comment]
Nope http://docs.oracle.com/javase/specs/jls/se6/html/names.html#9367

**Comment by darkhax** [comment]
Here is a list of the once I have found. This should be all of them, or at least the name spaced ones. Current clases are Block, PotionType, Potion, Enchantment, BiomeGenBase, SoundEvent and Item.

`!sf field_149771_c BLOCK_REGISTRY`
`!sf field_185176_a POTION_TYPE_REGISTRY`
`!sf field_188414_b POTION_REGISTRY`
`!sf field_185264_b ENCHANTMENT_REGISTRY`
`!sf field_185377_q BIOME_REGISTRY`
`!sf field_187505_a SOUND_REGISTRY`
`!sf field_150901_e ITEM_REGISTRY`

**Comment by LexManos** [comment]
What about the Init classes that hold the static things. In theory they should be CONSTANT_CASE no? Just somethign to think about.
We need to have someone go an name those correctly as those will be central to a lot of MC stuff and we dont want the community fighting over names.

**Comment by kenzierocks** [comment]
If we want to use an established standard, Google suggests using `ALL_CAPS` only when the field is truly constant, not like the registries which may change over time. I would vote for `ALL_CAPS` or `ALL_CAPS` and `camelCase`, where applicable.

**Comment by matthewprenger** [comment]
All of the MC registries and their current mapped names:
```
net/minecraft/client/renderer/block/model/ModelBakery.field_177605_n => bakedRegistry
net/minecraft/client/resources/data/IMetadataSerializer.field_110508_a => metadataSectionSerializerRegistry
net/minecraft/item/Item.field_185051_m => properties
net/minecraft/client/audio/SoundHandler.field_147697_e => sndRegistry
net/minecraft/block/Block.field_149771_c => blockRegistry
net/minecraft/potion/PotionType.field_185176_a => REGISTRY
net/minecraft/enchantment/Enchantment.field_185264_b => enchantmentRegistry
net/minecraft/item/Item.field_150901_e => itemRegistry
net/minecraft/potion/Potion.field_188414_b => potionRegistry
net/minecraft/util/SoundEvent.field_187505_a => soundEventRegistry
net/minecraft/world/biome/BiomeGenBase.field_185377_q => biomeRegistry
net/minecraft/block/BlockDispenser.field_149943_a => dispenseBehaviorRegistry
```

I definitely think we need to figure out a standard for all of these. I'm partial to `thingRegistry` myself (The way most of them are currently mapped), as these are not truly immutable fields.

**Comment by SoniEx2** [comment]
+1 for CONSTANT_CASE. Including for block/item fields, which should be their in-game names/IDs in uppercase.

**Comment by darkhax** [comment]
To comment on some of the recent changes, I still feel that CONSTANT_CASE should be used for all of the registries, or at least the namespaced ones. As for Soni's comment, I agree that all item and block fields should be updated to resemble their name ID, however I am not sure if they should be camelCase or not. In that situation I would be okay either way.

**Comment by grondag** [comment]
Would like to see all final static fields in CONSTANT_CASE, including registries or other instances that may have mutable content.  For me, it serves to remind that I am working with what is essentially a singleton instance, which in turn has other implications for state and concurrency.

**Comment by diesieben07** [comment]
But CONSTANT_CASE doesn't mean singleton. CONSTANT_CASE means it's a constant, hence the name.
If we follow that logic instance fields in blocks need to be CONSTANT_CASE as well, since they are "essentially a singleton instance".

**Comment by micahcowan** [comment]
Yeah, I for one am not having fun with all the CONSTANT_CASE "static final", mutable collections (such as List), including the registries. It really shouldn't be CONSTANT_CASE unless it's, you know, _constant_. Most of the registries would be expected to be modified by modders - removing and especially adding items, and it just feels wrong to me.

Or for instance, the various fields like `objectUseStats` in net.minecraft.stats.StatList, whose value will change constantly, but by current rules would have to be named in CONSTANT_CASE simply because it's "static final", even though it's an array whose elements will change frequently.

**Comment by SoniEx2** [comment]
Y'all are mixing up "constant" and "immutable" again.

"Constant" is a property of variables. "Immutable" is a property of values.

**Comment by kenzierocks** [comment]
Is it?
```java
static final AtomicInteger FOO_BAR = new AtomicInteger();
static {
     FOO_BAR.set(5);
}
```

Is `FOO_BAR` a constant or not? In English terms, does it *remain constant*?

**Comment by micahcowan** [comment]
As far as I'm concerned, constant implies immutable. If it's not immutable, it's not constant (but the reverse guarantee doesn't apply). I've never heard someone use the term "constant" to refer only to guarantees about whether a _reference_ can be reassigned or not.

**Comment by SoniEx2** [comment]
Let's put it in C words: "Constant" is a property of a pointer, "immutable" is a property of a value.

Thus, in C syntax, yes, `FOO_BAR` remains constant, `*FOO_BAR` doesn't.

**Comment by SoniEx2** [comment]
@micahcowan You have now ;)

**Comment by micahcowan** [comment]
I would not call that `char * const FOO` a constant in C either, even though the pointer technically is. Meanwhile, the much more common `const char *FOO` does in fact guarantee you at least won't modify the underlying characters. But I wouldn't call it "a constant" unless it was declared as `const char * const FOO`, providing both guarantees. I certainly wouldn't CONSTANT_CASE it unless that were true, as that would almost certainly confuse me or someone else into believing it couldn't be modified.

In C++ in particular, I wouldn't call an object "constant" unless invocations of the "const" methods were at all times implied (that is, the object itself/`this` is const, and not just some pointer to it). CONSTANT_CASE is for constant objects, not (just) constant pointers.

**Comment by diesieben07** [comment]
I'll link this again: https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names

**Comment by SoniEx2** [comment]
Those are google's. We're here to come up with something of our own.

**Comment by micahcowan** [comment]
We may be here to come up with something of our own, but surely we're not coming up with new definitions of terms? The linked Google guide provides a decent (and in my experience, mainstream) definition of what exactly "constant" means, with particular attention to the notion that not all "static final"s are constant, and an explicit statement that mutable objects almost always aren't considered constants.

**Comment by SoniEx2** [comment]
Hmm... How about this. Registries should be UPPER_CASE. Constants should be UPPER_CASE, including blocks and items. Everything else camelCase.

Not all Maps are a registry. Not all registries are a Map. And this would be reasonable because you don't (or at least shouldn't - constants don't exist in java if you use reflection) modify block and item registries after the game has started.

**Comment by micahcowan** [comment]
I think I'm indifferent to that, one way or another. But how would that be enforced by MCPBot? Memorizing the exceptions, I suppose? Combined with type awareness for static finals...

**Comment by diesieben07** [comment]
Why do you want registries in CONSTANT_CASE (funny how you now call it UPPER_CASE all of a sudden...)? I mean, how is a registry different from a "normal" Map in a static final field?

**Comment by SoniEx2** [comment]
@diesieben07 Change a registry while the game is running. Let me know how it goes.

**Comment by diesieben07** [comment]
How is that a valid argument? Yes, it is a bad idea to change it while the game is running. It still is neither immutable nor a constant.

**Comment by SoniEx2** [comment]
It should be treated as a constant by outside code. After initialization you can access block and item registries multithreaded with no issues.

**Comment by diesieben07** [comment]
That is not true. `FMLControlledNamespacedRegistry` is based on non-threadsafe collections such as `HashSet` or `HashBiMap`. These are not guaranteed to work when accessed from multiple threads, even if they are not modified. This has to do with visibility. There is no guarantee that the changes in the data is actually visible. Learn about happens-before relations if you want to properly understand this.

**Comment by SoniEx2** [comment]
Any read operation without side-effects will not cause issues with other read operations without side-effects happening on other threads.

I assume HashSet and HashBiMap have read operations without side-effects, and that makes them thread-safe.

**Comment by diesieben07** [comment]
Yes, they are thread-safe as long as you are not mutating them. But they do not (and cannot) make any guarantees about threads actually *seeing* the data.
There has to be a happens-before relation between the writing of the data (before the game starts) and the reading in the different thread. This needs to be an explicit operation, such as starting said thread. But if the data in the registry is mutated after the thread is started, there is no guarantee the data will be seen, unless there is another happens-before relation.

**Comment by SoniEx2** [comment]
And that's precisely why registries shouldn't be modified while the game is running.

In theory we'd have a registry builder and when the game is started we'd build the registries, but in practice things don't work that way.

**Comment by diesieben07** [comment]
You did not understand what I said apparently.

**Comment by SoniEx2** [comment]
Maybe you didn't understand the bigger picture (all the systems working together, not each system working independently).

During initialization? Not constant. After initialization aka 99% of the time? Constant.

**Comment by SoniEx2** [comment]
Also we should have `Block.REGISTRY` instead of `Block.blockRegistry` because the latter is too redundant.

**Comment by diesieben07** [comment]
"Almost constant" is not a thing. Something is constant, or not. Registries are not.

**Comment by SoniEx2** [comment]
"Effectively constant".

**Comment by SoniEx2** [comment]
Also the JVM guarantees some things for you... https://www.youtube.com/watch?v=uL2D3qzHtqY

**Comment by diesieben07** [comment]
I know that talk. And if you understand it you will also understand what I am talking about.
It still does not have much to do with the discussion at hand. No matter what the JVM guarantees or not, mutable things are not constants.

**Comment by SoniEx2** [comment]
Pros of `REGISTRY`:

- It stands out.
- Mojang also uses it.
- It's not redundant. (compared to what we currently have.)

Cons:

- Doesn't follow Google's thing, which's the only thing you (@diesieben07) seem to be arguing about.

**Comment by diesieben07** [comment]
> It stands out.

**Comment by diesieben07** [comment]
> It stands out.

Great. How exactly does this help? It stands out against... what? Why does it need to stand out?
> Mojang also uses it.

How is this relevant? "Someone else is doing it, too!" is not a justification for stupid.
> It's not redundant.

Neither is `registry`.

And no, "doesn't follow Google's thing" is not the only thing I have brought up. It is in fact not at all something I brought up, it is something I used to show you that other people (and those with a lot of knowledge behind them, Guava is very widely used) think of it in the same way that I do: Something that is mutable is not a constant and should thus not be mutable.

**Comment by SoniEx2** [comment]
If your code compiles both on MCP and on Mojang's code, that's a good thing.

If it stands out when reading code (e.g. you see "REGISTRY" easily), you can quickly see if something is using a registry without having to grep for it.

And yeah, sure, `registry` is not redundant. But you have to remember I was comparing `REGISTRY` to what we currently have.

**Comment by liach** [comment]
Um... I suggest to remain everything the same as before if we cannot get a good result from arguing. Moreover we'd finish arguments before some people come to lock this thread because of spamming.

**Comment by diesieben07** [comment]
> If your code compiles both on MCP and on Mojang's code, that's a good thing.

How so? It is not likely that we will ever get access to Mojang code in the original form.
> If it stands out when reading code (e.g. you see "REGISTRY" easily), you can quickly see if something is using a registry without having to grep for it.

Ok, so let's name everything in `UPPER_CASE` so it "stands out" and you can see if something is X without having to grep for it. This argument is ridiculous.
> And yeah, sure, registry is not redundant. But you have to remember I was comparing REGISTRY to what we currently have.

These are two different arguments. `blockRegistry` is redundant, yes. But if we are arguing on that level the change is `blockRegistry` to `registry`, that fixes one thing, the redundancy. If you want to change it to `REGISTRY` that is a different argument to the redundancy one.

> Also, conventions are arbitrary.
Indeed they are. This is not an argument why your convention is better than mine. I on the other hand have made serious arguments why "my" convention is better.

**Comment by SoniEx2** [comment]
@diesieben07 I think it's up to someone else to decide which one is better. We both have good arguments.

Also, don't forget all the `public static final MyThing INSTANCE;` all over Forge. `INSTANCE` is similar to `REGISTRY`, IMO.

**Comment by diesieben07** [comment]
> `INSTANCE` is similar to `REGISTRY`, IMO.

I disagree with `INSTANCE` in a lot of places, too. But yes, I will shut up now as I have nothing to add to this.

**Comment by elifoster** [comment]
I agree that `static final` **truly constant** variables should use `CONSTANT_CASE` instead of `camelCase`. In other words, I agree with @diesieben07 and the Google style guide.

**Comment by bspkrs** [comment]
All static final fields will be renamed in CONSTANT_CASE sometime in the near future. Thanks for all the input.

**Comment by matthewprenger** [comment]
All static final fields have been renamed to UPPER_CASE. To see a complete list of what has changed to what, see https://gist.github.com/matthewprenger/30655851b69b9af71ab9ee2e88659e13 (format is: srg,old,new)
