### ISSUE TITLE
SPacketUpdateEntityNBT -> SPacketUpdateBossBar

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#137]
`SPacketUpdateEntityNBT` does not update Entity NBT, it updates the `BossBarInfo` data.

**Comment by matthewprenger** [comment]
:+1:  This class is only used for the BossBar. Also `func_184325_a` will need to be renamed from `handleUpdateEntityNBT` to something more appropriate should this rename go through.

**Comment by LexManos** [comment]
1.9.4
net/minecraft/network/play/server/SPacketUpdateEntityNBT net/minecraft/network/play/server/SPacketUpdateBossInfo
