### ISSUE TITLE
Statistics command

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#138]
It'd be nice to have a statistics command that outputs:
- `named`/`total` methods
  - The number of methods with names, along with the total number of methods
- `named`/`total` fields
  - The number of fields with names, along with the total number of fields
- `named`/`total` parameters
  - The number of parameters with names, along with the total number of parameters

Certainly not an important feature, but it'd be one to know how much still needs to be mapped by looking at numbers.

**Comment by williewillus** [comment]
Also, xaero's unmapped stat dumps also indicate the percentage of unmapped members vs all members (basically divide the first and second numbers). Helps see at a glance what classes badly need help in a proportional manner
