### ISSUE TITLE
net/minecraft/client/resources/data/IMetadataSerializer -> MetadataSerializer

### ISSUE THREAD

**Issue by matthewprenger** [ModCoderPack/MCPBot-Issues#139]
Not sure why this class has an I prefix, it's not an interface.

**Comment by bspkrs** [comment]
Dunno... it's never been an interface as far as I can tell in the bot DB.

**Comment by kashike** [comment]
I think that's the point. It is prefixed with `I`, but it isn't an interface.

**Comment by matthewprenger** [comment]
Just did some further digging. The class appeared in 1.7.2 and has never been an interface.

**Comment by LexManos** [comment]
1.9.4: net/minecraft/client/resources/data/IMetadataSerializer net/minecraft/client/resources/data/MetadataSerializer
