### ISSUE TITLE
[TYPO] CreativeTabs.displayAllReleventItems

### ISSUE THREAD

**Issue by CruzBishop** [ModCoderPack/MCPBot-Issues#140]
Currently on: Staging / LIVE (1.9)

Current name:CreativeTabs.displayAllReleventItems 
SRG name: func_78018_a

It should be displayAllRelevantItems; A common typo :smile:

**Comment by matthewprenger** [comment]
Fixed:
`func_78018_a`: `displayAllReleventItems` -> `displayAllRelevantItems`

**Comment by CruzBishop** [comment]
Thank you :)
