### ISSUE TITLE
func_180614_a parameters are wrong after update

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#141]
SRG Params : `ItemStack p_180614_1_, EntityPlayer p_180614_2_, World p_180614_3_, BlockPos  p_180614_4_, EnumHand p_180614_5_, EnumFacing p_180614_6_, F p_180614_7_, F p_180614_8_, F p_180614_9_`
MCP Params : `ItemStack stack, EntityPlayer playerIn, World worldIn, BlockPos pos, EnumHand
side, EnumFacing hitX, float hitY, float hitZ, float p_180614_9_`

@bspkrs said:
> it sounds like something went wonky in the srg update or something... if the signature changed the method should have gotten a new srg name                                                       

`p_180614_5_` -> `hand`
`p_180614_6_` -> `facing`
`p_180614_7_` -> `x`
`p_180614_8_` -> `y`
`p_180614_9_` -> `z`

**Comment by xaeroverse** [comment]
Maybe we can call this mystery solved?  Lex has stated that this is intended:

```
<LexManos+> <Matthew> bspkrs, ever figure out why some of the param shuffling didn't 
            trigger methods to get new srgs?
<LexManos+> Because I expliclty chose to make them not have new srg names, params 
            will need to be updated but params dont mean anything in most code
<LexManos+> And with proper use of the @Override annotation modders will be fine.
```
