### ISSUE TITLE
Block.get/setStepSound -> Block.get/setSoundType

### ISSUE THREAD

**Issue by PaleoCrafter** [ModCoderPack/MCPBot-Issues#143]
These methods haven't just specified the step sound for a long time. Changing the mapping to get/setSoundType would reflect the type of the field the methods wrap (net.minecraft.block.SoundType) and the actual purpose.

**Comment by PaleoCrafter** [comment]
I forgot, but the actual field (Block.stepSound) should be changed as well, of course.

**Comment by mezz** [comment]
I agree, the block's `get/setStepSound` is really a `SoundType`, which contains the hit, break, place, and fall sounds in addition to step.

**Comment by CrazyPants** [comment]
I agree, change to sound type

**Comment by grondag** [comment]
Good change.

**Comment by matthewprenger** [comment]
Yeah looks like SoundType is more than just the step sound.

`func_149672_a`: `setStepSound` -> `setSoundType`
`func_185467_w`: `getStepSound` -> `getSoundType`
`field_149762_H`: `stepSound` -> `blockSoundType`
