### ISSUE TITLE
Item.itemModifierUUID -> Item.ATTACK_DAMAGE_MODIFIER[_UUID]

### ISSUE THREAD

**Issue by PaleoCrafter** [ModCoderPack/MCPBot-Issues#144]
With 1.9, Vanilla introduced the attack speed modifier which would also qualify as generic "item modifier", but has its own UUID (Item.field_185050_h right now), as both the damage and speed modifier can be applied at the same time. It would hence make sense to rename itemModifierUUID to something more appropriate.

Since the UUIDs are basically constant (UUID is immutable), the names should also use CONSTANT_CASE, which the current 'itemModifierUUID' does not (see #134). It's also questionable whether keeping the 'UUID' suffix makes a lot of sense, as the name only gets longer that way, the information can easily be gathered from context (type and usage).

Deciding on a convention for this field is also required for mapping Item.field_185050_h (attack speed modifier) and ItemArmor.field_185084_n (armor modifiers per armor part).

**Comment by matthewprenger** [comment]
Fixed:
`field_111210_e`: `itemModifierUUID` -> `ATTACK_DAMAGE_MODIFIER`
`field_185050_h`: -> `ATTACK_SPEED_MODIFIER`
`field_185084_n`: -> `ARMOR_MODIFIERS`
