### ISSUE TITLE
WorldClient.doPreChunk parameters have typos

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#145]
The first and second parameters of `WorldClient.doPreChunk` (`func_73025_a`) have typos: <code>chun<b><i>c</i></b>X</code> and <code>chun<b><i>c</i></b>Z</code>.

    !sp p_73025_1_ chunkX
    !sp p_73025_2_ chunkZ

**Comment by matthewprenger** [comment]
Fixed
