### ISSUE TITLE
Minecraft -> MinecraftClient

### ISSUE THREAD

**Issue by darkevilmac** [ModCoderPack/MCPBot-Issues#147]
Simple as the title says really, the Minecraft class as it currently stands is for a minecraft game client and should probably be named accordingly. I don't expect this to be in 1.9 but might be worth considering for 1.10.

**Comment by liach** [comment]
Agree! Like this idea so much. Should be named in the same way as `MinecraftServer`.

**Comment by diesieben07** [comment]
My opinion: Please no.

**Comment by williewillus** [comment]
Kinda pointless imo, and its just even more to type :P

**Comment by rfsantos1996** [comment]
I agree actually.
@williewillus by this argument, lets name it `MC`. Seriously now, I have C++ mainly because of their name conventions, a good API should not have any abbreviations or exclude any information that should be on the title and, considering @liach's comment, it should be named `MinecraftClient`

**Comment by williewillus** [comment]
there's other things to consider besides that too, like how we've had this name for years and now we're changing it for now reason.

By that reasoning we should change isRemote because it isn't really representative of what the Boolean means. Except wait we already tried that. It didn't go well ;p

**Comment by darkevilmac** [comment]
@williewillus Not trying to sound rude but that's pretty much just saying you don't like change. This change really just makes sense when you think about it, as mentioned by @liach it should be named in the same way MinecraftServer is.

Or we could just change MinecraftServer to Minecraft as well, heck it's in the server package anyway, plus it's easier to type! Do you kind of understand where I'm coming from? :P

**Comment by bspkrs** [comment]
This name will not be changed.

**Comment by LexManos** [comment]
Of all the classes Minecraft and MinecraftServer will never change names because we know without a shadow of a doubt that this is indeed the official Mojang names for them because they are the entry points.
