### ISSUE TITLE
IIconCreator -> ISpriteCreator

### ISSUE THREAD

**Issue by Glassmaker** [ModCoderPack/MCPBot-Issues#148]
As Icon doesn't exist starting with 1.8, I think ISpriteCreator is a better name for the interface.

~~Also, I would recommend to change iconRegistry (p_177059_1_)  to textureMap~~ moved to #155

**Comment by bspkrs** [comment]
Please open separate issues for class names and mapping names in the future. Not a huge thing, but it makes it easier to manage them.

**Comment by LexManos** [comment]
1.9.4: net/minecraft/client/renderer/texture/IIconCreator net/minecraft/client/renderer/texture/ITextureMapPopulator

It doesnt create anything it just tells the texture map what it needs to create when it reloads.
