### ISSUE TITLE
Suggestion for Path and PathEntity names

### ISSUE THREAD

**Issue by micahcowan** [ModCoderPack/MCPBot-Issues#151]
### Proposal

Name change. Something along the lines of:

net.minecraft.pathfinding.**Path** -> **PathFinderState**
net.minecraft.pathfinding.**PathEntity** -> **Path**

### Rationale

I don't know whether changing these class names will be pracitcal, but, the class currently named **PathEntity** simply describes a path, of the point-A to point-B variety.

The one named **Path**, on the other hand, is not a path at all, but a custom queue-like thing used to _seek_ paths. It doesn't contain the _logic_ for seeking paths - that's managed by, apparently, the **PathFinder** class and (separately) the **EntityDragon** class. But it does hold the saved state for path finding, and not just an actual path - a **PathEntity** is usually generated by following the shortest path we found using the **Path** object, so "PathEntity" is really, truly, the actual path we found, and **Path** should maybe be named something more like **PathFinderQueue** or **PathFinderState** or something of that nature, IMO.

**Comment by LexManos** [comment]
1.9.4:
net/minecraft/pathfinding/Path net/minecraft/pathfinding/PathHeap
net/minecraft/pathfinding/PathEntity net/minecraft/pathfinding/Path
