### ISSUE TITLE
Extended comment proposal for field_184681_bN/"neighbors"

### ISSUE THREAD

**Issue by micahcowan** [ModCoderPack/MCPBot-Issues#152]
The following is a proposed (big-ass) comment for field_184681_bN (which I've currently named "neighbors"), attempting to provide details for how it works. The comment is too large to do over IRC. The field is defined in net.minecraft.entity.boss.EntityDragon.

Since "code" blocks in github don't wrap lines, I'm only formatting the table at the end as monospace, since it looks better in it.

The neighbors field is an array of bitmaps indicating, for each member of pathPoints, which other members should be considered "neighboring" for the purpose of path-finding. The set bits indicate the indexes into pathPoints that should be considered to be candidates for the next step in a path through the circles. Generated by initPathPoints.

For instance, the first element (index 0), corresponding to the starting point of the first, large, low-to-ground circle, has bits 1, 11, and 12 set, indicating that the next step could be any of:

(a) the next point in the current circle,
(b) the previous point in the current circle (the end point of the circle, since this is the first), or
(c) the first point in the second, spiralling-upwards circle.

```
neighbors:

0x001802 000000000001100000000010 circle 1 start
0x002005 000000000010000000000101
0x00200A 000000000010000000001010
0x004014 000000000100000000010100
0x008028 000000001000000000101000
0x008050 000000001000000001010000
0x0100A0 000000010000000010100000
0x020140 000000100000000101000000
0x020280 000000100000001010000000
0x040500 000001000000010100000000
0x080A00 000010000000101000000000
0x080401 000010000000010000000001 circle 1 end
0x182001 000110000010000000000001 circle 2 (spiral) start
0x305006 001100000101000000000110
0x20A008 001000001010000000001000
0x614030 011000010100000000110000
0x428040 010000101000000001000000
0xC50180 110001010000000110000000
0x8A0200 100010100000001000000000
0x941C00 100101000001110000000000 circle 2 end
0xE83000 111010000011000000000000 circle 3 start
0xD0E000 110100001110000000000000
0xB38000 101100111000000000000000
0x7E0000 011111100000000000000000 circle 3 end
```

**Comment by micahcowan** [comment]
Alternatively, this comment could be matched to where the field gets initialized with these values, which is func_184671_o/initPathPoints. In which case it should also probably describe the other field whose values are initialized there, field_184680_bM/pathPoints.

```
A slightly longer description for pathPoints than it currently has, in case documenting that method is preferred over doccing the fields, follows.

The pathPoints field contains a series of 24 points describing three circles.

First 12 points describe a circle of radius 60, low to the ground.

Next 8 points describe a spiral/circle of radius 40, spiraling upwards by 80m.

Final 4 points describe a circle of radius 20 at the top of that spiral.

All circles are centered on the world origin (x: 0, z: 0)
```

**Comment by micahcowan** [comment]
(The neighbors comment might also benefit from explicitly listing which points can travel to which other points, instead of just spelling out the bitmap itself... I could reformat the comment to do that, if desired. Might be more useful.)

**Comment by kashike** [comment]
@micahcowan Is this still something you want done? Which of your comments? You're most likely able to set it yourself if you use DCC.

**Comment by micahcowan** [comment]
@kashike Ah! I did not realize I could use DCC to set comments. I'll try that. :)

**Comment by micahcowan** [comment]
in case I have trouble, though, it's the first comment I'd want to include, if someone wants to get it in directly.

**Comment by Pokechu22** [comment]
Yea, DCC doesn't have the length limitation a normal connection has.

One thing to note about that specific comment: You'll probably want to wrap the large block of text into a `<pre>` tag, so that it looks correct.   (Or, you can put it in an HTML table; that also works and will format correctly in javadocs).  If you leave it as-is, it'll not wrap automatically if you hover over the method in your IDE (where it's parsed as HTML), although it might look OK when viewed directly.

If you want another example of a huge comment, look at <ruby><rb>`FontRenderer.trimStringToWidth(String, int, Boolean)`</rb><rp> (</rp><rt>`func_78262_a`</rt></ruby>.  It's got a large table.  Note that using `!gm func_78262_a` in a normal MCPBot connection won't necessarily print the full message; you need to use DCC to actually print the full message due to its length.
