### ISSUE TITLE
CPacketPlayerTryUseItem and CPacketPlayerBlockPlacement are reversed

### ISSUE THREAD

**Issue by Aaron1011** [ModCoderPack/MCPBot-Issues#153]
`CPacketPlayerTryUseItem` is actually sent when a player places a block, while `CPacketPlayerBlockPlacement` is sent when a player right-clicks air with an item. These two packets should have their names swapped.

**Comment by gabizou** [comment]
This can't be resolved in 1.9? If the classes and related `INetHandlerPlayServer` methods are reversed, wouldn't this cause unnecessary confusion as to figure out which class to use instead of the other?

**Comment by kashike** [comment]
Class name changes are done for 1.9.

**Comment by matthewprenger** [comment]
Lex has said that class names won't be changed between 1.9 and 1.9.x as it is not worth breaking compatibility.

**Comment by gabizou** [comment]
I see, even with 1.9.1-1.9.2 breaking protocol compatibility?

**Comment by LexManos** [comment]
Actually neither of them have anything to do with placing a block.
One if using an item on a block.
The other is using it on air.
So:
1.9.4: 
net/minecraft/network/play/client/CPacketPlayerTryUseItem net/minecraft/network/play/client/CPacketPlayerTryUseItemOnBlock
net/minecraft/network/play/client/CPacketPlayerBlockPlacement net/minecraft/network/play/client/CPacketPlayerTryUseItem
