### ISSUE TITLE
`HorseType` and `HorseArmorType` are reversed.

### ISSUE THREAD

**Issue by Aaron1011** [ModCoderPack/MCPBot-Issues#154]
`HorseType` actually contains the various types of horse armor, while `HorseArmorType` contains the horse variants.

**Comment by LexManos** [comment]
Wonder how that happened, must of been a transposition when originally naming them.
1.9.4
net/minecraft/entity/passive/HorseType net/minecraft/entity/passive/HorseArmorType
net/minecraft/entity/passive/HorseArmorType net/minecraft/entity/passive/HorseType
