### ISSUE TITLE
Entity read/write method parameters

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#157]
Existing param names contain typos, others can be changed to be more consistent with `compound`.

`p_70037_1_`: `tagCompund` -> `compound`
`p_70020_1_`: `tagCompund` -> `compound`
`p_70039_1_`: `tagCompund` -> `compound`
`p_70109_1_`: `tagCompund` -> `compound`
`p_70014_1_`: `tagCompound` -> `compound`
`p_184198_1_`: `tagCompound` -> `compound`

**Comment by matthewprenger** [comment]
Fixed:
`p_70037_1_`: `tagCompund` -> `compound`
`p_70020_1_`: `tagCompund` -> `compound`
`p_70039_1_`: `tagCompund` -> `compound`
`p_70109_1_`: `tagCompund` -> `compound`
`p_70014_1_`: `tagCompound` -> `compound`
`p_184198_1_`: `tagCompound` -> `compound`
