### ISSUE TITLE
Collision rules

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#158]
It seems as if someone named the following two collision rules incorrectly after the visibility rules.

`Team$CollisionRule.HIDE_FOR_OTHER_TEAMS` -> `Team$CollisionRule.PUSH_OTHER_TEAMS`
`Team$CollisionRule.HIDE_FOR_OWN_TEAM` -> `Team$CollisionRule.PUSH_OWN_TEAM`

**Comment by matthewprenger** [comment]
:+1: Looks like they got the same names as `Team$EnumVisible`.

**Comment by LexManos** [comment]
Enum names are taken from the code itself and will never be changeable from the modders end. We use the official names because we have them.
