### ISSUE TITLE
method with completly wrong name/desc

### ISSUE THREAD

**Issue by clienthax** [ModCoderPack/MCPBot-Issues#16]
srg func_70058_J
Name       : bR => func_70058_J => handleLavaMovement
Descriptor : ()Z
Comment    : Whether or not the current entity is in lava

Proposed new data
Name: isNotColliding
Comment: checks that the entity is not colliding with any blocks / liquids

**Comment by clienthax** [comment]
data is correct for 1.6.4/1.7.2/1.7.10, seems to of changed functionality with 1.8

**Comment by bspkrs** [comment]
Done.
