### ISSUE TITLE
EnumStatus

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#160]
`EntityPlayer$EnumStatus` -> `EntityPlayer$SleepResult`

`EnumStatus` is very vague. `SleepResult` describes what it is (a result) and what it's for (sleeping).

**Comment by LexManos** [comment]
1.9.4:
net/minecraft/entity/player/EntityPlayer$EnumStatus net/minecraft/entity/player/EntityPlayer$SleepResult
