### ISSUE TITLE
BiomeGenBase -> Biome

### ISSUE THREAD

**Issue by Adubbz** [ModCoderPack/MCPBot-Issues#162]
This was brought up in IRC a while back and I tend to agree. I think 'GenBase' doesn't really add any additional information and seems to have stuck around mostly for legacy purposes. It's much more consistent with Item and Block which aren't 'BlockBase' or 'ItemBase'. Would be nice to see in 1.9.1 or what have you.

To coincide with this change, BiomeGenX classes should be renamed to BiomeX

**Comment by kashike** [comment]
:+1: for this, as well as renaming all biome classes to remove `Gen`: `BiomeGenPlains` -> `BiomePlains`

**Comment by Adubbz** [comment]
Definately, forgot to mention those as well

**Comment by LexManos** [comment]
1.9.4:

net/minecraft/world/biome/BiomeGenBase net/minecraft/world/biome/Biome
net/minecraft/world/biome/BiomeGenBeach net/minecraft/world/biome/BiomeBeach
net/minecraft/world/biome/BiomeGenDesert net/minecraft/world/biome/BiomeDesert
net/minecraft/world/biome/BiomeGenHills net/minecraft/world/biome/BiomeHills
net/minecraft/world/biome/BiomeGenEnd net/minecraft/world/biome/BiomeEnd
net/minecraft/world/biome/BiomeGenForest net/minecraft/world/biome/BiomeForest
net/minecraft/world/biome/BiomeGenForestMutated net/minecraft/world/biome/BiomeForestMutated
net/minecraft/world/biome/BiomeGenHell net/minecraft/world/biome/BiomeHell
net/minecraft/world/biome/BiomeGenJungle net/minecraft/world/biome/BiomeJungle
net/minecraft/world/biome/BiomeGenMesa net/minecraft/world/biome/BiomeMesa
net/minecraft/world/biome/BiomeGenMushroomIsland net/minecraft/world/biome/BiomeMushroomIsland
net/minecraft/world/biome/BiomeGenOcean net/minecraft/world/biome/BiomeOcean
net/minecraft/world/biome/BiomeGenPlains net/minecraft/world/biome/BiomePlains
net/minecraft/world/biome/BiomeGenRiver net/minecraft/world/biome/BiomeRiver
net/minecraft/world/biome/BiomeGenSavanna net/minecraft/world/biome/BiomeSavanna
net/minecraft/world/biome/BiomeGenSavannaMutated net/minecraft/world/biome/BiomeSavannaMutated
net/minecraft/world/biome/BiomeGenSnow net/minecraft/world/biome/BiomeSnow
net/minecraft/world/biome/BiomeGenStoneBeach net/minecraft/world/biome/BiomeStoneBeach
net/minecraft/world/biome/BiomeGenSwamp net/minecraft/world/biome/BiomeSwamp
net/minecraft/world/biome/BiomeGenTaiga net/minecraft/world/biome/BiomeTaiga
