### ISSUE TITLE
PlayerManager

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#163]
This manages players in chunks, not players directly.

- `net.minecraft.server.management.PlayerManager` -> `PlayerChunkMap`
- `net.minecraft.server.management.PlayerManager$PlayerInstance` -> `PlayerChunkMap$Entry`

**Comment by LexManos** [comment]
1.9.4:
net/minecraft/server/management/PlayerManager net/minecraft/server/management/PlayerChunkMap
net/minecraft/server/management/PlayerManager$PlayerInstance net/minecraft/server/management/PlayerChunkMap$Entry
