### ISSUE TITLE
Scoreboard Criteria

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#164]
To match with the rest:
`field_96642_c`: `deathCount` -> `DEATH_COUNT`
`field_96639_d`: `playerKillCount` -> `PLAYER_KILL_COUNT`
`field_96640_e`: `totalKillCount` -> `TOTAL_KILL_COUNT`
`field_96638_f`: `health` -> `HEALTH`

**Comment by matthewprenger** [comment]
Fixed:
`field_96642_c`: `deathCount` -> `DEATH_COUNT`
`field_96639_d`: `playerKillCount` -> `PLAYER_KILL_COUNT`
`field_96640_e`: `totalKillCount` -> `TOTAL_KILL_COUNT`
`field_96638_f`: `health` -> `HEALTH`
