### ISSUE TITLE
field_71305_c: worldServers -> worlds

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#168]
This field represents an array of server worlds, though the name suggests it's an array of world servers.
`field_71305_c`: `worldServers` -> `worlds`

**Comment by micahcowan** [comment]
Yes, or "WorldServer"s, which it is. Perhaps a change to the class name would be advisable as well. Agreed that `worlds` > `worldServers`

**Comment by kashike** [comment]
`ServerWorld` and `ClientWorld` are what I'd call them, but naming them that would cause them to be different from every other class (`BlockAir` instead of `AirBlock`, `EntityCow` instead of `CowEntity`, etc).

**Comment by kashike** [comment]
`field_71305_c`: `worldServers` -> `worlds`
