### ISSUE TITLE
func_179819_c: getPlayer -> getUniqueId; field_179820_b: playerId -> uniqueId

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#169]
The following method returns a unique id, not player.
`func_179819_c`: `getPlayer` -> `getUniqueId`
`field_179820_b`: `playerId` -> `uniqueId`

**Comment by matthewprenger** [comment]
Fixed:
`func_179819_c`: `getPlayer` -> `getUniqueId`
`field_179820_b`: `playerId` -> `uniqueId`
