### ISSUE TITLE
Connection managers

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#170]
These fields represent `NetHandlerPlayClient`, not a send queue:
- `field_71174_a`: `sendQueue` -> `connection`
- `field_73035_a`: `sendQueue` -> `connection`
- `func_147297_a`: `addToSendQueue` -> `sendPacket`

This field represents `NetHandlerPlayServer`, and to be consistent (as well as giving it a nicer name):
- `field_71135_a`: `playerNetServerHandler` -> `connection`

**Comment by matthewprenger** [comment]
Fixed:
`field_71174_a`: `sendQueue` -> `connection`
`field_73035_a`: `sendQueue` -> `connection`
`func_147297_a`: `addToSendQueue` -> `sendPacket`
`field_71135_a`: `playerNetServerHandler` -> `connection`
`func_147114_u`: `getNetHandler` -> `getConnection`
`field_78774_b`: `netClientHandler` -> `connection`
`field_146594_a`: `netHandlerPlayClient` -> `connection`
