### ISSUE TITLE
EntityLivingBase.field_70709_bj / newPosX

### ISSUE THREAD

**Issue by chylex** [ModCoderPack/MCPBot-Issues#171]
It's surrounded by:

    /** The X position the entity will be interpolated to. Used for teleporting. */
    protected double interpTargetX;
    /** The Y position the entity will be interpolated to. Used for teleporting. */
    protected double interpTargetY;
    /** The Z position the entity will be interpolated to. Used for teleporting. */
    protected double interpTargetZ;
    /** The yaw rotation the entity will be interpolated to. Used for teleporting. */
    protected double interpTargetYaw;
    /** The new X position to be applied to the entity. */
    protected double newPosX;

and all usages in the code relate to rotationPitch, so it should be interpTargetPitch with a similar comment (couldn't rename it manually since it already had a name assigned).

**Comment by matthewprenger** [comment]
`field_70709_bj`: `newPosX` -> `interpTargetPitch`
