### ISSUE TITLE
func_72693_b: updatePlayerInstances -> tick; func_152621_a: hasPlayerInstance -> contains

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#172]
- `func_72693_b`: `updatePlayerInstances` -> `tick`
- `func_152621_a`: `hasPlayerInstance` -> `contains`

**Comment by matthewprenger** [comment]
I don't like `contains` because it's checking if it contains a player *in a given chunk*.

**Comment by kashike** [comment]
@matthewprenger No, it's checking if the chunk map contains the given chunk entry. Reference #163

**Comment by matthewprenger** [comment]
Oh derp, right. `contains` sound's good then.

**Comment by matthewprenger** [comment]
`func_72693_b`: `updatePlayerInstances` -> `tick`
`func_152621_a`: `hasPlayerInstance` -> `contains`
