### ISSUE TITLE
field_70170_p: worldObj -> world

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#175]
As far as I can see, there is no reason to keep the `Obj` suffix here. It's redundant and ugly.
`field_70170_p`: `worldObj` -> `world`

**Comment by matthewprenger** [comment]
I'm :+1: to this, but I think it's similar to the `World.isRemote` thing because of how much it's used.

**Comment by kashike** [comment]
https://github.com/ModCoderPack/MCPBot-Issues/issues/294
