### ISSUE TITLE
WorldServer -> ServerWorld 

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#176]
MCP currently names all classes ("old" ones more-so, "newer" ones are named "forwards" (`DedicatedPlayerList`, for example)) "backwards" (`WorldServer` instead of `ServerWorld`, `EntityPlayer` instead of `PlayerEntity`, etc). It would be good for a number of reasons to switch this (change to `ServerWorld` instead of `WorldServer`, etc) to "forwards", the main reason being clarity.
Ex: `WorldServer` to someone who is not familiar with things can be viewed as a "server that controls a world", instead of a "server-side world".

This is certainly not a small change, so comments on opinions would be nice.

**Comment by LexManos** [comment]
Ya, the same argument can be said for ServerWorld, for now this will be staying as is.

**Comment by TheTemportalist** [comment]
I don't know. I'm in favor of writing class name from General to Specific, instead of Specific to General, because it makes searching for types easier. So a WorldServer, to me, sounds like a World which is specific to Servers.

**Comment by gabizou** [comment]
If you were to change the name to `ServerWorld`, you'd have to re-apply the same logic to plenty of other sided named classes/interfaces, including `NetHandlerPlayServer` or `ChunkProviderServer` etc. I'm leaning on keeping it as is as the nomenclature has been maintained for a while. If we started switching as @TheTemportalist towards Specific to General naming, several other classes would have to be renamed as well to represent that decision.

**Comment by kashike** [comment]
@gabizou This can be a generic "Specific to General" issue instead, yes.

**Comment by liach** [comment]
@kashike Is there any status update?
