### ISSUE TITLE
StatisticsFile, StatFileWriter

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#177]
- `StatisticsFile` -> `ServerStatisticManager`
 - This class not only handles reading/writing statistics from file, but also handles sending packets, serialisation, sending messages, etc.
- `StatFileWriter` -> `StatisticManager`
 - This class doesn't do anything related to writing stats to files, or anything similar. It manages a statistic/achievement amount map.

**Comment by LexManos** [comment]
1.9.4:
net/minecraft/stats/StatFileWriter net/minecraft/stats/StatisticsManager
net/minecraft/stats/StatisticsFile net/minecraft/stats/StatisticsManagerServer
