### ISSUE TITLE
field_77333_a: weight -> rarity; func_77324_c: getWeight -> getRarity

### ISSUE THREAD

**Issue by darkhax** [ModCoderPack/MCPBot-Issues#178]
Both of these are from the Enchantment class. The field is the Rarity for the enchantment, and the function is a getter for the Rarity. Both of these are currently refered to as weight and getWeight which has now been moved inside of Rarity. I propose that they be renamed to describe rarity instead of weight. 

`field_77333_a`: `weight` -> `rarity`
`func_77324_c`: `getWeight` -> `getRarity`

**Comment by matthewprenger** [comment]
`field_77333_a`: `weight` -> `rarity`
`func_77324_c`: `getWeight` -> `getRarity`
