### ISSUE TITLE
ChunkCoordIntPair

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#179]
The existing name of this class is rather... ugly. To be consistent with `BlockPos`:
`ChunkCoordIntPair` -> `ChunkPos`

The new name (`ChunkPos`) is accurate and clean, and is consistent with other position/vector classes.

**Comment by darkhax** [comment]
I really like the new name, it is much more efficient at describing what is actually going on.

**Comment by liach** [comment]
Shorter and more descriptive names are always welcomed.

**Comment by LexManos** [comment]
I was really hoping that that class would get a nice re-work to be a bit more like BlockPos with all the helper functions for moving around, but whatever.
1.9.4: 
net/minecraft/world/ChunkCoordIntPair net/minecraft/util/math/ChunkPos
