### ISSUE TITLE
GameRules method names

### ISSUE THREAD

**Issue by jk-5** [ModCoderPack/MCPBot-Issues#18]
I (and i'm sure i am not the only one) really dislike the methods for getting game rule values:
* `getGameRuleStringValue` (`func_82767_a` and `func_82756_a`)
* `getGameRuleBooleanValue` (`func_82766_b` and `func_82758_b`)

While the int version is just called `getInt` (`func_180263_c` and `func_180255_c`)

I think, the string and boolean methods should be renamed to `getString` and `getBoolean`, because the 'gameRule' and 'value' part in the names make zero sense. You are already in GameRules, so the name doesn't need to indicate that.

That said, i suggest also renaming `addGameRule` (`func_180262_a`) to simply `add`.
Same for `writeGameRulesToNBT` (`func_82770_a`) and `readGameRulesFromNBT` (`func_82768_a`) to simply `toNBT` and `fromNBT`.

The impact of this change on existing mods would be small. I wrote a simple tool that analyses bytecode to see if specific methods are called, and i pulled a few complete modpacks through that. There are only a few mods using these methods, including a project i am working on. The impact is small, so i think it's safe to change.

**Comment by bspkrs** [comment]
The value get methods will be fixed in 1.8.8. The NBT methods are fixed to use the standard NBT method names.
