### ISSUE TITLE
field_76578_c, func_76572_b

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#180]
- `field_76578_c`: `worldChunkMgr` -> `biomeProvider`
 - `WorldChunkManager` is now `BiomeProvider` as of #38, so this field name is outdated.
- `func_76572_b`: `registerWorldChunkManager` -> `createBiomeProvider`
 - as in the field above, name is outdated. This also creates the biome provider, it doesn't register it.

**Comment by matthewprenger** [comment]
Fixed:
`field_76578_c`: `worldChunkMgr` -> `biomeProvider`
`func_76572_b`: `registerWorldChunkManager` -> `createBiomeProvider`
