### ISSUE TITLE
func_75382_a: hasPlayerGotBoneInHand -> hasTemptationItemInHand

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#181]
This method doesn't just check if there is a `BONE` in a hand, it checks if it's a bone or if it's a breeding item.
`func_75382_a`: `hasPlayerGotBoneInHand` -> `hasTemptationItemInHand`

**Comment by darkhax** [comment]
I don't know if temptation is the right word here. It fits, but it seems like `hasBreedingItemInHand` or maybe `isHoldingBreedingItem` which is just as descriptive, but is slightly shorter.

**Comment by matthewprenger** [comment]
@darkhax Breeding item doesn't work because it checks for a breeding item OR a bone. I'm leaning towards temptation item or maybe interesting item?

**Comment by TheTemportalist** [comment]
I think temptation is good because breeding items usually lure their entities, hence the temptation

**Comment by bspkrs** [comment]
I think a lure makes more sense. isHoldingLure would be my suggestion.

On Mon, Jun 13, 2016 at 12:05 PM, The Temportalist <notifications@github.com

**Comment by phase** [comment]
`hasLoveItemInHand` or `isHoldingLoveItem`, since using the item makes the animal enter [love mode](https://twitter.com/notch/status/117866152771846145).

**Comment by darkhax** [comment]
@bspkrs lure may be confused with fishing lure. While not probable, we should try to avoid confusing names. 

Perhaps a simple `hasInterestingItem` would work, as it covers all use cases. The issue with breeding or love is that other items like bones are also part of the check. Bones are used for taming rather than breeding.

**Comment by matthewprenger** [comment]
Ok temptation it is.
`func_75382_a`: `hasPlayerGotBoneInHand` -> `hasTemptationItemInHand`
