### ISSUE TITLE
func_78475_f: setupViewBobbing -> applyBobbing

### ISSUE THREAD

**Issue by darkhax** [ModCoderPack/MCPBot-Issues#182]
`func_78475_f` is mapped as `setupViewBobbing` however the purpose of this method seems to have changed. The name `applyBobbing` or `updateBobbing` seems to be more appropriate now. 

`func_78475_f`: `setupViewBobbing` ->  `applyBobbing`

**Comment by kashike** [comment]
`func_78475_f`: `setupViewBobbing` -> `applyBobbing`
