### ISSUE TITLE
func_71019_a: dropPlayerItemWithRandomChoice -> dropItem

### ISSUE THREAD

**Issue by darkhax** [ModCoderPack/MCPBot-Issues#187]
This method is currently mapped as `dropPlayerItemWithRandomChoice` which seems to poorly describe what the method actually does. It seems to just drop the item into the world. Forge overrides this to use their own hook. 

`func_71019_a`: `dropPlayerItemWithRandomChoice` -> `dropItem`

**Comment by matthewprenger** [comment]
`func_71019_a`: `dropPlayerItemWithRandomChoice` -> `dropItem`
