### ISSUE TITLE
EntityFX

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#189]
`EntityFX` (and all children) should be renamed to `Particle`.

**Comment by mezz** [comment]
`EntityFX` are no longer `Entity`, makes perfect sense to me.

**Comment by LexManos** [comment]
1.9.4:
net/minecraft/client/particle/EffectRenderer net/minecraft/client/particle/ParticleManager
net/minecraft/client/particle/EntityFX net/minecraft/client/particle/Particle
net/minecraft/client/particle/EntityAnimatedFX net/minecraft/client/particle/ParticleSimpleAnimated
net/minecraft/client/particle/Barriernet/minecraft/client/particle/ParticleBarrier
net/minecraft/client/particle/EntityAuraFX net/minecraft/client/particle/ParticleSuspendedTown
net/minecraft/client/particle/EntityBlockDustFX net/minecraft/client/particle/ParticleBlockDust
net/minecraft/client/particle/EntityBreakingFX net/minecraft/client/particle/ParticleBreaking
net/minecraft/client/particle/EntityBubbleFX net/minecraft/client/particle/ParticleBubble
net/minecraft/client/particle/EntityCloudFX net/minecraft/client/particle/ParticleCloud
net/minecraft/client/particle/EntityCritFX net/minecraft/client/particle/ParticleSmokeLarge
net/minecraft/client/particle/EntityCrit2FX net/minecraft/client/particle/ParticleCrit
net/minecraft/client/particle/EntityDiggingFX net/minecraft/client/particle/ParticleDigging
net/minecraft/client/particle/EntityDragonBreathFX net/minecraft/client/particle/ParticleDragonBreath
net/minecraft/client/particle/EntityDropParticleFX net/minecraft/client/particle/ParticleDrip
net/minecraft/client/particle/EntityEnchantmentTableParticleFX net/minecraft/client/particle/ParticleEnchantmentTable
net/minecraft/client/particle/EntityEndRodFX net/minecraft/client/particle/ParticleEndRod
net/minecraft/client/particle/EntityExplodeFX net/minecraft/client/particle/ParticleExplosion
net/minecraft/client/particle/EntityFirework net/minecraft/client/particle/ParticleFirework
net/minecraft/client/particle/EntityFirework$OverlayFX net/minecraft/client/particle/ParticleFirework$Overlay
net/minecraft/client/particle/EntityFirework$SparkFX net/minecraft/client/particle/ParticleFirework$Spark
net/minecraft/client/particle/EntityFirework$StarterFX net/minecraft/client/particle/ParticleFirework$Starter
net/minecraft/client/particle/EntityFishWakeFX net/minecraft/client/particle/ParticleWaterWake
net/minecraft/client/particle/EntityFlameFX net/minecraft/client/particle/ParticleFlame
net/minecraft/client/particle/EntityFootStepFX net/minecraft/client/particle/ParticleFootStep
net/minecraft/client/particle/EntityHeartFX net/minecraft/client/particle/ParticleHeart
net/minecraft/client/particle/EntityHugeExplodeFX net/minecraft/client/particle/ParticleExplosionHuge
net/minecraft/client/particle/EntityLargeExplodeFX net/minecraft/client/particle/ParticleExplosionLarge
net/minecraft/client/particle/EntityLavaFX net/minecraft/client/particle/ParticleLava
net/minecraft/client/particle/EntityNoteFX net/minecraft/client/particle/ParticleNote
net/minecraft/client/particle/EntityParticleEmitter net/minecraft/client/particle/ParticleEmitter
net/minecraft/client/particle/EntityPickupFX net/minecraft/client/particle/ParticleItemPickup
net/minecraft/client/particle/EntityPortalFX net/minecraft/client/particle/ParticlePortal
net/minecraft/client/particle/EntityRainFX net/minecraft/client/particle/ParticleRain
net/minecraft/client/particle/EntityReddustFX net/minecraft/client/particle/ParticleRedstone
net/minecraft/client/particle/EntitySmokeFX net/minecraft/client/particle/ParticleSmokeNormal
net/minecraft/client/particle/EntitySnowShovelFX net/minecraft/client/particle/ParticleSnowShovel
net/minecraft/client/particle/EntitySpellParticleFX net/minecraft/client/particle/ParticleSpell
net/minecraft/client/particle/EntitySplashFX net/minecraft/client/particle/ParticleSplash
net/minecraft/client/particle/EntitySuspendFX net/minecraft/client/particle/ParticleSuspend
net/minecraft/client/particle/EntitySweepAttackFX net/minecraft/client/particle/ParticleSweepAttack
net/minecraft/client/particle/MobAppearance net/minecraft/client/particle/ParticleMobAppearance
