### ISSUE TITLE
playEvent - various names

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#192]
These methods are for playing "level events".

- `func_175718_b`: `playAuxSFX` -> `playEvent`
 - This can play more than just sounds.
- `func_180439_a`: `playAuxSFX` -> `playEvent`
 - This can play more than just sounds.
- `p_180439_2_`: `sfxType` -> `type`
- `func_180498_a`: `playAuxSFXAtEntity` -> `playEvent`
 - This can play more than just sounds.
 - Drop redundant `AtEntity`
- `p_180498_2_`: `sfxType` -> `type`

**Comment by matthewprenger** [comment]
Fixed:

`func_175718_b`: `playAuxSFX` -> `playEvent`
`func_180439_a`: `playAuxSFX` -> `playEvent`
`p_180439_2_`: `sfxType` -> `type`
`func_180498_a`: `playAuxSFXAtEntity` -> `playEvent`
`p_180498_2_`: `sfxType` -> `type`
