### ISSUE TITLE
func_180426_a: setPositionAndRotation2 -> setPositionAndRotation

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#197]
`func_180426_a`: `setPositionAndRotation2` -> `setPositionAndRotationDirect`
Unlike `setPositionAndRotation`, this method sets these values "directly", instead of applying any clamping/etc

**Comment by matthewprenger** [comment]
`func_180426_a`: `setPositionAndRotation2` -> `setPositionAndRotationDirect`
