### ISSUE TITLE
Give func_71517_b, func_71518_a, func_71514_a, func_184883_a, and func_180524_a simpler names.

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#199]
- `func_71517_b`: `getCommandName` -> `getName`
  - Redundant `Command` in name
- `func_71518_a`: `getCommandUsage` -> `getUsage`
  - Redundant `Command` in name
- `func_71514_a`: `getCommandAliases` -> `getAliases`
  - Redundant `Command` in name
- `func_184883_a`: `getTabCompletionOptions` -> `getTabCompletions`
  - Remove `Options` to be consistent with `func_184104_a`. This returns a list of possible completions, not completion options/settings
- `func_180524_a`: `getTabCompletionOptions` -> `getTabCompletions`
  - Remove `Options` to be consistent with `func_184104_a`. This returns a list of possible completions, not completion options/settings
- `func_70003_b`: `canCommandSenderUseCommand` -> ~~`hasPermission`~~ `canUseCommand`
  - This method name is unnecessarily verbose.

**Comment by bspkrs** [comment]
done.
