### ISSUE TITLE
Wrong mapping for EntityLivingBase.addRandomArmor

### ISSUE THREAD

**Issue by kenzierocks** [ModCoderPack/MCPBot-Issues#2]
> &lt;kenzierocks&gt; bspkrs: need to fix EntityLivingBase.addRandomArmor, it has a wrong comment and wrong name
&lt;kenzierocks&gt; http://pastebin.com/JC3LEnhY
&lt;kenzierocks&gt; additionally, &lt;AlphaModder&gt; func_180481_a is the right one for addRandomArmor i think

Fix that, may require more investigation for the proper mapping.

**Comment by bspkrs** [comment]
I will try to look at this today. In the future, please read the guidelines on info to provide for mapping defects in the repo readme.

**Comment by kenzierocks** [comment]
Oh, okay.

**Comment by bspkrs** [comment]
Changed to addRandomDrop. func_180481_a has already been named.
