### ISSUE TITLE
IEntitySelector is not an interface

### ISSUE THREAD

**Issue by kenzierocks** [ModCoderPack/MCPBot-Issues#20]
This is slightly annoying, and also has things listed as implementing when...it's a final class. Much confusion.

**Comment by bspkrs** [comment]
I can't actually fix this until we update to a new MC version. I will leave it open.

**Comment by LexManos** [comment]
Fixed in 1.8.1+ renamed to net.minecraft.util.EntitySelectors.

**Comment by bspkrs** [comment]
Will be fixed when the bot is updated.
