### ISSUE TITLE
Update method/param names after #98 rename

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#200]
- `func_152372_a`: `notifyOperators` -> `notifyListener`
 - #98 - this notifies the command listener, which isn't limited to operators
- `p_152372_4_`: `msgFormat` -> `translationKey`
 - this is a translation key, not a message format
- `p_152372_5_`: `msgParams` -> `translationArgs`
 - this is the arguments for the translation, not message params
- `func_152373_a`: `notifyOperators` -> `notifyCommandListener`
 - #98 - this notifies the command listener, which isn't limited to operators
- `p_152373_2_`: `msgFormat` -> `translationKey`
 - this is a translation key, not a message format
- `p_152373_3_`: `msgParams` -> `translationArgs`
 - this is the arguments for the translation, not message params
- `func_152374_a`: `notifyOperators` -> `notifyCommandListener`
 - #98 - this notifies the command listener, which isn't limited to operators
- `p_152374_3_`: `msgFormat` -> `translationKey`
 - this is a translation key, not a message format
- `p_152374_4_`: `msgParams` -> `translationArgs`
 - this is the arguments for the translation, not message params

**Comment by matthewprenger** [comment]
Fixed:
`func_152372_a`: `notifyOperators` -> `notifyListener`
`p_152372_4_`: `msgFormat` -> `translationKey`
`p_152372_5_`: `msgParams` -> `translationArgs`
`func_152373_a`: `notifyOperators` -> `notifyCommandListener`
`p_152373_2_`: `msgFormat` -> `translationKey`
`p_152373_3_`: `msgParams` -> `translationArgs`
`func_152374_a`: `notifyOperators` -> `notifyCommandListener`
`p_152374_3_`: `msgFormat` -> `translationKey`
`p_152374_4_`: `msgParams` -> `translationArgs`
