### ISSUE TITLE
Simpler method names for: func_72791_a, func_72786_a, func_72785_a, func_72790_b, func_72788_a, func_151247_a, field_72793_b, and func_111190_b

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#204]
- `func_72791_a`: `trackEntity` -> `track`
  - Remove redundant `Entity` from name
- `func_72786_a`: `trackEntity` -> `track`
  - Remove redundant `Entity` from name
- `func_72785_a`: `addEntityToTracker` -> `track`
  - Be consistent with other `track` methods
- `func_72790_b`: `untrackEntity` -> `untrack`
  - Remove redundant `Entity` from name
- `func_72788_a`: `updateTrackedEntities` -> `tick`
  - The current name is verbose, and can be shortened to `tick` - consistent with other methods ticking.
- `func_151247_a`: `sendToAllTrackingEntity` -> `sendToTracking`
  - Verbose, can be shortened
- `field_72793_b`: `trackedEntities` -> `entries`
  - This is a set of `EntityTrackerEntry` (entries), not `Entity` (entities).
- `func_111190_b`: `sendMetadataToAllAssociatedPlayers` -> `sendMetadata`
  - Method name is unnecessarily long and verbose

**Comment by matthewprenger** [comment]
Done:
`func_72791_a`: `trackEntity` -> `track`
`func_72786_a`: `trackEntity` -> `track`
`func_72785_a`: `addEntityToTracker` -> `track`
`func_72790_b`: `untrackEntity` -> `untrack`
`func_72788_a`: `updateTrackedEntities` -> `tick`
`func_151247_a`: `sendToAllTrackingEntity` -> `sendToTracking`
`field_72793_b`: `trackedEntities` -> `entries`
`func_111190_b`: `sendMetadataToAllAssociatedPlayers` -> `sendMetadata`
