### ISSUE TITLE
func_70082_c: setAngles -> turn

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#206]
- `func_70082_c`: `setAngles` -> `turn`
  - To be consistent with the move method, `set` should be dropped from this method and it should be named `turn`, seeing how this method turns the entity.

Thoughts?

**Comment by Lunatrius** [comment]
`turn` sounds like it turns the entity *relatively* to the previous state - `turnTo` might be a better alternative.

**Comment by kenzierocks** [comment]
@Lunatrius it is relative to the previous state, I would argue in favor of `turn` here.

**Comment by kashike** [comment]
`func_70082_c`: `setAngles` -> `turn`
