### ISSUE TITLE
func_71384_a/startGame, func_71197_b/startServer -> init

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#208]
These methods are both called to initialise the client/server, so it makes sense to use the same name for consistency.
- `func_71384_a`: `startGame` -> `init`
- `func_71197_b`: `startServer` -> `init`

**Comment by matthewprenger** [comment]
Done:
`func_71384_a`: `startGame` -> `init`
`func_71197_b`: `startServer` -> `init`
