### ISSUE TITLE
WeightedRandomChestContent field names

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#21]
WeightedRandomChestContent has two fields named `theMinimumChanceToGenerateItem` and `theMaximumChanceToGenerateItem`. (`field_76295_d` and `field_76296_e` in 1.8)

Besides the obvious mouthful of words, these names are incorrect. If you look further down the class, at generateChestContents (`func_177630_a`), Minecraft picks a random number between these two fields, then assigns it to the *stack size* of the generated item. It has nothing to do with generation chance. (Forge forwards this to a method in ChestGenHooks that uses these fields as stacksize limits as well)

I propose that these two fields be renamed to `minStackSize` and `maxStackSize` to correct this.

**Comment by bspkrs** [comment]
Done.
