### ISSUE TITLE
Block.getSelectedBoundingBox and getCollisionBoundingBox should be swapped.

### ISSUE THREAD

**Issue by Zaggy1024** [ModCoderPack/MCPBot-Issues#210]
Block.getSelectedBoundingBox is called to get the collision bounds, and getCollisionBoundingBox is called by RenderGlobal.drawSelectionBox.

**Comment by kashike** [comment]
This was fixed with 1.9.

**Comment by Zaggy1024** [comment]
Hm, this problem is in the version of 1.9 mappings I have, but perhaps it's been fixed since. My mappings are set to "snapshot_20160326".

**Comment by kashike** [comment]
Can you point me to what is causing you to think these are reversed?

**Comment by Zaggy1024** [comment]
Has been fixed, I was just out of date, apparently. :)
