### ISSUE TITLE
Container listener-related members

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#214]
- `func_75132_a`: `onCraftGuiOpened` -> `addListener`
 - This method adds a listener to the `Container`.
- `func_82847_b`: `removeCraftingFromCrafters` -> `removeListener`
 - This method removes a listener to the `Container`.
- `p_82847_1_`: `listeners` -> `listener`
 - We're removing a single listener, not many.
- `field_75149_d`: `crafters` -> `listeners`
 - This is a list of listeners, not crafters.

related: #213

**Comment by matthewprenger** [comment]
`func_82847_b`: `removeCraftingFromCrafters` -> `removeListener`
`p_82847_1_`: `listeners` -> `listener`
`field_75149_d`: `crafters` -> `listeners`

`func_75132_a` is locked so I'll let @bspkrs decide what to do about that one. It really should be renamed to `addListener`.

**Comment by bspkrs** [comment]
Fixed.
