### ISSUE TITLE
field_145850_b: worldObj -> world

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#215]
As far as I can see, there is no reason to keep the `Obj` suffix here. It's redundant and ugly.
`field_145850_b`: `worldObj` -> `world`

related: #175

**Comment by killjoy1221** [comment]
From what I remember from a discussion somewhere, this is because mcpbot has name restrictions so you can't name a field the same as its type. I'm for this, but we'd might as well find all the other fields named like this and change them as well.

**Comment by kashike** [comment]
@killjoy1221 You **can** name fields the same as it's type. You **can't** name parameters the same as it's MCP type.
Permitted:
- field `public World world`
- parameter `World worldIn`
- parameter `Random random`
 - Only MCP types have the parameter naming restriction.

Not Permitted:
- parameter `World world`

**Comment by iTitus** [comment]
Finally ;)

**Comment by kashike** [comment]
https://github.com/ModCoderPack/MCPBot-Issues/issues/294
