### ISSUE TITLE
Finish renaming chat components to text components

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#217]
To finish up #73
- `func_179258_d`: `readChatComponent` -> `readTextComponent`
- `func_179256_a`: `writeChatComponent` -> `writeTextComponent`
- `func_150869_b`: `matchEntitiesToChatComponent` -> `matchEntitiesToTextComponent`
- `func_151000_E`: `getChatComponent` -> `getTextComponent`

**Comment by matthewprenger** [comment]
Fixed:
`func_179258_d`: `readChatComponent` -> `readTextComponent`
`func_179256_a`: `writeChatComponent` -> `writeTextComponent`
`func_150869_b`: `matchEntitiesToChatComponent` -> `matchEntitiesToTextComponent`
`func_151000_E`: `getChatComponent` -> `getTextComponent`
