### ISSUE TITLE
Rename text sending methods (func_145747_a, func_146105_b)

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#218]
- `func_145747_a`: `addChatMessage` -> `sendMessage`
  - This method isn't guaranteed to be sending a **chat** message, it sends a message in general.
- `func_146105_b`: `addChatComponentMessage` -> `sendStatusMessage`
  - Used when trying to sleep, and with the `Structure` Block -- sends a "status" message to the player

**Comment by bspkrs** [comment]
done.
