### ISSUE TITLE
Cleanup PacketBuffer read/write method names

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#219]
- `func_150792_a`: `readVarIntFromBuffer` -> `readVarInt`
- `func_150787_b`: `writeVarIntToBuffer` -> `writeVarInt`
- `func_150793_b`: `readNBTTagCompoundFromBuffer` -> `readCompoundTag`
- `func_150786_`: `writeNBTTagCompoundToBuffer` -> `writeCompoundTag`
- `func_150791_c`: `readItemStackFromBuffer` -> `readItemStack`
- `func_150788_a`: `writeItemStackToBuffer` -> `writeItemStack`
- `func_150789_c`: `readStringFromBuffer` -> `readString`
- `func_179253_g`: `readUuid` -> `readUniqueId`
- `func_179252_a`: `writeUuid` -> `writeUniqueId`

**Comment by mezz** [comment]
These look good to me except the UUID changes. I think those two are fine as-is. 

The only reason to change them would be to get around the confusion about capitalizing acronyms in camel case. I think most people prefer the capitalization style that's there, `readUuid` http://stackoverflow.com/questions/15526107/acronyms-in-camelcase

**Comment by kashike** [comment]
@mezz `UniqueId` is used quite often throughout the MCP mappings, so it makes sense to start matching with them

**Comment by mezz** [comment]
I don't really understand the reasoning, but in that case these changes look good to me.

**Comment by diesieben07** [comment]
Since this still has the "comments wanted" label: yes, please!

**Comment by matthewprenger** [comment]
Done:
`func_150792_a`: `readVarIntFromBuffer` -> `readVarInt`
`func_150787_b`: `writeVarIntToBuffer` -> `writeVarInt`
`func_150793_b`: `readNBTTagCompoundFromBuffer` -> `readCompoundTag`
`func_150786_a`: `writeNBTTagCompoundToBuffer` -> `writeCompoundTag`
`func_150791_c`: `readItemStackFromBuffer` -> `readItemStack`
`func_150788_a`: `writeItemStackToBuffer` -> `writeItemStack`
`func_150789_c`: `readStringFromBuffer` -> `readString`
`func_179253_g`: `readUuid` -> `readUniqueId`
`func_179252_a`: `writeUuid` -> `writeUniqueId`
