### ISSUE TITLE
func_147360_c: kickPlayerFromServer -> disconnect

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#220]
Unnecessarily long name. This method disconnects the player.
`func_147360_c`: `kickPlayerFromServer` -> `disconnect` (or `kick`)

**Comment by micahcowan** [comment]
Couldn't `disconnect` sound like the game itself might be disconnecting from a remote server? I think the word is ambiguous/sounds like something to be paired with a `connect` method.

What about `kickPlayer` or similar (dropping the useless suffix)?

**Comment by kashike** [comment]
Just `kick`, then. `Player` is also redundant.

**Comment by micahcowan** [comment]
gp :)

**Comment by kashike** [comment]
@micahcowan "gp"?

**Comment by micahcowan** [comment]
"good point" :)
