### ISSUE TITLE
EntityFX.xSpeed, ySpeed and zSpeed are inconsistent with Entity.motionX, motionY, motionZ.

### ISSUE THREAD

**Issue by Zaggy1024** [ModCoderPack/MCPBot-Issues#225]
It seems logical for the two classes to have their fields be named the same thing, if possible.

**Comment by micahcowan** [comment]
I'm the one that named the `EntityFX` ones, and FWIW I agree with @Zaggy1024. Whichever direction makes the most sense (but the `motionX` ones have seniority I believe ;) ).

**Comment by mezz** [comment]
As I'm changing over all my particle's motionX into xSpeed, it feels very silly. It would be nicer and more consistent to keep motionX, which matches `Entity` and is the way it was before.

**Comment by matthewprenger** [comment]
Fixed:
`field_187129_i`: `xSpeed` -> `motionX`
`field_187130_j`: `ySpeed` -> `motionY`
`field_187131_k`: `zSpeed` -> `motionZ`
