### ISSUE TITLE
func_180614_a: onItemUse -> onRightClickBlock and func_77659_a: onItemRightClick -> onRightClick

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#226]
- `func_180614_a`: `onItemUse` -> `onRightClickBlock`
- `func_77659_a`: `onItemRightClick` -> `onRightClick`
  - redundant `Item`

**Comment by bspkrs** [comment]
Item 1 requires a lot of other renamings to be consistent, so it won't be done.
Item 2 makes sense, but would also require a lot of other renamings to be consistent, so it won't be done.
Sorry.
