### ISSUE TITLE
Bring some sanity to MathHelper method names

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#229]
- `func_82716_a`: `getRandomDoubleInRange` -> `nextDouble`
- `func_76123_f`: `ceiling_float_int` -> `ceil`
- `func_76128_c`: `floor_double` -> `floor`
- `func_76137_a`: `bucketInt` -> `intFloorDiv`
- `func_76125_a`: `clamp_int` -> `clamp`
- `func_151238_b`: `denormalizeClamp` -> `clampedLerp`
- `func_76143_f`: `ceiling_double_int` -> `ceil`
- `func_76124_d`: `floor_double_long` -> `lfloor`
- `func_76133_a`: `sqrt_double` -> `sqrt`
- `func_151237_a`: `clamp_double` -> `clamp`
- `func_82714_a`: `parseIntWithDefault` -> `getInt`
- `func_82712_a`: `parseDoubleWithDefault` -> `getDouble`
- `func_151239_c`: `calculateLogBaseTwo` -> `log2`
- `func_151236_b`: `roundUpToPowerOfTwo` -> `smallestEncompassingPowerOfTwo`
- `func_76129_c`: `sqrt_float` -> `sqrt`
- `func_82714_a`: `parseIntWithDefaultAndMax` -> `getInt`
- `func_76140_b`: `truncateDoubleToInt` -> `fastFloor`
- `func_76132_a`: `abs_max` -> `absMax`
- `func_151240_a`: `randomFloatClamp` -> `nextFloat`
- `func_76131_a`: `clamp_float` -> `clamp`
- `func_82713_a`: `parseDoubleWithDefaultAndMax` -> `getDouble`
- `func_76141_d`: `floor_float` -> `floor`
- `func_76130_a`: `abs_int` -> `abs`
- `func_76136_a`: `getRandomIntegerInRange` -> `nextInt`
- `func_151241_e`: `calculateLogBaseTwoDeBruijn` -> `log2DeBruijn`
- `func_180182_a`: `getRandomUuid` -> `getRandomUUID`  (there already is another `getRandomUUID`, change this one to keep consistency)
- `func_188208_f`: `getHash` -> `hash` (more consistent with JDK methods like Objects.hash)

Majority of names taken from `RealmsMth`.
Comments welcome.

**Comment by TheTemportalist** [comment]
This sounds good to me as it keeps in line with java standards

**Comment by bspkrs** [comment]
done.
