### ISSUE TITLE
Server cant find constructor

### ISSUE THREAD

**Issue by Wuerfel21** [ModCoderPack/MCPBot-Issues#23]
It seems like the constructor for EntityLargeFireball(World,DDDDDD) isnt available on servers, while both MCPBot and the javadoc say its there...
At least thats what i think this crash means:(only on servers, note that i tried without fastcraft with the same results) pastebin.com/RSyLyB4p

**Comment by matthewprenger** [comment]
It exists in the client jar only. If you look at the source with FML, you will see that the constructor has a `@SideOnly(Side.CLIENT)` annotation on it.

**Comment by Wuerfel21** [comment]
But why would it be? It makes no sense!


-------- Ursprüngliche Nachricht --------
Von: Matthew Prenger <notifications@github.com> 
Datum:22.05.2015  00:29  (GMT+01:00) 
An: ModCoderPack/MCPBot-Issues <MCPBot-Issues@noreply.github.com> 
Cc: Wuerfel21 <nunuu@gmx.net> 
Betreff: Re: [MCPBot-Issues] Server cant find constructor (#23) 

It exists in the client jar only. If you look at the source with FML, you will see that the constructor has a @SideOnly(Side.CLIENT) annotation on it.

**Comment by matthewprenger** [comment]
Because the vanilla server never uses that constructor, so at obfuscation time, it gets stripped out.

**Comment by Wuerfel21** [comment]
Then they shall go and fix their obsfuscstion, while for the time being, can i be told which constructors are not client only?


-------- Ursprüngliche Nachricht --------
Von: Matthew Prenger <notifications@github.com> 
Datum:22.05.2015  00:45  (GMT+01:00) 
An: ModCoderPack/MCPBot-Issues <MCPBot-Issues@noreply.github.com> 
Cc: Wuerfel21 <nunuu@gmx.net> 
Betreff: Re: [MCPBot-Issues] Server cant find constructor (#23) 

Because the vanilla server never uses that constructor, so at obfuscation time, it gets stripped out.

**Comment by bspkrs** [comment]
You should submit a PR to Forge to have it added to the server jar if you need it. It would be in the form of a patch.
