### ISSUE TITLE
func_82688_a: setReputationForPlayer -> addPlayerReputation and func_82684_a: getReputationForPlayer -> getPlayerReputation

### ISSUE THREAD

**Issue by PaleoCrafter** [ModCoderPack/MCPBot-Issues#230]
`Village.setReputationForPlayer` really adds to the existing reputation, the method probably was named while the method still set the value.

Since `addReputationForPlayer` sounds bad and to keep consistency, `Village.getReputationForPlayer` should also be changed to `getPlayerReputation`.

**Comment by matthewprenger** [comment]
Fixed:
`func_82688_a`:  `setReputationForPlayer` -> `modifyPlayerReputation`     (went with modify because it takes + and -)
`func_82684_a`: `getReputationForPlayer` -> `getPlayerReputation`
