### ISSUE TITLE
CPacketPlayer inner classes aren't renamed

### ISSUE THREAD

**Issue by gabizou** [ModCoderPack/MCPBot-Issues#231]
While all the outer classes have been renamed to exclude the packet index, the inner classes of `CPacketPlayer` have not been changed. Currently they are:
- `C04PacketPlayerPosition`
- `C05PacketPlayerLook`
- `C06PacketPlayerPosLook`

I'm not sure if other inner packet classes need to be renamed, but I just came across this today.

**Comment by LexManos** [comment]
1.9.4:

net/minecraft/network/play/client/CPacketPlayer$C04PacketPlayerPosition net/minecraft/network/play/client/CPacketPlayer$Position
net/minecraft/network/play/client/CPacketPlayer$C06PacketPlayerPosLook net/minecraft/network/play/client/CPacketPlayer$PositionRotation
net/minecraft/network/play/client/CPacketPlayer$C05PacketPlayerLook net/minecraft/network/play/client/CPacketPlayer$Rotation
