### ISSUE TITLE
Rename func_184595_k (teleportTo_)

### ISSUE THREAD

**Issue by gabizou** [ModCoderPack/MCPBot-Issues#235]
As it stands: `EntityLivingBase.teleportTo_` returns a `boolean` on whether the teleport was successful (either due to the position being loaded or considered "safe"), and returns false if the teleport was unsuccessful such that the position of the entity is reset back to before movement took place.

Possible renames could be:
- `attemptTeleport`
- `teleportIfSafe`
- `attemptSafeTeleport`

But overall, `teleportTo_` is kinda non-descriptive of what is actually happening behind the scenes.

**Comment by kashike** [comment]
:+1: for `attemptTeleport`

**Comment by matthewprenger** [comment]
`func_184595_k`: `teleportTo_` -> `attemptTeleport`
