### ISSUE TITLE
Rename `parX` to be meaningful

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#237]
- `p_179691_1_`: `par1` -> `enterDoors`
- `p_179685_1_`: `par1` -> `avoidSun`
- `p_77034_1_`: `par1` -> `prevYawOffset`
- `p_146070_1_`: `par1` -> `enabled`
- `p_77034_2_`: `par2` -> `yawOffset`
- `p_77034_3_`: `par3` -> `partialTicks`

**Comment by matthewprenger** [comment]
`p_179691_1_`: `par1` -> `enterDoors`
`p_179685_1_`: `par1` -> `avoidSun`
`p_77034_1_`: `par1` -> `prevYawOffset`
`p_146070_1_`: `par1` -> `enabled`
`p_77034_2_`: `par2` -> `yawOffset`
`p_77034_3_`: `par3` -> `partialTicks`
