### ISSUE TITLE
func_72953_d: isAnyLiquid -> containsAnyLiquid

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#240]
This method checks if the provided AABB contains any liquid, not if the AABB is a liquid.
`func_72953_d`: `isAnyLiquid` -> `containsAnyLiquid`

**Comment by matthewprenger** [comment]
Fixed:
`func_72953_d`: `isAnyLiquid` -> `containsAnyLiquid`
