### ISSUE TITLE
func_146980_g in GuiContainerCreative should be func_175378_g

### ISSUE THREAD

**Issue by maruohon** [ModCoderPack/MCPBot-Issues#242]
There is a broken mapping in GuiContainerCreative: what should be func_175378_g() aka. updateActivePotionEffects() is still named func_146980_g aka. updateDragSplitting().
This is (afaik) the last remaining broken thing related to the recent issue in #186.

**Comment by matthewprenger** [comment]
Yup looks like this is broken.

@bspkrs line 21606 of the current joined.srg: 
`MD: bgc/a ()V net/minecraft/client/gui/inventory/GuiContainerCreative/func_146980_g ()V` 
should be changed to: 
`MD: bgc/a ()V net/minecraft/client/gui/inventory/GuiContainerCreative/func_175378_g ()V`

**Comment by bspkrs** [comment]
I blame 19 hour work days. I had generated the new srg/csrg files, but never actually updated the artifacts. Check it now.

**Comment by maruohon** [comment]
Okay so now the updateActivePotionEffects method seems fine in InventoryEffectRenderer and GuiContainerCreative classes. But now the updateDragSplitting method in GuiContainer is also once again called updateActivePotionEffects in my dev environment, but not in MCPBot. What is going on...?

How exactly do these changes propagate/take effect? I ran ./gradlew setupDecompWorkspace --refresh-dependencies --info to re-setup my dev environment. And when will these changes be available in Forge so that I can make my mod depend on the correct version? In the next build made after this?

**Comment by matthewprenger** [comment]
Heh @bspkrs found one more.
Line 21486: `MD: bft/a ()V net/minecraft/client/gui/inventory/GuiContainer/func_175378_g ()V`
should be: `MD: bft/a ()V net/minecraft/client/gui/inventory/GuiContainer/func_146980_g ()V`

**Comment by bspkrs** [comment]
fixed.
