### ISSUE TITLE
Mirror enum field names don't seem logical.

### ISSUE THREAD

**Issue by Zaggy1024** [ModCoderPack/MCPBot-Issues#243]
In the enum `Mirror`, there are fields `LEFT_RIGHT` and `FRONT_BACK`. These names give no idea of what the axis is in world coordinates, and all uses of `LEFT_RIGHT` appear to be mirroring North/South, and `FRONT_BACK` mirroring East/West.

The fields should probably be renamed to contain the cardinal directions (like `NORTH_SOUTH`) or the axis (but this is less desirable since it would conflict with `EnumFacing.Axis`'s fields if imported statically).

**Comment by gabizou** [comment]
Since enums are non-obfuscated by default (you can't change an enum's name since it's provided in the byte code, regardless of obfuscation), the values do make sense as they're not "north-south" they're according to the facing value, as suggested by the `mirror(EnumFacing)EnumFacing` method.

**Comment by Zaggy1024** [comment]
Hm, the way I saw them used in Block.withMirror made me think it was mirroring along global axes.

**Comment by matthewprenger** [comment]
Yes, gabizou is right. `NONE`, `LEFT_RIGHT`, and `FRONT_BACK` are the names that Mojang uses for those enum values, so they won't be renamed by mcp.
