### ISSUE TITLE
Rename world data delegate methods.

### ISSUE THREAD

**Issue by darkhax** [ModCoderPack/MCPBot-Issues#246]
- `func_72943_a`: `loadItemData` -> `loadWorldData`
- `func_72823_a`: `setItemData` -> `setWorldData`

These methods are used to get/set WorldSavedData objects from/to a world. Vanilla uses to to save item data, however many mods make use of this to store custom world data as well.

**Comment by gabizou** [comment]
Except it's not limited to `WorldSavedData`, structures use it and there are other uses for it, but naming it  `loadWorldData` doesn't quite cut it imo.

**Comment by kashike** [comment]
- `func_72943_a`: `loadItemData` -> `getOrLoadSaveData`
- `func_72823_a`: `setItemData` -> `setSaveData`

**Comment by darkhax** [comment]
@gabizou @kashike In this situation I am using World because the return type is a WorldSavedData. While structures do make use of this method as well, they are still saving it to a World. Using save sounds like a bit of an over reach though, because a save has multiple worlds, however this method is world specific. Perhaps it might be best to reuse the names from the internal methods which are `getData` and `loadData`

**Comment by bspkrs** [comment]
- `func_72943_a`: `loadItemData` -> `loadData`
- `func_72823_a`: `setItemData` -> `setData`
