### ISSUE TITLE
Names for village creation params

### ISSUE THREAD

**Issue by mezz** [ModCoderPack/MCPBot-Issues#253]
The code leading up to the Forge Village hook `VillagerRegistry.getVillageComponent` is really confusing because most of the parameters are unnamed. This should clear up a decent amount of it. After this I'll clean up the parameter names on the Forge side as well.

Unfortunately Mojang has used lots of private static methods and not interfaces, so it's not possible for me to label all the MCP names for specific components without spending a lot more time. These additions should make it easier to figure out at least.

There seems to be a general mixup between "pieces" and "components", they need to be unified as one name. Most things seem to use component.
These are private static and should be safe to change:
`func_176067_c` : `generatePieceFromSmallDoor` -> `generateComponent`
`func_176066_d` : `generateAndAddPiece` -> `generateAndAddComponent`
`func_176065_a` : `findAndCreatePieceFactory` -> `findAndCreateComponentFactory`

And now some parameter names:

`p_176065_2_` -> `structureComponents`
`p_176065_4_` -> `structureMinX`
`p_176065_5_` -> `structureMinY`
`p_176065_6_` -> `structureMinZ`
`p_176065_8_` -> `componentType`

`p_176066_1_` -> `structureComponents`
`p_176066_3_` -> `structureMinX`
`p_176066_4_` -> `structureMinY`
`p_176066_5_` -> `structureMinZ`
`p_176066_7_` -> `componentType`

`p_176067_1_` -> `structureComponents`
`p_176067_3_` -> `structureMinX`
`p_176067_4_` -> `structureMinY`
`p_176067_5_` -> `structureMinZ`
`p_176067_7_` -> `componentType`

`p_75085_1_` -> `componentType`

`p_175897_0_` -> `structureMinX`
`p_175897_1_` -> `structureMinY`
`p_175897_2_` -> `structureMinZ`
`p_175897_3_` -> `xMin`
`p_175897_4_` -> `yMin`
`p_175897_5_` -> `zMin`
`p_175897_6_` -> `xMax`
`p_175897_7_` -> `yMax`
`p_175897_8_` -> `zMax`
`p_175897_9_` -> `facing`

`p_74891_2_` -> `structureComponents`

`p_74894_2_` -> `structureComponents`

**Comment by matthewprenger** [comment]
Fixed:
`func_176067_c`: `generatePieceFromSmallDoor` -> `generateComponent`
`func_176066_d`: `generateAndAddPiece` -> `generateAndAddComponent`
`func_176065_a`: `findAndCreatePieceFactory` -> `findAndCreateComponentFactory`

I've informed mezz that he can name the params himself as they are not currently named.
