### ISSUE TITLE
`minecraft:piston_head` and `minecraft:piston_extension` map to incorrect block class names

### ISSUE THREAD

**Issue by Aaron1011** [ModCoderPack/MCPBot-Issues#254]
The block `minecraft:piston_head` has a corresponding block class of `BlockPistonExtension`, even though the block id is correct.

Similarly, `minecraft:piston_extension`'s block class is `BlockPistonMoving`, when it should be named `BlockPistionExtension`.

**Comment by matthewprenger** [comment]
:+1: 
```java
registerBlock(36, "piston_extension", new BlockPistonMoving());
registerBlock(34, "piston_head", (new BlockPistonExtension()).setUnlocalizedName("pistonBase"));
```

**Comment by LexManos** [comment]
Moving is the block WHILE its moving.
Extension is the extension part of the block once it's finished.
I don't see a reason to rename the extension to 'head' because it is more then the head, its the head and arm, and in custom pistons sometimes more.

Ignore the registry names.

**Comment by Aaron1011** [comment]
I suppose so. My main concern was the fact that `piston_extension` doesn't correspond to `BlockPistonExtension`, but It doesn't matter that much.
