### ISSUE TITLE
Rename ItemBucket.isFull (field_77876_a ) to filledBlock

### ISSUE THREAD

**Issue by gabizou** [ModCoderPack/MCPBot-Issues#255]
This isn't so much of an error versus readability request. Currently, `ItemBucket` has various checks for whether the `this.isFull == Blocks.AIR` and other similar if checks, but it's not a `boolean`, it's flat out a check on "what `Block` is this bucket filled with?".

Possible names:
- `filledBlock`
- `blockType`
- `bucketBlock`

Edit: Best suggestion from comments: `containedBlock`

**Comment by jamierocks** [comment]
`blockFill`?

**Comment by shadowfacts** [comment]
`containedBlock` IMO, because it says what it is (a block) as well as what it represents (the fluid block contained in the bucket).

**Comment by kashike** [comment]
:+1: @shadowfacts

**Comment by iTitus** [comment]
What about `containedFluidBlock` ?

**Comment by gabizou** [comment]
> What about containedFluidBlock ?

Not really necessary to say it's a fluid block, granted in most cases it *should be*, but there's possibilities of it not being a fluid block ;)

**Comment by matthewprenger** [comment]
Fixed:
`field_77876_a`: `isFull` -> `containedBlock`
