### ISSUE TITLE
[Request] Bot functions to set Nullable annotations

### ISSUE THREAD

**Issue by mezz** [ModCoderPack/MCPBot-Issues#257]
Minecraft 1.9.4 brings us nullability annotation information, yay!
Unfortunately, some of them are incorrect and can lead to problems.

For example, `ItemOverrideList.handleItemState()` has parameters `p_handleItemState_3_` and `p_handleItemState_4_` that should be marked `@Nullable`. (see where they get used for `ItemOverrideList.applyOverride()`)

For a more problematic example, see `Minecraft.getConnection()` which can clearly return null but is treated as `@Nonnull` by default.
```java
public NetHandlerPlayClient getConnection() {
    return this.thePlayer != null?this.thePlayer.connection:null;
}
```

Since it will probably take forever for Mojang to fix these, it would be nice to have a feature in MCPBot to add the `@Nullable` to things, and perhaps even remove incorrect `@Nullable` annotations.

**Comment by LexManos** [comment]
No, Annotations are taken from the bytecode themselves we do NOT inject them.
The annotations you get are directly from mojang and correct.

**Comment by mezz** [comment]
The core issue that I want to bring up is that the annotations are not all correct for the code itself.
Is there somewhere else to discuss it?

**Comment by iTitus** [comment]
If you look at RenderGlobal.ContainerLocalRenderInformation you can see that its constructor has a @Nullable annotation for an `int`:
`private ContainerLocalRenderInformation(RenderChunk renderChunkIn, EnumFacing facingIn, @Nullable int counterIn)`
A way to fix those kind of issues would be nice.

**Comment by simon816** [comment]
It looks like it may be an off-by-one.
From the 1.9.4.jar:
![](http://puu.sh/oYULO/2b25d2d268.png)
The `@Nullable` is on the parameter `cs` which is `EnumFacing`

**Comment by iTitus** [comment]
Interesting ;)
So this is not a problem with the annotation but rather one with S2S or something.
