### ISSUE TITLE
net.minecraft.client.renderer.VertexBuffer -> BufferBuilder

### ISSUE THREAD

**Issue by Zaggy1024** [ModCoderPack/MCPBot-Issues#258]
According to a debug message in that class ("Needed to grow BufferBuilder buffer"), its proper name is BufferBuilder. Also, the name VertexBuffer conflicts with net.minecraft.client.renderer.vertex.VertexBuffer, which is a container for a vertex buffer object on the GPU.

**Comment by bs2609** [comment]
Also worth noting `VertexBufferUploader.field_178179_a` (`vertexBuffer`) is named after this particular `VertexBuffer`, so it should be changed also.
