### ISSUE TITLE
Problems with bot while trying to set method name of a 1.9.4 method.

### ISSUE THREAD

**Issue by iTitus** [ModCoderPack/MCPBot-Issues#259]
1.9.4 introduced the method `TileEntity.getUpdateTag()`. The srg name is (verified with MCP bot and Mappingsviewer) `func_189517_E_`.
When I do the !gm command it shows the method is UNLOCKED. So I should be do change the method name, right?
But when I type `!sf func_189517_E_ getInitialSyncTag` it says:
```
-MCPBot_Reborn- === Set Field: func_189517_E_ ===
-MCPBot_Reborn- Unable to find field func_189517_E_ in version 9.28!
```

Did I do something wrong when using the bot?
The desired name change is `TileEntity.getUpdateTag()` -> `getInitialSyncTag()`.

**Comment by iTitus** [comment]
After an IRC talk I came across the issue here ;) You cannot rename already renamed methods.
But the error message is pretty unclear.
So @matthewprenger, do you mind fixing?

**Comment by williewillus** [comment]
I disagree with this renaming
getUpdateTag is perfectly fine for this method
If you look at its uses, vanilla uses getUpdateTag() to create SPacketUpdateTileEntity's which are NOT for initial syncing
This method is merely a generic "get compound you want to send to client" method

**Comment by iTitus** [comment]
Then I would suggest a Javadoc stating the main use of the method.

**Comment by LexManos** [comment]
func's are not Fields.

**Comment by iTitus** [comment]
Ah. Thanks. That was a derp on my side
