### ISSUE TITLE
handleHealthUpdate actually seems to handle logic opcodes

### ISSUE THREAD

**Issue by clienthax** [ModCoderPack/MCPBot-Issues#26]
handleHealthUpdate is wrong, needs to be something like processLogicOpcode

1: rabbit running particles / spawner delay reset
2: entity hit process (plays hurt sound)
3: death
4: iron golem throw attack

6: tame effect failed
7: tame effect succeed
8: wolf shake
9: finish using item
10: ignite tnt minecart, sheep timer?
11: iron golem hold rose
12: spawnheart villager
13: spawn angry villager particle
14: spawn happy villager particle
15: spawn witch particles
16: play zombie sound

17: create fireworks
18: spawn heart particles
19: reset squid rotation to 0
20: spawn explosion particles, 
21: play guardian sound
22: reduce debug
23: full debug

**Comment by bspkrs** [comment]
In 1.8.8 it will change to handleStatusUpdate
