### ISSUE TITLE
Rename legacy BiomeGenBase methods

### ISSUE THREAD

**Issue by shadowfacts** [ModCoderPack/MCPBot-Issues#260]
With the advent of #162, the methods that were named based on the old `BiomeGenBase` name should be updated to reflect the new `Biome` name.

These are all the usages I could find:

- `func_180494_b`: `getBiomeGenForCoords` -> `getBiome`
- `func_180631_a`: `getBiomeGenerator` -> `getBiome`
- `func_180300_a`: `getBiomeGenerator` -> `getBiomeWithDefault`
- `func_76931_a`: `getBiomeGenAt` -> `getBiome`
- `func_180300_a`: `getBiomeGenerator` -> `getBiomeWithDefault`
- `func_180631_a`: `getBiomeGenerator` -> `getBiome`
- `func_76885_a`: `getBiomeGenAt` -> `getBiome`
- `p_180300_2_`: `biomeGenBaseIn` -> `defaultBiome`

**Comment by matthewprenger** [comment]
Fixed:
`func_180494_b`: `getBiomeGenForCoords` -> `getBiome`
`func_180631_a`: `getBiomeGenerator` -> `getBiome`
`func_180300_a`: `getBiomeGenerator` -> `getBiome`
`func_76885_a`: `getBiomeGenAt` -> `getBiome`
`p_180300_2_`: `biomeGenBaseIn` -> `defaultBiome`
`func_76931_a`: `getBiomeGenAt` -> `getBiomes`
`func_76933_b`: `loadBlockGeneratorData` -> `getBiomes` (this is just an overload to 76931)
`p_150513_1_`: `biomeGenBaseIn` -> `biomeIn`
`field_76947_d`: `biomeGenerator` -> `biome`
