### ISSUE TITLE
Rename INetHandlerPlayServer process PlaceBlock and UseItem methods

### ISSUE THREAD

**Issue by gabizou** [ModCoderPack/MCPBot-Issues#261]
`func_147346_a` is currently `processPlayerBlockPlacement`, but the intention (and parameter) is to process `CPacketPlayerTryUseItem`.

`func_184337_a` is current `processRightClickBlock`, but the intention (and parameter) is to process `CPacketPlayerTryUseItemOnBlock`.

The original methods intentions that have existed in previous versions need to be thrown out the window per say, since the `func_147346_a` is explicitly when a player is right clicking with an unknown `EnumHand`, and if there's an `ItemStack` available in that hand, `PlayerInteractionManager#processRightClick` is called (which transitively calls `stack.useItemRightClick`) with no block position or anything (since the player is not targeting a block face). 

I suggest a name for `func_147346_a` to be `processTryUseItem`, and potentially with the javadocs:

```
Called when a client is using an item while not pointing at a block, but simply using an item.
```

`func_184337_a` Is a bit different as it's roughly named correctly, but could be better named to `processUseItemOnBlock`.

**Comment by bspkrs** [comment]
done.
