### ISSUE TITLE
func_77616_k: isItemTool -> isEnchantable

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#263]
`func_77616_k`: `Item.isItemTool(ItemStack)` -> `isEnchantable(ItemStack)`

Used by:
- Used solely by `ItemStack.isItemEnchantable`, which returns true if isItemTool returns true and the stack is not already enchanted

Implementations:
- Item, by default, says it is enchantable if the item is not stackable and can be damaged. This applies to all tools and armor and weapons. 
- Books override this to say it is enchantable only if the stack is size 1
- Enchanted books override this to say false, as enchanted books can't be enchanted again

**Comment by mezz** [comment]
The wrong name here has messed me up before, glad this is reported already.

**Comment by matthewprenger** [comment]
Done:
`func_77616_k`: `isItemTool` -> `isEnchantable`
