### ISSUE TITLE
field_148859_d: metadata -> tileEntityType

### ISSUE THREAD

**Issue by Choonster** [ModCoderPack/MCPBot-Issues#264]
This field is used by vanilla to identify the `TileEntity` type, it's not related to block metadata at all. The getter is already called `getTileEntityType`.

`p_i46967_2_` (the constructor parameter for the field) also needs to be renamed.

**Comment by matthewprenger** [comment]
Done:
`field_148859_d`: `metadata` -> `tileEntityType`
`p_i46967_2_`: `metadataIn` -> `tileEntityTypeIn`
