### ISSUE TITLE
func_77043_a: RenderLivingBase.rotateCorpse -> applyRotations

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#265]
`func_77043_a`: `rotateCorpse` => `applyRotations` or `rotateBody`

Used for:
- Rotating corpse on death

But also:
- Flipping dinnerbone and grum upside down
- Rotating body when sleeping
- Rotating body when elytra flying

**Comment by matthewprenger** [comment]
Done:
`func_77043_a`: `rotateCorpse` -> `applyRotations`
