### ISSUE TITLE
func_180642_a: Block.onBlockPlaced -> Block.getStateForPlacement

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#266]
`func_180642_a`: `onBlockPlaced` -> `getStateForPlacement` (open to suggestions)

This is _frequently_ confused with `onBlockPlacedBy`, which runs _after_ the Block has been set in the world.
This method is run _before_ the Block is set. In fact, this method is solely responsible for converting the stack/stack meta back into an IBlockState.
To discourage modders from doing things that should be done in `onBlockPlacedBy`, this method should be renamed.

**Comment by imadnsn** [comment]
Since modders would still use it for other things, what about
`onBlockPlaced -> onBlockPlacing`

**Comment by shadowfacts** [comment]
`onBlockPlacing` is just as confusing as `onBlockPlaced` and still doesn't describe what the method actually does. I'm in favor of `getStateToPlace` because that's what the method does, it determines what state to place in the world.

**Comment by williewillus** [comment]
Forge added a more sensitive version called Block.getStateForPlacement, which properly captures the purpose of this method.

https://github.com/MinecraftForge/MinecraftForge/pull/3129

We should have the vanilla mapping follow suit.

**Comment by shadowfacts** [comment]
Bumping this as MinecraftForge/MinecraftForge#3129 has been merged and now the two methods functioning the same but being named different makes things confusing.

**Comment by williewillus** [comment]
^ request to remove modder comments wanted since forge's enhanced version has the proper name

**Comment by matthewprenger** [comment]
Done:
`func_180642_a`: `onBlockPlaced` -> `getStateForPlacement`
