### ISSUE TITLE
Change func_187242_a to transferPlayerToDimension

### ISSUE THREAD

**Issue by gabizou** [ModCoderPack/MCPBot-Issues#267]
changePlayerDimension used to be `transferPlayerToDimension` or under the search name: `func_72356_a`.

The change is rather confusing as it's only this method that is now prefixed with `change`, aside from the `Entity` based method: `changeDimension` (`func_184204_a`) replaced the signature changed method from 1.8.9: `travelToDimension` (`func_71027_c`).

This method name change is further exacerbated by the fact that Forge still adds the overloads in `PlayerList` using the old traditional name.

Requested method name changes:
- `Entity#func_184204_a` (`changeDimension`) -> `travelToDimension`
- `PlayerList#func_187242_a` (`changePlayerDimension`) -> `transferPlayerToDimension`

**Comment by bspkrs** [comment]
this will remain as-is.
