### ISSUE TITLE
Move ChunkProviderServer out of world.gen package

### ISSUE THREAD

**Issue by gabizou** [ModCoderPack/MCPBot-Issues#268]
Previously `IChunkProvider` would be involved in loading chunks _and_ generating chunks, but now in 1.9+, `IChunkProvider` is only used for providing loaded chunks. The only quandary is that `ChunkProviderServer` resides in the `net.minecraft.world.gen` package. My recommendation is to move it to `net.minecraft.world` or some sub package thereof. The list of affected classes:
- `net.minecraft.world.chunk.IChunkProvider`
- `net.minecraft.world.gen.ChunkProviderServer`

That isn't to say that https://github.com/ModCoderPack/MCPBot-Issues/issues/228 is partially involved, but this should only affect `ChunkProviderServer`.

**Comment by bs2609** [comment]
On a related note, `IChunkGenerator` should probably be moved into the `world.chunk.gen` package.

**Comment by bs2609** [comment]
Re #428, any chance of `IChunkProvider`/`IChunkGenerator` getting package moves?

**Comment by kashike** [comment]
To which package?

**Comment by bs2609** [comment]
`IChunkProvider` in with `ChunkProviderServer` (either in `world` or `world.chunk`) and `IChunkGenerator` in with the `ChunkGeneratorX` classes (`world.gen`)

**Comment by kashike** [comment]
I've added `net.minecraft.world.chunk.IChunkGenerator net.minecraft.world.gen.IChunkGenerator`, but I'm going to leave `IChunkProvider` up for discussion.

**Comment by bs2609** [comment]
I think `ChunkProviderServer` is what could do with moving, it's out of place in `world.gen`.

**Comment by kashike** [comment]
To where? What about `IChunkProvider`?

**Comment by bs2609** [comment]
`world.chunk` is probably the best location. `IChunkProvider` is already there, so it wouldn't need moving in that case.

**Comment by bs2609** [comment]
Re: #514, any comments on:

`world.gen.ChunkProviderServer` -> `world.chunk.ChunkProviderServer`

**Comment by killjoy1221** [comment]
According to `func_73148_d`, I feel like these classes should be renamed to:

`IChunkProvider` -> `AbstractChunkCache` (it's not an interface)
`ChunkProviderServer` -> `ServerChunkCache`
`ChunkProviderClient` -> `MultiplayerChunkCache`

**Comment by LexManos** [comment]
https://gist.github.com/LexManos/cab8cd55ff508e67d092e38452377e09#file-4_cleanup-tsrg-L407
