### ISSUE TITLE
PlayerChunkMap/etc cleanup

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#269]
#163
- `field_7306a3_M`: `thePlayerManager` -> `playerChunkMap`
  - `PlayerManager` is the old name for the `PlayerChunkMap` class
- `field_72700_c`: `playerInstances` -> `entryMap`
  - This is a map of (x, z) indexes to entries
- `field_72697_d`: `playerInstancesToUpdate` -> `dirtyEntries`
  - This is a set of entries which are dirty, usually due to a block change
- `func_187304_a`: `addEntry` -> `entryChanged`
  - This method is used to mark a `PlayerChunkMapEntry` as dirty
- `field_111193_e`: `playerInstanceList` -> `entries`
  - `PlayerInstance` is the old name for the `PlayerChunkMapEntry` class
- `field_187311_h`: `playersNeedingChunks` -> `entriesWithoutChunks`
  - This is a list of entries which, at time of creation, had a null chunk

**Comment by matthewprenger** [comment]
Done:
`field_73063_M`: `thePlayerManager` -> `playerChunkMap`
`field_72700_c`: `playerInstances` -> `entryMap`
`field_72697_d`: `playerInstancesToUpdate` -> `dirtyEntries`
`func_187304_a`: `addEntry` -> `entryChanged`
`field_111193_e`: `playerInstanceList` -> `entries`
`field_187311_h`: `playersNeedingChunks` -> `entriesWithoutChunks`
