### ISSUE TITLE
Remove "entity" from Particle methods

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#273]
As a result of #189, the following should be renamed to remove "entity" from their names.
- `func_187116_l`: `getEntityBoundingBox` -> `getBoundingBox`
- `func_187108_a`: `setEntityBoundingBox` -> `setBoundingBox`
- `func_187110_a`: `moveEntity` -> `move`
- `p_180434_1_`: `worldRendererIn` -> `buffer`
  - Not directly related to "entity", but the parameter should be updated for the new name as well - #39

**Comment by matthewprenger** [comment]
Done:
`func_187116_l`: `getEntityBoundingBox` -> `getBoundingBox`   (Looks like bspkrs already did this one earlier)
`func_187108_a`: `setEntityBoundingBox` -> `setBoundingBox`   (Looks like bspkrs already did this one earlier)
`func_187110_a`: `moveEntity` -> `move`
`p_180434_1_`: `worldRendererIn` -> `buffer`
