### ISSUE TITLE
SPacketUpdateTileEntity Metadata/type -> action

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#274]
The following fields, parameter, and method should be renamed to clarify what they are related to - the action, not metadata or type.
- `field_148859_d`: `metadata` -> `action`
- `p_i46967_2_,`: `metadataIn` -> `actionIn`
- `func_148853_f`: `getTileEntityType` -> `getAction`

**Comment by bspkrs** [comment]
related to #264

**Comment by matthewprenger** [comment]
#264
