### ISSUE TITLE
Barrier -> ParticleBarrier

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#275]
This class is missing the `Particle` prefix:
`net.minecraft.client.particle.Barrier` -> `net.minecraft.client.particle.ParticleBarrier`

**Comment by williewillus** [comment]
+1, all the other particle classes have Particle in front except this one

**Comment by shadowfacts** [comment]
Agreed, the barrier particle should follow the same conventions as everything else.

**Comment by LexManos** [comment]
Its a slow unimportant process, I want to move away from Smurf naming. 
Maybe if someone gathers up the de-smurfs for 1.13 i'll rename them all.

**Comment by Pokechu22** [comment]
For reference, smurf naming is defined [here](https://blog.codinghorror.com/new-programming-jargon/) (I didn't recognize the term).

I don't know if it is possible to move away from smurf naming - there have been problems with multiple classes of the same name (see, for instance, #373), so if, as an example, `net.minecraft.block.BlockFurnace`, `net.minecraft.client.gui.inventory.GuiFurnace`, `net.minecraft.inventory.ContainerFurnace`, and `net.minecraft.tileentity.TileEntityFurnace` were all renamed to get rid of the prefix (`net.minecraft.block.Furnace`, `net.minecraft.client.gui.inventory.Furnace`, `net.minecraft.inventory.Furnace`, and `net.minecraft.tileentity.Furnace`) there may be issues.

**Comment by williewillus** [comment]
yeah, I think it needs to be retained to *some* degree to disambiguate block vs te vs particle, etc.
Enums are really the only things that can do with eliminating their prefix, since they are likely not to clash with anything else. Maybe Items as well

**Comment by kashike** [comment]
Entities can pretty much be renamed without issue (`Player`, `Sheep`, `Cow`, etc) as well.

**Comment by LexManos** [comment]
Already named net/minecraft/client/particle/BarrierParticle in the bulk rename
