### ISSUE TITLE
net.minecraft.util.math.Vec4b -> net.minecraft.world.data.MapCoord

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#277]
This was renamed and moved some time in the 1.9/10 update.

This class does _not_ a represent a 4-dimensional vector of bytes. It is used _solely_ for Map Data syncing.

The first byte is the type of marker on the map (white/green arrow), the next two are the xy coordinates, and the last is the facing of the marker. This is not vector-ish and naming the class like it is one serves only to obfuscate and muddle the Map code. 

This class is used nowhere else.

I propose/request this be renamed and moved back to where it was before this change (`net.minecraft.world.data.MapCoord`)

**Comment by shadowfacts** [comment]
Agreed, `Vec4b` isn't an accurate description of what the class does. Either `MapCoord` or `MapDecoration` (the field in `MapData` that stores them is called `mapDecorations`) would be better.

**Comment by kashike** [comment]
Already changed for 1.11: `net/minecraft/util/math/Vec4b` -> `net/minecraft/world/storage/MapDecoration`

**Comment by bspkrs** [comment]
if that's the case, this will be closed.
