### ISSUE TITLE
Map mappings are incorrect

### ISSUE THREAD

**Issue by modwizcode** [ModCoderPack/MCPBot-Issues#28]
Version 1.8

For `func_82567_a` the parameter `p_82567_8_` is not `z` it should be `rotation`. Similarly for the same method parameter `p_82567_6_` is actually `worldZ` not `y`, finally for parameters the parameter `p_82567_4_` should be mapped to `worldX` as `x` doesn't show the fact that it's not a map canvas x coordinate, it's a world relative coordinate. The method itself should be called `updateMapDecorations` not `updatePlayersVisibleOnMap`.

The field `field_76203_h` should be called `mapDecorations` as that's what it actually stores, not specifically players or entities. The name is misleading and confuses the fact that non-entity entries are accepted and perfectly safe.

**Comment by bspkrs** [comment]
Is your name really Starbuck?

**Comment by modwizcode** [comment]
Yes it is.

**Comment by bspkrs** [comment]
The params are now fixed. I will add the field/method name refactorings to the list for 1.8.8.
