### ISSUE TITLE
func_180643_i: Block.createStackedBlock -> getSilkTouchDrop

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#280]
- This method is only called after a check to `canSilkHarvest`
- It is only overridden in the vanilla codebase in a redundant manner (wood logs), as vestiges of legacy bug fixes (redstone lamps), or to implement _custom silk touch logic_ (silverfish blocks)
- Name suggestions taken but I think the use of this method is evident and renaming it should be done so it is not conflated with the normal getItemDropped/damageDropped/getDrops trio.

**Comment by bspkrs** [comment]
done.
