### ISSUE TITLE
BlockCactus: swap AABB names

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#284]
Currently:
- field_185593_b -> CACTUS_AABB, 
- field_185594_c -> CACTUS_COLLISION_AABB

However, as is,  `getCollisionBoundingBox()` returns `CACTUS_AABB`, and `getSelectedBoundingBox()` uses `CACTUS_COLLISION_AABB`, which seems backwards. The names of the two fields should probably be swapped to properly reflect their usage.

**Comment by bspkrs** [comment]
done.
