### ISSUE TITLE
EntityFallingBlock canSetAsBlock

### ISSUE THREAD

**Issue by simon816** [ModCoderPack/MCPBot-Issues#285]
The name is inverted.
`canSetAsBlock` (`field_145808_f`) should be something like `dontSetAsBlock`

Relevant code from `onUpdate`:

``` java
if (!this.canSetAsBlock)
{
    if (this.worldObj.canBlockBePlaced(block, blockpos1, true, EnumFacing.UP, (Entity)null, (ItemStack)null)
        && !BlockFalling.canFallInto(this.worldObj, blockpos1.down())
        && this.worldObj.setBlockState(blockpos1, this.fallTile, 3))
    {
```

Also, the variable is only set to `true` when an anvil is falling with a `BlockAnvil.DAMAGE` property of `> 2`, so maybe it should be called `isAnvilFalling`
From the `fall` method:

``` java
boolean flag = block == Blocks.anvil;
[...]
if (flag && (double)this.rand.nextFloat() < 0.05000000074505806D + (double)i * 0.05D)
{
    int j = ((Integer)this.fallTile.getValue(BlockAnvil.DAMAGE)).intValue();
    ++j;

    if (j > 2)
    {
        this.canSetAsBlock = true;
    }
    else
    {
        this.fallTile = this.fallTile.withProperty(BlockAnvil.DAMAGE, Integer.valueOf(j));
    }
}
```

**Comment by kashike** [comment]
- `dontSetAsBlock`
- `dontSetBlock`
- `preventTransitionToBlock`

**Comment by kenzierocks** [comment]
`dontSetBlock` is my preferred option.

**Comment by simon816** [comment]
I'm thinking for correctness it should mention anvil somewhere, it looks like the intention of the flag is specific to whether an anvil will break once dropped or whether it will change back to a block

**Comment by williewillus** [comment]
I'd prefer more general names.
If mojang expands its use of this in the future we don't have to worry about it.
It also makes more sense, nothing about falling blocks has anything to do with anvils, the anvils just *utilize* this field to implement a feature

Being overly specific leads to names like (actual past examples) "RenderSnowball.getPotion()" (actually gets the itemstack to render) or RendererLivingBase.applyRotations/rotateCorps taking an EntityLivingBase someone decided to name "bat"

**Comment by kashike** [comment]
Which name do you like, @williewillus?

**Comment by jamierocks** [comment]
`dontSetBlock` sounds about right.

**Comment by williewillus** [comment]
I agree

**Comment by kashike** [comment]
Done.

`field_145808_f`: `canSetAsBlock` -> `dontSetBlock`
