### ISSUE TITLE
func_i46222_: ModelBlockDefinition comment

### ISSUE THREAD

**Issue by howtonotwin** [ModCoderPack/MCPBot-Issues#286]
Add comment to constructor along the lines of:

    Merges the given ModelBlockDefinitions into one, where all the variants from all the given ModelBlockDefinitions are merged together with later elements in the list taking precedence in case of conflicting names.
    
    A ModelBlockDefinition containing multipart data clears all the data from the list elements before it and replaces all of it with its own.

**Comment by williewillus** [comment]
Is this not evident from the code itself?

**Comment by howtonotwin** [comment]
In that case, I'll just drop this and close the issue.

**Comment by AEnterprise** [comment]
@williewillus it might be but that's not the point, javadoc is suposed to tell someone what a function does without looking at the code

**Comment by kashike** [comment]
Javadoc is not supported at the constructor level.
