### ISSUE TITLE
func_176214_u: Block.isVisuallyOpaque -> causesSuffocation

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#289]
This method is used for:
- Checking if an entity should be suffocating
- Checking if the suffocation overlay should be rendered in 1st person

We already have so many isBlah methods on Block like `isNormalCube` `isOpaqueCube` `isFullyOpaque` `isFullCube`.... the better we name the ones that we can figure out, the easier it'll be to make sense of the others.

**Comment by bspkrs** [comment]
done.
