### ISSUE TITLE
1.7.10 EntityLivingBase#isClientWorld() really returns server world

### ISSUE THREAD

**Issue by jabelar** [ModCoderPack/MCPBot-Issues#29]
The logic is backwards for the EntityLivingBase#isClientWorld(). If you look at the code it is:

    /**
     * Returns whether the entity is in a local (client) world
     */
    public boolean isClientWorld()
    {
        return !this.worldObj.isRemote;
    }

From a Minecraft perspective a client world is when isRemote is true, so you can see that the logic is backwards.

I suggest the name be changed to isServerWorld().

Note that EntityPlayerSP also has an isClientWorld() but that one is correct -- it returns true always, which makes sense for that case.

**Comment by bspkrs** [comment]
There are not currently any methods in 1.7.10 or 1.8 called isClientWorld:
```
>MCPBot_Reborn< gm isClientWorld
-MCPBot_Reborn- No results found.
>MCPBot_Reborn< gm isClientWorld 1.7.10
-MCPBot_Reborn- No results found.
```

**Comment by bspkrs** [comment]
I recommend that you make sure your mappings are up to date.

**Comment by jabelar** [comment]
Okay, I actually had latest mappings (stable_12) but my IDE was searching across some gradle caches for older forge versions so that is why I was getting hits on that method still. Sorry for the false alarm.
