### ISSUE TITLE
RegionRenderCacheBuilder -> VertexBufferLayers (or WorldRendererLayers)

### ISSUE THREAD

**Issue by Barteks2x** [ModCoderPack/MCPBot-Issues#293]
This class doesn't have anything to do with RegionRenderCache (which is now removed and ChunkCache is used everywhere).

Based on what this class does, `WorldRendererLayers` or `VertexBufferLayers` would be better names for that.

There is some inconsistency in naming, so I'm not sure which name would be better. Method names suggest `WorldRendererLayers` but their return types suggest `VertexBufferLayers`.

**Comment by kashike** [comment]
`BlockRenderLayers`?

**Comment by Barteks2x** [comment]
That seems fine too, but I didn't look at the code for a long time.

**Comment by bs2609** [comment]
Looking at the class, it's just a collection of `VertexBuffer`s, one for each `BlockRenderLayer`.
Perhaps `RenderLayerBuffers`?

The field/method names could do with an update too, tbh.

Initial suggestions:
* `field_179040_a`: `worldRenderers` -> `vertexBuffers`
* `func_179038_a`: `getWorldRendererByLayer` -> `getVertexBuffer`
* `func_179039_a`: `getWorldRendererByLayerId` -> `getVertexBuffer`

**Comment by bs2609** [comment]
References to the old class name:

Fields:
* `ChunkRenderWorker.regionRenderCacheBuilder` (`field_178478_c`)
* `ChunkCompileTaskGenerator.regionRenderCacheBuilder` (`field_178550_e`)

Methods:
* `ChunkRenderWorker.getRegionRenderCacheBuilder` (`func_178475_b`)
* `ChunkCompileTaskGenerator.getRegionRenderCacheBuilder` (`func_178545_d`)
* `ChunkCompileTaskGenerator.setRegionRenderCacheBuilder` (`func_178541_a`)
* `ChunkRenderDispatcher.freeRenderBuilder` (`func_178512_a`)
* `ChunkRenderDispatcher.allocateRenderBuilder` (`func_178515_c`)

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
