### ISSUE TITLE
Prefix/suffix name changes

### ISSUE THREAD

**Issue by shadowfacts** [ModCoderPack/MCPBot-Issues#294]
See #215, field names don't need prefixes/suffixes.

- `TileEntity.field_145850_b`: `worldObj` -> `world` (covered by #215)
- `Entity.field_70170_p`: `worldObj` -> `world`
- `Minecraft.field_71441_e`: `theWorld` -> `world`
- `Minecraft.field_71439_g`: `thePlayer` -> `player`

**Comment by bspkrs** [comment]
done.
