### ISSUE TITLE
IChunkProvider.func_73156_b: unloadQueuedChunks->onTick

### ISSUE THREAD

**Issue by Barteks2x** [ModCoderPack/MCPBot-Issues#295]
In ChunkProviderClient it's used to tick chunks, instead of unloading chunks.

**Comment by kashike** [comment]
Why not just `tick`? The `on` prefix isn't necessary, in my opinion.

**Comment by Barteks2x** [comment]
The `on` prefix is consistent with the method in Chunk. I agree that it's not necessary.

**Comment by matthewprenger** [comment]
Done:
`func_73156_b`: `unloadQueuedChunks` -> `tick`
