### ISSUE TITLE
setRecordPlaying -> setOverlayMessage

### ISSUE THREAD

**Issue by tterrag1098** [ModCoderPack/MCPBot-Issues#296]
This method no longer has anything to do with records. It is used for general purpose notifications.

Note that there is an overload of this method, the two that need name changes are:

* func_175188_a
* func_110326_a

The param `isPlaying` passed into these methods should also be renamed, perhaps to something like `rainbow` as the boolean controls whether the text cycles through colors (like the record notification).

The `isPlaying` srg names are:

* p_175188_2_
* p_110326_2_

**Comment by matthewprenger** [comment]
Done:
`func_175188_a`: `setRecordPlaying` -> `setOverlayMessage`
`func_110326_a`: `setRecordPlaying` -> `setOverlayMessage`
`field_73838_g`: `recordPlaying` -> `overlayMessage`
`field_73845_h`: `recordPlayingUpFor` -> `overlayMessageTime`
`field_73844_j`: `recordIsPlaying` -> `animateOverlayMessageColor`
`p_175188_2_`: `isPlaying` -> `animateColor`
`p_110326_2_`: `isPlaying` -> `animateColor`
