### ISSUE TITLE
p_146105_2_ name

### ISSUE THREAD

**Issue by shadowfacts** [ModCoderPack/MCPBot-Issues#298]
`p_146105_2_`: `p_146105_2_` -> `admin`

In 1.11, the parameter is used in `EntityPlayerMP.addChatComponentMessage`. If true, the `byte type` used by the `SPacketChat` constructed is 2 (indicating an admin message), otherwise it's 0 (indicating a normal chat message).

**Comment by matthewprenger** [comment]
This isn't an issue. You will be able to name this when the bot is updated.
