### ISSUE TITLE
1.11: func_76572_b: WorldProvider.createBiomeProvider -> init

### ISSUE THREAD

**Issue by Barteks2x** [ModCoderPack/MCPBot-Issues#299]
In 1.11 this method not only creates biome provider, but does a few other things, different for each world provider class.

WorldProvider.registerWorld could be also renamed to init, so in that case it this method could be initProviderProperties

**Comment by bs2609** [comment]
Hmm, I feel like creating a biome provider is the main purpose, it's kinda abused as a post-construction method by subclasses. Really that stuff should be moved into a seperate `protected void init()` method that just does nothing and can be overriden, but hey.
Does need a note about this stuff at least.

**Comment by kashike** [comment]
It is basically `init`, and `registerWorld` is more of `setWorld`.

**Comment by bs2609** [comment]
Sure, I'm fine with `init` if it's consistent with other usages. `setWorld` sounds right too

**Comment by kashike** [comment]
Done.
- [x] `func_76558_a`: `registerWorld` -> `setWorld`
- [x] `func_76572_b`: `createBiomeProvider` -> `init`
