### ISSUE TITLE
Ability to get new names from old names

### ISSUE THREAD

**Issue by AbrarSyed** [ModCoderPack/MCPBot-Issues#3]
Basically, if I updated snapshots, I want to be able to know what a given name has changed to.

**Comment by bspkrs** [comment]
Yeah, Lex was looking for something like this as well.  I'll try to figure out an easy way of doing that search.

**Comment by bspkrs** [comment]
This functionality is now present in the bot using the history commands with a non-srg name.
eg, !mh ItemStack.getItemDamage
