### ISSUE TITLE
PRIVMSG replies from bot

### ISSUE THREAD

**Issue by hdon** [ModCoderPack/MCPBot-Issues#30]
It would be nice to be able to receive replies to my commands from the bot with PRIVMSG to my nick. Hexchat and XChat2 both have the behavior that receiving a PRIVMSG creates a new window or tab just for the corresponding channel or nick, and would be more convenient when issuing many commands and reading at leisure (like when first learning to use the bot.)

Thanks :)

**Comment by bspkrs** [comment]
The bot already uses notices to send replies so unless you already have a dialog window open with the bot it shouldn't be forcing a separate tab. 
http://i.imgur.com/ycCnKcg.png

**Comment by hdon** [comment]
Sorry, I explained myself poorly. I would like to be able to receive PRIVMSG to my nick.

Thanks again!
