### ISSUE TITLE
EntityList String -> ResourceLocation renames

### ISSUE THREAD

**Issue by kenzierocks** [ModCoderPack/MCPBot-Issues#300]
`EntityList.isStringValidEntityName` (`func_180125_b`) and `EntityList.isStringEntityName` (`func_180123_a`) should be changed since they now take a ResourceLocation instead of a String. Perhaps just drop the `String` part?

**Comment by kashike** [comment]
- [x] `func_180125_b`: `isStringValidEntityName` -> `isRegistered`
- [x] `func_180123_a`: `isStringEntityName` -> `isMatchingName`
