### ISSUE TITLE
Slot.canBeHovered (func_111238_b) has outdated name

### ISSUE THREAD

**Issue by TechnicianLP** [ModCoderPack/MCPBot-Issues#304]
Slot.canBeHovered() (func_111238_b) should be updated to Slot.isDisabled()
Since 1.11 this Method also disables the rendering of the contained ItemStack as well as click-behaviour, where it previously only disabled the gradient-rect while hovering a slot.
Description can be updated to: "Disables rendering and click-behaviour" as it is no longer used in horses

**Comment by kashike** [comment]
This doesn't seem correct. Are you sure you meant `isDisabled`? `isEnabled` makes sense more than `isDisabled` does.

**Comment by kashike** [comment]
done.
- [x] `func_111238_b`: `canBeHovered` -> `isEnabled`
