### ISSUE TITLE
theProfiler -> profiler

### ISSUE THREAD

**Issue by kenzierocks** [ModCoderPack/MCPBot-Issues#305]
Following the changes made to `theWorld` and `thePlayer`, the 3 `theProfiler` fields should be changed to `profiler`.

- [ ] `field_72984_F`: `theProfiler` -> `profiler`
- [ ] `field_75781_c`: `theProfiler` -> `profiler`
- [ ] `field_71304_b`: `theProfiler` -> `profiler`

**Comment by kashike** [comment]
done.
- [x] `field_72984_F`: `theProfiler` -> `profiler`
- [x] `field_75781_c`: `theProfiler` -> `profiler`
- [x] `field_71304_b`: `theProfiler` -> `profiler`
