### ISSUE TITLE
EntityDragonPart -> MultiPartEntityPart

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#307]
`net.minecraft.entity.boss.EntityDragonPart` -> `net.minecraft.entity.MultiPartEntityPart`

`net.minecraft.entity.boss.EntityDragonPart` is named as if it can only be used by an `EntityDragon`, whereas it has nothing tying it to a dragon. It's simply a part of a multipart entity.

**Comment by mezz** [comment]
This is a good change. Nobody knows to use it for their multipart entities because it has Dragon-specific names.

**Comment by jredfox** [comment]
There is a good chance people know how to use multi entity part.

Ender Dragon > Multi Part
Dragon Mount Dragon > Multi Part
Lycites Mobs Mod > Multi Part
Wild Cryptids and consperisies > Multi Part

Who hired you? you are disregarding any and all bugs that I have seen.

**Comment by williewillus** [comment]
+1 for this, updating an older mod and it could've saved several tens of lines by using this
`MultiPartEntityPart` is a bit of a mouthful though...don't have any better suggestions though

**Comment by bs2609** [comment]
`CompoundEntityPart`/`ICompoundEntity`?
