### ISSUE TITLE
Fix shifted parameters

### ISSUE THREAD

**Issue by shadowfacts** [ModCoderPack/MCPBot-Issues#308]
In 1.11, the ItemStack parameter to Item.onItemUse was removed so all the parameter names have to be shifted:

- `p_180614_1_`: `stack` -> `player`
- `p_180614_2_`: `playerIn` -> `worldIn`
- `p_180614_3_`: `worldIn` -> `pos`
- `p_180614_4_`: `pos` -> `hand`
- `p_180614_5_`: `hand` -> `facing`
- `p_180614_6_`: `facing` -> `hitX`
- `p_180614_7_`: `hitX` -> `hitY`
- `p_180614_8_`: `hitY` -> `hitZ`

**Comment by shadowfacts** [comment]
Some more from other methods:

- `p_184230_2_`: `stack` -> `hand`
- `p_180639_6_`: `heldItem` -> `facing`
- `p_180639_7_`: `side` -> `hitX`
- `p_180639_8_`: `hitX` -> `hitY`
- `p_180639_9_`: `hitY` -> `hitZ`

**Comment by kashike** [comment]
Done.
- `p_180614_1_`: `stack` -> `player`
- `p_180614_2_`: `playerIn` -> `worldIn`
- `p_180614_3_`: `worldIn` -> `pos`
- `p_180614_4_`: `pos` -> `hand`
- `p_180614_5_`: `hand` -> `facing`
- `p_180614_6_`: `facing` -> `hitX`
- `p_180614_7_`: `hitX` -> `hitY`
- `p_180614_8_`: `hitY` -> `hitZ`
- `p_184230_2_`: `stack` -> `hand`
- `p_180639_6_`: `heldItem` -> `facing`
- `p_180639_7_`: `side` -> `hitX`
- `p_180639_8_`: `hitX` -> `hitY`
- `p_180639_9_`: `hitY` -> `hitZ`
