### ISSUE TITLE
GuiTextField.drawCursorVertical -> GuiTextField.drawSelectionBox

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#310]
`drawCursorVertical` does not draw the cursor.  It draws the blue selection highlight, and should be renamed to reflect that.

This is a private method, so the change shouldn't affect any mods, but it still should be changed to make it a lot easier to understand.

```
!sm func_146188_c drawSelectionBox Draws the blue selection box.
```

**Comment by kashike** [comment]
Done.
`func_146188_c`: `drawCursorVertical` -> `drawSelectionBox`

**Comment by Pokechu22** [comment]
Thanks!
