### ISSUE TITLE
func_176214_u / func_191058_s naming should be consistent

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#311]
Currently:
  * `func_176214_u` = `Block.causesSuffocation`
  * `func_191058_s` = `IBlockProperties.isViewBlocking`

The interface method calls through to the block method with itself as a state parameter.
Following the pattern of other methods in this interface, these functions should have the same name for clarity.

Any opinions on the better name?

**Comment by bs2609** [comment]
See #289 for notes on the block method name

**Comment by kashike** [comment]
done.
`func_191058_s`: `isViewBlocking` -> `causesSuffocation`
