### ISSUE TITLE
GuiSlider constructor 'name', 'min', 'max' parmeters -> 'nameIn', 'minIn', 'maxIn' + comment

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#312]
I'd like to add a comment to the `name` parameter in the GuiSlider constructor, but that parameter can't be edited (due to `name` also being a field).

EDIT: same thing with `min` and `max`.

My requested changes:

```
fsp p_i45541_5_ nameIn Translation key for the slider's text (takes no parameters)
fsp p_i45541_6_ minIn Minimum value of the slider
fsp p_i45541_7_ maxIn Maximum value of the slider
```

**Comment by kashike** [comment]
done.
`p_i45541_5_`: `name` -> `nameIn` (`Translation key for the slider's text (takes no parameters)`)
`p_i45541_6_`: `min` -> `minIn` (`Minimum value of the slider`)
`p_i45541_7_`: `max` -> `maxIn` (`Maximum value of the slider`)
