### ISSUE TITLE
[1.10.2] snapshot_20161117 causes recompilation errors with Forge

### ISSUE THREAD

**Issue by Choonster** [ModCoderPack/MCPBot-Issues#313]
The `snapshot_20161117` mappings cause [this patch](https://github.com/MinecraftForge/MinecraftForge/blob/2cb99f0e74cc41b8f96b3873585d8f7b5812dd08/patches/minecraft/net/minecraft/inventory/ContainerPlayer.java.patch#L9) to fail with a compilation error during the `recompileMc` ForgeGradle task.

The error:
```
[ant:javac] Compiling 2578 source files to C:\Users\USER\Documents\Minecraft\Mods\TestMod3_1.10.2\build\tmp\recompileMc\compiled
[ant:javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6
[ant:javac] C:\Users\USER\Documents\Minecraft\Mods\TestMod3_1.10.2\build\tmp\recompileMc\sources\net\minecraft\inventory\ContainerPlayer.java:62: error: local variable player is accessed from within inner class; needs to be declared final
[ant:javac]                         return stack.getItem().isValidArmor(stack, entityequipmentslot, player);
[ant:javac]                                                                                         ^
```
[Full log](https://gist.github.com/Choonster/1678526957af752f1ee6d029db5bb94a)

This is happening because both `p_i1819_3_` and `field_82862_h` are named `player`, so the parameter is used instead of the field (which the Forge patch actually references).

`p_i1819_3_` was renamed to `playerIn` on 2016-11-17 by kashike, but this doesn't seem to have made it into `snapshot_20161117`. The new name is present in `snapshot_20161118` for 1.11, but there are no newer mappings for 1.10.2.

Could a new snapshot be generated for 1.10.2 that includes the new name?

**Comment by kashike** [comment]
`stable_29` exists, and you should be using that.

**Comment by Choonster** [comment]
I didn't think to look for a new stable version. That fixed it, thanks.
