### ISSUE TITLE
FontRendererObj.splitStringWidth, and semirelated drawSplitString, listFormattedStringToWidth, and wrapFormattedStringToWidth

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#315]
I've got two major points with these methods:

- [x] `splitStringWidth` (`func_78267_b`) &rarr; `getWordWrappedHeight`
    * `splitStringWidth` is an **incorrect** name.  That method returns the _height_ of the string, not the width (looking at its code makes this obvious).  I propose naming it `getWordWrappedHeight` instead.
- [ ] `drawSplitString` (`func_78279_b`) &rarr; `drawWordWrappedString`
- [ ] `listFormattedStringToWidth` (`func_78271_c`) &rarr; `getWordWrappedLines`
- [ ] `wrapFormattedStringToWidth` (`func_78280_d`) &rarr; `wordWrapString`
    * In my opinion, `drawSplitString`, `listFormattedStringToWidth`, and `wrapFormattedStringToWidth` all are awkward.  The names work, but aren't particularly elegant.  I propose naming them `drawWordWrappedString`, `getWordWrappedLines` and `wordWrapString` instead (but these names aren't necessarily perfect).  However, since `drawSplitString` and `listFormattedStringToWidth` are public, this _may_ break mods (`wrapFormattedStringToWidth` isn't public so I don't see renaming it causing any problems).

I'm currently working on cleaning up the documentation relating to `FontRenderer`, and I'll be able to write nicer comments if the names are better (I can still write the comments now, but it's not ideal if the names don't make sense).

**Comment by matthewprenger** [comment]
Ok so `func_78267_b` has been changed from `splitStringWidth` to `getWordWrappedHeight`. The rest of them I'm going to leave open to debate for a little while since they're not technically wrong and happen to be used quite a bit.

**Comment by ArtixAllMighty** [comment]
drawSplitString still sounds like a good name, and defines exactly what it does. drawWrappedString would be even better indeed. 

getWordWrappedLines doesn't imply in the name that it is a list with the wrapped string, maybe getWrappedStringList ? 

although the wrongly named method got names to getWordWrappedHeight, the rest should follow the 'word' logic right ? 

drawSplitString (func_78279_b) → drawWrappedWord
listFormattedStringToWidth (func_78271_c) → getWrappedWordList

that's my 2 cents. no idea on how to name wrapFormattedStringToWidth

**Comment by killjoy1221** [comment]
Removing `word` from `drawWordWrappedString` would be a lot more straightforward and cleaner.
