### ISSUE TITLE
func_184154_a: WorldClient.buildChunkCoordList -> updateViewableChunks

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#318]
`ChunkCoordIntPair` got renamed, and this doesn't actually build a `List`, so this method name is pretty unhelpful.

Suggesting `updateViewableChunks` for the rename as that's what the relevant field is called. (`field_184157_a -> viewableChunks`)

**Comment by kashike** [comment]
done.
- [x] `func_184154_a`: `buildChunkCoordList` -> `refreshVisibleChunks`

**Comment by bs2609** [comment]
update the field name too?

**Comment by kashike** [comment]
done.
- [x] `field_184157_a`: `viewableChunks` -> `visibleChunks`

Thanks, missed that!
