### ISSUE TITLE
getStackInSlotOnClosing should be removeStackFromSlot

### ISSUE THREAD

**Issue by SoniEx2** [ModCoderPack/MCPBot-Issues#32]
Renaming it might make modders fix their implementations. [Even BC does it wrong](https://github.com/BuildCraft/BuildCraft/blob/6.5.x/common/buildcraft/robotics/EntityRobot.java#L696-L699).

**Comment by asiekierka** [comment]
We do it wrong because we don't have anyone to audit our code. I *know* how the function *should* work.

**Comment by bspkrs** [comment]
I'll make sure it gets updated in 1.8.8

**Comment by asiekierka** [comment]
Thank you very much.

2015-11-11 17:08 GMT+01:00 bspkrs <notifications@github.com>:
