### ISSUE TITLE
AxisAlignedBB's expanding and contracting methods (addCoord(DDD), expand(DDD), expandXyz(D), contract(DDD), contract(D))

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#321]
The methods in question and the problems with them:

* `addCoord` (`func_72321_a`) is an **incorrect** name.  It doesn't resize a box to include a new point; it increases it in either the +x or -x directions.
* `expandXyz` (`func_186662_g`) is just not that great of a name - the `xyz` is superfluous (and even confusing, as you might think it's a version that lets you _specify_ xyz but for that you want just `expand`).  
* The two methods named `contract` (`func_186664_h` and `func_191195_a`) do different things - `191195` is the inverse of `addCoord`, while `186664` is the inverse of `expandXyz`.

I've got two proposals:

<h4>Safe proposal</h4>

This proposal avoids changing method names in a way that could break existing code without generating errors, but doesn't get what I consider the best names.

* `contract(DDD)` (`191195`) &rarr; `shrink`  &mdash; We rename this instead of the other contract so that the other is consistent with expand.
* `addCoord(DDD)` (`72321`) &rarr; `grow`
* `expand(DDD)` (`72314`): Unchanged
* `expandXyz(D)` (`186662`) &rarr; `expand` &mdash; No need for the "xyz"
* `contract(D)` (`186664`): Unchanged

<h4>Dangerous proposal</h4>

IMO it would be better to swap `grow` and `expand`, as I think that `grow` represents all directions while `expand` a single one, but swapping one method for another of the same signature with subtle differences, so it may not be a good idea.  I'm still providing this as a perfect-world suggestion, as I think the names are clearer.

* `contract(DDD)` (`191195`): Unchanged
* `addCoord(DDD)` (`72321`) &rarr; `expand` &mdash; Expanding in one direction.
* `expand(DDD)` (`72314`) &rarr; `grow` &mdash; "Grow"ing in all directions.
* `expandXyz(D)` (`186662`) &rarr; `grow` &mdash; No need for the "xyz".
* `contract(D)` (`186664`) &rarr; `shrink` &mdash; To go with `grow`.

**Comment by Pokechu22** [comment]
I just realized I made a minor derp with `contract`, as `contract` is similar to `addCoord`, not `expand`.  There's also a few other changes I might want made (I'm still looking through that code and working on sample cases), so hold off on this for a little bit (I'll reopen it when it's ready).

**Comment by Pokechu22** [comment]
OK, reworked and cleaned up to the point where I feel like the proposal makes sense.

Also do note that I've added (long) comments for all of these methods.  Once they're renamed I'll need to modify those comments, but that shouldn't be too hard.

**Comment by kashike** [comment]
Also see https://github.com/ModCoderPack/MCPBot-Issues/issues/302.

**Comment by kashike** [comment]
I'm going to close this in favour of #302 so that all AABB names are in one place - feel free to comment there and I'll update my description as people thumbs-up/thumbs-down and comment with their suggestions.
