### ISSUE TITLE
Remove GuiScreen.fontRendererObj suffix

### ISSUE THREAD

**Issue by shadowfacts** [ModCoderPack/MCPBot-Issues#322]
As per #215 and #294, field names don't need suffixes.

- `field_146289_q`: `fontRendererObj` -> `fontRenderer`
- `field_71466_p`: `fontRendererObj` -> `fontRenderer`

**Comment by kashike** [comment]
done.
- [x] `field_71466_p`: `fontRendererObj` -> `fontRenderer`
- [x] `field_146289_q`: `fontRendererObj` -> `fontRenderer`
