### ISSUE TITLE
BlockRotationProcessor -> TemplateProcessorIntegrity

### ISSUE THREAD

**Issue by darkhax** [ModCoderPack/MCPBot-Issues#323]
The BlockRotationProcessor class is used by Mojang's nbt schematic format to handle integrity checks. Integrity is used to lower the accuracy of a loaded structure. For example, if the integrity was 0.90f each block in the structure would have a 10% chance of being loaded as null/air. This class has nothing to do with rotations.

**Comment by bs2609** [comment]
Another one for #514?

**Comment by kashike** [comment]
The suggested name sounds *really* weird to me. `TemplateIntegrityProcessor`?

**Comment by bs2609** [comment]
The interface is `ITemplateProcessor`, and it fits with the 'prefix' style of naming used elsewhere (`INamedThing` -> `NamedThingSubtype`), but as it's the only vanilla implementation, it could be changed.

**Comment by darkhax** [comment]
In this case the name used isn't important to me, as long as it accurately describes the class. I went with the current suggestion for the reason bs2609 stated.

**Comment by kashike** [comment]
- [x] `net/minecraft/world/gen/structure/template/BlockRotationProcessor` → `net/minecraft/world/gen/feature/template/IntegrityProcessor`
