### ISSUE TITLE
[bot] Discord support?

### ISSUE THREAD

**Issue by Gaelan** [ModCoderPack/MCPBot-Issues#326]
This is kind of a big ask, but it doesn't actually seem that hard to do. It seems like `MCPBotCmds` has a pretty light coupling on `bot` and `evt`. If `MCPBotCmds` instead was passed an abstract "context" or something which handled the connection to the backend protocol (and we implemented an `IrcContext` and a `DiscordContext` using something like [discord.py](https://github.com/Rapptz/discord.py)), it seems like it would be pretty easy.

In fact, it looks like (correct me if wrong) irc_lib may be homegrown. Could it be possible to just add a `protocols/discord.py` that was a wrapper around discord.py (the library)?

I'd be willing to work on this, though I'm not sure how to get a dev database set up. I couldn't host the discord bot long-term though–I don't have a desktop that runs 24/7.

**Comment by bspkrs** [comment]
https://github.com/ModCoderPack/mcpbot is defunct. The current bot code is located at https://bitbucket.org/ProfMobius/mcpbot
