### ISSUE TITLE
SPacketChunkData: field_149279_g and func_149274_i

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#327]
`field_149279_g`: `loadChunk` -> `fullChunk`
`func_149274_i`: `doLoadChunk` -> `isFullChunk`

The method is a getter for the field.

The field is set to true if 65535 is passed into the packet constructor, meaning that the entire chunk (all sections) are requested to be sent to the client, it doesn't have anything, specifically, to do with loading or unloading chunks.

**Comment by Pokechu22** [comment]
Additionally, `getExtractedSize` (`func_149276_g`) should be changed to `getAvailableSections` as per the field name (and the names on wiki.vg).

**Comment by matthewprenger** [comment]
Done.
`field_149279_g`: `loadChunk` -> `fullChunk`
`func_149274_i`: `doLoadChunk` -> `isFullChunk`
