### ISSUE TITLE
DebugRenderer member naming

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#329]
`DebugRenderer`'s fields are all named `debugRendererFoo` and `fooEnabled`.  All except for the ones relating to the collision box renderer.  For consistency, those should be renamed to match the others.  Additionally, chunk border is inconsistently pluralized (I think that not pluralizing makes more sense, since the class name isn't pluralized).  Elsewhere in the class, the name `toggleDebugScreen` isn't accurate - it toggles only one renderer, not all debug messages. Finally, are a few unnamed things from 1.11.2, which can't be named yet but should get matching names when it becomes possible (only noted here for future reference).

- [ ] `collisionBoxRenderer` (191325) &rarr; `debugRendererCollisionBox`
- [ ] `renderCollision` (191326) &rarr; `collisionBoxEnabled`
- [ ] `chunkBordersEnabled` (190079) &rarr; `chunkBorderEnabled`
- [ ] `toggleDebugScreen` (190075) &rarr; `toggleChunkBorders` ("Toggles the visibility of the chunk border renderer")
- [ ] `field_191557_f` &rarr; `debugRendererNeighborsUpdate`
- [ ] `field_191558_l` &rarr; `enableNeighborsUpdate`
- [ ] `func_191556_a` &rarr; `renderDebugText` ("Renders debug text at the center of the block at the given coordinates.")

**EDIT**: One other thing with the collision renderer, this time in `DebugRendererCollisionBox` itself, that should be changed for consistency:

- [ ] `mc` (191312) &rarr; `minecraft`

**Comment by ThisTestUser** [comment]
Some more mappings:
field_191525_da -> IRON_NUGGET
field_191530_r -> SWEEPING
field_191552_t -> FIREWORKS

By the way, when are 1.11.2 mappings coming out?

**Comment by williewillus** [comment]
1. this issue tracker is for incorrect mappings not missing ones
2. this issue is completely unrelated to what you are posting about

**Comment by kashike** [comment]
I've gone ahead and shortened these fields instead.
- [x] `field_188286_a`: `debugRendererPathfinding` -> `pathfinding`
- [x] `field_188287_b`: `debugRendererWater` -> `water`
- [x] `field_190077_c`: `debugRendererChunkBorder` -> `chunkBorder`
- [x] `field_190078_d`: `debugRendererHeightMap` -> `heightMap`
- [x] `field_191325_e`: `collisionBoxRenderer` -> `collisionBox`
- [x] `field_190079_e`: `chunkBordersEnabled` -> `chunkBorderEnabled`
- [x] `field_190082_h`: `heightmapEnabled` -> `heightMapEnabled`
- [x] `field_191326_j`: `renderCollision` -> `collisionBoxEnabled`
- [x] `field_191312_a`: `mc` -> `minecraft`
