### ISSUE TITLE
(set)isWillingToTrade should be (set)isWillingToMate

### ISSUE THREAD

**Issue by kenzierocks** [ModCoderPack/MCPBot-Issues#33]
From EntityAIVillagerMate:
```
    private void giveBirth()
    {
        EntityVillager entityvillager = this.villagerObj.spawnVillager(this.mate);
        this.mate.setGrowingAge(6000);
        this.villagerObj.setGrowingAge(6000);
        this.mate.func_175549_o(false);
        this.villagerObj.func_175549_o(false);
        entityvillager.setGrowingAge(-24000);
        entityvillager.setLocationAndAngles(this.villagerObj.posX, this.villagerObj.posY, this.villagerObj.posZ, 0.0F, 0.0F);
        this.worldObj.spawnEntityInWorld(entityvillager);
        this.worldObj.setEntityState(entityvillager, (byte)12);
    }
```
 (`stable_16`)

In the newest mappings, `func_175549_o` is `setIsWillingToTrade`. This is very clearly wrong, as it's only used in the mate AI. The field in `EntityVillager` is also wrong (`field_175565_bs`).

Credit for discovery to @unascribed

**Comment by bspkrs** [comment]
The field should actually just be called isWilling. The field is used in both trading and mating code.

**Comment by bspkrs** [comment]
Actually, you're right... the only link to trading is tangential.

**Comment by bspkrs** [comment]
Added to the 1.8.8 list
