### ISSUE TITLE
WorldProvider.hasSkyLight and hasNoSky

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#330]
These fields and methods in `WorldProvider` are somewhat confusing since they share similar names but do different things.

`hasSkylight` (`func_191066_m` and `field_191067_f`) is only true for the overworld.  It controls:
* Daylight detectors
* Entity AI regarding houses
* Player spreading at world spawn
* Whether `ExtendedBlockStorage.skylightArray` is null
    * Whether skylight is included in the chunk data packet
    * Whether the `Skylight` tag in an anvil chunk contains data or just all 0's
* Whether skylight is used in any calculations regarding total light
* Whether weather exists

`hasNoSky` (`func_177495_o` and `field_76576_e`) is only true in the nether.  It controls:
* The delay between lava flowing (10 when true, 30 when false)
* Whether map data should be brown and black instead of useful
* The "actual height" of the world (128 when true, 256 when false)
* Generation of bushes, plants, and flowers (although, it seems like that's implemented wrong, as it's checking for y < 255, not a more sane value)

IMO, `hasNoSky` is a confusing and misleading name.  Previously, `hasNoSky` was the _only_ name, but that's changed recently (for maps in the end), and that field no longer controls skylight.

I think that `hasSkylight` should remain unchanged, and `hasNoSky` should be changed to `isNether`.  However, it's open to discussion (I can see several options).

**Comment by kashike** [comment]
I'm not sure changing this name to `isNether` makes much sense. As far as I can see, this *does* indicate whether or not the dimension has sky - example:
```java
    public int getActualHeight() {
        return this.provider.hasNoSky() ? 128 : 256;
    }
```

**Comment by Pokechu22** [comment]
I don't think `hasNoSky` accurately defines all of the behavior, which is why I don't like it.  Though, `isNether` is probably not a good name on reflection (mods could have a reason to set it, and they won't necessarily be in the nether).

**Comment by me4502** [comment]
`isHalfHeight()` ?

**Comment by Pokechu22** [comment]
Maybe, but the field _also_ affects lava flow speed and map textures.

**Comment by me4502** [comment]
Ah, then it basically is a method that checks if it's the nether

**Comment by williewillus** [comment]
@kashike that check makes sense if it's named `isNether` because the "official" accessible height of the nether dimension is only 128, not 256

**Comment by kashike** [comment]
Have we reached a name for this yet? `isNether`?

**Comment by ArtixAllMighty** [comment]
isNether sounds good. if the variable is only used to define nether-height/logic/lavaflow/... 
if it can be used by any modded dimension, then it should be named more appropriatly.

**Comment by Barteks2x** [comment]
While it can be used by other modded dimensions, they would have many properties of the nether. It would have nether lava flow, actualHeight of nether (128). The only reasonable use case I can think of is if someone wants to create another nether-like dimension. So I think the name `isNether` is right.

**Comment by kashike** [comment]
done.
- [x] `field_76576_e`: `hasNoSky` -> `nether`
- [x] `func_177495_o`: `hasNoSky` -> `isNether`

**Comment by ryantheleach** [comment]
This should be changed to isCaveLike

**Comment by Sollace** [comment]
Old issue, but I think some better names would have been "isOverworld" and "isUnderworld." Overworld is, well, any world above ground, whilst is underworld is any hellish world with a closed roof like the nether.
