### ISSUE TITLE
Block.func_176212_b: isBlockSolid -> causesDownwardCurrent

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#331]
Needs a better new name, but I just really want it to not have the old name.

Used for:
* This method is used only in liquid/fluid flow check calculations, in order to check if an additional -6 vertical drag should be applied to the entity. See BlockLiquid.getFlow()
* Case where it's called:
    * Make a 2 tall 1x1 hole, put water in the top space.
    * Jump in and feel the drag needed to jump out ("isBlockSolid" is returning true)
    * Replace the 8 blocks around the water with ice
    * Feel how the drag is significantly less ("isBlockSolid" is returning false)
* It is only called from Liquid/Fluid classes
* It is not overridden by anything except Liquid classes and is never polymorphically called (the fluid/liquid classes always call this method on themselves, never another block)

I'm on a quest to eliminate all the confusing Block names (isOpaqueCube, isFullCube, isBlockNormalCube, etc....) and this is one step of it :P It has *nothing* to do with finding out if a block is solid or not, even if that happens to be the default impl.

**Comment by kashike** [comment]
@williewillus This method is also used in `net.minecraft.block.BlockLiquid#getSlopeAngle`. Could you please verify the usage?

**Comment by williewillus** [comment]
`getSlopeAngle` just calls `getFlow` which uses this method, as the liquid rendering is based on the actual flow of the liquid.

But thinking back on this, the suggested name is kinda bad. I'll change my mind to `causesDownwardCurrent`

**Comment by kashike** [comment]
done.
- [x] `func_176212_b`: `isBlockSolid` -> `causesDownwardCurrent`
