### ISSUE TITLE
Block.func_185481_k: isFullyOpaque -> isTopSolid

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#332]
Existing name and comment are very narrow-sighted.

This method is actually used to determine if the block is "solid enough" on the top side to support other blocks, like redstone components.

Proof of this:
* Hoppers return true always: In vanilla you can place rails and redstone components on hoppers even though they are not solid in the naive sense
* Half slabs return true only when they are upper half slabs: Allowing redstone on upper slabs was a feature explicitly added by Mojang
* Levers, redstone dust, comparators, repeaters, flower pots, and fire all call this to check if they can stay on top of something
* Forge's own `Block.isSideSolid` delegates to this method if the side given is `EnumFacing.UP`
* Forge even patches a message onto this saying `// Forge: Use isSideSolid(IBlockAccess, BlockPos, EnumFacing.UP) instead`

I want to rename as many ambiguously named Block methods possible (isOpaqueCube/isNormalCube/isBlockNormalCube/etc) and this is another step of the way there :P

**Comment by gigaherz** [comment]
Could we make it `canSupportComponents` or similar? Since it has nothing to do with the top being solid?

**Comment by williewillus** [comment]
I'm more in support of `isTopSolid`. Fire and flower pots aren't "components"

**Comment by matthewprenger** [comment]
Done. Also updated `func_185896_q` to match.

`func_185481_k`: `isFullyOpaque` -> `isTopSolid`
`func_185896_q`: `isFullyOpaque` -> `isTopSolid`
