### ISSUE TITLE
GuiScreen.drawCreativeTabHoveringText -> drawHoveringText

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#334]
<ruby><rb>`drawCreativeTabHoveringText`</rb><rp> (</rp><rt>func_146279_a</rt><rp>)</rp></ruby> is an older name that claims to be exclusively for creative use, but the method is used for general hovering text - it's basically just a version of <ruby><rb>`drawHoveringText`</rb><rp> (</rp><rt>func_146283_a</rt><rp>)</rp></ruby> that takes a single String instead of a `List`.  It should be renamed to just `drawHoveringText` so that the two matching methods are named the same (and are easier to find).

* `func_146279_a`: `drawCreativeTabHoveringText` &rarr; `drawHoveringText`
* `p_146279_1_`: `tabName` &rarr; `text`
* `p_146279_2_`: `mouseX` &rarr; `x`
* `p_146279_3_`: `mouseY` &rarr; `y`

Here's the commands:

```
sm func_146279_a drawHoveringText Draws the given text as a tooltip.
sp p_146279_1_ text The text to draw.  Will not be word wrapped, and should not contain newlines.
sp p_146279_2_ x Approximate x-coordinate to draw at (may be shifted slightly to avoid going off of the screen).  Usually mouse x.
sp p_146279_3_ y Approximate y-coordinate to draw at (may be shifted slightly to avoid going off of the screen).  Usually mouse y.
```

I'll make the same comment changes for the `List` variant when I get back to my IRC client.

**Comment by kashike** [comment]
done.
- [x] `func_146279_a`: `drawCreativeTabHoveringText` -> `drawHoveringText`
- [x] `p_146279_1_`: `tabName` -> `text`
- [x] `p_146279_2_`: `mouseX` -> `x`
- [x] `p_146279_3_`: `mouseY` -> `y`
