### ISSUE TITLE
ScorePlayerTeam prefix/suffix/color members

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#335]
The names for these members are somewhat misleading.  

* <ruby><rb>`getColorPrefix`</rb><rp> (</rp><rt>func_96668_e</rt><rp>)</rp></ruby> and <ruby><rb>`setNamePrefix`</rb><rp> (</rp><rt>func_96666_b</rt><rp>)</rp></ruby> both work with the prefix.  However, this prefix is _not_ necessarily just a single color code (it can be up to 16 chars long and can be modified (albeit not very well) by Bukkit) and describing it as such is misleading.  I recommend switching to `getPrefix` and `setPrefix`.
* Similarly, <ruby><rb>`getColorSuffix`</rb><rp> (</rp><rt>func_96663_f</rt><rp>)</rp></ruby> and <ruby><rb>`setNameSuffix`</rb><rp> (</rp><rt>func_96662_c</rt><rp>)</rp></ruby> should be changed to `getSuffix` and `setSuffix`.
    * And the <ruby><rb>`colorSuffix`</rb><rp> (</rp><rt>field_96671_f</rt><rp>)</rp></ruby> field should be renamed to just `suffix`.
* An unrelated complaint is that <ruby><rb>`teamNameSPT`</rb><rp> (</rp><rt>field_96673_d</rt><rp>)</rp></ruby> and <ruby><rb>`namePrefixSPT`</rb><rp> (</rp><rt>field_96674_e</rt><rp>)</rp></ruby> have random SPT suffixes (which may stand for ScorePlayerTeam).  They should be renamed to `displayName` and `prefix`.
* Finally, <ruby><rb>`getChatFormat`</rb><rp> (</rp><rt>func_178775_l</rt><rp>)</rp></ruby> and <ruby><rb>`setChatFormat`</rb><rp> (</rp><rt>func_178774_a</rt><rp>)</rp></ruby> are not valid for arbitrary chat formats.  They should instead only be used for color values and RESET.  They also affect the `TeamColor` NBT value, and as such I recommend naming them `getTeamColor`/`setTeamColor`
    * And the <ruby><rb>`chatFormat`</rb><rp> (</rp><rt>field_178777_k</rt><rp>)</rp></ruby> field should be changed to `teamColor`
    * And the <ruby><rb>`format`</rb><rp> (</rp><rt>p_178774_1_</rt><rp>)</rp></ruby> parameter should be changed to `color` or `teamColorIn`.

Here's the commands:

```plain
sm func_96668_e getPrefix
sm func_96666_b setPrefix
sm func_96663_f getSuffix
sm func_96662_c setSuffix
sf field_96671_f suffix
sf field_96673_d displayName
sf field_96674_e prefix
sm func_178775_l getTeamColor
sm func_178774_a setTeamColor
sf field_178777_k teamColor
sp p_178774_1_ color
```

I have already updated the comments for all of the methods and parameters in ScorePlayerTeam.

**Comment by kashike** [comment]
done, with minor changes.
- [x] `field_96674_e`: `namePrefixSPT` -> `prefix`
- [x] `func_96668_e`: `getColorPrefix` -> `getPrefix`
- [x] `func_96666_b`: `setNamePrefix` -> `setPrefix`
- [x] `field_96671_f`: `colorSuffix` -> `suffix`
- [x] `func_96663_f`: `getColorSuffix` -> `getSuffix`
- [x] `func_96662_c`: `setNameSuffix` -> `setSuffix`
- [x] `field_178777_k`: `chatFormat` -> `color`
- [x] `p_178774_1_`: `format` -> `color`
- [x] `func_178775_l`: `getChatFormat` -> `getColor`
- [x] `func_178774_a`: `setChatFormat` -> `setColor`
- [x] `p_i2308_1_`: `theScoreboardIn` -> `scoreboardIn`
- [x] `field_96673_d`: `teamNameSPT` -> `displayName`
- [x] `func_96669_c`: `getTeamName` -> `getDisplayName`
- [x] `func_96664_a`: `setTeamName` -> `setDisplayName`
- [x] `field_96675_b`: `registeredName` -> `name`
- [x] `func_96661_b`: `getRegisteredName` -> `getName`
