### ISSUE TITLE
ExtendedBlockStorage.func_76672_e: removeInvalidBlocks -> recalculateRefCounts

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#337]
The method doesn't remove anything, it just recalculates the block and random-tick-needing refcounts. Called when an EBS is freshly loaded from disk or freshly received from network

**Comment by kashike** [comment]
done.
`func_76672_e`: `removeInvalidBlocks` -> `recalculateRefCounts`
