### ISSUE TITLE
EntityItem.func_92059_d: getEntityItem -> getItemStack

### ISSUE THREAD

**Issue by Daeruin** [ModCoderPack/MCPBot-Issues#338]
When using an EntityItemPickupEvent to see if an EntityItem was a certain Item, I recently ended up with this horrific construction: event.getItem().getEntityItem().getItem(). It would be improved by renaming the methods according to what they actually return. In this case, getEntityItem does not return an EntityItem, it returns an ItemStack. (EntityItemPickupEvent.getItem should also be renamed from getItem to getEntityItem, but that's Forge code.)

**Comment by kashike** [comment]
done.
- [x] `func_92059_d`: `getEntityItem` -> `getItem`
- [x] `func_92058_a`: `setEntityItemStack` -> `setItem`

**Comment by bs2609** [comment]
`event.getItem().getItem().getItem()` is not the greatest improvement...

**Comment by Daeruin** [comment]
At least it's not completely misleading, but it's not what I meant. It should have been changed from getEntityItem to getItemStack.

**Comment by liach** [comment]
That's forge's fault then, unrelated to mcp

**Comment by Daeruin** [comment]
It's definitely related to MCP. The mapping was not updated as I originally suggested. But Forge has a problem, too.

**Comment by kashike** [comment]
This method, like many others, is named after the NBT tag name:
```java
        NBTTagCompound nbttagcompound = compound.getCompoundTag("Item");
        this.setItem(new ItemStack(nbttagcompound));

        if (this.getItem().isEmpty()) {
            this.setDead();
        }
```
