### ISSUE TITLE
PhaseList -> PhaseFactory

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#339]
`net.minecraft.entity.boss.dragon.phase.PhaseList` -> `net.minecraft.entity.boss.dragon.phase.PhaseFactory`

Not a list of `Phase`, but rather a factory for them. Also holds a static list of all factories known.

**Comment by williewillus** [comment]
also `IPhase.func_188652_i`: `getPhaseList` -> `getFactory`

**Comment by kashike** [comment]
`PhaseType` seems like a more fitting name for this.

**Comment by williewillus** [comment]
Sure

**Comment by kashike** [comment]
- [x] `func_188652_i`: `getPhaseList` -> `getType`

**Comment by kashike** [comment]
- [x] `net/minecraft/entity/boss/dragon/phase/PhaseList` → `net/minecraft/entity/boss/dragon/phase/PhaseType`
