### ISSUE TITLE
EnumBorderStatus field+method+parameter

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#342]
Someone thought it was a brilliant idea that the seemingly random numbers are ids. They're not, they're used to color the world border while it's in the given state -.-

`EnumBorderStatus.field_177767_d`: `id` -> `color`
`EnumBorderStatus.func_177766_a`: `getID` -> `getColor`
`EnumBorderStatus.p_i45647_3_`: `id` -> `color`

**Comment by kashike** [comment]
done.
`field_177767_d`: `id` -> `color`
`p_i45647_3_`: `id` -> `color`
`func_177766_a`: `getID` -> `getColor`
