### ISSUE TITLE
MCP does not update assetIndex argument value

### ISSUE THREAD

**Issue by Marcono1234** [ModCoderPack/MCPBot-Issues#343]
MCP version: 9.35 rc1

In the last MCP versions the `Start.main(String[])` class always starts Minecraft with `1.8` as `assetIndex`. This causes multiple error messages because of missing files.

**Comment by bspkrs** [comment]
Theoretically that should be impossible unless your MCP setup is borked... MCP pulls all of that info from the version.cfg file in the conf folder. All of the MCP processes use this same file to determine what version of MC we are attempting to use with MCP. In fact, the argument you are referring to isn't even included in the standard config for running the client, which is part of the mcp.cfg file.

**Comment by Marcono1234** [comment]
Is it a bug with MCP then? Because the `version.cfg` file would only contain the exact version and not the asset version. It would for example contain "1.11.2" as version while the asset index is "1.11".

**Comment by bspkrs** [comment]
Can you provide a stacktrace?

**Comment by Marcono1234** [comment]
Stacktrace of what?

**Comment by bspkrs** [comment]
"In the last MCP versions the Start.main(String[]) class always starts Minecraft with 1.8 as assetIndex. This causes multiple error messages because of missing files."

The error messages and everything before that.

**Comment by Marcono1234** [comment]
From MCP 9.37, I only removed the realms library, no other changes were done.

```
[20:21:21] [Client thread/ERROR]: Can't find the resource index file: assets\indexes\1.8.json
[20:21:21] [Client thread/INFO]: Setting user: Player324
[20:21:23] [Client thread/INFO]: LWJGL Version: 2.9.4
[20:21:23] [Client thread/INFO]: Reloading ResourceManager: Default
[20:21:23] [Client thread/WARN]: Missing sound for event: minecraft:ambient.cave
...
```

Break point for "Can't find the resource index file: assets\indexes\1.8.json":
```
Client [Java Application]	
	Start at localhost:52850	
		Thread [Client thread] (Suspended (breakpoint at line 64 in ResourceIndex))	
			ResourceIndex.<init>(File, String) line: 64	
			GameConfiguration$FolderInformation.getAssetsIndex() line: 61	
			Minecraft.<init>(GameConfiguration) line: 396	
			Main.main(String[]) line: 115	
			Start.main(String[]) line: 11	
		Daemon Thread [Snooper Timer] (Running)	
	C:\Program Files\Java\jre1.8.0_121\bin\javaw.exe (11.04.2017, 20:26:44)
```	

Break point for "Missing sound for event:":
```
Client [Java Application]	
	Start at localhost:52805	
		Thread [Client thread] (Suspended (breakpoint at line 104 in SoundManager))	
			SoundManager.reloadSoundSystem() line: 104	
			SoundHandler.onResourceManagerReload(IResourceManager) line: 116	
			SimpleReloadableResourceManager.registerReloadListener(IResourceManagerReloadListener) line: 113	
			Minecraft.startGame() line: 527	
			Minecraft.run() line: 429	
			Main.main(String[]) line: 115	
			Start.main(String[]) line: 11	
		Daemon Thread [Snooper Timer] (Running)	
		Daemon Thread [Timer hack thread] (Running)	
	C:\Program Files\Java\jre1.8.0_121\bin\javaw.exe (11.04.2017, 20:23:03)
```	

I hope that is what you wanted.

**Comment by ramaroberto** [comment]
Hey there, I'm just a beginner with MCP. This happened to me also, I made a quick grep searching for "1.8" and I found this:

```
conf/patches/Start.java:16:        Main.main(concat(new String[]{"--version", "mcp", "--accessToken", "0", "--assetsDir", "assets", "--assetIndex", "1.8", "--userProperties", "{}"}, args));
src/minecraft/Start.java:11:        Main.main(concat(new String[] {"--version", "mcp", "--accessToken", "0", "--assetsDir", "assets", "--assetIndex", "1.8", "--userProperties", "{}"}, args));
```

Changing 1.8 to 1.11 in conf/patches/Start.java did nothing, but changing it in src/minecraft/Start.java from Eclipse and running using the run configuration solves the problem.

Hope it helps to find the real issue.

**Comment by Marcono1234** [comment]
@ramaroberto did you decompile Minecraft again after changing the pachtes file? If so I think it should have modified the src file.
