### ISSUE TITLE
MCP does not set UUID making player unable to join online servers and LAN

### ISSUE THREAD

**Issue by Marcono1234** [ModCoderPack/MCPBot-Issues#344]
MCP does not modify the code to use an UUID to start Minecraft. Therefor the player name is used which results in `NullPointerException`s when trying to connect to online servers or when trying to join LAN worlds.

It might be a good idea to generate a static UUID when decompiling to prevent Minecraft from creating a new player profile every time you start it. This could be then passed by the `Start.main(String[])` method as value for the `uuid` argument.

**Comment by Corosauce** [comment]
To make it more persistant, you can pass in your own players UUID via program arguments in whatever IDE you use, for example with forge you can do: "--username Corosus --uuid=e0bc7f7a-0d68-4e85-bbc4-8bd17e52e9e5". I'm pretty sure with pure mcp setup you'd be able to accomplish the same.

**Comment by Marcono1234** [comment]
You are right, I did not think about that. But it is quite interesting that the unmodified Minecraft defaults the player name but not the UUID. I reported that as [MC-114080](https://bugs.mojang.com/browse/MC-114080).
