### ISSUE TITLE
Item.onItemUse parameter names are shifted

### ISSUE THREAD

**Issue by Marcono1234** [ModCoderPack/MCPBot-Issues#345]
The parameter names of the method `net.minecraft.item.Item.onItemUse(EntityPlayer, World, BlockPos, EnumHand, EnumFacing, float, float, float)` are shifted:

`EntityPlayer stack, World playerIn, BlockPos worldIn, EnumHand pos, EnumFacing hand, float facing, float hitX, float hitY`

**Comment by kashike** [comment]
This was fixed already, update your mappings.
