### ISSUE TITLE
Particle.move method is not decompiled correctly causing sliding particles

### ISSUE THREAD

**Issue by Marcono1234** [ModCoderPack/MCPBot-Issues#346]
Version: MCP 9.35 rc1

It looks like the method `net.minecraft.client.particle.Particle.move(double, double, double)` is not decompiled correctly because it contains like `y != y` which are in that case no `NaN` checks. This makes the particles slide over the ground.

**Comment by Corosauce** [comment]
Noticed this myself some months ago. Confirmed in the bytecode that it is a decompile issue. Decided now to just go ahead and PR a patch fix into forge as I don't think fixing fernflower decompiling for this is going to happen any time soon.

Link to PR: https://github.com/MinecraftForge/MinecraftForge/pull/3716

**Comment by bspkrs** [comment]
We'll have to update the patches for MCP to fix this...
