### ISSUE TITLE
IContainerListener.updateCraftingInventory

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#347]
`func_71110_a`: `updateCraftingInventory` -> `sendAllContents`

Ancient name, container listener is more general than just a crafting inventory. The method syncs all slots of the given inventory to the client, based on the supplied list of stacks.

Keeping the "send" prefix to match everything else in the interface.

**Comment by kashike** [comment]
Additionally, `sendProgressBarUpdate` (`func_71112_a`) should be changed to `sendWindowProperty`.

**Comment by kashike** [comment]
`func_711110_a` is pending.
- [x] `func_71112_a`: `sendProgressBarUpdate` -> `sendWindowProperty`

**Comment by kashike** [comment]
done.
- [x] `func_71110_a`: `updateCraftingInventory` -> `sendContents`
