### ISSUE TITLE
Remove redundant 'Chunk' from some Chunk fields/methods

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#348]
Methods:
*  `onChunkLoad()` (`func_76631_c`)
*  `onChunkUnload()` (`func_76623_d`)
*  `setChunkModified()` (`func_76630_e`)
*  `populateChunk()`  (`func_186030_a`, `func_186034_a`)
*  `isChunkTicked()` (`func_186035_j`)
*  `fillChunk()` (`func_186033_a`)
*  `setChunkLoaded()` (`func_177417_c`)

Fields:
*  `isChunkLoaded` (`field_76636_d`)
*  `chunkTileEntityMap` (`field_150816_i`)
*  `chunkTicked` (`field_150815_m`)

Also suggesting `isChunkTicked()`/`chunkTicked` might be better as `hasTicked`.
`fillFromBuffer` might also be better than just `fill`.

**Comment by kashike** [comment]
@Barteks2x Thoughts?

**Comment by Barteks2x** [comment]
That looks fine. The current names don't bother me that much but  removing `chunks` from there will probably be better. I know it will break my mod but almost every more major mappings update does.

**Comment by kashike** [comment]
done.
- [x] `field_76636_d`: `isChunkLoaded` -> `loaded`
- [x] `field_150816_i`: `chunkTileEntityMap` -> `tileEntities`
- [x] `field_150815_m`: `chunkTicked` -> `ticked`
- [x] `field_76643_l`: `isModified` -> `dirty`
- [x] `func_76631_c`: `onChunkLoad` -> `onLoad`
- [x] `func_76623_d`: `onChunkUnload` -> `onUnload`
- [x] `func_76630_e`: `setChunkModified` -> `markDirty`
- [x] `func_186030_a`: `populateChunk` -> `populate`
- [x] `func_186034_a`: `populateChunk` -> `populate`
- [x] `func_177417_c`: `setChunkLoaded` -> `markLoaded`
- [x] `func_186033_a`: `fillChunk` -> `read`

**Comment by bs2609** [comment]
Was `isChunkTicked()` (`func_186035_j`) updated?

**Comment by kashike** [comment]
It is now. :cat:
