### ISSUE TITLE
Particle.func_187111_c: isTransparent -> shouldDisableDepth

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#350]
`Particle.func_187111_c`: `isTransparent` -> `shouldDisableDepth`

How is it used?
* ParticleManager.updateEffects() adds the particle to a differently indexed queue depending on whether this method returns true or not. `0` if it returns true, `1` if it doesn't
* ParticleManager.renderParticles() disables the depth buffer if rendering out of the `0` buffer, and enables it if rendering out of the `1` buffer

so the method should be named something about the depth state, not the alpha state.

**Comment by kashike** [comment]
`func_187111_c`: `isTransparent` -> `shouldDisableDepth`
