### ISSUE TITLE
[Request] Way to clear a comment

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#351]
There's some things that have comments that are no longer needed, such as magic int fields that have since been replaced with enums. example: `EnchantmentProtection.protectionType`'s comment. 

Less unneeded comments => less noise in the codebase => easier to trudge through

currently the set commands, when given the same mcp name with no comment supplied, retain the old comment.

**Comment by kashike** [comment]
The example field can still have a comment, just remove the indexes.

**Comment by williewillus** [comment]
it's kind of redundant though, the name and type of the field already describe its function fully without a 3 line comment saying the same "Defines the type of protection of the enchantment"

**Comment by matthewprenger** [comment]
This can be accomplished by setting the comment to `None`, but I agree. There should be a more obvious way to clear comments.
