### ISSUE TITLE
Entity.func_174816_a: verifyExplosion -> canExplosionDestroyBlock

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#352]
"verify" is vague.

`Entity.func_174816_a`: `verifyExplosion` -> `canExplosionDestroyBlock`

This is called on an `Explosion`'s `exploder` to check if the explosion can destroy a certain blockpos/state.
For example, TNT carts use these to spare rails from destruction.

The new name still isn't super clear that it's the exploder Entity that's getting called, but better than "verify"

**Comment by kashike** [comment]
done.
- [x] `func_174816_a`: `verifyExplosion` -> `canExplosionDestroyBlock`
