### ISSUE TITLE
Rename AxisAlignedBB#addCoord() to includeCoord

### ISSUE THREAD

**Issue by mezz** [ModCoderPack/MCPBot-Issues#353]
`func_72321_a` should be named in a way that makes it clear that the box will grow to include the given coordinate. It needs to sound different from `offset` or `add` which are sometimes used interchangeably for talking about bounding boxes.

This request was prompted by this bug: https://github.com/MinecraftForge/MinecraftForge/pull/3709

**Comment by Pokechu22** [comment]
See also #321 and #302

**Comment by kashike** [comment]
I'm going to close this in favour of #302 so that all AABB names are in one place - feel free to comment there and I'll update my description as people thumbs-up/thumbs-down and comment with their suggestions.

**Comment by mezz** [comment]
I didn't search for previous issues properly, thanks.
