### ISSUE TITLE
NBTTagCompound.func_179237_a: merge -> mergeWithCopy

### ISSUE THREAD

**Issue by Marcono1234** [ModCoderPack/MCPBot-Issues#354]
The method `net.minecraft.nbt.NBTTagCompound.merge(NBTTagCompound)` merges `this` `NBTTagCompound` with copies of the entries of the other one. This should probably be represented in the name of the method.

**Comment by kashike** [comment]
I'm not sure if this needs to be renamed - the javadocs can be updated to specify the beheaviour.

**Comment by ArtixAllMighty** [comment]
i agree with kashike, the docs could be updated for this.

**Comment by kashike** [comment]
I've updated the comment for this method.
