### ISSUE TITLE
Entity.func_71061_d_: resetHeight -> makeWaterSoundAndParticles

### ISSUE THREAD

**Issue by Marcono1234** [ModCoderPack/MCPBot-Issues#355]
It looks like the method `net.minecraft.entity.Entity.resetHeight()` (and `net.minecraft.entity.player.EntityPlayer.resetHeight()`) is not about the entity height at all, instead it creates water particles and plays the splash sound. It would be good if the Java doc could be removed as well.

**Comment by kashike** [comment]
done.
- [x] `func_71061_d_`: `resetHeight` -> `doWaterSplashEffect`
