### ISSUE TITLE
TileEntityHopper.putStackInInventoryAllSlots parameter names are shifted

### ISSUE THREAD

**Issue by Marcono1234** [ModCoderPack/MCPBot-Issues#356]
The parameter names of the method `TileEntityHopper.putStackInInventoryAllSlots` are shifted:
`putStackInInventoryAllSlots(IInventory inventoryIn, IInventory stack, ItemStack side, @Nullable EnumFacing p_174918_3_)`

**Comment by kashike** [comment]
done.
