### ISSUE TITLE
EntityAIBase.func_75253_b: continueExecuting -> shouldContinueExecuting

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#359]
`EntityAIBase.func_75253_b`: `continueExecuting` -> `shouldContinueExecuting`

It's a stateful conditional check, just like `shouldExecute`, and should be named consistently as such.

Currently it sounds too much like a verb and could be conflated with `updateTask`

**Comment by matthewprenger** [comment]
Done.
`func_75253_b`: `continueExecuting` -> `shouldContinueExecuting`
