### ISSUE TITLE
Mappings for 1.11.2

### ISSUE THREAD

**Issue by liach** [ModCoderPack/MCPBot-Issues#360]
Now on http://export.mcpbot.bspk.rs/, there is no mapping for minecraft 1.11.2. I hope to see mappings for the latest released minecraft version.

**Comment by chibill** [comment]
The MCP mappings exist but no mapping thru MCPBot

**Comment by kashike** [comment]
Hence the `bot` label.

**Comment by chibill** [comment]
Yeah. I guess.

**Comment by Pokechu22** [comment]
The ones you find on the actual MCP distribution are still 1.11.0 mappings, just used with 1.11.2.

**Comment by chibill** [comment]
Really? That's goofy. But it makes using people's scripts with 1.11.2 a pain as it tries to get 1.11.2 mappings  and fails.

**Comment by PizzaCrust** [comment]
@chibill hahaha, i'm fixing it...

**Comment by PizzaCrust** [comment]
I've fixed it for Iodine.... @chibill

**Comment by Pokechu22** [comment]
It's a bit goofy, but the CSVs target searge names that are designed not to change between versions, so you _could_ use 1.10.2 names with it too.  The only problem is the structure of the maven site requires you to guess the MC version.

**Comment by bspkrs** [comment]
@Pokechu22 You don't have to guess... Forge maven has the versions.json file. http://files.minecraftforge.net/maven/de/oceanlabs/mcp/versions.json

**Comment by Pokechu22** [comment]
Hm.  True, it's not so much guessing.  It's still a bit annoying that you need to figure out the MC version to get a set of mappings that work with _any_ MC version (more or less), especially if you need to target multiple MC versions.  The requirement to iterate through all versions ([as forgegradle does](https://github.com/MinecraftForge/ForgeGradle/blob/c438b06df6339a6763e1549ebfa7b039100c1c0c/src/main/java/net/minecraftforge/gradle/common/BaseExtension.java#L274)) is just somewhat ugly (that's what I was thinking of when I said "guessing").  It's not a good model for the data IMO.

**Comment by liach** [comment]
Closing since 1.12 mappings are out.
