### ISSUE TITLE
EntityArmorStand.applyPlayerInteraction hand parameter name incorrect

### ISSUE THREAD

**Issue by Marcono1234** [ModCoderPack/MCPBot-Issues#363]
The parameter name for the `EnumHand` parameter of the method `net.minecraft.entity.item.EntityArmorStand.applyPlayerInteraction(EntityPlayer, Vec3d, EnumHand)` is wrong:
`applyPlayerInteraction(EntityPlayer player, Vec3d vec, EnumHand stack)`

**Comment by kashike** [comment]
fixed
