### ISSUE TITLE
ItemElytra.func_185069_d: isBroken -> isUsable

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#365]
`ItemElytra.func_185069_d`: `isBroken` -> `isUsable`

This is checked before letting the player fly, meaning it checks if the elytra is *not* broken.

**Comment by liach** [comment]
Or `isUseable`, `hasDurability`?

**Comment by williewillus** [comment]
I'll take `isUsable`

**Comment by matthewprenger** [comment]
Done.
`func_185069_d`: `isBroken` -> `isUsable`
