### ISSUE TITLE
EntityPlayerMP.field_71136_j: playerConqueredTheEnd -> queuedEndExit

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#366]
`EntityPlayerMP.field_71136_j`: `playerConqueredTheEnd` -> `queuedEndExit`

This flag is only true when the player is inside the exit portal but hasn't yet been respawned in the overworld. It's not a permanent flag that is set when the player "conquers the end" (which doesn't even have a clear meaning after 1.9). The flag is cleared after the respawn is complete.

**Comment by kashike** [comment]
done.
`field_71136_j`: `playerConqueredTheEnd` -> `queuedEndExit`
