### ISSUE TITLE
BiomeCache$Block -> BiomeCache$Entry

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#367]
`BiomeCache$Block` -> `BiomeCache$Entry`

Not sure why this was called "Block"...

**Comment by bs2609** [comment]
`BiomeCache.func_76840_a` (`getBiomeCacheBlock`) will also need updating. It could probably be improved too, any suggestions?

**Comment by kashike** [comment]
- [x] `func_76840_a`: `getBiomeCacheBlock` -> `getEntry`

**Comment by kashike** [comment]
- [x] `net/minecraft/world/biome/BiomeCache$Block` → `net/minecraft/world/biome/BiomeCache$Entry`
