### ISSUE TITLE
AttributeMap.field_111163_c: descriptionToAttributeInstanceMap -> instancesByName

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#368]
`AttributeMap.field_111163_c`: `descriptionToAttributeInstanceMap` -> `instancesByName`

1. It's not by description, it's by the attribute name
2. it's a mouthful

**Comment by kashike** [comment]
done.
- [x] `field_111163_c`: `descriptionToAttributeInstanceMap` -> `instancesByName`
