### ISSUE TITLE
AttributeMap.field_111162_d: attributeInstanceSet -> dirtyInstances + associated method

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#369]
`AttributeMap.field_111162_d`: `attributeInstanceSet` -> `dirtyInstances`

This is a set of all dirty attribute instances that need to be synced to the client. It's retrieved when SPacketEntityProperties is being built and cleared after the packet is sent. Instances are placed into it when the value of the attribute is changed.

**Comment by williewillus** [comment]
also 
`AttributeMap.func_111161_b`: `getAttributeInstanceSet` -> `getDirtyInstances`

**Comment by kashike** [comment]
done.

- [x] `field_111162_d`: `attributeInstanceSet` -> `dirtyInstances`
- [x] `func_111161_b`: `getAttributeInstanceSet` -> `getDirtyInstances`
