### ISSUE TITLE
EntityLivingBase.isServerWorld -> canUpdateAI

### ISSUE THREAD

**Issue by xaeroverse** [ModCoderPack/MCPBot-Issues#37]
This function used to be called `isClientWorld` a few years back (as described in issue #29) but was changed to `isServerWorld` because of the `!world.isRemote` check.  `isServerWorld` was appropriate for most cases in 1.7.10 but 1.8 introduced new logic that makes the name inappropriate (actually, `isClientWorld` was correct for a different case as I'll describe below).  Two subclasses in particular, `EntityLiving` and `EntityArmorStand`, override the definition to incorporate new NBT tags introduced in 1.8.  As an example, I'll reduce `EntityLiving` for clarity but the same can be applied to `EntityArmorStand`:

```java
    // EntityLivingBase
    public boolean isServerWorld()
    {
        return !this.worldObj.isRemote;
    }
    // EntityLiving extends EntityLivingBase
    public boolean isServerWorld()
    {
        return super.isServerWorld() && !this.isAIDisabled();
    }
    // EntityArmorStand extends EntityLivingBase
    public boolean isServerWorld()
    {
        return super.isServerWorld() && !this.hasNoGravity();
    }
```

Reduction of double-negatives:

```java
super.isServerWorld() && !this.isAIDisabled()
!world.isRemote && !isAIDisabled
!world.isRemote && AIEnabled
```

Calling this function on the client will never return true.  However, the case where the function is now a misnomer is when on the server, an entity's AI is disabled:

```
!world.isRemote && AIEnabled
true && false
false
```

As for a more appropriate name, I'm tentatively proposing `canUpdateAI` based on an important code section:

1.8 EntityLivingBase#onLivingUpdate

```java
        this.worldObj.theProfiler.startSection("ai");

        if (this.isMovementBlocked())
        {
            this.isJumping = false;
            this.moveStrafing = 0.0F;
            this.moveForward = 0.0F;
            this.randomYawVelocity = 0.0F;
        }
        else if (this.isServerWorld())
        {
            this.worldObj.theProfiler.startSection("newAi");
            this.updateEntityActionState();
            this.worldObj.theProfiler.endSection();
        }

        this.worldObj.theProfiler.endSection();
```

1.7.10 EntityLivingBase#onLivingUpdate

```java
        this.worldObj.theProfiler.startSection("ai");

        if (this.isMovementBlocked())
        {
            this.isJumping = false;
            this.moveStrafing = 0.0F;
            this.moveForward = 0.0F;
            this.randomYawVelocity = 0.0F;
        }
        else if (this.isServerWorld())
        {
            if (this.isAIEnabled())
            {
                this.worldObj.theProfiler.startSection("newAi");
                this.updateAITasks();
                this.worldObj.theProfiler.endSection();
            }
            else
            {
                this.worldObj.theProfiler.startSection("oldAi");
                this.updateEntityActionState();
                this.worldObj.theProfiler.endSection();
                this.rotationYawHead = this.rotationYaw;
            }
        }

        this.worldObj.theProfiler.endSection();
```

Other possibilities I thought of are:
- canUpdateEntityActionState (because of the call in newAi)
- canUpdateMovement (because of various references to motion in `moveEntityWithHeading`, and the `NoGravity` NBT tag in one of the definitions)
- canUpdatePosition

But, since the important code is within an AI section, I eliminated the `canUpdateMovement`/`canUpdatePosition` candidates.  I also eliminated `canUpdateEntityActionState` because if this mapping were hypothetically applied retroactively to 1.7.10, it would be too specific as 1.7.10 has both the entity "oldAi" and "newAi" present (AI is more general than EntityActionState).

Of course, Minecraft's code is not straight-forward.  The monkey wrench is `net.minecraft.client.entity.EntityPlayerSP` (extending `EntityPlayer` extending `EntityLivingBase`) which overrides the superclass's method definition to always return true.  ~~However, it also overrides `onLivingUpdate` so it seems that the overridden method is never called for `EntityPlayerSP`.~~ Despite `onLivingUpdate` and `moveEntityWithHeading` being overridden, they do call the `super()` method at some point - I suspect this is the origin of the `isClientWorld` name.

So there are two cases to consider for this method: 1) one and only one `EntityPlayerSP` as instantiated by `Minecraft.thePlayer`, and 2) one or more `EntityLivingBase`s on the logically local server (first one being the `EntityPlayerSP`).  For now, `canUpdateAI` is my recommendation, though I can see the case for `canUpdateMovement` (esp. with the `moveEntityWithHeading` method).  I'm open to suggestions as well...

**Comment by kashike** [comment]
Usage in `EntityGuardian` as well, now:
```java
    public void moveEntityWithHeading(float strafe, float forward) {
        if (this.isServerWorld() && this.isInWater()) {
            this.moveRelative(strafe, forward, 0.1F);
            this.move(MoverType.SELF, this.motionX, this.motionY, this.motionZ);
            this.motionX *= 0.8999999761581421D;
            this.motionY *= 0.8999999761581421D;
            this.motionZ *= 0.8999999761581421D;

            if (!this.isMoving() && this.getAttackTarget() == null) {
                this.motionY -= 0.005D;
            }
        } else {
            super.moveEntityWithHeading(strafe, forward);
        }
    }
```

**Comment by liach** [comment]
@kashike I think we should call it `shouldUpdateAction` since it is called where drag, action, and other motions are applied.

**Comment by williewillus** [comment]
further research suggests this be called `canControlMotion` or something similar. 

Analyzing cases where this is called, in 1.12.2:
* Guardians (as noted above), check this before moving in water, applying drag, and sinking when not aggroed
* EntityLivingBase guard everything in `travel` around this method or being steered by a rider. This covers everything from gravity, air friction, AI, slippery blocks, etc.
* EntityLivingBase applies minor drag every tick if this method returns false, so the entity eventually slows to a stop

Analyzing implementations:
* By default, returns `!world.isRemote`, which makes sense since the server ultimately controls motion.
* On AI-eligible entities, adds additional condition that the NoAI tag is not set. In vanilla, NoAI causes entities to not respond at all to natural motion and not perform pathfinding at all, which agrees with the analysis above
* Likewise, armor stands check that the NoGravity tag is not set.
* On client players, always returns true. This is expected, because client players are the only entities in MC where the client tells the server what to do, not the other way around.

`shouldUpdateAction` is a bit too vague for my taste. "Action" is a very broad term, and the usage of this method implies some sort of "control" over motion, not just a check to see if updating should happen.

**Comment by bs2609** [comment]
Do think "motion" is a little narrow here, especially due to the use in controlling despawning. AI tasks can also involve more than just moving.

**Comment by darkhax** [comment]
I ran into this issue recently, it is a pretty misleading name.
