### ISSUE TITLE
ChunkCache 'extendedLevels' field/method needs renaming

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#370]
Current names:
*  `field_72814_d => hasExtendedLevels`
*  `func_72806_N => extendedLevelsInChunkCache`

These are not only both long and not overly descriptive, they also represent the opposite of what they claim.

`hasExtendedLevels` is true by default, and is set to false if `!chunk.getAreLevelsEmpty(posFromIn.getY(), posToIn.getY())` evaluates to true for a contained chunk (ie the chunk in question is not empty at those y-levels).

The only vanilla usage is in `RenderChunk.rebuildChunk()` which skips rendering if the check ` !this.region.extendedLevelsInChunkCache()` fails.

So the field (and associated method) do not represent the ChunkCache 'having' anything, they indicate an absence of data.

Any suggestions for better names that work with the unfortunate amount of negation welcome.

**Comment by williewillus** [comment]
I think a simple `empty` and `isEmpty()` should suffice.

The field is set to false if any part of the desired region has any blocks, so the word "empty" captures the meaning pretty well.

**Comment by bs2609** [comment]
Also `Chunk.getAreLevelsEmpty()` (`func_76606_c`) could also do with a change while we're at it.
Perhaps `isEmptyBetween()`?

**Comment by kashike** [comment]
done.
- [x] `field_72814_d`: `hasExtendedLevels` -> `empty`
- [x] `func_72806_N`: `extendedLevelsInChunkCache` -> `isEmpty`
- [x] `func_76606_c`: `getAreLevelsEmpty` -> `isEmptyBetween`
