### ISSUE TITLE
TileEntityHopper.func_145884_b: getHopperInventory -> getSourceInventory

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#372]
`TileEntityHopper.func_145884_b`: `getHopperInventory` -> `getSourceInventory`

This does not retrieve the inventory of the hopper itself, it retrieves the IInventory (block or entity) the hopper should extract from (by passing y+1 as the vertical coordinate)

**Comment by kashike** [comment]
done.
- [x] `func_145884_b`: `getHopperInventory` -> `getSourceInventory`
