### ISSUE TITLE
IBlockStatePalette.func_186040_a: getSerializedState -> getSerializedSize

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#374]
`IBlockStatePalette.func_186040_a`: `getSerializedState` -> `getSerializedSize`

Should be fairly self explanatory, calculates the number of bits to hold each entry in the palette, then sums them. Used by `BlockStateContainer.getSerializedSize`, which is properly named.

**Comment by kashike** [comment]
done.
- [x] `func_186040_a`: `getSerializedState` -> `getSerializedSize`
