### ISSUE TITLE
VillageDoorInfo.func_75473_b: getInsidePosY -> getLastActivityTimestamp

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#375]
`VillageDoorInfo.func_75473_b`: `getInsidePosY` -> `getLastActivityTimestamp`

The setter and field are named right but the getter isn't :P

**Comment by kashike** [comment]
done.
- [x] `func_75473_b`: `getInsidePosY` -> `getLastActivityTimestamp`
