### ISSUE TITLE
Various "/save-all flush" methods and fields

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#376]
`/save-all flush`
=> `WorldServer.saveChunkData`
=> `ChunkProviderServer.saveExtraData`
=> `IChunkLoader.saveExtraData`
=> `AnvilChunkLoader` implementation which just waits for threads to finish writing to disk.

This method chain is only invoked when the `flush` subcommand of `/save-all` is issued.

So to avoid confusion with the normal saving methods, requesting the following renames:
`WorldServer.func_104140_m`: `saveChunkData` -> `flushToDisk`
`ChunkProviderServer.func_104112_b`: `saveExtraData` -> `flushToDisk`
`IChunkLoader.func_75818_b`: `saveExtraData` -> `flush`
`AnvilChunkLoader.field_183014_e`: `savingExtraData` -> `flush`

made the first two `flushToDisk` so it's more clear what's happening. in the context of the second pair it's clear what `flush` means, but not necessarily for the first two

**Comment by kashike** [comment]
Could you please provide some comments to be set when changing these?

**Comment by williewillus** [comment]
Just updated the comments for all of them

**Comment by kashike** [comment]
Do these sound good to you, @williewillus?
- [ ] `func_104140_m`: `saveChunkData` -> `saveDirtyChunks`
- [ ] `func_104112_b`: `saveExtraData` -> `flushPendingWrites`
- [ ] `func_75818_b`: `saveExtraData` -> `flushPendingWrites`
- [ ] `field_183014_e`: `savingExtraData` -> `flushing`

**Comment by williewillus** [comment]
Sound good to me

**Comment by kashike** [comment]
done.
- [x] `func_104140_m`: `saveChunkData` -> `saveDirtyChunks`
- [x] `func_104112_b`: `saveExtraData` -> `flushPendingWrites`
- [x] `func_75818_b`: `saveExtraData` -> `flushPendingWrites`
- [x] `field_183014_e`: `savingExtraData` -> `flushing`
