### ISSUE TITLE
ModelBiped.func_178719_a, ModelPlayer.func_178719_a: setInvisible -> showModelParts

### ISSUE THREAD

**Issue by Marcono1234** [ModCoderPack/MCPBot-Issues#377]
The method `net.minecraft.client.model.ModelBiped.setInvisible(boolean)` and the overriding method `net.minecraft.client.model.ModelPlayer.setInvisible(boolean)` do not set the invisibility but instead if the model should be shown (the opposite).

**Comment by kashike** [comment]
done.
- [x] `func_178719_a`: `setInvisible` -> `setVisible`
