### ISSUE TITLE
Shader.func_148042_a: loadShader -> render (+1)

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#378]
`Shader.func_148042_a`: `loadShader` -> `render`

This doesn't do any loading, it binds the shader, draws the contents of an FBO, then unbinds the shader.

With that, also: `Shader.func_148040_d`: `preLoadShader` -> `preRender`

(The class names of the shader pkg are also questionable but that's for another ticket)

**Comment by williewillus** [comment]
Additionally,
`ShaderGroup.func_148018_a`: `loadShaderGroup` -> `render` (calls `Shader.loadShader`)

**Comment by matthewprenger** [comment]
Done.
`func_148042_a`: `loadShader` -> `render`
`func_148040_d`: `preLoadShader` -> `preRender`
`func_148018_a`: `loadShaderGroup` -> `render`
