### ISSUE TITLE
ChunkCompileTaskGenerator -> ChunkRenderTask

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#379]
`ChunkCompileTaskGenerator` -> `ChunkRenderTask`

* It doesn't generate tasks, it *is* the task
* It doesn't just compile the chunk, it also holds the actual vertex data and has a state `UPLOADING` where said data is uploaded to the GPU, so I'm generalizing the name to `ChunkRenderTask`

**Comment by bs2609** [comment]
This error message seems to suggest `ChunkRenderTask` is a good name:
```java
ChunkRenderWorker.LOGGER.warn("Chunk render task was {} when I expected it to be uploading; aborting task", (Object)generator.getStatus());
```

Also proposing related field rename:
`RenderChunk.field_178599_i`: `compileTask` -> `renderTask`

**Comment by bs2609** [comment]
Also I guess I should request if this could be added to #514?

**Comment by kashike** [comment]
added

**Comment by kashike** [comment]
- [x] `net/minecraft/client/renderer/chunk/ChunkCompileTaskGenerator` → `net/minecraft/client/renderer/chunk/ChunkRenderTask`
