### ISSUE TITLE
Rename WorldChunkManager

### ISSUE THREAD

**Issue by gabizou** [ModCoderPack/MCPBot-Issues#38]
It's not actually a World Chunk manager. It provides biomes for the world (seeing as it's a one to one relationship of world to manager).

Possible names to suggest are:
- BiomeProvider
- BiomeManager
- BiomeGeneratorManager
- WorldBiomeManager

@Deamon5550 can likely provide more explanation and or name options.

**Comment by LexManos** [comment]
BiomeProvider is probably best, and WorldChunkManagerHell should be BiomeProviderSingle.

**Comment by LexManos** [comment]
1.9: 
net/minecraft/world/biome/WorldChunkManager -> BiomeProvider
net/minecraft/world/biome/WorldChunkManagerHell -> BiomeProviderSingle
