### ISSUE TITLE
BlockFenceGate bounding box constants names interchanged

### ISSUE THREAD

**Issue by Marcono1234** [ModCoderPack/MCPBot-Issues#380]
The `BlockFenceGate` class has 6 bounding box constants. Two are the collision boxes and the other four are the hitboxes. Currently the names are interchanged, the hitboxes are named for example `AABB_COLLIDE_ZAXIS`.

|SRG Name|Current constant name|Suggested constant name|
|---|---|---|
|`field_185540_C`|`AABB_CLOSED_SELECTED_XAXIS`|`AABB_COLLISION_BOX_XAXIS`|
|`field_185539_B`|`AABB_CLOSED_SELECTED_ZAXIS`|`AABB_COLLISION_BOX_ZAXIS`|
|`field_185542_e`|`AABB_COLLIDE_XAXIS`|`AABB_HITBOX_XAXIS`|
|`field_185544_g`|`AABB_COLLIDE_XAXIS_INWALL`|`AABB_HITBOX_XAXIS_INWALL`|
|`field_185541_d`|`AABB_COLLIDE_ZAXIS`|`AABB_HITBOX_ZAXIS`|
|`field_185543_f`|`AABB_COLLIDE_ZAXIS_INWALL`|`AABB_HITBOX_ZAXIS_INWALL`|

**Comment by kashike** [comment]
done.
- [x] `field_185540_C`: `AABB_CLOSED_SELECTED_XAXIS` -> `AABB_COLLISION_BOX_XAXIS`
- [x] `field_185539_B`: `AABB_CLOSED_SELECTED_ZAXIS` -> `AABB_COLLISION_BOX_ZAXIS`
- [x] `field_185542_e`: `AABB_COLLIDE_XAXIS` -> `AABB_HITBOX_XAXIS`
- [x] `field_185544_g`: `AABB_COLLIDE_XAXIS_INWALL` -> `AABB_HITBOX_XAXIS_INWALL`
- [x] `field_185541_d`: `AABB_COLLIDE_ZAXIS` -> `AABB_HITBOX_ZAXIS`
- [x] `field_185543_f`: `AABB_COLLIDE_ZAXIS_INWALL` -> `AABB_HITBOX_ZAXIS_INWALL`
