### ISSUE TITLE
Entity.func_70076_C: kill -> dealVoidDamage

### ISSUE THREAD

**Issue by Marcono1234** [ModCoderPack/MCPBot-Issues#382]
The method `Entity.kill()` deals damage to the entity when it falls out of the world. Since it does not kill `EntityLivingBase` entities directly it might be better to change the name of the method.
Additionally the description of the method needs to be changed as well.

**Comment by kashike** [comment]
It doesn't damage, it simply marks the `Entity` as removed. `voidRemove`?

**Comment by matthewprenger** [comment]
It does deal damage in EntityLivingBase, but I don't think the word damage should be a part of the name. My vote is for `outOfWorld`.
![](https://i.imgur.com/MuMmIdk.png)

**Comment by Marcono1234** [comment]
Maybe rather `handleOutOfWorld` or something similar, otherwise it is missing a verb and therefor sounds rather like a field name.

**Comment by kashike** [comment]
done.
- [x] `func_70076_C`: `kill` -> `outOfWorld`

**Comment by Marcono1234** [comment]
@kashike what do you think about my previous comment?

**Comment by kashike** [comment]
A verb isn't necessary in every name.
