### ISSUE TITLE
Items ~ Item field_191525_da

### ISSUE THREAD

**Issue by LambdaXV** [ModCoderPack/MCPBot-Issues#383]
There is an item in the Items class that has a obfuscated name of : field_191525_da

It seems to be used in Smelting, specifically, Chainmail armor and Iron tools/armor.

**Comment by kashike** [comment]
So name it. You don't need to open an issue to name unnamed fields/methods/parameters.

**Comment by liach** [comment]
`smeltToItem`?

**Comment by williewillus** [comment]
It's probably the iron nugget which can't be mapped yet bc it's 1.11.2

**Comment by liach** [comment]
Ok... #360
