### ISSUE TITLE
GuiMainMenu.updateCounter -> minceraftRandomNumber

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#386]
GuiMainMenu's <ruby><rb><code>updateCounter</code></rb><rp> (<rt><code>field_73974_b</code></rt><rp>)</rp</ruby> isn't actually a counter.  It instead controls the chance of the title screen [saying Minceraft](https://minecraft.gamepedia.com/Menu_screen#Minceraft) instead of Minecraft, and is set to a random number on construction.  I've already updated the documentation.

"minceraftRandomNumber" isn't the perfect name, but it conveys the purpose better than "updateCounter".  If there's a nicer name, I'm for that instead.

**Comment by kashike** [comment]
`minceraftChance`?

**Comment by Pokechu22** [comment]
That was my first thought, but IMO that name implies the chance that it would occur (eg, `.0001`), not the already-rolled random number that is compared with the chance.

**Comment by bs2609** [comment]
`minceraftRoll`?

**Comment by kashike** [comment]
done.
- [x] `field_73974_b`: `updateCounter` -> `minceraftRoll`
