### ISSUE TITLE
Cleanup of _Obj field names

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#387]
What's left:
* `villageObj`:
  *  `EntityVillager#field_70954_d`
  *  `EntityIronGolem#field_70857_d`
  *  `EntityAIVillagerMate#field_75452_a`
* `villagerObj`:
  *  `EntityAIPlay#field_75262_a`
  *  `EntityAIVillagerMate#field_75450_b`
* `villageCollectionObj`: `World#field_72982_D`
* `entityObj`:
  *  `EntitySenses#field_75526_a`
  *  `EntityAIMoveIndoors#field_75424_a`
  *  `EntityAIRestrictOpenDoor#field_75275_a`
* `entityDragonObj`: `EntityDragonPart#field_70259_a`
* `entityplayerObj`: `MapData$MapInfo#field_76211_a`
* `bookObj`: `GuiScreenBook#field_146474_h`
* `worldSelectionObj`: `GuiListWorldSelection#field_186798_v`
* `playerNBTManagerObj`: `PlayerList#field_72412_k`

**Comment by diesieben07** [comment]
May I also suggest `playerNBTManagerObj` => `playerNbtManagerObj`?

**Comment by kashike** [comment]
done.
- [x] `field_70259_a`: `entityDragonObj` -> `parent`
- [x] `field_70857_d`: `villageObj` -> `village`
- [x] `field_70954_d`: `villageObj` -> `village`
- [x] `field_72412_k`: `playerNBTManagerObj` -> `playerDataManager`
- [x] `field_72982_D`: `villageCollectionObj` -> `villageCollection`
- [x] `field_75262_a`: `villagerObj` -> `villager`
- [x] `field_75275_a`: `entityObj` -> `entity`
- [x] `field_75424_a`: `entityObj` -> `entity`
- [x] `field_75450_b`: `villagerObj` -> `villager`
- [x] `field_75452_a`: `villageObj` -> `village`
- [x] `field_75526_a`: `entityObj` -> `entity`
- [x] `field_76211_a`: `entityplayerObj` -> `player`
- [x] `field_146474_h`: `bookObj` -> `book`
- [x] `field_186798_v`: `worldSelectionObj` -> `worldSelection`
