### ISSUE TITLE
PotionHealth -> PotionInstant

### ISSUE THREAD

**Issue by Choonster** [ModCoderPack/MCPBot-Issues#388]
`PotionHealth` -> `PotionInstant`

This class is used for all instant effects, not just Instant Health. There's nothing health-specific about it.

**Comment by bs2609** [comment]
Another change I'd like to see in #514 if possible.

**Comment by kashike** [comment]
- [x] `net/minecraft/potion/PotionHealth` → `net/minecraft/potion/PotionInstant`
