### ISSUE TITLE
Block.blocksMovement back to isPassable?

### ISSUE THREAD

**Issue by BrainStone** [ModCoderPack/MCPBot-Issues#389]
`Block.blocksMovement` should be renamed back to `isPassable` as the doc states:

> Determines if an entity can path through this block

And if it returns true it means the block does **not** block the movement. Very confusing. The old name was fine.

**Comment by kashike** [comment]
@LexManos You changed this, so I'll leave this one up to you.

**Comment by mezz** [comment]
This needs to be changed. The implementation looks like this, clearly a mistake:
```java
    public boolean blocksMovement(IBlockAccess worldIn, BlockPos pos)
    {
        return !this.blockMaterial.blocksMovement();
    }
```

**Comment by kashike** [comment]
done.
- [x] `func_176205_b`: `blocksMovement` -> `isPassable`
