### ISSUE TITLE
Chunk position fields

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#390]
* `Chunk#field_76635_g`: xPosition -> xPos
* `Chunk#field_76647_h`: zPosition -> zPos

Not a particularly important change, but it cuts down on line lengths in a good few places, and it's consistent with the NBT tag names.

**Comment by diesieben07** [comment]
Why not `x` and `z`?

**Comment by bs2609** [comment]
`x` and `z` would be best for brevity, but I also wanted to not clash with parameter names.

**Comment by kashike** [comment]
done.
- [x] `field_76635_g`: `xPosition` -> `x`
- [x] `field_76647_h`: `zPosition` -> `z`

additionally, these have been changed as well:
- [x] `field_77275_b`: `chunkZPos` -> `z`
- [x] `field_77276_a`: `chunkXPos` -> `x`
