### ISSUE TITLE
field_76805_H, field_76801_G: BiomeDecorator.sandPerChunk and sandPerChunk2 - inaccurate names and javadoc

### ISSUE THREAD

**Issue by Barteks2x** [ModCoderPack/MCPBot-Issues#391]
They don't actually mean the same thing. The `sandPerChunk` one is for gravel, and `sandPerChunk2` is for sand. It generates underwater gravel/sand and sometime salso parts of it appear on surface.

My proposed names and documentation:
 * `sandPerChunk2` -> `sandPatchesPerChunk`. Javadoc: copy that of current `sandPerChunk`
 * `sandPerChunk` -> `gravelPatchesPerChunk`. Javadoc: keep current but change "sand" to "gravel"

**Comment by matthewprenger** [comment]
Fixed.
`field_76801_G`: `sandPerChunk` -> `gravelPerChunk`
`field_76805_H`: `sandPerChunk2` -> `sandPerChunk`

**Comment by Barteks2x** [comment]
I wanted to avoid the name `gravelPerChunk` because it could be easily confused with gravel generated undergound as "ore"

**Comment by matthewprenger** [comment]
Good point. Updated.
