### ISSUE TITLE
func_175672_r: World.getTopSolidOrLiquidBlock actually ignores liquid blocks

### ISSUE THREAD

**Issue by Barteks2x** [ModCoderPack/MCPBot-Issues#392]
The real condition for returnign a give position is:
```
if (state.getMaterial().blocksMovement() && !state.getBlock().isLeaves(state, this, blockpos1) && !state.getBlock().isFoliage(this, blockpos1))
```
 Liquids don't block movement so this is no longer accurate.

I'm not sure what the right name of this method should be.  Maybe `getTopSolidBlock`?
It also seems to actually return the position of block above, not of the solid block.

**Comment by bs2609** [comment]
`getHighestSurface()`?

**Comment by Barteks2x** [comment]
There is also getHeight which returns the top *opaque* block position (well, the blocm above) which I think also could be renamed to avoid confusion. `getSurfaceLevel` sounds reasonable.

**Comment by Minecrell** [comment]
It returns the coordinates of a block, not just the y coordinates. Maybe `getSurfaceBlock` would be more appropriate?

**Comment by bs2609** [comment]
It takes a block position as a parameter, and returns a new position with the same x, z coordinates. Only the y value is changed.

**Comment by PaleoCrafter** [comment]
Considering it translates the provided position to the surface level, maybe the method should be renamed to `translateToSurfaceLevel`? That seems to incorporate both the fact that it's about the surface level and that the method returns another BlockPos.

**Comment by kashike** [comment]
`getTopSolidBlock`?

**Comment by bs2609** [comment]
Dunno. It returns a position, and it's the position of the (non-solid) block above.

**Comment by kashike** [comment]
`getAboveTopSolidBlock`? :dancer:

**Comment by bs2609** [comment]
Personally I prefer `getSurfaceLevel` or `translateToSurface`.

**Comment by kashike** [comment]
`getSurfaceLevel` and `translateToSurface` don't seem right:
>  it's the position of the (non-solid) block above

Let's see if there are any other names we can find, maybe.

**Comment by bs2609** [comment]
It's consistent with `getSeaLevel` - the y-value is at the bottom of the block.
