### ISSUE TITLE
EntityLivingBase.field_70708_bq: entityAge -> despawnTimer (+ getter)

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#394]
`EntityLivingBase.field_70708_bq`: `entityAge` -> `despawnTimer`
`EntityLivingBase.func_70654_ax`: `getAge` -> `getDespawnTimer`

This isn't really the entity's age, but rather a kind of "idle counter".

* It's incremented every tick before despawning/AI runs
* It's reset to 0 whenever un-despawnable entities and bosses try to despawn
* It's reset to 0 when the entity is attacked
* If this counter is greater than 600 and the nearest player is further than sqrt(1024) away, and a random check passes, the entity tries to despawn
* But if a player is within sqrt(1024) of the entity, it's reset to 0.

So it's pretty evident this is some sort of idle/despawn counter that increments but gets reset often, not really a monotonically increasing age field.

**Comment by matthewprenger** [comment]
My vote would be for `inactiveTime` or `idleTime`.

**Comment by williewillus** [comment]
i had something like `idleCounter` at first, and @kashike also had something with "idle" in it, so consensus says probably a safe bet to go with `idleTime`

**Comment by kashike** [comment]
done.
- [x] `field_70708_bq`: `entityAge` -> `idleTime`
- [x] `func_70654_ax`: `getAge` -> `getIdleTime`
