### ISSUE TITLE
EntityLivingBase.field_70755_b: entityLivingToAttack -> revengeTarget (+ getter)

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#395]
`EntityLivingBase.field_70755_b`: `entityLivingToAttack` -> `revengeTarget`
`EntityLivingBase.func_70643_av`: `getAITarget()` -> `getRevengeTarget`
The associated setter is already named properly.

This field is 
* set immediately after the owner is damaged (if the attacker is EntityLivingBase)
* cleared 100 ticks later (or if the entity in the variable dies)
* zombie pigmen use this field for some special case magic to force pigmen to remember the player pretty much forever

The only thing it's used for is to give AI tasks such as `EntityAIHurtByTarget` a chance to react and change the owner's behaviour (which *may* involve changing the active target to the revenge target).
Zombie pigmen constantly reset this field if they're true-aggroed by a player so their targeting tasks will keep on selecting the aggroed player for the active target again and again.

The primary reason for this rename is that this field/method pair is easily conflated with the more common `EntityLiving.{get, set}AttackTarget` and `EntityLiving.attackTarget` pair, which holds the target that this entity is *actively* pursuing. This field is only set for a short time to give entities a *chance* to react, but is not the active target as the name suggests. Better name suggestions welcome (though `lastAttacker` is already taken by another field)

**Comment by matthewprenger** [comment]
Done.
`field_70755_b`: `entityLivingToAttack` -> `revengeTarget`
`func_70643_av`: `getAITarget` -> `getRevengeTarget`
