### ISSUE TITLE
EntityAIHurtByTarget.field_179447_c: targetClasses -> excludeWhenCallingForHelp

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#396]
`EntityAIHurtByTarget.field_179447_c`: `targetClasses` -> `excludeWhenCallingForHelp`

Name suggestions taken :P 

This is not the classes that the task should target, but rather the classes that should be *excluded when calling for help*. By default, the task calls for help from all same/subclasses of the task owner, so it's used by `EntityZombie` to avoid calling for help from their subclass `EntityPigZombie`.

**Comment by bs2609** [comment]
`invalidReinforcements`?

**Comment by kashike** [comment]
`excludedReinforcementTypes`

**Comment by williewillus** [comment]
that sounds fine

**Comment by kashike** [comment]
done.
- [x] `field_179447_c`: `targetClasses` -> `excludedReinforcementTypes`
