### ISSUE TITLE
All thePrefixes

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#397]
### A
* `theAchievement`: `GuiAchievement.field_146266_k`
* `theAnimal`: `EntityAIMate.field_75390_d`

### B
* `theBiomeDecorator`: `Biome.field_76760_I`
* `theBlockPos`: `BlockPos$2$1.field_179314_b`

### C
* `theCalender`: `World.field_83016_L`
* `theCreature`: `EntityAIFleeSun.field_75372_a`

### D
* `theDefendingTameable`: `EntityAIOwnerHurtByTarget.field_75316_a`

### E
* `theEffectRenderer`: `ParticleFirework$Starter.field_92040_ay`
* `theEntity`:
  *  `EntityAISwimming [ field_75373_a ]`
  *  `EntityAIAvoidEntity [ field_75380_a ]`
  *  `EntityAIDoorInteract [ field_75356_a ]`
  *  `EntityAIMoveTowardsRestriction [ field_75436_a ]`
  *  `EntityRabbit$RabbitMoveHelper [ field_179929_g ]`
  *  `EntityAIOcelotAttack [ field_75409_b ]`
  *  `EntityAIMoveThroughVillage [ field_75420_a ]`
  *  `EntityAIMoveTowardsTarget [ field_75431_a ]`
  *  `EntityGuardian$AIGuardianAttack [ field_179456_a ]`
  *  `EntityAINearestAttackableTarget$Sorter [ field_75459_b ]`
  *  `PathNavigate [ field_75515_a ]`
  *  `EntityRabbit$RabbitJumpHelper [ field_180070_c ]`
  *  `EntityAIMoveToBlock [ field_179495_c ]`
  *  `EntityAIRestrictSun [ field_75273_a ]`
  *  `EntityAISit [ field_75272_a ]`
  *  `EntityRabbit$AIPanic [ field_179486_b ]`
* `theEntityTameable`: `EntityAIOwnerHurtTarget.field_75314_a`
* `theEntityTracker`: `WorldServer.field_73062_L`

### F
* `theFlatGeneratorInfo`: `GuiCreateFlatWorld.field_146387_g`

### G
* `theGameRules`:
  *  `WorldInfo.field_82577_x`
  *  `GameRules.field_82771_a`
* `theGameType`:
  *  `WorldSettings.field_77172_b`
  *  `WorldInfo.field_76113_q`
* `theGolem`:
  *  `EntityAILookAtVillager.field_75397_a`
  *  `EntityAIFollowGolem.field_75292_b`

### H
* `theHorse`: `ContainerHorseInventory.field_111242_f`

### I
* `theIntegratedServer`: `Minecraft.field_71437_Z`
* `theInventory`: `InventoryMerchant.field_70474_b`
* `theInventoryEnderChest`: `EntityPlayer.field_71078_a`
* `theItemStack`: `Achievement.field_75990_d`

### L
* `theLiving`: `EntityBodyHelper.field_75668_a`

### M
* `theMapItemRenderer`: `EntityRenderer.field_147709_v`
* `theMerchant`:
  *  `SlotMerchantResult.field_75234_h`
  *  `ContainerMerchant.field_75178_e`
  *  `InventoryMerchant.field_70476_a`
  *  `EntityAILookAtTradePlayer.field_75335_b`
* `theMerchantInventory`:
  *  `SlotMerchantResult.field_75233_a`
  *  `NpcMerchant.field_70937_a`
* `theMetadataSerializer`: `LanguageManager.field_135047_b`

### N
* `theNearestAttackableTargetSorter`: `EntityAINearestAttackableTarget.field_75306_g`

### O
* `theOwner`: `EntityAIFollowOwner.field_75339_e`
* `theOwnerAttacker`: `EntityAIOwnerHurtByTarget.field_75315_b`

### P
* `thePet`: `EntityAIFollowOwner.field_75338_d`

### R
* `theRConThreadMain`: `DedicatedServer.field_71339_n`
* `theRConThreadQuery`: `DedicatedServer.field_71342_m`
* `theRenderEngine`: `ParticleExplosionLarge.field_70583_ar`
* `theReportCategory`: `CrashReport.field_85061_c`
* `theResourceManager`: `TextureManager.field_110582_d`

### S
* `theScoreboard`:
  *  `ScoreboardSaveData.field_96507_a`
  *  `Score.field_96656_b`
  *  `ScoreObjective.field_96686_a`
  *  `ScorePlayerTeam.field_96677_a`
* `theScoreObjective`: `Score.field_96657_c`
* `theShaderGroup`: `EntityRenderer.field_147707_d`
* `theSlot`:
  *  `ContainerBrewingStand.field_75186_f`
  *  `GuiContainer.field_147006_u`

### T
* `theTameable`: `EntityAITargetNonTamed.field_75310_g`
* `theTarget`: `EntityAIOwnerHurtTarget.field_75313_b`
* `theTexture`:
  *  `Stitcher$Holder.field_98151_a`
  *  `CreativeTabs.field_78043_p`
* `theToolMaterial`: `ItemHoe.field_77843_a`

### V
* `theVictim`: `EntityAIOcelotAttack.field_75410_c`
* `theVillage`: `VillageSiege.field_75531_f`
* `theVillager`:
  *  `EntityAILookAtVillager.field_75395_b`
  *  `EntityAIFollowGolem.field_75294_a`
  *  `EntityAIHarvestFarmland.field_179504_c`

### W
* `theWatcher`: `EntityAIWatchClosest.field_75332_b`
* `theWolf`: `EntityAIBeg.field_75387_a`
* `theWorldGenerator`: `BiomeHills.field_82915_S`
* `theWorldSettings`: `IntegratedServer.field_71350_m`

**Comment by kashike** [comment]
Bah, you added more!

**Comment by bs2609** [comment]
That's all, I promise!

**Comment by kashike** [comment]
done - this result list should be correct, give or take a field or two.
- [x] `field_146266_k`: `theAchievement` -> `achievement`
- [x] `field_75390_d`: `theAnimal` -> `animal`
- [x] `field_76760_I`: `theBiomeDecorator` -> `decorator`
- [x] `field_179314_b`: `theBlockPos` -> `pos`
- [x] `field_83016_L`: `theCalender` -> `calendar`
- [x] `field_75372_a`: `theCreature` -> `creature`
- [x] `field_75316_a`: `theDefendingTameable` -> `tameable`
- [x] `field_92040_ay`: `theEffectRenderer` -> `manager`
- [x] `field_75373_a`: `theEntity` -> `entity`
- [x] `field_75380_a`: `theEntity` -> `entity`
- [x] `field_75356_a`: `theEntity` -> `entity`
- [x] `field_75436_a`: `theEntity` -> `creature`
- [x] `field_179929_g`: `theEntity` -> `rabbit`
- [x] `field_75409_b`: `theEntity` -> `entity`
- [x] `field_75420_a`: `theEntity` -> `entity`
- [x] `field_75431_a`: `theEntity` -> `creature`
- [x] `field_179456_a`: `theEntity` -> `guardian`
- [x] `field_75459_b`: `theEntity` -> `entity`
- [x] `field_75515_a`: `theEntity` -> `entity`
- [x] `field_180070_c`: `theEntity` -> `rabbit`
- [x] `field_179495_c`: `theEntity` -> `creature`
- [x] `field_75273_a`: `theEntity` -> `entity`
- [x] `field_75272_a`: `theEntity` -> `tameable`
- [x] `field_179486_b`: `theEntity` -> `rabbit`
- [x] `field_75314_a`: `theEntityTameable` -> `tameable`
- [x] `field_73062_L`: `theEntityTracker` -> `entityTracker`
- [x] `field_146387_g`: `theFlatGeneratorInfo` -> `generatorInfo`
- [x] `field_82577_x`: `theGameRules` -> `gameRules`
- [x] `field_82771_a`: `theGameRules` -> `rules`
- [x] `field_77172_b`: `theGameType` -> `gameType`
- [x] `field_76113_q`: `theGameType` -> `gameType`
- [x] `field_75397_a`: `theGolem` -> `ironGolem`
- [x] `field_75292_b`: `theGolem` -> `ironGolem`
- [x] `field_111242_f`: `theHorse` -> `horse`
- [x] `field_71437_Z`: `theIntegratedServer` -> `integratedServer`
- [x] `field_70474_b`: `theInventory` -> `slots`
- [x] `field_71078_a`: `theInventoryEnderChest` -> `enderChest`
- [x] `field_75990_d`: `theItemStack` -> `icon`
- [x] `field_75668_a`: `theLiving` -> `living`
- [x] `field_147709_v`: `theMapItemRenderer` -> `mapItemRenderer`
- [x] `field_75234_h`: `theMerchant` -> `merchant`
- [x] `field_75178_e`: `theMerchant` -> `merchant`
- [x] `field_70476_a`: `theMerchant` -> `merchant`
- [x] `field_75335_b`: `theMerchant` -> `villager`
- [x] `field_75233_a`: `theMerchantInventory` -> `merchantInventory`
- [x] `field_70937_a`: `theMerchantInventory` -> `merchantInventory`
- [x] `field_135047_b`: `theMetadataSerializer` -> `metadataSerializer`
- [x] `field_75306_g`: `theNearestAttackableTargetSorter` -> `sorter`
- [x] `field_75339_e`: `theOwner` -> `owner`
- [x] `field_75315_b`: `theOwnerAttacker` -> `attacker`
- [x] `field_75338_d`: `thePet` -> `tameable`
- [x] `field_71339_n`: `theRConThreadMain` -> `rconThread`
- [x] `field_71342_m`: `theRConThreadQuery` -> `rconQueryThread`
- [x] `field_70583_ar`: `theRenderEngine` -> `textureManager`
- [x] `field_85061_c`: `theReportCategory` -> `systemDetailsCategory`
- [x] `field_110582_d`: `theResourceManager` -> `resourceManager`
- [x] `field_96507_a`: `theScoreboard` -> `scoreboard`
- [x] `field_96656_b`: `theScoreboard` -> `scoreboard`
- [x] `field_96686_a`: `theScoreboard` -> `scoreboard`
- [x] `field_96677_a`: `theScoreboard` -> `scoreboard`
- [x] `field_96657_c`: `theScoreObjective` -> `objective`
- [x] `field_147707_d`: `theShaderGroup` -> `shaderGroup`
- [x] `field_75186_f`: `theSlot` -> `slot`
- [x] `field_147006_u`: `theSlot` -> `hoveredSlot`
- [x] `field_75310_g`: `theTameable` -> `tameable`
- [x] `field_75313_b`: `theTarget` -> `attacker`
- [x] `field_98151_a`: `theTexture` -> `sprite`
- [x] `field_78043_p`: `theTexture` -> `backgroundTexture`
- [x] `field_77843_a`: `theToolMaterial` -> `toolMaterial`
- [x] `field_75410_c`: `theVictim` -> `target`
- [x] `field_75531_f`: `theVillage` -> `village`
- [x] `field_75395_b`: `theVillager` -> `villager`
- [x] `field_75294_a`: `theVillager` -> `villager`
- [x] `field_179504_c`: `theVillager` -> `villager`
- [x] `field_75332_b`: `theWatcher` -> `entity`
- [x] `field_75387_a`: `theWolf` -> `wolf`
- [x] `field_82915_S`: `theWorldGenerator` -> `silverfishSpawner`
- [x] `field_71350_m`: `theWorldSettings` -> `worldSettings`
