### ISSUE TITLE
BiomeDecorator.field_76808_K: generateLakes -> generateRandomLiquidBlocks

### ISSUE THREAD

**Issue by Barteks2x** [ModCoderPack/MCPBot-Issues#398]
It doesn't enable surface and underground lakes, it enables single block liquid sources that appear as waterfalls.

**Comment by bs2609** [comment]
`generateWaterfallSources`, then

**Comment by Barteks2x** [comment]
Do lava sources fall under the definition of "**water**fall"?

**Comment by bs2609** [comment]
You called them waterfalls first :p

**Comment by Barteks2x** [comment]
From the lack of better word. I said that it generates liquid sources.

**Comment by bs2609** [comment]
`generateFalls`? Would be reasonable as a couterpart to `generateLakes`

**Comment by Pokechu22** [comment]
`generateSprings`?  Same concept, but I think springs more accurately explains it.

**Comment by kashike** [comment]
`generateFalls`? `generateSprings`?

**Comment by ArtixAllMighty** [comment]
generateSprings sounds good, though spring sounds to ofresh i.m.o, i automaticly coupled it with water. 

generateLiquidFalls is a general name that could be used , where liquid can be replaced in-mind by the reader by  'lava' , 'water', 'oil', ... generateFalls in this case is good too.

I must however disagree with generateSprings, as a spring is mostly something that comes out of the ground, and is very tight to water. (googling lava springs only brings up images of hot water springs)

**Comment by kashike** [comment]
done.
- [x] `field_76808_K`: `generateLakes` -> `generateFalls`
