### ISSUE TITLE
DamageSource.getSourceOfDamage and getEntity

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#399]
`DamageSource.func_76364_f`: `getSourceOfDamage` -> ???
`DamageSource.func_76346_g`: `getEntity` -> ???

Every single time I use one of these I have to check the bot to read the comment I put in to make sure I'm using the right one :P I think they need to be renamed to better fit their purpose.

The comment for `getSourceOfDamage`:
```
Retrieves the immediate causer of the damage, e.g. the arrow entity, not its shooter
```

The comment for `getEntity`:
```
Retrieves the true causer of the damage, e.g. the player who fired an arrow, the shulker who fired the bullet, etc.
```

Looking for better names for these two (`getSourceOfDamage` seems especially backward)

**Comment by williewillus** [comment]
also, if there is no layer of indirection, then `getSourceOfDamage` delegates to `getEntity`

**Comment by williewillus** [comment]
`getImmediateSource` and `getTrueSource` maybe?

**Comment by kashike** [comment]
done.
- [x] `func_76364_f`: `getSourceOfDamage` -> `getImmediateSource`
- [x] `func_76346_g`: `getEntity` -> `getTrueSource`
