### ISSUE TITLE
Rename EntityAIAttackOnCollide

### ISSUE THREAD

**Issue by Corosauce** [ModCoderPack/MCPBot-Issues#40]
EntityAIAttackOnCollide constantly repathfinds to target entity and will call attack method when close
EntityAIMoveTowardsTarget pathfinds once to target entity, and thats it

This class is the main 'chase target entity' class that all hostile land entities use, but the name doesn't quite explain it all

suggested rename:
EntityAIMoveTowardsTargetAndAttack

or maybe since its more about persistantly pathing to entity target, some suggestions:
EntityAIHuntTargetAndAttack
EntityAIChaseTargetAndAttack
EntityAIFollowTargetAndAttack

**Comment by bspkrs** [comment]
EntityAIFollowAndAttack?

**Comment by LexManos** [comment]
1.9:
net/minecraft/entity/ai/EntityAIAttackOnCollide  -> EntityAIAttackMelee
net/minecraft/entity/ai/EntityAIArrowAttack -> EntityAIAttackRanged
Also a new 'Bow' specific class added in 1.9: 'EntityAIAttackRangedBow'
