### ISSUE TITLE
MapStorage -> WorldDataStorage

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#400]
This isn't just for maps, it's for all `WorldSavedData` instances, so it should have a more generic name.

It's also full of comments referencing `MapDataBase` that should be updated to refer to `WorldSavedData` instead.

**Comment by bs2609** [comment]
`World.field_72988_C` (`mapStorage`) would also need updating if this class name changes.

**Comment by kashike** [comment]
- [x] `net/minecraft/world/storage/MapStorage` → `net/minecraft/world/storage/WorldSavedDataStorage`
