### ISSUE TITLE
EnchantmentDamage.field_77359_A: PROTECTION_NAME -> DAMAGE_NAME

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#403]
Used to store translation key parts for Sharpness, Smite, and Bane of Arthropods enchants, nothing to do with protection. The comment also needs updating accordingly.

**Comment by matthewprenger** [comment]
Done:
`field_77359_A`: `PROTECTION_NAME` -> `DAMAGE_NAMES`
