### ISSUE TITLE
Better names for tree generator classes

### ISSUE THREAD

**Issue by Barteks2x** [ModCoderPack/MCPBot-Issues#405]
Some of them are a bit confusing. Suggested renames: 
 * `WorldGenTrees` -> `WorldGenOakTree`
 * `WorldGenBigTree` -> `WorldGenBigOakTree`
 * `WorldGenHugeTrees` -> ??? (I don't know what it could be renamed to, maybe WorldGenHugeTreesBase? the crrent name definitely doesn't tell me what it aactually does)
 * `WorldGenSwamp` -> `WorldGenSwampTree`

**Comment by bs2609** [comment]
Also would like to see renames for:
* `WorldGenTaiga1` -> ???
* `WorldGenTaiga2` -> ???

Both actually tree generators, generating different types of spruce tree.

**Comment by kashike** [comment]
`WorldGenHugeTrees` -> `WorldGenMegaTree`
