### ISSUE TITLE
WorldType field/method names

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#408]
Fields:
* `field_82748_f`: `worldTypeId` -> `id`
* `field_77133_f`: `worldType` -> `name`
* `field_77141_i`: `isWorldTypeVersioned` -> `isVersioned`
* `field_151361_l`: `hasNotificationData` -> `hasInfoNotice`

Methods:
* `func_77128_b`: `getTranslateName()` -> `getTranslationKey()`
* `func_151359_c`: `getTranslatedInfo()` -> `getInfoTranslationKey()`
* `func_82747_f`: `getWorldTypeID()` -> `getID()`
* `func_151357_h`: `showWorldInfoNotice()` -> `hasInfoNotice()`
* `func_151358_j`: `setNotificationData()` -> `enableInfoNotice()`

**Comment by kashike** [comment]
done.
- [x] `field_180272_g`: `DEBUG_WORLD` -> `DEBUG_ALL_BLOCK_STATES`
- [x] `field_82748_f`: `worldTypeId` -> `id`
- [x] `field_77133_f`: `worldType` -> `name`
- [x] `field_77134_g`: `generatorVersion` -> `version`
- [x] `field_77141_i`: `isWorldTypeVersioned` -> `versioned`
- [x] `field_151361_l`: `hasNotificationData` -> `hasInfoNotice`
- [x] `func_82747_f`: `getWorldTypeID` -> `getId`
- [x] `func_77131_c`: `getGeneratorVersion` -> `getVersion`
- [x] `func_77128_b`: `getTranslateName` -> `getTranslationKey`
- [x] `func_151359_c`: `getTranslatedInfo` -> `getInfoTranslationKey`
- [x] `func_151357_h`: `showWorldInfoNotice` -> `hasInfoNotice`
- [x] `func_151358_j`: `setNotificationData` -> `enableInfoNotice`

`func_77132_a` could use a new name too - got a suggestion, @bs2609?

**Comment by bs2609** [comment]
`func_77132_a`: `getWorldTypeForGeneratorVersion` -> `ofVersion`?

**Comment by kashike** [comment]
`ofVersion` and `forVersion` both make sense to me
