### ISSUE TITLE
WorldProvider.func_76557_i: getAverageGroundLevel -> getMinimumGroundLevel

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#409]
Doesn't actually involve any averaging, normally delegates to `WorldType.getMinimumSpawnHeight()`, which generally returns (sea level+1).

Is used in average ground level calculations, but as the _minimum_ value to take in the event that `World.getTopSolidOrLiquidBlock()` returns a value below this (see #392). This prevents villages bordering lakes/oceans from being half-submerged.

**Comment by kashike** [comment]
`getSpawnYPosition`?
