### ISSUE TITLE
Rename EntityAIArrowAttack

### ISSUE THREAD

**Issue by Aaron1011** [ModCoderPack/MCPBot-Issues#41]
The class `EntityAIArrowAttack` isn't specifically to arrows. It calls `IRangedMob#attackEntityWithRangedAttack`, which is used for launching Wither skulls in `EntityWither`.

I suggest `EnittyAIRangedAttack` or `EntityAIProjectileAttack` as better names.

**Comment by LexManos** [comment]
https://github.com/ModCoderPack/MCPBot-Issues/issues/40
