### ISSUE TITLE
Other _Instance field names

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#410]
* `entityInstance`: `EntityRabbit$AIAvoidEntity.field_179511_d`
* `fontRendererInstance`: `GuiTextField.field_146211_a`
* `resourcePackInstance`: `ResourcePackRepository.field_148532_f`
* `clientInstance`: `GuiChat$ChatTabCompleter.field_186853_g` (might be ok)

**Comment by kashike** [comment]
done.
- [x] `field_179511_d`: `entityInstance` -> `rabbit`
- [x] `field_146211_a`: `fontRendererInstance` -> `fontRenderer`
- [x] `field_148532_f`: `resourcePackInstance` -> `serverResourcePack`
- [x] `func_148530_e`: `getResourcePackInstance` -> `getServerResourcePack`
- [x] `func_177319_a`: `setResourcePackInstance` -> `setServerResourcePack`
- [x] `field_186853_g`: `clientInstance` -> `client`
