### ISSUE TITLE
Minecraft.func_71410_x: getMinecraft -> getInstance

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#411]
As the field is now `Minecraft.instance`, this makes more sense (and reads better) as `getInstance()`, or just `instance()`.

**Comment by diesieben07** [comment]
I think this is a similar case to `World.isRemote`. This is so common and so widely used that by now it's just a standard.

**Comment by bs2609** [comment]
Not exactly the same... the name hasn't been changed and then changed back, it's just not been touched, along with the field until recently.

**Comment by kashike** [comment]
This method is used very often, and I don't see a reason to rename it at this point in time.

**Comment by bs2609** [comment]
That's fine, just thought it was worth considering at least.

**Comment by matthewprenger** [comment]
Yeah according to my 1.10.2 [data](https://gist.github.com/matthewprenger/309a6b43bfd64a52106b446f39acc6d6) this is the 13th most used Minecraft method by mods. I don't really see a solid reason to change it.
