### ISSUE TITLE
IChunkGenerator.func_180514_a: recreateStructures -> ???

### ISSUE THREAD

**Issue by Barteks2x** [ModCoderPack/MCPBot-Issues#412]
In a way this name is "technically correct" but it's very confusing/misleading. I think the name should be changed to something else, but I'm not sure what a good name would be. 

So I will explain how I got to that conclusion:

It seemed like a good idea for a name to me when I first saw it... it calls `generate` on all structure generators for that given chunk. It seems to be generating them again. But it also gives null `ChunkPrimer`.

In my mod (that replaces the whole chunk loading and generation code) I didn't really know what this method was about so I completely skipped it thinking it's not very important. Why would I need to re-create structures in existing chunks? And then I started getting crashes in the nether when trying to spawn mobs. It looked like the code was expecting `generate()` to be called before generating anything.

To me it looks like the purpose of that `recreateStructures` is to initialize the structure generator with World object, and load/regenerate internal information that these structures exist in that chunk. So for example mob spawning code "knows" that the structure is there. In a way it does re-create the structures, but the name is still confusing and I think it should be changed.

**Comment by bs2609** [comment]
An informative comment might help.

`generateStructures` also has a somewhat confusing name, but the comment at least clarifies what it's used for.

**Comment by williewillus** [comment]
I think recreateStructures is fine given what you've described. As bs said, maybe a good comment will do the trick

**Comment by Barteks2x** [comment]
I agree with that, I wasn't able to come up with a better name so far. Even when this one by itself is confusing. Maybe something like `reinitializeStructures`mwould also work.

**Comment by kashike** [comment]
Sounds like another case where a comment will help. Would you like to set a comment, since you've investigated this @Barteks2x?

**Comment by Barteks2x** [comment]
Would comment like this be ok?
```
Recreates data about structures intersecting given chunk (used for example by getPossibleCreatures), without placing any blocks. When called for the first time before any chunk is generated - also initializes the internal state needed by getPossibleCreatures.
```

**Comment by kashike** [comment]
Yup.

**Comment by Barteks2x** [comment]
Done.
