### ISSUE TITLE
MobSpawnerBaseLogic.field_98282_f : randomEntity -> currentSpawnEntry

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#413]
`MobSpawnerBaseLogic.field_98282_f` : `randomEntity` -> `currentSpawnEntry` (taking better names)

It holds the current entry from `spawnPotentials` that the spawner is actively using

**Comment by kashike** [comment]
`spawnData`?
```java
this.setNextSpawnData(new WeightedSpawnerEntity(1, nbt.getCompoundTag("SpawnData")));
```

**Comment by williewillus** [comment]
sure

**Comment by kashike** [comment]
done.
- [x] `field_98282_f`: `randomEntity` -> `spawnData`
