### ISSUE TITLE
World.func_184137_a.p_184137_9_: spectator -> ???

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#414]
This param doesn't control whether the detected players are in spectator mode or not. When this parameter is true, it checks for a player that is not in creative nor spectator. when false, it only checks for not spectator.

Unfortunately, not sure what a better name would be. I don't want to just say `aiTargettable` because of the name of the predicate used, because unrelated parts of the codebase like particles or enchanting tables call this too

**Comment by kashike** [comment]
Related methods that should also be renamed:
- [ ] `func_72890_a`
- [ ] `func_184136_b`

**Comment by kashike** [comment]
`aiTargettable` makes sense based on the usages, in my opinion.
