### ISSUE TITLE
IProjectile.func_70186_c: setThrowableHeading -> ???

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#417]
This is now implemented by `EntityArrow` and `EntityLlamaSpit` as well as `EntityThrowable`.
The comment also needs updating, it refers to `setArrowHeading`, which now doesn't exist (presumably replaced by the implementation of this method for arrows).

**Comment by matthewprenger** [comment]
IMO this shouldn't be called setHeading either. It's setting the heading, velocity, and inaccuracy. I'd call it `shoot` since it's actually shooting the projectile. Thoughts?

**Comment by bs2609** [comment]
`defineTrajectory`?

On a related note: `EntityArrow.setAim()` (`func_184547_a`) and `EntityThrowable.setHeadingFromThrower()` (`func_184538_a`) are functionally identical and could do with a unified name.

**Comment by kashike** [comment]
I agree with Matthew, `shoot` seems like the name for this.

**Comment by kashike** [comment]
done.
- [x] `func_70186_c`: `setThrowableHeading` -> `shoot`
- [x] `func_184547_a`: `setAim` -> `shoot`
- [x] `func_184538_a`: `setHeadingFromThrower` -> `shoot`

**Comment by bloodmc** [comment]
@kashike I don't agree with this change as the entity hasn't spawned into the world yet. "shoot" implies it's happening immediately but this is not the case.

setAim or setHeading is better.

**Comment by kashike** [comment]
The name was chosen based off the feedback given. Many people have seen this issue and have not been against it.

**Comment by bloodmc** [comment]
2 people is not many. You still haven't explained why "shoot" should be used when all uses for this method come BEFORE the entity has spawned.

**Comment by kashike** [comment]
2 people agreed with the same name, and there were no objections to it in the 2+ months this issue has been open. I know for a fact that other people have seen this issue.

It's worth noting that we (MCP) are not the only ones to have chosen this name - it seems CraftBukkit-based mappings use this name too:
```java
package net.minecraft.server;

public interface IProjectile {
    void shoot(double var1, double var3, double var5, float var7, float var8);
}
```

**Comment by PaleoCrafter** [comment]
I do admit that `shoot` is somewhat unfortunate in that it can both mean the act of shooting an object as well as a projectile 'launching' after being fired (See [Definition 2 in this dictionary for that](https://en.oxforddictionaries.com/definition/shoot)). The argument that the method is used before the entity is even spawned doesn't hold up for me, since the projectile IMO can be 'shot' even without existing in the world already (for purposes of some limited simulation, for instance).

**Comment by Corosauce** [comment]
I almost wanna suggest something like setVectorData that might cover heading/velocity/etc but even that sounds a bit odd.

**Comment by PaleoCrafter** [comment]
I don't think `launch` is a bad name, either, but it kind of has the same problems that `shoot` has. Anything else IMO is either too vague (`setVectorData`) or doesn't include everything (`setHeading`).

**Comment by williewillus** [comment]
I personally liked `setAim`

**Comment by Corosauce** [comment]
Yeah i was happy with setHeading, setAim would work too, sometimes you cant get a perfect method, the params and javadocs might help explain it more.

**Comment by bs2609** [comment]
I suggested "trajectory" as a slightly more catch-all term than heading, while not being too vague.

**Comment by covers1624** [comment]
These single noun names are stupid imo. For this context it needs 'set' before the name, "setAim", "setTrajectory", "setHeading".

**Comment by kashike** [comment]
Here's some options based on what has been said:
 - [ ] `setHeading`: :+1: 
 - [x] `shoot`: :-1: 
 - [ ] `defineTrajectory`: :laughing: 
 - [ ] `aim`: :tada: 
 - [ ] `setAim`: :confused:

React to *this* comment with your vote, or comment to suggest a name that is *not* in this list.

**Comment by covers1624** [comment]
I vote for `setTrajectory`

**Comment by williewillus** [comment]
I still don't like shoot. It sounds like calling it spawns the projectile in the world and sends it on it's way.

The projectile doesn't start moving until you add it to a world; it really hasn't been "shot" until that happens.
