### ISSUE TITLE
EntityLivingBase.field_184630_bs/field_184631_bt: handInventory/armorArray -> inventoryHandsCache/inventoryArmorCache

### ISSUE THREAD

**Issue by Choonster** [ModCoderPack/MCPBot-Issues#419]
These fields don't store the entity's current inventory, they store the entity's inventory as it was the previous tick so the entity can detect when its equipment changes.

The new names are closer to the ones used by `EntityLiving`, making it easier to see the relationship between them.

**Comment by gigaherz** [comment]
I don't think "cache" fits here, since it's not really a cache in any way. I'd go with something more like `prevInventoryHands`/`prevInventoryArmor`.
