### ISSUE TITLE
(x/y/z)Position fields

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#421]
Requesting changes to `xPos` or just `x` (if there's no other `xEtc` name).

* `GUIButton`:
  *  `field_146128_h`
  *  `field_146129_i`
* `Frustum`:
  *  `field_78550_b`
  *  `field_78551_c`
  *  `field_78549_d`
* `BiomeCache$Block`:
  *  `field_76888_d`
  *  `field_76889_e`
* `EntityAIWander`:
  *  `field_75455_b`
  *  `field_75456_c`
  *  `field_75453_d`
* `GuiTextField`:
  *  `field_146209_f`
  *  `field_146210_g`

**Comment by bs2609** [comment]
Similarly, possible `xCoord` -> `x` renames:

* `Vec3d`:
  *  `field_72450_a`
  *  `field_72448_b`
  *  `field_72449_c`
* `PathPoint`:
  *  `field_75839_a`
  *  `field_75837_b`
  *  `field_75838_c`

**Comment by kashike** [comment]
done.
- [x] `field_146128_h`: `xPosition` -> `x`
- [x] `field_146129_i`: `yPosition` -> `y`
- [x] `field_78550_b`: `xPosition` -> `x`
- [x] `field_78551_c`: `yPosition` -> `y`
- [x] `field_78549_d`: `zPosition` -> `z`
- [x] `field_76888_d`: `xPosition` -> `x`
- [x] `field_76889_e`: `zPosition` -> `z`
- [x] `field_75455_b`: `xPosition` -> `x`
- [x] `field_75456_c`: `yPosition` -> `y`
- [x] `field_75453_d`: `zPosition` -> `z`
- [x] `field_146209_f`: `xPosition` -> `x`
- [x] `field_146210_g`: `yPosition` -> `y`
- [x] `field_75839_a`: `xCoord` -> `x`
- [x] `field_75837_b`: `yCoord` -> `y`
- [x] `field_75838_c`: `zCoord` -> `z`
- [x] `field_72450_a`: `xCoord` -> `x`
- [x] `field_72448_b`: `yCoord` -> `y`
- [x] `field_72449_c`: `zCoord` -> `z`
