### ISSUE TITLE
MinecraftServer.func_71218_a: worldServerForDimension -> ???

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#422]
This could do with a snappier name, the current one's a bit of a mouthful.

Any ideas?

**Comment by williewillus** [comment]
A simple `getWorld` would suffice imo, the signature would tell you it takes the dim

**Comment by matthewprenger** [comment]
Done.
`func_71218_a`: `worldServerForDimension` -> `getWorld`
