### ISSUE TITLE
Biome.field_180281_af: GRASS_COLOR_NOISE -> PERLIN_NOISE

### ISSUE THREAD

**Issue by Barteks2x** [ModCoderPack/MCPBot-Issues#423]
This field has now more usages than just swamplands grass color, it's used 2 different parts of population code. Since there is no clear usage, I think it's supposed to be just perlin noise generator that is supposed to be used by populators whenever a perlin noise generator is needed.

All usages in 1.11.2:
 * `BiomeForest#pickRandomFlower` - specifies the type of flower generated
 * `BiomePlains#decorate` - switches between plains with more flowers and plains with more tall grass
 * `BiomePlains#pickRandomFlower` - same as above, same condition used, determines the types of slowers to use
 * `BiomeSwamp#genTerrainBlocks` - this one seems to make random water puddles with lilypads
 *  `BiomeSwamp#getGrassColorAtPos` - generates biome color, as the current name suggests

**Comment by kashike** [comment]
`INFO_NOISE`?

**Comment by gegy1000** [comment]
What about `COVER_NOISE`? Both flowers & grass can be seen as cover.

**Comment by Barteks2x** [comment]
Another possiblilty would be something closer to `SHARED_NOISE`. `INFO_NOISE` seems a bit confusing to me, but also explains a bit more than just `PERLIN_NOISE`.

**Comment by bs2609** [comment]
`DECORATION_NOISE`?

**Comment by kashike** [comment]
- [x] `field_180281_af`: `GRASS_COLOR_NOISE` &rarr; `INFO_NOISE`
