### ISSUE TITLE
Explosion field names

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#424]
* `field_77284_b`: `explosionX` -> `x`
* `field_77285_c`: `explosionY` -> `y`
* `field_77282_d`: `explosionZ ` -> `z`
* `field_77280_f`: `explosionSize` -> `size`
* `field_77290_i`: `explosionRNG` -> `random`
* `field_77286_a`: `isFlaming` -> `causesFire`
* `field_82755_b`: `isSmoking` -> `damagesTerrain` (updated)

**Comment by williewillus** [comment]
maybe a good time to look at `causesSmoke`
It gates the check to drop destroy and drop blocks, and multiple places in vanilla pass the result of the mobGriefing gamerule in. Seems like the smoke is just a sympton not the actual purpose.

Maybe `griefsTerrain`? `modifiesTerrain`?

**Comment by kashike** [comment]
I'd also like to propose new names for two methods:
- [ ] `func_77278_a`: `doExplosionA` -> `explode`
- [ ] `func_77279_a`: `doExplosionB` -> `finalizeExplosion`

**Comment by bs2609** [comment]
`damagesTerrain`? Agree that smoke isn't the main thing here, will revise suggested name.

`doExplosionA` raytraces the explosion and computes potentially affected block positions. It also damages entities and causes knockback. `doExplosionB` handles the block state changes and the explosion effects.

maybe `simulate()` and `processEffects()`?

**Comment by bs2609** [comment]
There's also a mismatch between `strength` (used by the World method params) and `size` (used by the Explosion class)

The World methods that might need tweaking:
* `World.func_72876_a` (`createExplosion`)
* `World.func_72885_a` (`newExplosion`)
(They should probably share a name too, one just overloads the other)

**Comment by gigaherz** [comment]
`simulate` seems a bad name if it processes entities. I'd go more like `processBlast` and `processErosionAndEffects`.

However, I feel like the two methods are too... vaguely delimited, to have such specific purposes, I feel like `firstPass` and `secondPass` might be closer to the originals.

**Comment by kashike** [comment]
Fields are done.
- [x] `field_77284_b`: `explosionX` -> `x`
- [x] `field_77285_c`: `explosionY` -> `y`
- [x] `field_77282_d`: `explosionZ` -> `z`
- [x] `field_77280_f`: `explosionSize` -> `size`
- [x] `field_77290_i`: `explosionRNG` -> `random`
- [x] `field_77286_a`: `isFlaming` -> `causesFire`
- [x] `field_82755_b`: `isSmoking` -> `damagesTerrain`

**Comment by kashike** [comment]
Method discussion is moving to https://github.com/ModCoderPack/MCPBot-Issues/issues/434.
