### ISSUE TITLE
GameType.func_82752_c: isAdventure -> ???

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#426]
Since spectator mode is a thing, this name could do with an update.

Currently it's most often used in this context:
```java
if (this.currentGameType.isAdventure())
{
	if (this.currentGameType == GameType.SPECTATOR)
	{
		return false;
	}

	if (!this.mc.player.isAllowEdit())
	{
		ItemStack itemstack = this.mc.player.getHeldItemMainhand();

		if (itemstack.isEmpty())
		{
			return false;
		}

		if (!itemstack.canDestroy(this.mc.world.getBlockState(pos).getBlock()))
		{
			return false;
		}
	}
}
```
The immediate check for `SPECTATOR` makes the current name not very fitting.

For replacements:
* `isAdventureOrSpectator()`, which at least is an exact description of the implementation
* Something that's more about its purpose, like `allowsEdits()` or similar

**Comment by gigaherz** [comment]
Feels more like `hasLimitedInteractions` to me...

**Comment by PaleoCrafter** [comment]
Something along the line of `allowsEdits` fits best, in my opinion. `hasLimitedInteractions` doesn't really work here, considering that, right now, it's only used in the context of block breaking, not interaction (i.e. right clicking etc.) in general.
I'd also like to propose at least changing the name of `isSurvivalOrAdventure` (`func_77144_e`) as well. It's only used for determining whether to show the experience bar, so a more descriptive name would be more appropriate. We could either go for a very narrow definition (`seesExperience` or something similar) or we could think about possible further uses (maybe from mods) of the method. One broader category where "is in Survival or Adventure mode" matters might be captured by `requiresResources`.
To complete the set of methods like these in `GameType`, we'd technically have to change `isCreative` (`func_77145_d`) as well, but I think the term "creative" is well established in an MC context and the usages of that method are all over the place, so we can probably stick with it.

**Comment by kashike** [comment]
`allowsEdits` doesn't fit here.

```java
    public boolean isAdventure() {
        return this == ADVENTURE || this == SPECTATOR;
    }
```

**Comment by bs2609** [comment]
I also looked at `isSurvivalOrAdventure`, the problem with that is it's also used by elder guardians to inflict mining fatigue on players (perhaps because of the overlay effect).

**Comment by kashike** [comment]
`isSurvivalOrAdventure` is also used in `net.minecraft.entity.monster.EntityElderGuardian#updateAITasks`.

**Comment by bs2609** [comment]
I got the name backwards for `allowsEdits` really, it's more like `disallowsEdits`.
Regarding the actual method definition (`this == ADVENTURE || this == SPECTATOR`), the alternate name suggestion was based on the usage of that method by `configurePlayerCapabilities()`.

**Comment by PaleoCrafter** [comment]
`forbidsEdits` or another negative version of "allow" is probably the way to go for the method, then. I didn't realise the fact that it wasn't the positive the method is checking for.
As far as `isSurvivalOrAdventure` is concerned: I didn't see its other uses, probably didn't go far enough up through the call chain. `requiresResources` indeed isn't the best term to capture these conditions then, but the method appears to be used to distinguish "normal" from "god mode" game types, where the latter don't require resources or are affected by the environment. I can't come up with a good term to capture this concept, though.

**Comment by kashike** [comment]
`disallowsEdits` and `forbidsEdits` don't really make sense, seeing as they **are** allowed to edit, it's just limited:
`PlayerControllerMP`:
```java
    // SRG: func_180511_b
    public boolean clickBlock(BlockPos loc, EnumFacing face) {
        if (this.currentGameType.isAdventure()) {
            if (this.currentGameType == GameType.SPECTATOR) {
                return false;
            }

            if (!this.mc.player.isAllowEdit()) {
                ItemStack itemstack = this.mc.player.getHeldItemMainhand();

                if (itemstack.isEmpty()) {
                    return false;
                }

                if (!itemstack.canDestroy(this.mc.world.getBlockState(loc).getBlock())) {
                    return false;
                }
            }
        }

    // SRG: func_187103_a
    public boolean onPlayerDestroyBlock(BlockPos pos) {
        if (this.currentGameType.isAdventure()) {
            if (this.currentGameType == GameType.SPECTATOR) {
                return false;
            }

            if (!this.mc.player.isAllowEdit()) {
                ItemStack itemstack = this.mc.player.getHeldItemMainhand();

                if (itemstack.isEmpty()) {
                    return false;
                }

                if (!itemstack.canDestroy(this.mc.world.getBlockState(pos).getBlock())) {
                    return false;
                }
            }
        }
```

`PlayerInteractionManager`:
```java
    // SRG: func_180784_a
    public void onBlockClicked(BlockPos pos, EnumFacing side) {
        if (this.isCreative()) {
            if (!this.world.extinguishFire((EntityPlayer)null, pos, side)) {
                this.tryHarvestBlock(pos);
            }
        } else {
            IBlockState iblockstate = this.world.getBlockState(pos);
            Block block = iblockstate.getBlock();

            if (this.gameType.isAdventure()) {
                if (this.gameType == GameType.SPECTATOR) {
                    return;
                }

                if (!this.player.isAllowEdit()) {
                    ItemStack itemstack = this.player.getHeldItemMainhand();

                    if (itemstack.isEmpty()) {
                        return;
                    }

                    if (!itemstack.canDestroy(block)) {
                        return;
                    }
                }
            }

    // SRG: func_180237_b
    public boolean tryHarvestBlock(BlockPos pos) {
        if (this.gameType.isCreative() && !this.player.getHeldItemMainhand().isEmpty() && this.player.getHeldItemMainhand().getItem() instanceof ItemSword) {
            return false;
        } else {
            IBlockState iblockstate = this.world.getBlockState(pos);
            TileEntity tileentity = this.world.getTileEntity(pos);
            Block block = iblockstate.getBlock();

            if ((block instanceof BlockCommandBlock || block instanceof BlockStructure) && !this.player.canUseCommandBlock()) {
                this.world.notifyBlockUpdate(pos, iblockstate, iblockstate, 3);
                return false;
            } else {
                if (this.gameType.isAdventure()) {
                    if (this.gameType == GameType.SPECTATOR) {
                        return false;
                    }

                    if (!this.player.isAllowEdit()) {
                        ItemStack itemstack = this.player.getHeldItemMainhand();

                        if (itemstack.isEmpty()) {
                            return false;
                        }

                        if (!itemstack.canDestroy(block)) {
                            return false;
                        }
                    }
                }
```

**Comment by PaleoCrafter** [comment]
If we go with @gigaherz' idea, maybe `limitsEdits` would be appropriate?

**Comment by bs2609** [comment]
The game type disallows edits _by default_, in the case of adventure mode, this restriction can be overriden by the players capabilities.

**Comment by kashike** [comment]
`hasLimitedInteractions` or `limitsInteraction` seem reasonable.

**Comment by kashike** [comment]
done.
- [x] `func_82752_c`: `isAdventure` -> `hasLimitedInteractions`
