### ISSUE TITLE
EntityOtherPlayerMP fields

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#427]
The fields in question:

* `field_71185_c` (`otherPlayerMPX`)
* `field_71182_d` (`otherPlayerMPY`)
* `field_71183_e` (`otherPlayerMPZ`)
* `field_71180_f` (`otherPlayerMPYaw`)
* `field_71181_g` (`otherPlayerMPPitch`)
* `field_71184_b` (`otherPlayerMPPosRotationIncrements`) (eww)

Set in `setPositionAndRotationDirect()`, used by `onLivingUpdate()`.

Seems to be just reimplementing a section of code (for interpolating position/rotation changes) from `EntityLivingBase`, but with entirely new fields and a bad inline implementation of `MathHelper.wrapDegrees()`.

`interpTargetX` and similar are the names in the superclass, any not-clashing name suggestions for here?

**Comment by bs2609** [comment]
Related:
`EntityLivingBase.field_70716_bi`: `newPosRotationIncrements` -> `interpTicks`

**Comment by kashike** [comment]
Not sure if there's a clean way to name these...
`remoteInterpTargetX`?
