### ISSUE TITLE
Entity.moveToBlockPosAndAngles -> setLocationAndAngles

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#429]
They're just overloads and should have the same name

**Comment by kashike** [comment]
In the future, please include the SRG name of the method.

I think now would be a good time to look into all these methods and try to find better names:
- [ ] `func_174828_a`: `moveToBlockPosAndAngles`
- [ ] `func_70080_a`: `setPositionAndRotation`
- [ ] `func_70012_b`: `setLocationAndAngles`
- [ ] `func_180426_a`: `setPositionAndRotationDirect`
- [ ] `func_70634_a`: `setPositionAndUpdate`
- [ ] `func_184189_br`: `setPositionNonDirty`
