### ISSUE TITLE
Entity#isDead/setDead

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#430]
This method and field is used to mark an `Entity` as "removed".

- [ ] `func_70106_y`: `setDead` -> `remove`?
- [ ] `field_70128_L`: `isDead` -> `removed`?

**Comment by LordFokas** [comment]
I think it makes sense because it exists outside of living entities, which at least for me caused a certain degree of confusion.

**Comment by PaleoCrafter** [comment]
I'm kind of okay with changing the field name to `removed`, but the method sounds way too 'active' for me. It doesn't actually remove the entity from anything, but marks it for removal later on. I can't really propose a better name, but something that conveys the idea of enqueuing the entity for removal would be good. Could go with something like `markRemoved`, but that doesn't sound quite that good.

**Comment by bs2609** [comment]
What was originally `Chunk.unloaded` caused confusion, I think future tense rather than past tense is more appropriate - it's about what _will_ happen.

**Comment by kashike** [comment]
This was the intention:
```java
    /** When {@code true}, this entity has been marked as removed and will be removed from the world at the next available opportunity. */
    // SRG: field_70128_L
    public boolean removed;

    /** Marks this entity for removal at the next available opportunity. */
    // SRG: func_70106_y
    public void remove()
    {
        this.removed = true;
    }
```

**Comment by PaleoCrafter** [comment]
While the documentation clarifies the purpose of the method, we should still aim for a name that is as descriptive as possible. As I said before, `remove` has the connotation of immediate action, especially because it is used in collections. Like @bs2609 says, we need to clarify that the action *will* happen

**Comment by kashike** [comment]
http://www.verbix.com/webverbix/English/remove.html
http://www.maxgyan.com/english/future-tense-of/remove.html

**Comment by bs2609** [comment]
`pendingRemoval`, `markForRemoval()`?

**Comment by kashike** [comment]
`pendingRemoval` doesn't make sense in this case, because an `Entity` can stick around even after it has been removed (lists, etc), and makes it sound as if that's only used when it's pending removal. As for `remove()`, `markForRemoval` is quite long and the same can be achieved with documentation on the method itself.
`removed`/`remove` seem the best option here, even though it isn't removed from the `World` right away, and as I linked above: future tense: "will remove".

For reference, `remove` is used in these projects:
- https://github.com/Bukkit/Bukkit/blob/master/src/main/java/org/bukkit/entity/Entity.java#L146-L149
- https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/entity/Entity.java#L464-L468

**Comment by bs2609** [comment]
The comment on `isDead` suggests `inactive` so I'll add it to the suggestion pile.
Anyway, `Entity.isEntityAlive()` (func_70089_S) will need updating regardless.

**Comment by kashike** [comment]
`invalid`/`invalidate()`/`isValid`?

**Comment by PaleoCrafter** [comment]
I can get behind the valid/invalid concept, especially since TEs use a similar scheme, iirc.

**Comment by gabizou** [comment]
I feel like I'd have to agree with `pendingRemoval` or `isValid`. `isValid` will make a lot more sense for all entities as it should be considered for removal or "don't bother with this entity as it will be removed at the next chance from the world" and consideration for processing in various aspects.

**Comment by kashike** [comment]
@gabizou `pendingRemoval` was the suggested name for the field.

Suggestions so far:

| field          | set            | 
|----------------|----------------| 
| removed        | remove         | 
| invalid        | invalidate     | 
| pendingRemoval | markForRemoval |

**Comment by gabizou** [comment]
How about 

field | set
----- | -----
isInvalid | invalidate

**Comment by williewillus** [comment]
I vote for invalid and invalidate(). Fields should not have an "is" prefix, only methods should.

**Comment by williewillus** [comment]
Though, i am not sure of the value of this change as a whole since setDead/isDead are mappings many modders encounter often

**Comment by kashike** [comment]
Same reason `worldObj` went to `world`, `MathHelper` methods got overhauled, etc.

It seems `invalid`, `invalidate`, and `isValid` are what make the most sense.

**Comment by gigaherz** [comment]
I'm not a big fan of `invalidate` (I associate it with something that can be re-validated afterward), but I can't think of anything that sounds better so +1 from me too.

**Comment by bs2609** [comment]
It can be revalidated, that's done by setting the field directly however.

**Comment by maxanier** [comment]
If this has to be changed, I would go with `invalid`, `invalidate`, `isValid`.
Even if it is probably never revalidated, it still makes sense to me to `invalidate` it.

**Comment by TechnicianLP** [comment]
scheduleRemoval ?

**Comment by williewillus** [comment]
I'd still rather not change it but if it had to change I would also go with invalid(ate)

**Comment by Glassmaker** [comment]
Is it possible to include this change in 1.13 milestone?
There is a field named `dead` (field_70729_aU) in `EntityLivingBase` which causes uncertainty between the two fields as demonstrated in this [twitter thread](https://twitter.com/AtomicBlom/status/1036947714733293568)

**Comment by kashike** [comment]
After discussing with @pokechu22 and others:
- [x] `field_70128_L`: `isDead` &rarr; `removed` 
- [x] `func_70106_y`: `setDead` &rarr; `remove`
