### ISSUE TITLE
BiomeDecorator#genStandardOres methods need better names

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#431]
These methods could use some new names. Suggestions?
- [ ] `func_76795_a`: `genStandardOre1`
- [ ] `func_76793_b`: `genStandardOre2`

**Comment by Barteks2x** [comment]
The first one creates more or less uniform distribution so I would go for `genOreUniform` (as in uniform distribution), and the other one... well, in my code I needed to replace them. The distribution of the second one is relatively close to gaussian actually, so my version is named `genOreGaussian`, but there may be some existing name for what vanilla does.

**Comment by kashike** [comment]
Those seem like good names. Let's see what others think.

**Comment by gigaherz** [comment]
It's not gaussian. I plotted 1 million samples with spread=15, and I got this (scaled to 80 wide):

```
#### - 4435
####### - 8729
########## - 13098
############## - 17830
################# - 21914
##################### - 26772
######################## - 31027
########################### - 35731
############################### - 40239
################################## - 44682
##################################### - 48647
######################################### - 53545
############################################ - 57672
############################################### - 62139
################################################## - 66366
############################################### - 61968
############################################ - 58137
######################################### - 53281
##################################### - 49008
################################## - 44530
############################### - 39846
########################### - 35604
######################## - 30998
##################### - 26759
################# - 22241
############## - 18049
########## - 13252
####### - 9040
#### - 4461
```

Well, I used C# for the plotting, so I'm assuming java's random generator is also uniform. ;P

**Comment by gigaherz** [comment]
I meant to say, it looks very much like a triangular distribution, so genOreTriangle would be a better choice.

**Comment by Barteks2x** [comment]
It is, I knew what the distribution looks like and I knew it's not the correct name, but it's still close when you plot it. If triangular distribution is the correct name - this would be better method name I think.

I just said what I approximated it with in my code, because I needed something that more nicely extends into infinite depth. And if you add the fact that a single ore vein isn't exactly a point, it will be very close to gaussian.

**Comment by gigaherz** [comment]
Also called "triangle distribution" apparently: http://www.statisticshowto.com/triangular-distribution/

**Comment by kashike** [comment]
This is no longer applicable with 1.13.
