### ISSUE TITLE
func_177500_n: doesWaterVaporize -> isHot

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#432]
Not just used to test if water/ice vaporises.
- [ ] `field_76575_d`: `doesWaterVaporize` -> `hot` (`ultraWarm`)
- [ ] `func_177500_n`: `doesWaterVaporize` -> `isHot` (`isUltraWarm`)

**Comment by diesieben07** [comment]
UltraWarm, the new hot! Get it now while it's still ultra warm!

**Comment by williewillus** [comment]
on that note, what's wrong with "hot"? :P

**Comment by diesieben07** [comment]
That's what I was trying to convey ;)

**Comment by kashike** [comment]
That's no fun! :dancer:

**Comment by bs2609** [comment]
SUPER. HOT.

**Comment by bs2609** [comment]
For an actual suggestion, how about `superheated`?

**Comment by diesieben07** [comment]
"Hot" was an actual suggestion. Both "ultra warm" and "superheated" are made-up synonyms for hot...

**Comment by bs2609** [comment]
"superheated" is an actual term, though this isn't the 'correct' use for it. I feel like 'hot' doesn't quite cut it - deserts are 'hot', but water doesn't immediately vapourise there...

**Comment by PaleoCrafter** [comment]
How 'bout boiling hot?
