### ISSUE TITLE
Explosion method names

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#434]
Moving from https://github.com/ModCoderPack/MCPBot-Issues/issues/424#issuecomment-306778095.

These methods could use more descriptive names.
- [ ] `func_77278_a`: `doExplosionA` 
- [ ] `func_77279_a`: `doExplosionB`

**Comment by gigaherz** [comment]
Repeating (sortof) what I said in the other ticket:

For more descriptive names, I'd probably go with something like `processBlast` and `processErosionAndEffects`. However, I feel like the two methods are too... vaguely delimited, to have such specific names, and maybe `firstPass` and `secondPass` might be more representative.

**Comment by gabizou** [comment]
func_77278_a: doExplosionA : performBlockAndEntityCalculations
func_77279_a: doExplosionB : performBlockTransactionsAndEffects

**Comment by gabizou** [comment]
To kinda revive this:

Noticing also that there's duplicated method names:

- [ ] `func_72885_a` : `newExplosion`
- [ ] `func_72876_a` : `createExplosion`

Both of these do the same thing, except `createExplosion` is a shorthand for `newExplosion`. 

My proposition:
- [ ] `func_77278_a` : `calculateAffectedBlocksAndEntities`
- [ ] `func_77279_a` : `doBlockChangesAndEffects`
- [ ] `func_72885_a` : `createExplosion`
- [ ] `func_72876_a` : `createExplosion`
