### ISSUE TITLE
ExtendedBlockStorage methods

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#435]
Change request for lighting getter/setter method names:

* `func_76670_c`: `getExtSkylightValue` -> `getSkylightAt`
* `func_76657_c`: `setExtSkylightValue` -> `setSkylightAt`
* `func_76674_d`: `getExtBlocklightValue` -> `getBlocklightAt`
* `func_76677_d`: `setExtBlocklightValue` -> `setBlocklightAt`

Possibly better without the `...At` naming, but I wanted to have a clear distinction between these and the `getSkylightArray`-style array getter/setter methods.

Bonus:
* `func_76675_b`: `getNeedsRandomTick` -> `needsRandomTick`

**Comment by kashike** [comment]
This is an internal class, really. We can clarify with javadocs. How is this?
- [ ] `field_76679_g`: `blocklightArray` -> `blockLight`
- [ ] `field_76685_h`: `skylightArray` -> `skyLight`
- [ ] `func_76671_l`: `getSkylightArray` -> `getSkyLight`
- [ ] `func_76666_d`: `setSkylightArray` -> `setSkyLight`
- [ ] `func_76670_c`: `getExtSkylightValue` -> `getSkyLight`
- [ ] `func_76657_c`: `setExtSkylightValue` -> `setSkyLight`
- [ ] `func_76661_k`: `getBlocklightArray` -> `getBlockLight`
- [ ] `func_76659_c`: `setBlocklightArray` -> `setBlockLight`
- [ ] `func_76674_d`: `getExtBlocklightValue` -> `getBlockLight`
- [ ] `func_76677_d`: `setExtBlocklightValue` -> `setBlockLight`
- [ ] `func_76675_b`: `getNeedsRandomTick` -> `needsRandomTick`

**Comment by kashike** [comment]
@bs2609 ^ :cat:

**Comment by bs2609** [comment]
Those names should be ok, I don't think the array/postitional forms are seen together?

**Comment by kashike** [comment]
The array methods are used in `AnvilChunkLoader` and `SPacketChunkData`, as well as `Chunk#read(PacketBuffer, int, boolean)`, while the rest are used in `Chunk`.

**Comment by kashike** [comment]
done.
- [x]`field_76679_g`: `blocklightArray` -> `blockLight`
- [x]`field_76685_h`: `skylightArray` -> `skyLight`
- [x]`func_76671_l`: `getSkylightArray` -> `getSkyLight`
- [x]`func_76666_d`: `setSkylightArray` -> `setSkyLight`
- [x]`func_76670_c`: `getExtSkylightValue` -> `getSkyLightAt`
- [x]`func_76657_c`: `setExtSkylightValue` -> `setSkyLightAt`
- [x]`func_76661_k`: `getBlocklightArray` -> `getBlockLight`
- [x]`func_76659_c`: `setBlocklightArray` -> `setBlockLight`
- [x]`func_76674_d`: `getExtBlocklightValue` -> `getBlockLightAt`
- [x]`func_76677_d`: `setExtBlocklightValue` -> `setBlockLightAt`
- [x]`func_76675_b`: `getNeedsRandomTick` -> `needsRandomTick`
