### ISSUE TITLE
Quick prefix cleanup

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#436]
Just a few that were missed by #397.

* `theEntityCreature`: `EntityAIPanic.field_75267_a`
* `theEnumGameType`: `WorldSummary.field_75791_f`
* `theNetherBridgePieceWeight`: `StructureNetherBridgePieces$Start.field_74970_a`

**Comment by kashike** [comment]
- [x] `field_75267_a`: `theEntityCreature` -> `creature`
- [x] `field_75791_f`: `theEnumGameType` -> `gameType`

Do you have a name for `field_74970_a`?

**Comment by bs2609** [comment]
Based on the code, it looks like it's the details of the previous structure piece placed.
It's not initialised at first and it gets set here:

```java
if (structurenetherbridgepieces$piece != null)
{
	++structurenetherbridgepieces$pieceweight.placeCount;
	p_175871_1_.theNetherBridgePieceWeight = structurenetherbridgepieces$pieceweight;

	if (!structurenetherbridgepieces$pieceweight.isValid())
	{
		p_175871_2_.remove(structurenetherbridgepieces$pieceweight);
	}

	return structurenetherbridgepieces$piece;
}
```

`PieceWeight` isn't very well named, it's also the mutable state of placements. (tracks count of times the piece has been placed in this particular structure)

So:
`StructureNetherBridgePieces$Start.field_74970_a`: `lastPlaced`?

**Comment by bs2609** [comment]
Also:
* `ItemMultiTexture.field_179227_b`: `theBlock` -> `unused`

`block` is already an inherited field from `ItemBlock`, and this field isn't used by vanilla at all.

**Comment by kashike** [comment]
done.
- [x] `field_74970_a`: `theNetherBridgePieceWeight` -> `lastPlaced`
- [x] `field_179227_b`: `theBlock` -> `unused`
