### ISSUE TITLE
NetherBridge -> NetherFortress

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#438]
Classes:
* `MapGenNetherBridge` -> `MapGenNetherFortress`
* `StructureNetherBridgePieces` -> `StructureNetherFortressPieces`

**Comment by Hornwitser** [comment]
If these classes are renamed, The field `genNetherBridge` of `ChunkGeneratorHell` should probably be renamed to `genNetherFortress` as well.

**Comment by kashike** [comment]
- [x] `net/minecraft/world/gen/structure/MapGenNetherBridge` → `net/minecraft/world/gen/feature/FortressStructure`
- [x] `net/minecraft/world/gen/structure/StructureNetherBridgePieces` → ` net/minecraft/world/gen/feature/FortressPieces`
