### ISSUE TITLE
Hell -> Nether

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#439]
Class names:
* `BiomeHell` -> `BiomeNether`
* `BiomeHellDecorator` -> `BiomeNetherDecorator`
* `WorldGenHellLava` -> `WorldGenNetherLava`
* `ChunkGeneratorHell` -> `ChunkGeneratorNether`
* `MapGenCavesHell` -> `MapGenCavesNether`
* `WorldProviderHell` -> `WorldProviderNether`

The End uses `End`, not `Sky`, for its class names. In both cases, the biome instance is the only thing named differently.

**Comment by Meronat** [comment]
I wouldn't mind this change. If world provider changes, these changes should go along with it: https://github.com/ModCoderPack/MCPBot-Issues/issues/90

**Comment by kashike** [comment]
Some of these have been done, some are named as intended.
