### ISSUE TITLE
1.8.8 IBlockState.getPropertyNames -> getProperties

### ISSUE THREAD

**Issue by Zaggy1024** [ModCoderPack/MCPBot-Issues#44]
getPropertyNames returns a collection of properties rather than strings, so this name is incorrect.

**Comment by bspkrs** [comment]
I'll see what I can do, but this will be an annoying change as there is already a getProperties defined for IBlockState.

**Comment by RainWarrior** [comment]
getProperties returns a key-value map, getPropertyNames returns keys of that map. The names is appropriate, though something getPropertyKeys might be better.

**Comment by kashike** [comment]
`func_177227_a`: `getPropertyNames` -> `getPropertyKeys`
