### ISSUE TITLE
Structure piece field names

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#441]
See comments about the nether fortress example in #436.

Strongholds:
* `StructureStrongholdPieces.Stairs2.field_75027_a`: `strongholdPieceWeight` -> `lastPlaced`
(`Stairs2` is also probably the `Start` piece for strongholds)

(see `StructureStrongholdPieces.generatePieceFromSmallDoor()` for usage)

Villages:
* `StructureVillagePieces.Start`:
  *  `field_74926_d`: `structVillagePieceWeight` -> `lastPlaced`
  *  `field_74929_a`: `worldChunkMngr` -> `biomeProvider`
  *  `field_74931_h`: `structureVillageWeightedPieceList` -> `availablePieces`

(see `StructureVillagePieces.generateComponent()` for usage)

**Comment by kashike** [comment]
done.
- [x] `field_75027_a`: `strongholdPieceWeight` -> `lastPlaced`
- [x] `field_74926_d`: `structVillagePieceWeight` -> `lastPlaced`
- [x] `field_74929_a`: `worldChunkMngr` -> `biomeProvider`
- [x] `field_74931_h`: `structureVillageWeightedPieceList` -> `availablePieces`
