### ISSUE TITLE
ComponentScatteredFeaturePieces field names

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#443]
`ComponentScatteredFeaturePieces.Feature`:
* `field_74939_a`: `scatteredFeatureSizeX` -> `width`
* `field_74937_b`: `scatteredFeatureSizeY` -> `height`
* `field_74938_c`: `scatteredFeatureSizeZ` -> `depth`

Names taken from NBT tags.

`ComponentScatteredFeaturePieces.JunglePyramid`:
* `field_74942_n`: `junglePyramidsRandomScatteredStones` -> `cobblestoneSelector`

Produces a random mix of regular/mossy cobblestone to make up the temple.

**Comment by matthewprenger** [comment]
Done:
`field_74939_a`: `scatteredFeatureSizeX` -> `width`
`field_74937_b`: `scatteredFeatureSizeY` -> `height`
`field_74938_c`: `scatteredFeatureSizeZ` -> `depth`
`field_74942_n`: `junglePyramidsRandomScatteredStones` -> `cobblestoneSelector`
