### ISSUE TITLE
creativetab.CreativeTabs -> item.ItemGroup

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#444]
`net/minecraft/creativetab/CreativeTabs net/minecraft/item/ItemGroup`

**Comment by Meronat** [comment]
Yes please.

**Comment by bs2609** [comment]
Re: Lex's comment about this on #514, vanilla does also use this for the recipe book now, so the "creative" part of the name is less appropriate.

**Comment by kashike** [comment]
- [x] `net/minecraft/creativetab/CreativeTabs` → `net/minecraft/item/ItemGroup`
