### ISSUE TITLE
1.12 Timer rewrite

### ISSUE THREAD

**Issue by LeafHacker** [ModCoderPack/MCPBot-Issues#445]
In 1.12, `net.minecraft.util.Timer` has been rewritten, changing a few of the field mappings for the class.

The following is based on a quick read through of the new code.

- `field_194147_b` is the new name for `field_74281_c` (`renderPartialTicks`).

- `field_194148_c`  is the new name for `field_74279_e` (`elapsedPartialTicks`).

- `field_194149_e` is a new field, the tick-length in milliseconds.
  - It perhaps should be named `tickLength` with a comment along the lines of `"The length of a tick in milliseconds"`.
  - Now used instead of the old `field_74282_a` (`ticksPerSecond`).
  - Calculated based on the TPS passed into the constructor.

Many other fields are removed due to the simplified rewrite.

-----------------

There is also a local variable `long i = Minecraft.getSystemTime()` within `func_74275_a` (`updateTimer`) which could be renamed to something like `systemTime`, or `sysClock` to be consistent with `field_74277_g` (`lastSyncSysClock`).

**Comment by kashike** [comment]
These fields are unnamed. Simply wait for MCPBot to be updated to 1.12, and then you can name them.

**Comment by LeafHacker** [comment]
@kashike is that just a case of adding the 1.12 artefacts to MCPBot? As per [1.11](https://bitbucket.org/ProfMobius/mcpbot/commits/15be6316a6ea2142886e42d309f1927aacd5f3bb)?

**Comment by kashike** [comment]
Yes. @bspkrs will get to it when he has time.

**Comment by Pokechu22** [comment]
To be more precise: it's not _just_ adding 1.12 artefacts to MCPBot; there's also some manual database updating that needs to be done (which bspkrs handles) - adding the artefacts is one step, but not the only one.

**Comment by kashike** [comment]
I missed the word "just" there, oops.
