### ISSUE TITLE
Package net.minecraft.advancement.critereon -> criterion

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#446]
title

**Comment by kashike** [comment]
- [x] `net/minecraft/advancements/critereon/AbstractCriterionInstance` → `net/minecraft/advancements/criterion/AbstractCriterionInstance`
- [x] `net/minecraft/advancements/critereon/BredAnimalsTrigger` → `net/minecraft/advancements/criterion/BredAnimalsTrigger`
- [x] `net/minecraft/advancements/critereon/BrewedPotionTrigger` → `net/minecraft/advancements/criterion/BrewedPotionTrigger`
- [x] `net/minecraft/advancements/critereon/ChangeDimensionTrigger` → `net/minecraft/advancements/criterion/ChangeDimensionTrigger`
- [x] `net/minecraft/advancements/critereon/ConstructBeaconTrigger` → `net/minecraft/advancements/criterion/ConstructBeaconTrigger`
- [x] `net/minecraft/advancements/critereon/ConsumeItemTrigger` → `net/minecraft/advancements/criterion/ConsumeItemTrigger`
- [x] `net/minecraft/advancements/critereon/CuredZombieVillagerTrigger` → `net/minecraft/advancements/criterion/CuredZombieVillagerTrigger`
- [x] `net/minecraft/advancements/critereon/DamagePredicate` → `net/minecraft/advancements/criterion/DamagePredicate`
- [x] `net/minecraft/advancements/critereon/DamageSourcePredicate` → `net/minecraft/advancements/criterion/DamageSourcePredicate`
- [x] `net/minecraft/advancements/critereon/DistancePredicate` → `net/minecraft/advancements/criterion/DistancePredicate`
- [x] `net/minecraft/advancements/critereon/EffectsChangedTrigger` → `net/minecraft/advancements/criterion/EffectsChangedTrigger`
- [x] `net/minecraft/advancements/critereon/EnchantedItemTrigger` → `net/minecraft/advancements/criterion/EnchantedItemTrigger`
- [x] `net/minecraft/advancements/critereon/EnchantmentPredicate` → `net/minecraft/advancements/criterion/EnchantmentPredicate`
- [x] `net/minecraft/advancements/critereon/EnterBlockTrigger` → `net/minecraft/advancements/criterion/EnterBlockTrigger`
- [x] `net/minecraft/advancements/critereon/EntityHurtPlayerTrigger` → `net/minecraft/advancements/criterion/EntityHurtPlayerTrigger`
- [x] `net/minecraft/advancements/critereon/EntityPredicate` → `net/minecraft/advancements/criterion/EntityPredicate`
- [x] `net/minecraft/advancements/critereon/ImpossibleTrigger` → `net/minecraft/advancements/criterion/ImpossibleTrigger`
- [x] `net/minecraft/advancements/critereon/InventoryChangeTrigger` → `net/minecraft/advancements/criterion/InventoryChangeTrigger`
- [x] `net/minecraft/advancements/critereon/ItemDurabilityTrigger` → `net/minecraft/advancements/criterion/ItemDurabilityTrigger`
- [x] `net/minecraft/advancements/critereon/ItemPredicate` → `net/minecraft/advancements/criterion/ItemPredicate`
- [x] `net/minecraft/advancements/critereon/KilledTrigger` → `net/minecraft/advancements/criterion/KilledTrigger`
- [x] `net/minecraft/advancements/critereon/LevitationTrigger` → `net/minecraft/advancements/criterion/LevitationTrigger`
- [x] `net/minecraft/advancements/critereon/LocationPredicate` → `net/minecraft/advancements/criterion/LocationPredicate`
- [x] `net/minecraft/advancements/critereon/MinMaxBounds` → `net/minecraft/advancements/criterion/MinMaxBounds`
- [x] `net/minecraft/advancements/critereon/MobEffectsPredicate` → `net/minecraft/advancements/criterion/MobEffectsPredicate`
- [x] `net/minecraft/advancements/critereon/NBTPredicate` → `net/minecraft/advancements/criterion/NBTPredicate`
- [x] `net/minecraft/advancements/critereon/NetherTravelTrigger` → `net/minecraft/advancements/criterion/NetherTravelTrigger`
- [x] `net/minecraft/advancements/critereon/PlacedBlockTrigger` → `net/minecraft/advancements/criterion/PlacedBlockTrigger`
- [x] `net/minecraft/advancements/critereon/PlayerHurtEntityTrigger` → `net/minecraft/advancements/criterion/PlayerHurtEntityTrigger`
- [x] `net/minecraft/advancements/critereon/PositionTrigger` → `net/minecraft/advancements/criterion/PositionTrigger`
- [x] `net/minecraft/advancements/critereon/RecipeUnlockedTrigger` → `net/minecraft/advancements/criterion/RecipeUnlockedTrigger`
- [x] `net/minecraft/advancements/critereon/SummonedEntityTrigger` → `net/minecraft/advancements/criterion/SummonedEntityTrigger`
- [x] `net/minecraft/advancements/critereon/TameAnimalTrigger` → `net/minecraft/advancements/criterion/TameAnimalTrigger`
- [x] `net/minecraft/advancements/critereon/TickTrigger` → `net/minecraft/advancements/criterion/TickTrigger`
- [x] `net/minecraft/advancements/critereon/UsedEnderEyeTrigger` → `net/minecraft/advancements/criterion/UsedEnderEyeTrigger`
- [x] `net/minecraft/advancements/critereon/UsedTotemTrigger` → `net/minecraft/advancements/criterion/UsedTotemTrigger`
- [x] `net/minecraft/advancements/critereon/VillagerTradeTrigger` → `net/minecraft/advancements/criterion/VillagerTradeTrigger`
