### ISSUE TITLE
Advancement.Builder -> Advancement.TaskAdvancement

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#447]
Advancement.Builder -> Advancement.TaskAdvancement
* this one's a no brainer from the toString method

~~Advancement -> AdvancementTab (?)~~
* ~~This object represents one tab in the advancements gui, deserialized from the `root.json` of the current folder in the advancements directory.~~
* ~~Some people may get this confused with Achievements, but this is more analagous to a grouping of achievements like the old AchievementPage~~
* ~~what's the vanilla terminology for the tab vs the task?~~

**Comment by williewillus** [comment]
from the vanilla wiki, seems like people are considering advancements <=> achievements, so I think the Advancement -> AdvancementTab rename makes more sense 

or maybe AdvancementGroup

**Comment by kashike** [comment]
In what way is it a tab or group?

**Comment by kashike** [comment]
It really isn't as far as I can see.

**Comment by williewillus** [comment]
`GuiScreenAdvancements` uses it as map values...

but hmm on further look, seems like they use an advancement itself for the tab/grouping as well as for the actual tasks? maybe no rename then

**Comment by kashike** [comment]
![x](https://i.imgur.com/Hp7JyaN.png)
The orange-brown buttons are the "tabs".

**Comment by kashike** [comment]
Oh, I see what you're trying to say - the map (`field_191810_m`) is used to map from the *root* advancements (`root.json`) to a tab.

**Comment by kashike** [comment]
Invalid. This is a builder.
