### ISSUE TITLE
MapGenX -> StructureX

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#448]
The following are all subclasses of `MapGenStructure`. This brings the naming more in line with ocean monuments and woodland mansions.

* `EndCity`
* `Mineshaft`
* `NetherBridge` (see also #438)
* `ScatteredFeature` (could be improved too?)
* `Stronghold`
* `Village`

`ComponentScatteredFeaturePieces` could also do with a better name.

There is a mismatch between the terms 'piece' used by the various `StructureNamePieces` classes, and 'component', used by `MapGenStructureIO`, and the abstract superclasses `StructureComponent` and `StructureComponentTemplate`. It would be nice to have some consistency here too.

**Comment by Hornwitser** [comment]
I'm not sure I like this name change that much.  `MapGenStructure` is a subclass of `MapGenBase`, and the other subclasses of that base class are `MapGenCaves`, `MapGenCavesHell`, and `MapGenRavine`.  In the `ChunkGeneratorOverworld` class they are all used by calling `generate` on instances of them.  They primarily serve to generate and query structures in the world, the actual structures are stored in a list of structure components/pieces in a StructureStart subclass.

**Comment by kashike** [comment]
- [x] `MapGen*` -> `*Structure`
