### ISSUE TITLE
Biome.func_180626_a: getFloatTemperature -> ???

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#449]
`Biome.func_185353_n` (`getTemperature`) also returns a float, so the current name isn't a useful description.

The difference is that this method returns a different value based on the position given, so a name like `getLocalTemperature` or `getTemperatureAtPos` would be more suitable.

**Comment by Barteks2x** [comment]
Maybe just `getTemperatureAt` so it would be used like `getTemperatureAt(blockPos)`?

**Comment by PaleoCrafter** [comment]
I personally prefer `getLocalTemperature`. In other renames, we moved away from the `getXAt` style as well, so it makes sense to do so here as well.

**Comment by Barteks2x** [comment]
I didn't know that, then `getLocalTemperature` probably makes more sense.

**Comment by bs2609** [comment]
In that case, it's also worth renaming the following:

Biome:
* `func_180627_b` (`getGrassColorAtPos`)
* `func_180625_c` (`getFoliageColorAtPos`)

BiomeColorHelper:
* `func_180285_a` (`getColorAtPos`)
* `func_180286_a` (`getGrassColorAtPos`)
* `func_180287_b` (`getFoliageColorAtPos`)
* `func_180288_c` (`getWaterColorAtPos`)

BiomeColorHelper$ColorResolver:
* `func_180283_a` (`getColorAtPos`)

**Comment by kashike** [comment]
Thoughts?
- [ ] `func_180626_a`: `getFloatTemperature` -> `getTemperature`
- [ ] `func_185353_n`: `getTemperature` -> `getDefaultTemperature`

**Comment by Pokechu22** [comment]
Support.  I've added the following comments:

* `getTemperature`: "Gets the current temperature at the given location, based off of the default for this biome, the elevation of the position, and {@linkplain #TEMPERATURE_NOISE} some random perlin noise."
* ` getDefaultTemperature`: "Gets the constant default temperature for this biome"

**Comment by kashike** [comment]
done.
- [x] `func_180626_a`: `getFloatTemperature` -> `getTemperature`
- [x] `func_185353_n`: `getTemperature` -> `getDefaultTemperature`
