### ISSUE TITLE
GeneratorBushFeature -> WorldGenBush

### ISSUE THREAD

**Issue by Deamon5550** [ModCoderPack/MCPBot-Issues#45]
GeneratorBushFeature is the only `WorldGenerator` not in the gen.feature package and not following the WorldGen* naming convention. Changing `net.minecraft.world.gen.GeneratorBushFeature` to `net.minecraft.world.gen.feature.WorldGenBush` would fix this inconsistency.

Possible names:
- WorldGenBush
- WorldGenSmallMushroom (it takes a BlockBush but is only used for mushrooms)

**Comment by LexManos** [comment]
1.9: 
net/minecraft/world/gen/GeneratorBushFeature -> net/minecraft/world/gen/feature/WorldGenBush
Not a personal fan of smurf naming but it brings it in line with the rest of the features.
