### ISSUE TITLE
TileEntitySpecialRenderer -> TileEntityRenderer

### ISSUE THREAD

**Issue by darkevilmac** [ModCoderPack/MCPBot-Issues#450]
The 'Special' wording doesn't serve much of a purpose besides making the name longer. It would be nice to have a simpler name that's more direct to the point.

**Comment by diesieben07** [comment]
Although "TESR" has been established as a shorthand, I still think this is a good idea.

**Comment by PaleoCrafter** [comment]
I've also mapped what used to be `renderTileEntityAt` to `render` in 1.12, so this would go along nicely with that.

**Comment by PaleoCrafter** [comment]
Looks like *somebody* changed `render` back to `renderTileEntityAt`, probably due to the slight brokeness of the mappings in between, should I create a separate issue for it?

**Comment by kashike** [comment]
- [x] `net/minecraft/client/renderer/tileentity/TileEntitySpecialRenderer` → `net/minecraft/client/renderer/tileentity/TileEntityRenderer`
