### ISSUE TITLE
[1.12] Some missing mappings.

### ISSUE THREAD

**Issue by mrAppleXZ** [ModCoderPack/MCPBot-Issues#451]
Version: snapshot_20170613
Enchantment.func_190936_d() => Enchantment.isCurse()
NonNullList.func_191196_a() => NonNullList.create()
The names was correct in snapshot_20170610.

**Comment by gigaherz** [comment]
The mappings database was somewhat "corrupted" during the 1.12 switch, and is being repaired. Things will be fixed. ;P

**Comment by mrAppleXZ** [comment]
OK, thank you for the very fast reply :).
