### ISSUE TITLE
DataSerializers.OPTIONAL_ITEM_STACK should be renamed

### ISSUE THREAD

**Issue by dshadowwolf** [ModCoderPack/MCPBot-Issues#452]
After having it pointed out to me by a member of the Forge team, I've brought this here.

net.minecraft.network.datasync.DataSerializers.OPTIONAL_ITEM_STACK was, in the past, Optional<> as ItemStacks were Nullable.

While the rest of the items in that package that start as "OPTIONAL" are still Optional<> - OPTIONAL_ITEM_STACK is no longer Nullable or Optional<> - the name should change to reflect this and match the other non-Optional's, which would change it to be just "ITEM_STACK"

**Comment by matthewprenger** [comment]
Done:
`field_187196_f`: `OPTIONAL_ITEM_STACK` -> `ITEM_STACK`
