### ISSUE TITLE
EntityLivingBase.func_191987_a: setPartying -> ???

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#453]
Used for parrot parties, but it's not a parrot-specific method. It's more like a 'react to sound' method.

Called from `RenderGlobal.func_193054_a` which is called by `RenderGlobal.playRecord`. That method loops over all living entities within 3 blocks of the given sound position and calls this method on each of them.

For reference:
```java
private void func_193054_a(World p_193054_1_, BlockPos p_193054_2_, boolean p_193054_3_)
{
	for (EntityLivingBase entitylivingbase : p_193054_1_.getEntitiesWithinAABB(EntityLivingBase.class, (new AxisAlignedBB(p_193054_2_)).grow(3.0D)))
	{
		entitylivingbase.yourNameHere(p_193054_2_, p_193054_3_);
	}
}
```

**Comment by kashike** [comment]
@williewillus thoughts on `setReactToSound` as mentioned above?

**Comment by williewillus** [comment]
"setReact" sounds weird. It should only have one verb, either something like "setNearbySound" or "reactToNearbySound"

**Comment by kashike** [comment]
`reactToNearbySound` gets my vote.

**Comment by tterrag1098** [comment]
A more standard name might be `onNearbySound` ?

**Comment by bs2609** [comment]
Also `func_193054_a` has now also been named `setPartying`, so also I'll put that up for a rename too.

**Comment by Pokechu22** [comment]
This is specifically used for records; I'd say `onNearbySound` isn't ideal (especially since it doesn't pass the sound event) and instead it should specify records.  How about `onNearbyRecordSound`?

**Comment by Pokechu22** [comment]
Just added javadocs, and now I've thought of a better name maybe: `onRecordPlaybackChange`.  Also, the parameter names probably should be changed, so my current idea is:

- [ ] `func_193054_a`: setPartying &rarr; `onRecordPlaybackChange`
- [ ] `p_193054_3_`: `isPartying` &rarr; `started` ("True if the record started; false if it stopped.")
- [ ] `func_191987_a`: setPartying &rarr; `onRecordPlaybackChange`
- [ ] `p_191987_2_`: `isPartying` &rarr; `started`
