### ISSUE TITLE
IRecipe.isHidden() needs a different name

### ISSUE THREAD

**Issue by TechnicianLP** [ModCoderPack/MCPBot-Issues#454]
is suggest isSpecial() as it is specialcased pretty much everywhere ...
Any other ideas?

**Comment by williewillus** [comment]
I don't understand what's wrong with the current name. If it returns true, the recipe book doesn't show it, otherwise it does. What special case are you mentioning?

**Comment by TechnicianLP** [comment]
It is not just not shown in the RecipeBook ...
Let me cite kashike: "<kashike> hides from recipe book, excluded from /recipe command, special behaviour in Container & SlotCrafting & RecipeBookServer"

**Comment by kashike** [comment]
```java
                        if (irecipe.isHidden()) {
                            throw new CommandException("commands.recipe.unsupported", new Object[] {args[2]});
                        }
```


```java
            if (irecipe != null && (irecipe.isHidden() || !p_192389_1_.getGameRules().getBoolean("doLimitedCrafting") || entityplayermp.getRecipeBook().containsRecipe(irecipe))) {
                p_192389_4_.func_193056_a(irecipe);
                itemstack = irecipe.getCraftingResult(p_192389_3_);
            }
```

```java
        if (irecipe != null && !irecipe.isHidden()) {
            this.player.unlockRecipes(Lists.newArrayList(irecipe));
            inventorycraftresult.func_193056_a((IRecipe)null);
        }
```

```java
    // SRG: func_194073_a
    public void setRecipes(IRecipe recipe) {
        if (!recipe.isHidden()) {
            this.recipes.set(getRecipeId(recipe));
        }
    }
```

```java
    // SRG: func_193835_a
    public void add(List<IRecipe> p_193835_1_, EntityPlayerMP player) {
        List<IRecipe> list = Lists.<IRecipe>newArrayList();

        for (IRecipe irecipe : p_193835_1_) {
            if (!this.recipes.get(getRecipeId(irecipe)) && !irecipe.isHidden()) {
                this.setRecipes(irecipe);
                this.addDisplayedRecipe(irecipe);
                list.add(irecipe);
                CriteriaTriggers.RECIPE_UNLOCKED.trigger(player, irecipe);
            }
        }

        this.sendPacket(SPacketRecipeBook.State.ADD, player, list);
    }
```

**Comment by PaleoCrafter** [comment]
We discussed this on IRC when it was first named. `ìsSpecial` is too generic to really state its purpose. Something like `skipsUnlocks` or `isAlwaysUnlocked` would be more appropriate, imo, since that is what it essentially means (in addition to being hidden from the book).

**Comment by kashike** [comment]
`skipsUnlocks`/`isAlwaysUnlocked` doesn't make sense for hiding it from the recipe book, however.

**Comment by PaleoCrafter** [comment]
I totally agree there, but it's definitely better than `isSpecial` 😝

**Comment by TechnicianLP** [comment]
isUnpredictable() would also makes sense as the outputs of those recipes are based on the inputs ...

**Comment by williewillus** [comment]
isDynamicRecipe? If I'm reading this properly it's like the vanilla recipes that need NBT/other dynamic work and can't be statically represented or visualized, and make no sense to be gated.

**Comment by williewillus** [comment]
Throw in a good comment as well and it should be alright

**Comment by PaleoCrafter** [comment]
`isDynamic` sounds fine to me, just keep that "Recipe" suffix out of there, that can be gathered from context.

**Comment by kashike** [comment]
done.
- [x] `func_192399_d`: `isHidden` -> `isDynamic`
