### ISSUE TITLE
KeyBinding.field_193627_d: CATEGORY_RANKINGS -> CATEGORY_WEIGHTS

### ISSUE THREAD

**Issue by PaleoCrafter** [ModCoderPack/MCPBot-Issues#455]
I thought I had actually mapped that field already, must have forgotten it, though. "Weights" is a much more common and well-defined term, while "rankings" sounds a lot like the categories are in some sort of competition xD

**Comment by tterrag1098** [comment]
Changed to CATEGORY_ORDER as per discussion.

**Comment by PaleoCrafter** [comment]
Welp.
