### ISSUE TITLE
[1.12] EntityLivingBase moveForward is mapped to the incorrect field.

### ISSUE THREAD

**Issue by darkevilmac** [ModCoderPack/MCPBot-Issues#457]
moveForward in EntityLivingBase is currently mapped to the srg field field_70701_bs, this is incorrect and should be mapped to field_191988_bg instead. I'm not entirely sure what the other field is for but it's evidently been mixed up with another.

**Comment by ThisTestUser** [comment]
The other field determines a player's movement vertically, and also as of now I think this error has been resolved.

**Comment by matthewprenger** [comment]
I fixed this yesterday.
