### ISSUE TITLE
RecipeBook methods and fields

### ISSUE THREAD

**Issue by PaleoCrafter** [ModCoderPack/MCPBot-Issues#458]
`RecipeBook` was already completely mapped, but I think we should use the opportunity to use the best names possible and I find the current version unsatisfactory.

I propose the following changes:

- `field_194078_b`: `unseenRecipes` -> `newRecipes` - This is largely subjective, but despite the recipes in this set being "unseen" by the player in the book, they might have seen them, namely before unlocking them through crafting.
- `func_193824_a`: `apply` -> `copyFrom` - The using method also is named `copyFrom`.
- `func_194073_a`: `setRecipes` -> `unlock` - It doesn't "set recipes" in any regard, it allows a player to actually craft and see a recipe.
- `func_193830_f`: `containsRecipe` -> `isUnlocked` - Keep it consistent.
- `func_193831_b`: `removeRecipe` -> `lock` - Again, consistency. While the recipe *is* removed from the book, it's also "unknown" from the player from this point forward, so this rename would make the implications clearer.
- `func_194076_e`: `isRecipeUnseen` -> `isNew` - Consistency with the field name and we're in the context of a *recipe* book, it should be clear what the method is referring to.
- `func_194074_f`: `setRecipeSeen` -> `markSeen` - Opposite of the one below.
- `func_193825_e`: `addDisplayedRecipe` -> `markNew` - Every recipe in the book is *displayed*, this method specifically marks them as new and (as the comment on the field correctly states) makes the recipes animate.

**Comment by williewillus** [comment]
I'm still very meh about unseen -> new, but the others are fine

**Comment by kashike** [comment]
Two options:

1:
- [ ] `field_194078_b`: `unseenRecipes` -> `newRecipes`
- [ ] `func_193824_a`: `apply` -> `copyFrom`
- [ ] `func_194073_a`: `setRecipes` -> `unlock`
- [ ] `func_193830_f`: `containsRecipe` -> `isUnlocked`
- [ ] `func_193831_b`: `removeRecipe` -> `lock`
- [ ] `func_194076_e`: `isRecipeUnseen` -> `isNew`
- [ ] `func_194074_f`: `setRecipeSeen` -> `markSeen`
- [ ] `func_193825_e`: `addDisplayedRecipe` -> `markNew`

2:
- [ ] `func_193824_a`: `apply` -> `copyFrom`
- [ ] `func_194073_a`: `setRecipes` -> `unlock`
- [ ] `func_193830_f`: `containsRecipe` -> `isUnlocked`
- [ ] `func_193831_b`: `removeRecipe` -> `lock`
- [ ] `func_194076_e`: `isRecipeUnseen` -> `isUnseen`
- [ ] `func_194074_f`: `setRecipeSeen` -> `markSeen`
- [ ] `func_193825_e`: `addDisplayedRecipe` -> `markUnseen`

**Comment by PaleoCrafter** [comment]
Any decision on this? :D

**Comment by kashike** [comment]
done.
- [x] `field_194078_b`: `unseenRecipes` -> `newRecipes`
- [x] `func_193824_a`: `apply` -> `copyFrom`
- [x] `func_194073_a`: `setRecipes` -> `unlock`
- [x] `func_193830_f`: `containsRecipe` -> `isUnlocked`
- [x] `func_193831_b`: `removeRecipe` -> `lock`
- [x] `func_194076_e`: `isRecipeUnseen` -> `isNew`
- [x] `func_194074_f`: `setRecipeSeen` -> `markSeen`
- [x] `func_193825_e`: `addDisplayedRecipe` -> `markNew`
