### ISSUE TITLE
RenderGlobal.field_72773_u (cloudTickCounter) and related fields/methods

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#459]
This isn't just used for clouds, and the 'cloud' names make no sense in the context of classes such as `DestroyBlockProgress`.

Likewise `RenderGlobal.func_72734_e` (`updateClouds`) has nothing to do with updating clouds, it's just the function that gets called each client tick.

With that in mind, the following could do with better, more generic names:

* `RenderGlobal`
  *  `field_72773_u` (`cloudTickCounter`)
  *  `func_72734_e` (`updateClouds`)

* `DestroyBlockProgress`
  *  `field_82745_f` (`createdAtCloudUpdateTick`)
  *  `func_82744_b` (`setCloudUpdateTick`)
  *  `func_82743_f` (`getCreationCloudUpdateTick`)

Any suggestions?

**Comment by kashike** [comment]
- [x] `field_72773_u`: `cloudTickCounter` -> `ticks`
- [x] `func_72734_e`: `updateClouds` -> `tick`
