### ISSUE TITLE
ServersideAttributeMap -> AttributeMap and BaseAttributeMap -> AbstractAttributeMap

### ISSUE THREAD

**Issue by Aaron1011** [ModCoderPack/MCPBot-Issues#46]
`ServersideAttributeMap` is used on both the client and server. Additionally, it's the only subclass of the abstract class `BaseAttributeMap`, so it makes more sense to simply call it `AttributeMap`.

 Since `BaseAttributeMap` is only extended by one class, it makes more sense to call it `AbstractAttributeMap` - it doesn't really serve as a base class.

**Comment by LexManos** [comment]
1.9:
net/minecraft/entity/ai/attributes/BaseAttributeMap -> AbstractAttributeMap
net/minecraft/entity/ai/attributes/ServersideAttributeMap -> AttributeMap
