### ISSUE TITLE
EntityWitch: Potion drinking logic

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#460]
The logic for which item usage is named as if it were attacking, but it is instead for drinking a potion (eg, to heal):

- [ ] <ruby><rb>IS_AGGRESSIVE</rb><rp> (</rp><rt>field_184731_c</rt><rp>)</rp></ruby> &rarr; IS_DRINKING
- [ ] <ruby><rb>witchAttackTimer</rb><rp> (</rp><rt>field_82200_e</rt><rp>)</rp></ruby> &rarr; potionUseTimer (or itemUseTimer)
- [ ] <ruby><rb>setAggressive</rb><rp> (</rp><rt>func_82197_f</rt><rp>)</rp></ruby> &rarr; setDrinkingPotion (or setUsingItem)
- [ ] <ruby><rb>aggressive</rb><rp> (</rp><rt>p_82197_1_</rt><rp>)</rp></ruby> &rarr; drinkingPotion (or usingItem)
- [x] <ruby><rb>isDrinkingPotion</rb><rp> (</rp><rt>func_184730_o</rt><rp>)</rp></ruby>: already good as is (or change to isUsingItem)

```
fsf field_184731_c IS_DRINKING
fsf field_82200_e potionUseTimer
fsm func_82197_f setDrinkingPotion
fsp p_82197_1_ drinkingPotion
```

**Comment by kashike** [comment]
done.
- [x] `field_184731_c`: `IS_AGGRESSIVE` -> `IS_DRINKING`
- [x] `field_82200_e`: `witchAttackTimer` -> `potionUseTimer`
- [x] `func_82197_f`: `setAggressive` -> `setDrinkingPotion`
- [x] `p_82197_1_`: `aggressive` -> `drinkingPotion`
