### ISSUE TITLE
AABB Comments

### ISSUE THREAD

**Issue by ThisTestUser** [ModCoderPack/MCPBot-Issues#461]
This is just about the comments on the functions after the refactoring, since comments weren't changed after the AABB names was changed.

Functions that have broken links:
- func_72314_b (grow)
- func_186662_g (grow) 
- func_72321_a (expand)
- func_191195_a (contract)

**Comment by PaleoCrafter** [comment]
You can change these comments yourself with the bot, just use the existing name in the bot command.
