### ISSUE TITLE
Loggers not named LOGGER

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#462]
The following loggers are not named `LOGGER`:

- [x] <ruby><rb>LayeredColorMaskTexture.LOG</rb><rp> (</rp><rt>field_174947_f</rt><rp>)</rp></ruby> (note: has a comment, which maybe is superfluous)
- [ ] <ruby><rb>SimpleTexture.LOG</rb><rp> (</rp><rt>field_147639_c</rt><rp>)</rp></ruby>
- [ ] <ruby><rb>EntityLivingBase.LOG</rb><rp> (</rp><rt>field_190632_a</rt><rp>)</rp></ruby>
- [ ] <ruby><rb>MinecraftServer.LOG</rb><rp> (</rp><rt>field_147145_h</rt><rp>)</rp></ruby>
- [ ] <ruby><rb>PlayerList.LOG</rb><rp> (</rp><rt>field_148546_d</rt><rp>)</rp></ruby>
- [x] <ruby><rb>TileEntityEndGateway.LOG</rp><rp> (</rp><rt>field_184314_a</rt><rp>)</rp></ruby>

```
fsf field_174947_f LOGGER
fsf field_147639_c LOGGER
fsf field_190632_a LOGGER
fsf field_147145_h LOGGER
fsf field_148546_d LOGGER
fsf field_184314_a LOGGER
```

**Comment by kashike** [comment]
`field_147639_c`, `field_190632_a`, `field_147145_h`, and `field_148546_d` cannot be named `LOGGER` because there's a field with the name `LOGGER` within the scope.

**Comment by kashike** [comment]
- [x] `field_174947_f`: `LOG` -> `LOGGER`
- [x] `field_184314_a`: `LOG` -> `LOGGER`

**Comment by Pokechu22** [comment]
I don't see any in the scope for those: field_147145_h (`MinecraftServer`) and field_148546_d (`PlayerList`) are both abstract classes, with no parents; while field_147639_c (`SimpleTexture`) has a parent class, it has no logger.

For field_190632_a (`EntityLivingBase`), there is a field named `LOGGER` in the superclass (field_184243_a of `Entity`), but that's private, so it shouldn't make any difference (unless there's a technical reason why that wouldn't work for remapping)

**Comment by matthewprenger** [comment]
Yeah IMO there is a problem with the scope check. Everything should be able to be named LOGGER.

@bspkrs Your thoughts?

**Comment by bspkrs** [comment]
I'll have yet another look at that SQL... >.<

**Comment by bspkrs** [comment]
This is why I've been putting this off: https://pastebin.com/XSknkZxc

**Comment by bspkrs** [comment]
Done.
