### ISSUE TITLE
Agression entity metadata

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#465]
I've done some more research, and there are some pieces of metadata which seem to be incorrect (both in MCP and on wiki.vg).  Some of these I can change myself, but I think some feedback and a second look at these would be nice.  This includes my comments.

## EntityBlaze

 - [ ] <ruby><rb>ON_FIRE</rb><rp> (</rp><rt>field_184712_c</rt><rp>)</rp></ruby> &rarr; BLAZE_FLAGS `A flag field that stores the blaze's charging state in its lowest bit.`
 - [ ] <ruby><rb>isCharged</rb><rp> (</rp><rt>func_70845_n</rt><rp>)</rp></ruby> &rarr; isCharging `Whether this blaze is preparing an attack.\n \nNote that this is identical to whether the blaze is visually on fire.`
 - [ ] <ruby><rb>setOnFire</rb><rp> (</rp><rt>func_70844_e</rt><rp>)</rp></ruby> &rarr; setCharging `Marks whether this blaze is preparing an attack.`
 - [ ] <ruby><rb>onFire</rb><rp> (</rp><rt>p_70844_1_</rt><rp>)</rp></ruby> &rarr; isCharging `The new value`

## EntityVex

 * <ruby><rb>VEX_FLAGS</rb><rp> (</rp><rt>field_190664_a</rt><rp>)</rp></ruby>: keep, comment `A flag field that stores the vex's charging state in its lowest bit.`
 * <ruby><rb>isCharging</rb><rp> (</rp><rt>func_190647_dj</rt><rp>)</rp></ruby>: keep, comment `Whether this vex is charging an attack.  This affects the texture used.`
 - [ ] <ruby><rb>setIsCharging</rb><rp> (</rp><rt>func_190648_a</rt><rp>)</rp></ruby> &rarr; setCharging `Marks whether this vex is preparing an attack.`
 * p_190648_1_ &rarr; isCharging `The new value`

## AbstractIllager

 - [ ] <ruby><rb>AGGRESSIVE</rb><rp> (</rp><rt>field_193080_a</rt><rp>)</rp></ruby> &rarr; ILLAGER_FLAGS `A flag field that has various uses between different illagers, but mainly stores the illager's attacking state in its lowest bit.`
 - [ ] <ruby><rb>isAggressive(int)</rb><rp> (</rp><rt>func_193078_a</rt><rp>)</rp></ruby> &rarr; getIllagerFlag
 - [ ] <ruby><rb>setAggressive(int, boolean)</rb><rp> (</rp><rt>func_193079_a</rt><rp>)</rp></ruby> &rarr; setIllagerFlag

## EntityVindicator

 - [ ] <ruby><rb>isAggressive</rb><rp> (</rp><rt>func_190639_o</rt><rp>)</rp></ruby> &rarr; hasTarget? `True if this vindicator has a target.\n \nIf true, the held item is rendered and the {@link AbstractIllager.IllagerArmPose#ATTACKING ATTACKING} pose is used.`
 - [ ] <ruby><rb>setAggressive</rb><rp> (</rp><rt>func_190636_a</rt><rp>)</rp></ruby> &rarr; setHasTarget? `Sets whether this vindicator has a target, and thus renders its held item and is in an attacking pose.`
 * p_190636_1_ &rarr; hasTarget? `The new value`

## EntityIllusionIllager

 - [ ] <ruby><rb>isAggressive</rb><rp> (</rp><rt>func_193096_dj</rt><rp>)</rp></ruby> &rarr; hasTarget? `True if this illusioner has a target.\n \nIf true, the held item is rendered and the {@link AbstractIllager.IllagerArmPose#BOW_AND_ARROW BOW_AND_ARROW} pose is used.`
 * setSwingingArms (from parent)

## AbstractSkeleton

 - [ ] <ruby><rb>SWINGING_ARMS</rb><rp> (</rp><rt>field_184728_b</rt><rp>)</rp></ruby> &rarr; ATTACKING?
 * setSwingingArms (from parent)
 - [ ] <ruby><rb>isSwingingArms</rb><rp> (</rp><rt>func_184725_db</rt><rp>)</rp></ruby> &rarr; hasTarget? `True if this skeleton has a target, OR is performing an arm swing animation.\n \nThis method is used for 2 things.  If the skeleton has a bow, then the bow-drawn pose is used if this is true.  If the skeleton does NOT have a bow, then this instead indicates that the arm swing animation is underway (much like with zombies).`

## IRangedAttackMob
 - [ ] <ruby><rb>setSwingingArms</rb><rp> (</rp><rt>func_184724_a</rt><rp>)</rp></ruby> &rarr; setHasTarget? `Sets whether this ranged entity is currently targeting another entity (usually causing it to use the drawn bow pose).\n \nNote that not all entities use this method, and that "melee" skeletons also use this for their arm swing animation.`
 - [ ] <ruby><rb>swingingArms</rb><rp> (</rp><rt>p_184724_1_</rt><rp>)</rp></ruby> &rarr; hasTarget `The new value`

## EntityWitch

See #460

# Command form

The changes above in command form are:

```
sf field_184712_c BLAZE_FLAGS A flag field that stores the blaze's charging state in its lowest bit.
sm func_70845_n isCharging Whether this blaze is preparing an attack.\n \nNote that this is identical to whether the blaze is visually on fire.
sm func_70844_e setCharging Marks whether this blaze is preparing an attack.
sp p_70844_1_ isCharging The new value
sf field_190664_a VEX_FLAGS A flag field that stores the vex's charging state in its lowest bit.
sm func_190647_dj isCharging Whether this vex is charging an attack.  This affects the texture used.
sm func_190648_a setCharging Marks whether this vex is preparing an attack.
sp p_190648_1_ isCharging The new value
sf field_193080_a ILLAGER_FLAGS A flag field that has various uses between different illagers, but mainly stores the illager's attacking state in its lowest bit.
sm func_193078_a getIllagerFlag
sm func_193079_a setIllagerFlag
sm func_190639_o hasTarget True if this vindicator has a target.\n \nIf true, the held item is rendered and the {@link AbstractIllager.IllagerArmPose#ATTACKING ATTACKING} pose is used.
sm func_190636_a setHasTarget Sets whether this vindicator has a target, and thus renders its held item and is in an attacking pose.
sp p_190636_1_ hasTarget The new value
sm func_193096_dj hasTarget True if this illusioner has a target.\n \nIf true, the held item is rendered and the {@link AbstractIllager.IllagerArmPose#BOW_AND_ARROW BOW_AND_ARROW} pose is used.
sf field_184728_b ATTACKING
sm func_184725_db hasTarget True if this skeleton has a target, OR is performing an arm swing animation.\n \nThis method is used for 2 things.  If the skeleton has a bow, then the bow-drawn pose is used if this is true.  If the skeleton does NOT have a bow, then this instead indicates that the arm swing animation is underway (much like with zombies).
sm func_184724_a setHasTarget Sets whether this ranged entity is currently targeting another entity (usually causing it to use the drawn bow pose).\n \nNote that not all entities use this method, and that "melee" skeletons also use this for their arm swing animation.
sp p_184724_1_ hasTarget The new value
```

I don't recommend directly applying these yet; some of the suggested names aren't perfect.

**Comment by kashike** [comment]
- [x] `func_190648_a`: `setIsCharging` -> `setCharging`

**Comment by PaleoCrafter** [comment]
I'm personally not too keen on the `X_FLAGS` names. I get the reasoning behind them, but I don't think `EntityX.X_FLAGS` to be particularly nice to read (when using the data parameters from outside). While I don't think that just `FLAGS` is a particularly good alternative, it'd remove some redundancy in the naming.
Another suggestion from me would be `COMBAT_FLAGS` across all entities. While that assumes some specified purpose for the data parameter, it would at least give the user *some* clue by name already.
