### ISSUE TITLE
EntityCreeper.isAIEnabled -> ableToCauseSkullDrop

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#467]
`EntityCreeper.func_70650_aV` has nothing to do with AI, but instead relates to whether entities exploded by a charged creeper may drop skulls and the internal skull counter.  I propose changing the name to something like `ableToCauseSkullDrop`, with a comment of something like "Returns true if an entity is able to drop its skull due to being blown up by this creeper.\n \nDoes not test if this creeper is charged; the caller must do that.  However, does test the doMobLoot gamerule."

```
fsm func_70650_aV ableToCauseSkullDrop Returns true if an entity is able to drop its skull due to being blown up by this creeper.\n \nDoes not test if this creeper is charged; the caller must do that.  However, does test the doMobLoot gamerule.
```

(this is apart from the fact that this method seems to have re-used the SRG name of an older method that actually _did_ handle AI, which was located in `EntityLivingBase` during 1.7.10 at least)

**Comment by kashike** [comment]
done.
- [x] `func_70650_aV`: `isAIEnabled` -> `ableToCauseSkullDrop`
