### ISSUE TITLE
ChestRenderer -> ???

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#468]
This isn't chest specific, it needs a more generic name.

Used only by `BlockRendererDispatcher` in vanilla code, and has only one method (`func_178175_a` -> `renderChestBrightness`), which calls through to `TileEntityItemStackRenderer.renderByItem` to do the actual rendering.

It's just a wrapper around that class/method, handling TESR-rendered blocks which aren't placed in world or in item form. The only vanilla method to use it is `BlockRendererDispatcher.renderBlockBrightness`, which is used to render blocks held by endermen, or in a minecart.

Both the class and the method could do with a better name, any good suggestions?

Edit:
`BlockRendererDispatcher.field_175024_d` (`chestRenderer`) would also need renaming.

**Comment by ThisTestUser** [comment]
I suggest changing the name to TileEntityRenderer, because it renders tile entities. renderBlockBrightness should be renderTileEntityWithColor.

**Comment by kashike** [comment]
No to the above. #450

**Comment by bs2609** [comment]
`TileEntityRenderer` would conflict with #450, though, and I think that's a better candidate for the name.

How about `TileEntityBlockRenderer` as a counterpart to `TileEntityItemStackRenderer`?

**Comment by kashike** [comment]
Usage:
```java
                case ENTITYBLOCK_ANIMATED:
                    this.chestRenderer.renderChestBrightness(state.getBlock(), brightness);
```

**Comment by ThisTestUser** [comment]
What about TileRenderHelper?

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
