### ISSUE TITLE
Rename ItemReed

### ISSUE THREAD

**Issue by gabizou** [ModCoderPack/MCPBot-Issues#47]
`ItemReed` used to be named for specifically the `Item` representation of a reed block, but now, it is instantiated for:
- cakes
- reeds
- string
- repeater
- brewing_stand
- cauldron
- flower_pot
- comparator

To be honest, I'm not 100% sure what the name should be instead, but as you can see, it's misleading for it to be named `ItemReed`. What this class does do is represent an item that isn't just the full rendering of a block, but strictly the item representation of what the block would be (the difference between a technical block itemstack and the actual item itemstack).

Some ideas: `ItemRepresentedBlock`, `ItemBlockProxy`, `ItemBlockWrapper`

**Comment by LexManos** [comment]
1.9: net/minecraft/item/ItemReed -> ItemBlockSpecial
It's used as a "Don't treat this render as a block" as well as having custom placement exceptions for snow {tho I suspect this is a bug}
