### ISSUE TITLE
Enum Options (GameSettings)

### ISSUE THREAD

**Issue by ThisTestUser** [ModCoderPack/MCPBot-Issues#470]
There are some deobfuscated names there are just weird.
GameSettings
field_74385_A - enumFloat > isFloat
field_74386_B - enumBoolean > isBoolean
field_74387_C - enumString > name (Refers to the untranslated name, like "options.invertMouse")
func_74378_d - getEnumString > getName()
func_74379_a - getEnumOptions > getOption
func_74380_a - getEnumFloat > isFloat()
func_74381_c - returnEnumOrdinal > getOrdinal()
func_74382_b - getEnumBoolean > isBoolean()

p_i1015_3_ - str > nameIn 
And also, following #464, we should rename enumOptions also:
field_146137_o - enumOptions > option

**Comment by kashike** [comment]
done.
- [x] `field_74385_A`: `enumFloat` -> `isFloat`
- [x] `field_74386_B`: `enumBoolean` -> `isBoolean`
- [x] `field_74387_C`: `enumString` -> `translation`
- [x] `func_74378_d`: `getEnumString` -> `getTranslation`
- [x] `func_74379_a`: `getEnumOptions` -> `byOrdinal`
- [x] `func_74380_a`: `getEnumFloat` -> `isFloat`
- [x] `func_74381_c`: `returnEnumOrdinal` -> `getOrdinal`
- [x] `func_74382_b`: `getEnumBoolean` -> `isBoolean`
