### ISSUE TITLE
Will 1.11.2 and 1.12 be soon in your obfuscation lists?

### ISSUE THREAD

**Issue by vrackfall** [ModCoderPack/MCPBot-Issues#472]
H'llo, just wondering if you could update soon the [MCPBot obfuscation lists](http://export.mcpbot.bspk.rs/versions.json) to add MC 1.11.2 and 1.12? Normally I would not ask for something like this, but this is needed for a very cool modding framework/api that is compatible with each Minecraft versions. It is named [PML](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/2602016) and it require your mappings as you can see [here](https://gist.github.com/vrackfall/13add81b8e996c2b9c132fb12be09044) and [here](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1285986-the-seasons-mod-minecraft-1-7-10-release-version?comment=2700).
Thanks

-vrack.

**Comment by Pokechu22** [comment]
1.12 is already in there.

1.11.2 isn't, and probably never will be, but you can still use 1.11 (or 1.12) mappings and they'll work fine except for a few things that are unnamed.

The SRGs already exist for both 1.11.2 and 1.12.

**Comment by vrackfall** [comment]
Thanks.
