### ISSUE TITLE
CraftingManager.findMatchingRecipe misnamed parameter

### ISSUE THREAD

**Issue by Earthcomputer** [ModCoderPack/MCPBot-Issues#473]
The method `net.minecraft.item.crafting.CraftingManager.findMatchingResult(InventoryCrafting, World)` might have changed signature in 1.12, which might be what has caused this. The 'World' parameter currently has the name `craftMatrix`. It should be renamed to `worldIn`. The parameter ID is `p_82787_1_`.
Edit: it seems there is a similar effect on `net.minecraft.item.crafting.CraftingManager.getRemainingItems(InventoryCrafting, World)`

**Comment by matthewprenger** [comment]
Done:
`p_82787_1_`: `craftMatrix` -> `worldIn`
`p_82787_0_`: -> `craftMatrix`
`p_180303_1_`: `craftMatrix` -> `worldIn`
`p_180303_0_`: -> `worldIn`
