### ISSUE TITLE
TileEntityHopper.func_145891_a (captureDroppedItems) -> pullItems [1.12]

### ISSUE THREAD

**Issue by howtonotwin** [ModCoderPack/MCPBot-Issues#474]
`func_145891_a` -> `pullItems`

`func_145891_a` doesn't just pull items from the world, but also pulls items from inventories, so it should be named accordingly.

**Comment by kashike** [comment]
done.
- [x] `func_145891_a`: `captureDroppedItems` -> `pullItems`
