### ISSUE TITLE
ResourceLocation -> RegistryName?

### ISSUE THREAD

**Issue by liach** [ModCoderPack/MCPBot-Issues#475]
Back in 1.7, this class is named resource location because it is only used for some sound resources. Now, it is widely used in registries. ResourceLocation, clearly, is no longer the best name. I suggest a few alternatives:
- RegistryName
- Name
- RegistryKey

**Comment by ryantheleach** [comment]
Namespace?

**Comment by Pokechu22** [comment]
I don't think it's good to mark it for registries specifically.

IIRC bukkit (the API) is using `Identifier` for the same concept; I think that that works well.  (Craftbukkit/spigot mappings use `MinecraftKey`; I don't like that but it's worth noting).

**Comment by kashike** [comment]
I don't see a reason to rename this.

**Comment by LexManos** [comment]
It's fine. Even with registries it's still a apt name. As it's the location of the resource in the registry.
