### ISSUE TITLE
markBlocksDirtyVertical has wrong parameters

### ISSUE THREAD

**Issue by mcenderdragon** [ModCoderPack/MCPBot-Issues#476]
int x2 -> y0
int z2 -> y1

x, and z are wrong

**Comment by bspkrs** [comment]
Please include the SRG names of the method and parameters in mapping issue reports.

**Comment by Pokechu22** [comment]
The method is `func_72975_g`.

I think what they mean is that the method doesn't mark a horizontal range.  Which seems to be correct.  So, here's my proposal:

* `p_72975_1_`: `x1` &rarr; `x` "The x coordinate of the column to update"
* `p_72975_2_`: `z1` &rarr; `z` "The y coordinate of the column to update"
* `p_72975_3_`: `x2` &rarr; `y1` "The lower coordinate to update"
* `p_72975_4_`: `z2` &rarr; `y2` "The upper coordinate to update"
* `func_72975_g`: comment "Marks a vertical column of blocks dirty, scheduling a render update.\n \nAutomatically swaps y1 and y2 if they are backwards."

**Comment by kashike** [comment]
done.
- [x] `p_72975_1_`: `x1` -> `x`
- [x] `p_72975_2_`: `z1` -> `z`
- [x] `p_72975_3_`: `x2` -> `y1`
- [x] `p_72975_4_`: `z2` -> `y2`
