### ISSUE TITLE
optionsFileIn > mcDataDirIn

### ISSUE THREAD

**Issue by ThisTestUser** [ModCoderPack/MCPBot-Issues#479]
p_i46326_2: optionsFileIn > mcDataDirIn

The parameter in the GameSettings constructor does not hold the location of the options file; it holds the location of the main Minecraft directory.

**Comment by Pokechu22** [comment]
:+1: but could probably be just `mcDataDir`; unlike `optionsFile`, there's no field named `mcDataDir`

**Comment by matthewprenger** [comment]
Done:
`p_i46326_2_`: `optionsFileIn` -> `mcDataDir`

**Comment by bs2609** [comment]
Taking the suggestion from #527, this would be better as `gameDir`.
