### ISSUE TITLE
WorldGenForest -> WorldGenBirchTree

### ISSUE THREAD

**Issue by Deamon5550** [ModCoderPack/MCPBot-Issues#48]
Some of the `WorldGenerator`s for generating trees are named very inconsistently. Specifically in mind is the WorldGenerator for birch trees `WorldGenForest` which would be better suited as `WorldGenBirchTree`.

For reference here are all the `WorldGenerator`s for the various tree types. `WorldGenShrub` (to `WorldGenJungleBush`) and `WorldGenSwamp` (to `WorldGenSwampTree`) are also possible candidates for renaming.

Tree | Small variant | Large Variant
---- | ---- | -----
Oak | `WorldGenTrees (ctor param)` | `WorldGenBigTree`
Birch | `WorldGenForest` | `WorldGenForest (ctor param)`
Pointy_Taiga | `WorldGenTaiga1` | `WorldGenMegaPine`
Tall_Taiga | `WorldGenTaiga2` | `WorldGenMegaPine`
Jungle | `WorldGenTrees (ctor param)` | `WorldGenMegaJungle`
Jungle_Bush | `WorldGenShrub` | --
Savanna | `WorldGenSavannaTree` | --
Canopy | `WorldGenCanopyTree` | --
Swamp | `WorldGenSwamp` | --

**Comment by LexManos** [comment]
1.9:
net/minecraft/world/gen/feature/WorldGenForest -> WorldGenBirchTree

The rest tho somewhat misleading usually take arguments or some form of parameter so specifically putting a name of the type would be a bad idea.
But if you have any other suggestions open a new issue and reference this.
