### ISSUE TITLE
world.makeFireworks has typo in NBTDataTagCompound argument

### ISSUE THREAD

**Issue by PfisterFactor** [ModCoderPack/MCPBot-Issues#480]
` public void makeFireworks(double x, double y, double z, double motionX, double motionY, double motionZ, @Nullable NBTTagCompound compund)`

should be

` public void makeFireworks(double x, double y, double z, double motionX, double motionY, double motionZ, @Nullable NBTTagCompound compound)`

**Comment by Pokechu22** [comment]
The parameter in question is `p_92088_13_`.

**Comment by bspkrs** [comment]
Done.
