### ISSUE TITLE
Several getColorFromItemstack -> colorMultiplier [1.12]

### ISSUE THREAD

**Issue by howtonotwin** [ModCoderPack/MCPBot-Issues#481]
`IItemColor.func_186726_a` -> `colorMultiplier`
`ItemColors.func_186728_a` -> `colorMultiplier`

Both of these methods' current name, `getColorFromItemstack` is not *wrong*, per se, but inconsistent with `IBlockColor.func_186720_a` and `BlockColors.func_186724_a` (`colorMultiplier`).

**Comment by williewillus** [comment]
+1. I named it getColorFromItemstack initially to align with the old method in Item to ease porting to 1.9, but we should consistentify it now. Should also rename the method in ItemColors if it hasn't been already.

**Comment by kashike** [comment]
done.
- [x] `func_186726_a`: `getColorFromItemstack` -> `colorMultiplier`
- [x] `func_186728_a`: `getColorFromItemstack` -> `colorMultiplier`
