### ISSUE TITLE
BlockPos.getAllInBoxMutable/BlockPos.mutablesBetween

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#482]
func_191531_b (`mutablesBetween`) and func_177975_b (`getAllInBoxMutable`) are logically overloads of eachother - one takes a pair of `BlockPos`es and the other takes 6 ints.  They should have the same name (as is the case with `getAllInBox` for func_191532_a and func_177980_a).

I think that getAllInBoxMutable is the better name, as it follows the convention used by the non-mutable methods (and is older).  As such, `func_191531_b` should be changed to getAllInBoxMutable.

**Comment by kashike** [comment]
done.
- [x] `func_191531_b`: `mutablesBetween` -> `getAllInBoxMutable`
