### ISSUE TITLE
MathHelper.clampAngle(int) / MathHelper.wrapDegrees(double / float)

### ISSUE THREAD

**Issue by joazlazer** [ModCoderPack/MCPBot-Issues#483]
_func_188209_b_ (`clampAngle`) has a different name than its float and double functional overrides _func_76142_g_ and _func_76138_g_ (both `wrapDegrees`), despite all three methods being logically identical and differing only in the data type used.

I believe `clampAngle` should be renamed to be another override of `wrapDegrees` in order to clarify the functional similarity of the methods and because `wrapDegrees` is a more appropriate name than `clampAngle`. Not only does `wrapDegrees` signify the angle format used, but "clamp" implies a mathematical clamping operation, and the method instead performs a wrapping operation.

**Conclusion**: _func_188209_b_ (`clampAngle`) should be renamed to `wrapDegrees`

**Comment by kashike** [comment]
done.
- [x] `func_188209_b`: `clampAngle` -> `wrapDegrees`
