### ISSUE TITLE
Boat lerp parameters [1.12]

### ISSUE THREAD

**Issue by howtonotwin** [ModCoderPack/MCPBot-Issues#484]
`field_70281_h` -> `lerpX` (old: `boatPitch`)
`field_70273_g` -> `lerpYaw` (old: `boatYaw`)
`field_184479_ay` -> `lerpPitch` (old: `lerpXRot`)

The last two are for consistency and clarity, and the first one's old name was just wrong.

**Comment by kashike** [comment]
done.
- [x] `field_70281_h`: `boatPitch` -> `lerpX`
- [x] `field_70273_g`: `boatYaw` -> `lerpYaw`
- [x] `field_184479_ay`: `lerpXRot` -> `lerpPitch`
