### ISSUE TITLE
StateMap.Builder.* [1.12]

### ISSUE THREAD

**Issue by howtonotwin** [ModCoderPack/MCPBot-Issues#485]
<details>
<summary>Old suggestions</summary>
<code>func_178442_a</code> -&gt; <code>withIgnores</code> (old: <code>ignore</code>)
<br/>
<code>field_178444_c</code> -&gt; <code>ignores</code> (old: <code>ignored</code>)
<br/>
<code>p_178440_1_</code> -&gt; <code>namer</code> (old: <code>builderPropertyIn</code>)
<br/>
<code>p_178439_1_</code> -&gt; <code>suffix</code> (old: <code>builderSuffixIn</code>)
<br/>
<br/>
<p><code>ignore</code> should use the plural to identify that it takes multiple ignores, and the <code>with</code> prefix is so it fits the pattern of names better.</p>
</details>
<br/>

`func_178442_a` -> `ignoring` (old: `ignore`)
`func_178440_a` -> `namedBy` (old: `withName`)
`func_178439_a` -> `suffixing` (old: `withSuffix`)
`field_178444_c` -> `ignores` (old: `ignored`)
`p_178440_1_` -> `namer` (old: `builderPropertyIn`)
`p_178439_1_` -> `suffix` (old: `builderSuffixIn`)

The method renames are to provide a more fluent interface as per the below conversation. The field rename is so that the field name is a noun,  and the parameter renames are for clarity.

**Comment by bs2609** [comment]
How about `ignoring` for the field/method names?

**Comment by howtonotwin** [comment]
I think the field name should stay `ignores`, or even `ignoredProperties`, simply because it's a noun. `ignoring`, while nice, also breaks the name pattern. If it's called that, then the other methods should also be fluently named, so `withSuffix` should be `suffixing` and `withName` `namedBy`.

**Comment by howtonotwin** [comment]
I think I actually like `ignoring` better. I'll edit the main issue.

**Comment by kashike** [comment]
Invalid as of 1.13.
