### ISSUE TITLE
"Uploader" Classes

### ISSUE THREAD

**Issue by ThisTestUser** [ModCoderPack/MCPBot-Issues#486]
(net.minecraft.client.renderer)
VertexBufferUploader > BufferBuilderUploader
WorldVertexBufferUploader > WorldBufferBuilderUploader

These names were from before the VertexBuffer rename, so they should be changed accordingly.

**Comment by bs2609** [comment]
Actually, `VertexBufferUploader` is ok as is, it uses the `VertexBuffer` class that wasn't renamed (and actually is to do with VBOs).

`WorldVertexBufferUploader` does need a rename though.

Would just `BufferUploader` do? There isn't any need for the "World" prefix, which isn't a very good disambiguation anyway, and we don't upload the builder itself, just the (now built) buffer.

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
