### ISSUE TITLE
SPacketEntity's inner classes aren't renamed

### ISSUE THREAD

**Issue by ThisTestUser** [ModCoderPack/MCPBot-Issues#487]
The classes still resemble what CPacketPlayer was like in 1.8. (e.g. S15PacketEntityRelMove)
So is it a good idea to rename those classes?
(My suggestion is to rename it like what CPacketPlayer does, with the "Position" and "Rotation" and such.)

**Comment by Pokechu22** [comment]
(ref for the CPacketPlayer thing: #231)

**Comment by bs2609** [comment]
As these are inner classes, they don't need another layer of `SPacketEntity`, they can just be:

`RelMove`
`Look`
`LookMove`

**Comment by kashike** [comment]
Updated.

**Comment by kashike** [comment]
- [x] `net/minecraft/network/play/server/SPacketEntity$S15PacketEntityRelMove` → `net/minecraft/network/play/server/SPacketEntity$RelMove`
- [x] `net/minecraft/network/play/server/SPacketEntity$S16PacketEntityLook` → `net/minecraft/network/play/server/SPacketEntity$Look`
- [x] `net/minecraft/network/play/server/SPacketEntity$S17PacketEntityLookMove` → `net/minecraft/network/play/server/SPacketEntity$Move`
