### ISSUE TITLE
BlockBreakable -> ???

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#489]
Extended by glass, ice (except packed ice), slime and portal block classes.
Has implementations of `isOpaqueCube` and `shouldSideBeRendered`.

The name doesn't really fit the function here, it's just a base class for 'connected' transparent/translucent blocks.

Any snappy suggestions?

**Comment by liach** [comment]
`TranslucentBlock`

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
