### ISSUE TITLE
WeightedRandomMinecart -> WeightedRandomSpawnable

### ISSUE THREAD

**Issue by ZephireNZ** [ModCoderPack/MCPBot-Issues#49]
It seems that the MobSpawner's base logic inherited much of the names for spawnerMinecarts.

The things that I think should be renamed:

* WeightedRandomMinecart -> WeightedRandomSpawnable (or something to signify it's not a complete entity)
* field_98285_e, minecartToSpawn -> possibleEntities

**Comment by LexManos** [comment]
1.9:
Not the same exact class but this utility class have been moved to net/minecraft/util/WeightedSpawnerEntity
