### ISSUE TITLE
RenderSnowball -> RenderSprite

### ISSUE THREAD

**Issue by Corosauce** [ModCoderPack/MCPBot-Issues#491]
It's a generic class that renders the texture of a passed in item, if you check out RenderManager you can see all the other entities that use it, eg ender pearl, egg, etc.

**Comment by bs2609** [comment]
Bump for #514?

**Comment by kashike** [comment]
added

**Comment by kashike** [comment]
- [x] `net/minecraft/client/renderer/entity/RenderSnowball` → `net/minecraft/client/renderer/entity/RenderSprite`
