### ISSUE TITLE
Better names for some world.gen.structure classes and methods

### ISSUE THREAD

**Issue by Hornwitser** [ModCoderPack/MCPBot-Issues#492]
I've looked through the world.gen.structure classes and found a few of the classes and methods to have misleading or inconsistent names.  It may not be desirable to do all of these renames, but the descriptions I've made can be added at the very least.

**Descriptions**
- `MapGenStructure.setStructureStart`
  Sets the StructureStart located at the provided chunk coordinates.

- `MapGenStructure.getStructureStart`
  Gets the StructureStart located at the provided chunk coordinates

**Misleading names**
- `StructureStart.isSizeableStructure` -> `*.isValid`
  Returns true if the generated structure is valid.

- ~~`MapGenStructureIO`~~ _`StructureIO`_ -> `StructureLoader`
  Doesn't actually do any IO.  Provides functions for loading `StructureStart` and `StructureComponent` from an NBTCompound based on a hard coded list of start and component types.

  _This class is interesting as the complete mapping between structure ids and the classes they correspond to is in it._

- `MapGenStructureIO.getStructureStart` -> `*.readStructureStartFromNBT`
  Reads a StructureStart from an NBTCompound passed as a parameter.
 
- `MapGenStructureIO.getStructureComponent` -> `*.readStructureComponentFromNBT`
  Reads a StructureComponent from an NBTCompound passed as a parameter.

**Inconsistent names**
- `StructureOceanMonument.StartMonument` -> `*.Start`
  For consistency with structure start classes.  The classes for the other structure types are named `MapGenVillage.Start`, `MapGenNetherBridge.Start`, `MapGenStronghold.Start`, `MapGenScatteredFeature.Start`, `MapGenEndCity.Start` and `WoodlandMansion.Start`

- ~~`ComponentScatteredFeaturePieces` -> `StructureScatteredFeaturePieces`
  `WoodLandMansionPieces` -> `StructureWoodlandMansionPieces`
  For consistency with structure pieces classes.  The classes for the other structure types are named `StructureMineshaftPieces`, `StructureVillagePieces`, `StructureNetherBridgePieces`, `StructureOceanMonumentPieces`, `StructureEndCityPieces`.~~
  
  _`Structure*Pieces` -> `*Pieces` has been done._

- `StructureMineshaftPieces.registerStructurePieces` -> `*.registerMineshaftPieces`
  `StructureEndCityPieces.registerPieces` -> `*.registerEndCityPieces`
  ~~`StructureNetherBridge.registerNetherFortressPieces` -> `*.registerNetherBridgePieces`~~ \*
  For consistency with registerXPieces methods.  The methods for the other structure types are name `registerVillagePieces`, `registerStrongHoldPieces`, `registerScatteredFeaturePieces`, `registerOceanMonumentPieces`, and `registerWoodlandMansionPieces`

  \* ~~An alternative is to rename `MapGenNetherBridge` and `StructureNetherBridgePieces` to use `NetherFortress` instead of `NetherBridge`.~~ _was done in #438_

- ~~`StructureOceanMonument` -> `MapGenOceanMonument`
  `WoodlandMansion` -> `MapGenWoodlandMansion`
  For consistency with the other MapGen classes.  The classes for the other structure types are named `MapGenVillage`, `MapGenNetherBridge`, `MapGenStronghold`, `MapGenScatteredFeature` and `MapGenEndCity`~~
  _`MapGen*` was renamed to `*Structure` in #448_

There is an odd one out: `StructureMineshaftStart`.  Had it followed the same pattern as the other classes it would have been a nested class of `MapGenMineshaft` called `Start`.  Maybe rename it to `MapGenMineshaftStart`?

**Comment by bs2609** [comment]
See also #438, #440, #441 and #448.

I'd prefer changing the 'worse' names to be more consistent with the 'better' ones.

I'd also prefer just `registerPieces`, you'll know what structure it is because of the class, you don't need to keep repeating it.

**Comment by Hornwitser** [comment]
Oh, derp.  I tried searching to see if this issue had been brought up before, but apparently I'm blind.

I suggested consistent names instead of logical ones to reduce the number of classes needed to be renamed.  But doing an overhaul on the names to better ones I'm all for.

**Comment by williewillus** [comment]
can we have `isSizeableStructure` renamed in 1.13?

**Comment by kashike** [comment]
- [x] `func_75069_d`: `isSizeableStructure` &rarr; `isValid`

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
