### ISSUE TITLE
Snow block names

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#493]
* `BlockSnow` -> `BlockSnowLayer`
* `BlockSnowBlock` -> `BlockSnow`

Matches with the registry names.
Also, `BlockSnowBlock` is kinda dumb.

**Comment by bs2609** [comment]
Also possibly `ItemSnow` -> `ItemSnowLayer`

**Comment by liach** [comment]
`SnowBlock`, `SnowLayerBlock`, and `SnowLayerItem`

**Comment by kashike** [comment]
https://github.com/MinecraftForge/MCPConfig/commit/193437679055c44272076c6ddf94b6f65178d57d
