### ISSUE TITLE
ModelSheep1 and ModelSheep2

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#494]
Yeah, not sure what happened here...
1 is for the fur, 2 is the actual model.

`ModelSheep1` -> `ModelSheepFur`
`ModelSheep2` -> `ModelSheep`

**Comment by bs2609** [comment]
Think I prefer `ModelSheepWool` for the first.

**Comment by kashike** [comment]
- [x] `net/minecraft/client/model/ModelSheep1` → `net/minecraft/client/model/ModelSheepWool`
- [x] `net/minecraft/client/model/ModelSheep2` → `net/minecraft/client/model/ModelSheep`
