### ISSUE TITLE
CommandBlockBaseLogic.fillInInfo wrong javadoc

### ISSUE THREAD

**Issue by liach** [ModCoderPack/MCPBot-Issues#495]
```java
/**
 * Fills in information about the command block for the packet. X/Y/Z for the minecart version, and entityId for
 * the traditional version
 */
```
This excerpt above is the javadoc for `CommandBlockBaseLogic#fillInInfo(ByteBuf)`. However, they are reversed. The x, y, and z coordinates are for the tile entity, while the entity id is for the minecart.

**Comment by PaleoCrafter** [comment]
JavaDoc changes can be done directly with the bot, simply reuse the existing MCP name when mapping: `!sm <srg name> <existing mcp name> <new JavaDoc>`.

**Comment by liach** [comment]
Aye, I don't really use irc. Can you fix it for me? @PaleoCrafter

**Comment by Pokechu22** [comment]
Done.

**Comment by liach** [comment]
Thanks!
