### ISSUE TITLE
Entity.velocityChanged and setBeenAttacked

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#497]
These two members are linked but have different names.  `velocityChanged` (`field_70133_I`) is checked in a few places and used to send a `SPacketEntityVelocity` when it's true (after which it is reset).  `setBeenAttacked` (`func_70018_K`) sets that field to true.

Now, while `setBeenAttacked` is _mostly_ called when an entity is attacked, it's also used elsewhere (specifically, in `EntityMinecartEmpty.onActivatorRailPass`), and modders may wish to use it in other contexts too.

I think that `markVelocityChanged` or something like that would be a better name.  The new Javadoc could be something like "Marks this entity's velocity as changed, so that it can be re-synced with the client later".

**Comment by kashike** [comment]
done.
- [x] `func_70018_K`: `setBeenAttacked` -> `markVelocityChanged`
