### ISSUE TITLE
EntityRenderer.fogColor1/2 -> ???

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#498]
These fields could do with proper names:
* `fogColor1` (`field_78539_ae`)
* `fogColor2` (`field_78535_ad`)

Some observations:
* Not colours, single `float` values, looks like a brightness multiplier
* `fogColor2` is the previous value of `fogColor1`, for interpolating between ticks
* `fogColor1` is updated each tick by `updateRenderer()` like so:
```java
float f3 = this.mc.world.getLightBrightness(new BlockPos(this.mc.getRenderViewEntity()));
float f4 = (float)this.mc.gameSettings.renderDistanceChunks / 32.0F;
float f2 = f3 * (1.0F - f4) + f4;
this.fogColor1 += (f2 - this.fogColor1) * 0.1F;
```
Any ideas?

**Comment by Pokechu22** [comment]
I haven't tried to investigate this with the actual code, but it's probably this (note the difference in the fog in the distance):

![2017-09-05_09 51 54](https://user-images.githubusercontent.com/8334194/30072669-e7ecbdaa-921f-11e7-94f2-b0b073b5d772.png)
![2017-09-05_09 52 00](https://user-images.githubusercontent.com/8334194/30072671-e7fa68ba-921f-11e7-9f2c-ed7905a2388a.png)
