### ISSUE TITLE
PotionHelper -> BrewingUtil

### ISSUE THREAD

**Issue by liach** [ModCoderPack/MCPBot-Issues#499]
There are two potion utilities classes (Classes that don't have instances but only static methods) right now: `PotionHelper` and `PotionUtils`. From another look, I find that `PotionHelper` actually handles potion recipes, while `PotionUtils` do more operations related to `Potion`, `PotionType` and `ItemStack`s. Thus, I suggest this rename, from `PotionHelper` to `PotionRecipeManager`.

**Comment by liach** [comment]
@kashike Will this be accepted for 1.13 changes?

**Comment by kashike** [comment]
Alternative names:
- [ ] `PotionBrewing`
- [ ] `BrewingUtil`

**Comment by liach** [comment]
Will this go into #514?

**Comment by kashike** [comment]
If a name is decided on.

**Comment by williewillus** [comment]
+1 BrewingUtil

**Comment by kashike** [comment]
- [x] `net/minecraft/potion/PotionHelper` →`net/minecraft/potion/PotionBrewing`
