### ISSUE TITLE
About 5K parameter names were dropped

### ISSUE THREAD

**Issue by xaeroverse** [ModCoderPack/MCPBot-Issues#5]
As requested, here's the report:

I maintain a private changelog and noticed ~5K parameter names missing.  Here's the diff:

https://gist.github.com/xaeroverse/e6ed35afc8e755a6e474

If you also check the export site, the latest `params.csv` is about ~25 KB but previous `params.csv` files are around ~130 KB in size.

edit:  checking the "Last Change" field, these params seem to all report a date of `2014-09-25`, which was the date when 1.8 supplanted 1.7.10 as the current bot version.  I suspect this is more than just coincidence.

**Comment by bspkrs** [comment]
Indeed. I have corrected the issue. This was a result of an incorrect where clause in an update statement during one-time database maintenence.

**Comment by bspkrs** [comment]
Thank you for catching this... everything went so smoothly during the database maintenance that I was sure I was missing SOMETHING ;)
