### ISSUE TITLE
RenderItem.func_183005_a: isThereOneNegativeScale -> isReflection

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#502]
It's a bit too literal, and it's not even right - it's checking for an odd number, not specifically one.

Usage (in `renderItemModel`):
```java
if (this.isThereOneNegativeScale(itemcameratransforms.getTransform(transform)))
{
	GlStateManager.cullFace(GlStateManager.CullFace.FRONT);
}
```

Effectively, every reflection changes the vertex winding from clockwise, to counter-clockwise (or vice-versa). As a result, the culling is reversed so that models don't render 'inside-out'.

`isReflection` might be a sufficient description, and it's a lot more concise.

**Comment by gegy1000** [comment]
Another option could possibly be `isInverse` or `isInverted`?
