### ISSUE TITLE
Realms names

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#503]
Here's a list of 'equivalent' names that I found were different between the "realms" and "regular" versions of classes.

To be taken as a list of suggestions for discussion. I don't think we should actually adopt all of these, but it's good to move towards consistency, and there are a good number of names that are an improvement.

* `ISaveFormat` (`RealmsAnvilLevelStorageSource`):
  - [ ]  `func_90033_f`: `canLoadWorld` -> `levelExists`
  - [ ]  `func_75805_a`: `convertMapFormat` -> `convertLevel`
  - [ ]  `func_75801_b`: `isOldMapFormat` -> `requiresConversion`
  - [ ]  `func_75802_e`: `deleteWorldDirectory` -> `deleteLevel`
  - [ ]  `func_75806_a`: `renameWorld` -> `renameLevel`
  - [ ]  `func_75800_d`: `flushCache` -> `clearAll`
  - [ ]  `func_75799_b`: `getSaveList` -> `getLevelList`

* `BufferBuilder` (`RealmsBufferBuilder`):
  - [ ]  `func_181674_a`: `sortVertexData` -> `sortQuads`
  - [ ]  `func_178968_d`: `putColor4` -> `fixupQuadColor`
  - [ ]  `func_178966_f`: `getByteBuffer` -> `getBuffer`
  - [ ]  `func_178975_e`: `putNormal` -> `postNormal`
  - [ ]  `func_178969_c`: `setTranslation` -> `offset`
  - [ ]  `func_178993_a`: `setVertexState` -> `restoreState`
  - [ ]  `func_178977_d`: `finishDrawing` -> `end`
  - [ ]  `func_178962_a`: `putBrightness4` -> `faceTex2`
  - [ ]  `func_178987_a`: `putPosition` -> `postProcessFacePosition`
  - [ ]  `func_178994_b`: `putColorRGB_F` -> `fixupVertexColor`
  - [ ]  `func_178978_a`: `putColorMultiplier` -> `faceTint`
  - [ ]  `func_187314_a`: `lightmap` -> `tex2`
  - [ ]  `func_178981_a`: `addVertexData` -> `putBulkData`
  - [ ]  `func_178965_a`: `reset` -> `clear`
  - [ ]  `func_181662_b`: `pos` -> `vertex`
  - [ ]  `func_178990_f`: `putColorRGB_F4` -> `fixupQuadColor`

* `GuiButton` (`RealmsButton`):
  - [ ]  `func_191745_a`: `drawButton` -> `render`
  - [ ]  `func_73729_b`: `drawTexturedModalRect` -> `blit`

* `GuiSlot` (`RealmsClickableScrolledSelectionList`):
  - [ ]  `func_148128_a`: `drawScreen` -> `render`
  - [ ]  `func_148145_f`: `scrollBy` -> `scroll`
  - [ ]  `func_148148_g`: `getAmountScrolled` -> `getScroll`
  - [ ]  `func_148140_g`: `setSlotXBoundsFromLeft` -> `setLeftPos`

* `GuiTextField` (`RealmsEditBox`):
  - [ ]  `func_146179_b`: `getText` -> `getValue`
  - [ ]  `func_146178_a`: `updateCursorCounter` -> `tick`
  - [ ]  `func_146195_b`: `setFocused` -> `setFocus`
  - [ ]  `func_146180_a`: `setText` -> `setValue`
  - [ ]  `func_146201_a`: `textboxKeyTyped` -> `keyPressed`
  - [ ]  `func_146194_f`: `drawTextBox` -> `render`
  - [ ]  `func_146203_f`: `setMaxStringLength` -> `setMaxLength`
  - [ ]  `func_146184_c`: `setEnabled` -> `setIsEditable`

* `WorldSummary` (`RealmsLevelSummary`):
  - [ ]  `func_75786_a`: `getFileName` -> `getLevelId`
  - [ ]  `func_75783_h`: `getCheatsEnabled` -> `hasCheats`
  - [ ]  `func_75789_g`: `isHardcoreModeEnabled` -> `isHardcore`
  - [ ]  `func_75788_b`: `getDisplayName` -> `getLevelName`
  - [ ]  `func_75784_e`: `getLastTimePlayed` -> `getLastPlayed`

* `GuiScreen`+`Gui` (`RealmsScreen`):
  - [ ]  `func_152125_a`: `drawScaledCustomSizeModalRect` -> `blit`
  - [ ]  `func_146110_a`: `drawModalRectWithCustomSizedTexture` -> `blit`
  - [ ]  `func_73733_a`: `drawGradientRect` -> `fillGradient`
  - [ ]  `func_146276_q_`: `drawDefaultBackground` -> `renderBackground`
  - [ ]  `func_73868_f`: `doesGuiPauseGame` -> `isPauseScreen`
  - [ ]  `func_146270_b`: `drawWorldBackground` -> `renderBackground`
  - [ ]  `func_146285_a`: `renderToolTip` -> `renderTooltip`
  - [ ]  `func_146283_a`: `drawHoveringText` -> `renderTooltip`
  - [ ]  `func_146279_a`: `drawHoveringText` -> `renderTooltip`

* `VertexFormat` (`RealmsVertexFormat`):
  - [ ]  `func_177344_b`: `getUvOffsetById` -> `getUvOffset`
  - [ ]  `func_177347_a`: `hasUvOffset` -> `hasUv`
  - [ ]  `func_177338_f`: `getNextOffset` -> `getVertexSize`

* `VertexFormatElement` (`RealmsVertexFormatElement`):
  - [ ]  `func_177374_g`: `isPositionElement` -> `isPosition`
  - [ ]  `func_177368_f`: `getSize` -> `getByteSize`
  - [ ]  `func_177370_d`: `getElementCount` -> `getCount`

* `Tessellator` (`Tezzelator`):
  - [ ] `func_78381_a`: `draw` -> `end`

**Comment by Pokechu22** [comment]
I'm planning on doing a large rework of the GUI code (especially since I'm one of the few people who actually uses the scrollable lists).  This will be helpful in deciding on good names for some of that code.
