### ISSUE TITLE
Entity.isCollided fields

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#506]
These fields:
* `field_70132_H`: `isCollided`
* `field_70123_F`: `isCollidedHorizontally`
* `field_70124_G`: `isCollidedVertically`

"isCollided" just sounds bad, I think "isColliding", or just "colliding" would work better.

**Comment by kashike** [comment]
How about:
- [ ] `field_70132_H`: `isCollided` -> `collided`
- [ ] `field_70123_F`: `isCollidedHorizontally` -> `horizontallyCollided`
- [ ] `field_70124_G`: `isCollidedVertically` -> `verticallyCollided`

**Comment by Pokechu22** [comment]
I'd prefer `collidedHorizontally`/`collidedVertically` - it feels more natural to me.

**Comment by kashike** [comment]
Sure, those work.

**Comment by kashike** [comment]
done.
- [x] `field_70132_H`: `isCollided` -> `collided`
- [x] `field_70123_F`: `isCollidedHorizontally` -> `collidedHorizontally`
- [x] `field_70124_G`: `isCollidedVertically` -> `collidedVertically`

**Comment by bloodmc** [comment]
@kashike I don't really like this change. Collided sounds to me like the entity has collided and is no longer colliding. It would be better with the original change as "isColliding", "isCollidingHorizontally", "isCollidingVertically".

**Comment by kashike** [comment]
The only change was dropping `is`.
