### ISSUE TITLE
EntityAIAttackMelee.field_75438_g: entityPathEntity -> pathToTarget

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#509]
pls no `entityPathEntity`

**Comment by bs2609** [comment]
also `EntityAIAvoidEntity.field_75374_f`: `entityPathEntity` -> `pathToTarget`

**Comment by kashike** [comment]
done.
- [x] `field_75438_g`: `entityPathEntity` -> `path`
- [x] `field_75374_f`: `entityPathEntity` -> `path`
- [x] `field_75419_c`: `entityPathNavigate` -> `path`
- [x] `field_75375_g`: `entityPathNavigate` -> `navigation`
