### ISSUE TITLE
Rename DamageSource.setExplosionSource to causeExplosionSource

### ISSUE THREAD

**Issue by gabizou** [ModCoderPack/MCPBot-Issues#51]
The method creates a new `DamageSource` each time it is called and doesn't "set" anything.

**Comment by gabizou** [comment]
Just pinging as this was reported last year, but seeing as 1.9 has come around, I believe it's time to actually resolve this.

**Comment by matthewprenger** [comment]
Fixed:
setExplosionSource -> causeExplosionDamage (damage instead of source to align with the other methods in the class)
