### ISSUE TITLE
Small pathfinding method cleanup

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#510]
- [x] `PathFinder.func_75853_a`: `createEntityPath` -> `createPath`
- [x] `NodeProcessor.func_186315_a` `initProcessor` -> `init`
- [x] `PathNavigate.func_75499_g`: `clearPathEntity` -> `clearPath`

**Comment by bs2609** [comment]
Also I think that these `PathNavigate` methods:

* `func_75488_a` (`getPathToXYZ`)
* `func_179680_a` (`getPathToPos`)
* `func_75494_a` (`getPathToEntityLiving`)

should all have a common name, as should these:

* `func_75492_a` (`tryMoveToXYZ`)
* `func_75497_a` (`tryMoveToEntityLiving`)

**Comment by kashike** [comment]
- [x] `func_75853_a`: `createEntityPath` -> `createPath`
- [x] `func_186315_a`: `initProcessor` -> `init`
- [x] `func_75499_g`: `clearPathEntity` -> `clearPath`

**Comment by kashike** [comment]
Got some suggestions for that second batch?

**Comment by bs2609** [comment]
For the second set, just `getPathTo` and `tryMoveTo` are ok.

**Comment by bs2609** [comment]
Another name that needs a look:
* `func_75487_m`: `removeSunnyPath` -> ???

Defined by the base `PathNavigate`. `PathNavigateGround` extends this to also trim sunlit areas if `shouldAvoidSun` is true, but it's not really a good name for the base method.

**Comment by kashike** [comment]
- [x] `func_75487_m`: `removeSunnyPath` -> `trimPath`

**Comment by gegy1000** [comment]
Some proposals from #775 for `PathNavigate`:

#### Fields
- [ ] `field_75514_c` (`currentPath`) -> `activePath`
- [ ] `field_188563_q` (`lastTimeUpdated`) -> `lastCalculateTime`
- [ ] `field_188562_p` (`tryUpdatePath`) -> `shouldRecalculate`
- [ ] `field_75520_h` (`ticksAtLastPos`) -> `lastStuckCheckTicks`

#### Methods
- [ ] `func_188554_j ` (`updatePath`) -> `recalculatePath`
- [ ] `func_75488_a` (`getPathToXYZ`) -> `findPath`
- [ ] `func_179680_a` (`getPathToPos`) -> `findPath`
- [ ] `func_75494_a` (`getPathToEntityLiving`) -> `findPath`
- [ ] `func_75492_a` (`tryMoveToXYZ`) -> `navigateTo`
- [ ] `func_75497_a` (`tryMoveToEntityLiving`) -> `navigateTo`
- [ ] `func_75484_a` (`setPath`) -> `followPath`
- [ ] `func_75505_d` (`getPath`) -> `getActivePath`
- [ ] `func_75508_h` (`pathFollow`) -> `followPath`
- [ ] `func_179677_a` (`checkForStuck`) -> `checkStuck`
- [ ] `func_75500_f` (`noPath`) -> `isInactive`
- [ ] `func_75499_g` (`clearPath`) -> `stop`
- [ ] `func_188553_i` (`canUpdatePathOnTimeout`) -> `shouldRecalculate`
