### ISSUE TITLE
damageVsEntity -> attackDamage

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#512]
Fields:
* `Item$ToolMaterial.field_78011_i`: `damageVsEntity` -> `attackDamage`
* `ItemTool.field_77865_bY`: `damageVsEntity` -> `attackDamage`

Methods:
* `Item$ToolMaterial.func_78000_c`: `getDamageVsEntity` -> `getAttackDamage`
* `ItemSword.func_150931_i`: `getDamageVsEntity` -> `getAttackDamage`

**Comment by kashike** [comment]
done.
- [x] `field_78011_i`: `damageVsEntity` -> `attackDamage`
- [x] `field_77865_bY`: `damageVsEntity` -> `attackDamage`
- [x] `func_78000_c`: `getDamageVsEntity` -> `getAttackDamage`
- [x] `func_150931_i`: `getDamageVsEntity` -> `getAttackDamage`
