### ISSUE TITLE
getStrVsBlock -> ???

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#513]
* `InventoryPlayer.func_184438_a`
* `ItemStack.func_150997_a`
* `Item.func_150893_a`

I'd say something like `getMiningSpeed`, but other suggestions would be welcome.

**Comment by bs2609** [comment]
Also would like to propose dropping the "OnProperMaterial" suffix here:

* `efficiencyOnProperMaterial`
  *  `Item$ToolMaterial.field_78010_h` 
  *  `ItemTool.field_77864_a`

* `getEfficiencyOnProperMaterial`
  *  `Item$ToolMaterial.func_77998_b`

**Comment by kashike** [comment]
done.
- [x] `func_184438_a`: `getStrVsBlock` -> `getDestroySpeed`
- [x] `func_150997_a`: `getStrVsBlock` -> `getDestroySpeed`
- [x] `func_150893_a`: `getStrVsBlock` -> `getDestroySpeed`
- [x] `field_78010_h`: `efficiencyOnProperMaterial` -> `efficiency`
- [x] `field_77864_a`: `efficiencyOnProperMaterial` -> `efficiency`
- [x] `func_77998_b`: `getEfficiencyOnProperMaterial` -> `getEfficiency`
