### ISSUE TITLE
AnvilChunkLoader.chunksToRemove -> chunksToSave

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#515]
I was looking over `AnvilChunkLoader`, and the name of <ruby><rb>`chunksToRemove`</rb><rp>( </rp><rt>field_75828_a</rt><rp>)</rp></ruby> seems wrong.  It isn't used to store chunks to be removed (from what?), but instead to store chunks to be written to disk.

There's also a `Set` field named <ruby><rb>`currentSave`</rb><rp>( </rp><rt>field_193415_c</rt><rp>)</rp></ruby> (although it was named <ruby><rb>`pendingAnvilChunksCoordinates`</rb><rp>( </rp><rt>field_75826_b</rt><rp>)</rp></ruby> prior to 1.12).  While the current name seems to be accurate, I think it could still be changed.  Oh, and it's worth noting that it seems like this will only at max one entry (though changes to the way threaded IO works may make this different, but I doubt that will happen).  However, it sort of makes sense to describe it in plural for consistency.  Finally, this is based off of `Collections.newSetFromMap`.

It's worth noting that the type of this field changed between 1.8 and 1.8.9 from a `List` to a `Map`.  So the original name _may_ have been accurate.  The logic behind both of the fields also changed in this time range, so there is very clearly a possibility that things may be different.  Unfortunately I don't like poking in 1.8 (code's bleh, no generics) so I can't say for sure whether that's the case.

Here's my proposal:

 - [ ] `field_75828_a`: `chunksToRemove` &rArr; `chunksToSave`, commented "A map containing chunks to be written to disk (but not those that are currently in the process of being written).  Key is the chunk position, value is the NBT to write."
 - [ ] `field_193415_c`: `currentSave` &rArr; `chunksBeingSaved`, commented "A set containing the chunk that is currently in the process of being written to disk."

See also:
* [MC-119971](https://bugs.mojang.com/browse/MC-119971 "[MC-119971] Various duplications, deletions, and data corruption at chunk boundaries, caused by loading outdated chunks — includes duping and deletion of entities/mobs, items in hoppers, and blocks moved by pistons, among other problems") - this is the issue that's prompted me and theosib to be looking at this code in the first place.  It's worth noting that the fix includes changing the type of `currentSave` to a Map, which is part of the reason why I've written it this way.
* #376 - also related to AnvilChunkLoader, and helped with some of the weirdly named methods.

**Comment by kashike** [comment]
done.
- [x] `field_75828_a`: `chunksToRemove` -> `chunksToSave`
- [x] `field_193415_c`: `currentSave` -> `chunksBeingSaved`
