### ISSUE TITLE
EntityLiving.leashedToEntity renames

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#516]
* `field_110168_bw`: `leashedToEntity` -> `leashHolder`
* `func_110166_bE`: `getLeashedToEntity` -> `getLeashHolder`
* `func_110162_b`: `setLeashedToEntity` -> `setLeashHolder`

**Comment by kashike** [comment]
done.
- [x] `field_110168_bw`: `leashedToEntity` -> `leashHolder`
- [x] `func_110166_bE`: `getLeashedToEntity` -> `getLeashHolder`
- [x] `func_110162_b`: `setLeashedToEntity` -> `setLeashHolder`
