### ISSUE TITLE
Various doThingToEntity(Entity) renames

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#517]
* `Entity`:
  - [x] `func_70068_e`: `getDistanceSqToEntity` -> `getDistanceSq`
  - [x] `func_70032_d`: `getDistanceToEntity` -> `getDistance`
  - [ ] `func_184190_l`: `applyOrientationToEntity` -> `adjustOrientation` ?

* `EntityWither`:
  - [ ] `func_82216_a`: `launchWitherSkullToEntity` -> `fireAtTarget` / `shootAtTarget`
  - [ ] `func_82209_a`: `launchWitherSkullToCoords` -> `fireAtTarget` / `shootAtTarget`

* `EntityBoat`:
  - [ ] `func_184454_a`: `applyYawToEntity` -> `adjustYaw` ?

**Comment by kashike** [comment]
- [x] `func_70068_e`: `getDistanceSqToEntity` -> `getDistanceSq`
- [x] `func_70032_d`: `getDistanceToEntity` -> `getDistance`
