### ISSUE TITLE
Block.func_180651_a: damageDropped -> getItemMetadata

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#519]
Fits better with the existing comment, too.

**Comment by kashike** [comment]
This is a heavily used method, so I'm going to let this one sit for a little bit.

**Comment by Pokechu22** [comment]
Note the impending [flattening](https://minecraft.gamepedia.com/1.13/Flattening) of 1.13, which will more or less get rid of damage values/metadata in the inventory.  I'm guessing that this method won't exist in 1.13.

**Comment by kashike** [comment]
That was my thought too.

**Comment by kashike** [comment]
This method no longer exists in 1.13.
