### ISSUE TITLE
Entity method cleanup

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#522]
* `Entity`:
  - [x] `func_70088_a`: `entityInit` -> `registerDataParameters` ?
  - [ ] `func_70046_E`: `getCollisionBoundingBox` -> `getCollisionBox` ?
  - [ ] `func_70100_b_`: `onCollideWithPlayer` -> `onPlayerCollision`
  - [ ] `func_70108_f`: `applyEntityCollision` -> `handleCollision` ?
  - [ ] `func_70097_a`: `attackEntityFrom` -> `takeDamage` ?
  - [x] `func_174824_e`: `getPositionEyes` -> `getEyePosition`
  - [ ] `func_70067_L`: `canBeCollidedWith` -> `blocksMovement` ?
  - [ ] `func_145770_h`: `isInRangeToRender3d` -> `isInRenderRange`
  - [ ] `func_70112_a`: `isInRangeToRenderDist` -> `isInRenderRange`
  - [ ] `func_70089_S`: `isEntityAlive` -> `isAlive`
  - [x] `func_70094_T`: `isEntityInsideOpaqueBlock` -> `isSuffocating` / `shouldSuffocate`
  - [x] `func_180431_b`: `isEntityInvulnerable` -> `isInvulnerableTo`
  - [x] `func_190530_aW`: `getIsInvulnerable` -> `isInvulnerable`
  - [x] `func_184224_h`: `setEntityInvulnerable` -> `setInvulnerable`
  - [ ] `func_145773_az`: `doesEntityNotTriggerPressurePlate` ->???
  - [x] `func_85029_a`: `addEntityCrashInfo` -> `addToCrashReport`
  - [x] `func_174833_aM`: `getAlwaysRenderNameTag` -> `isCustomNameVisible`
  - [x] `func_174805_g`: `setAlwaysRenderNameTag` -> `setCustomNameVisible`
  - [ ] `func_94059_bO`: `getAlwaysRenderNameTagForRender` -> `alwaysRenderCustomName`
  - [ ] `func_174813_aQ`: `getEntityBoundingBox` -> `getBoundingBox`
  - [ ] `func_174826_a`: `setEntityBoundingBox` -> `setBoundingBox`

* `ICommandSender`:
  - [ ] `func_130014_f_`: `getEntityWorld` -> `getWorld`
  - [ ] `func_174793_f`: `getCommandSenderEntity` -> `getEntity`
  - [ ] `func_174792_t_`: `sendCommandFeedback` -> `shouldReceiveFeedback`

**Comment by bs2609** [comment]
Notes:
* `isEntityInsideOpaqueBlock` takes the name change from #289.
* For the nametag methods, "CustomNameVisible" is the NBT tag name.
* `doesEntityNotTriggerPressurePlate` also affects tripwires, but I'm not sure of a good name for it.

**Comment by bs2609** [comment]
Also `func_70070_b`: `getBrightnessForRender` -> `getPackedLightmapCoords` ?

For consistency with the `Block` method, which functions similarly. It's also a better description of the result.

**Comment by bs2609** [comment]
* `EntityLivingBase`:
  * `func_110147_ax`: `applyEntityAttributes` -> `applyAttributes`
  * `func_70662_br`: `isEntityUndead` -> `isUndead`
  * `func_70665_d`: `damageEntity` -> ???
  * `func_94060_bK`: `getAttackingEntity` -> `getAttacker`
  * `func_85035_bI`: `getArrowCountInEntity` -> `getArrowsHitBy` ?
  * `func_85034_r`: `setArrowCountInEntity` -> `setArrowsHitBy` ?
  * `func_110148_a`: `getEntityAttribute` -> `getAttribute`
  * `func_70626_be`: `updateEntityActionState` -> `updateActions`
  * `func_82167_n`: `collideWithEntity` -> `collideWith`
  * `func_70685_l`: `canEntityBeSeen` -> `canSee`

* `EntityLiving`:
  * `func_184651_r`: `initEntityAI` -> `initAI`
  * `func_70627_aG`: `getTalkInterval` -> ???
  * `func_70642_aH`: `playLivingSound` -> `playAmbientSound`
  * `func_175456_n`: `applyEntityAI` -> ???
  * `func_70623_bb`: `despawnEntity` -> `checkDespawn`
  * `func_70601_bi`: `getCanSpawnHere` -> `canSpawnHere`
  * `func_70641_bl`: `getMaxSpawnedInChunk` -> `getChunkSpawnLimit`

Notes:

* `func_70665_d` (`damageEntity`) needs to fit with `Entity.func_70097_a` (`attackEntityFrom`)

* Not sure what happened with `func_175456_n` (`applyEntityAI`), here it is:
```java
private void applyEntityAI()
{
	this.livingSoundTime = -this.getTalkInterval();
}
```
It's called from `onEntityUpdate` and `playHurtSound`.

**Comment by bs2609** [comment]
Seems like there's some issue with `func_175456_n`, it appears both as the mentioned private method in `EntityLiving` and also as a protected method in `EntityZombie`.

**Comment by kashike** [comment]
@bs2609 `func_175456_n` issue will be fixed with 1.13.1+, thanks for finding that

**Comment by kashike** [comment]
- [x] `func_180431_b`: `isEntityInvulnerable` -> `isInvulnerableTo`

**Comment by bs2609** [comment]
Other "invulnerable" names need #702 resolving first.
