### ISSUE TITLE
TileEntity.field_145846_f: tileEntityInvalid -> invalid

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#523]
See title.

**Comment by kashike** [comment]
I think this should be `removed` instead, along with the getter/setter being renamed to match - it's `true` when removing a block entity or replacing a block entity, as well as a special case in the piston block entity.

**Comment by bs2609** [comment]
#430 is relevant then, I think.

**Comment by kashike** [comment]
- [x] `field_145846_f`: `tileEntityInvalid` &rarr; `removed` 
- [x] `func_145837_r`: `isInvalid` &rarr; `isRemoved` 
- [x] `func_145843_s`: `invalidate` &rarr; `remove`

**Comment by bs2609** [comment]
What are you planning to do about `func_145829_t` (`validate`)?
