### ISSUE TITLE
Item/ItemStack cleanup

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#524]
* `Item`:
  - [x] `func_77639_j`: `getItemStackLimit` -> `getMaxStackSize`
  - [ ] ~~`func_77614_k`: `getHasSubtypes` -> `hasSubtypes`~~
  - [ ] ~~`func_77627_a`: `setHasSubtypes` -> `withSubtypes`~~
  - [ ] `func_150897_b`: `canHarvestBlock` -> `canHarvest`
  - [ ] `func_111207_a`: `itemInteractionForEntity` -> `attemptEntityInteraction` / `interactWithEntity` ?
  - [x] `func_77661_b`: `getItemUseAction` -> `getUseAction`
  - [x] `func_77626_a`: `getMaxItemUseDuration` -> `getUseDuration`
  - [ ] `func_77653_i`: `getItemStackDisplayName` -> `getDisplayName`
  - [ ] `func_77619_b`: `getItemEnchantability` -> `getEnchantability`
  - [ ] `func_82788_x`: `canItemEditBlocks` -> `canModifyWorld` ?
  - [ ] `func_82789_a`: `getIsRepairable` -> `isRepairable`
  - [x] `func_111205_h`: `getItemAttributeModifiers` -> `getAttributeModifiers`
  - [ ] `field_77701_a`: `tabToDisplayOn` -> `creativeTab` / `group`
  - [x] `field_77697_d`: `itemRand` -> `random`
  - [ ] `field_77789_bW`: `bFull3D` -> `full3D`

* `ItemStack`:
  - [x] `func_77984_f`: `isItemStackDamageable` -> `isDamageable`
  - [ ] `func_77981_g`: `getHasSubtypes` -> `hasSubtypes`
  - [ ] `func_150998_b`: `canHarvestBlock` -> `canHarvest`
  - [x] `func_77951_h`: `isItemDamaged` -> `isDamaged`
  - [x] `func_77952_i`: `getItemDamage` -> `getDamage`
  - [x] `func_77964_b`: `setItemDamage` -> `setDamage`
  - [ ] `func_111282_a`: `interactWithEntity` -> `attemptEntityInteraction` / (keep) ?
  - [x] `func_77975_n`: `getItemUseAction` -> `getUseAction`
  - [x] `func_77988_m`: `getMaxItemUseDuration` -> `getUseDuration`
  - [ ] `func_151001_c`: `setStackDisplayName` -> `setDisplayName`
  - [ ] `func_135074_t`: `clearCustomName` -> `clearDisplayName`
  - [x] `func_77956_u`: `isItemEnchantable` -> `isEnchantable`
  - [x] `func_77948_v`: `isItemEnchanted` -> `isEnchanted`

* `Slot`:
  - [ ] `func_178170_b`: `getItemStackLimit` -> `getMaxStackSize`

* `InventoryPlayer`:
  - [ ] `func_184432_b`: `canHarvestBlock` -> `canHarvest`

* `EntityPlayer`:
  - [ ] `func_184823_b`: `canHarvestBlock` -> `canHarvest`

**Comment by PaleoCrafter** [comment]
Overall great suggestions, only the `withSubtypes` jumps out at me, but I also can't come up with a better name off the top of my head, except maybe `enableSubtypes` to express the side effects more clearly. There's also a small typo in `getEnchantablility` ^^

**Comment by bs2609** [comment]
Here's the `onEvent` names that could do with changing. I've included the names that I thought sounded best individually, but any suggestions for good names that are more consistent would be welcome.

* `Item`:
  * `func_180614_a`: `onItemUse` -> `onUse` ?
  * `func_77659_a`: `onItemRightClick` -> `onRightClick` ?
  * `func_77654_b`: `onItemUseFinish` -> `onFinishedUsing` ?
  * `func_77615_a`: `onPlayerStoppedUsing` -> `onStoppedUsing` ?

* `ItemStack`:
  * `func_179546_a`: `onItemUse` -> `onUse` ?
  * `func_77957_a`: `useItemRightClick` -> `onRightClick` ?
  * `func_77950_b`: `onItemUseFinish` -> `onFinishedUsing` ?
  * `func_77974_b`: `onPlayerStoppedUsing` -> `onStoppedUsing` ?

**Comment by williewillus** [comment]
onItemUse/onItemRightClick are still ambiguous. Since we're renaming we can take the opportunity to clarify those.

onItemUse is when the item is right clicked while targeting a block, onItemRightClick is when onItemUse passes or the player is not targeting a block

**Comment by PaleoCrafter** [comment]
I feel like this doesn't require a separate issue, so an additional suggestion:
`func_150898_a`: `getItemFromBlock` -> `fromBlock`

**Comment by kashike** [comment]
- [x] `func_77639_j`: `getItemStackLimit` -> `getMaxStackSize`
- [x] `func_111205_h`: `getItemAttributeModifiers` -> `getAttributeModifiers`
- [x] `func_77956_u`: `isItemEnchantable` -> `isEnchantable`
- [x] `func_77948_v`: `isItemEnchanted` -> `isEnchanted`
- [x] `func_77661_b`: `getItemUseAction` -> `getUseAction`
- [x] `func_77626_a`: `getMaxItemUseDuration` -> `getUseDuration`
- [x] `func_77975_n`: `getItemUseAction` -> `getUseAction`
- [x] `func_77988_m`: `getMaxItemUseDuration` -> `getUseDuration`
- [x] `field_77697_d`: `itemRand` -> `random`
