### ISSUE TITLE
ResourceLocation renames

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#526]
- [ ] `field_110626_a`: `resourceDomain` &rarr; `namespace`
- [ ] `field_110625_b`: `resourcePath` &rarr; `path`
- [ ] `func_110624_b`: `getResourceDomain` &rarr; `getNamespace`
- [ ] `func_110623_a`: `getResourcePath` &rarr; `getPath`
- [ ] `p_i1292_1_`: `resourceDomainIn` &rarr; `namespaceIn`
- [ ] `p_i1292_2_`: `resourcePathIn` &rarr; `pathIn`

**Comment by Pokechu22** [comment]
I'd also add:

- [ ] `p_i1292_1_`: `resourceDomainIn` &rarr; `namespaceIn`
- [ ] `p_i1292_2_`: `resourcePathIn` &rarr; `pathIn`

**Comment by covers1624** [comment]
Any particular reason we are switching from "domain" to "namespace"?

**Comment by kashike** [comment]
"domain" sounds weird when also used with "path" in this case.
Additionally, it's the official name used in documentation - people coming from the wiki will be used to a single term: *namespace*.
https://gist.github.com/Dinnerbone/943fbcd763c19be188ed6b72a12d7e65#file-wip_changelog-md
https://minecraft.gamepedia.com/1.12-pre1#General
https://minecraft.gamepedia.com/Function#Usage

**Comment by williewillus** [comment]
Namespace is the vanilla term so better to go that way

**Comment by bs2609** [comment]
Can't we just have `namespace` and `path` for the param names?

**Comment by kashike** [comment]
Yes.

**Comment by covers1624** [comment]
Honestly, if that is the naming vanilla is using then its the name we should be to, atleast in this instance considering the class. The only reason i asked was it seemed like there was no motive but there indeed was and its entirely valid.

**Comment by kashike** [comment]
- [x] `field_110626_a`: `resourceDomain` &rarr; `namespace`
- [x] `field_110625_b`: `resourcePath` &rarr; `path`
- [x] `func_110624_b`: `getResourceDomain` &rarr; `getNamespace`
- [x] `func_110623_a`: `getResourcePath` &rarr; `getPath`
- [x] `p_i1292_1_`: `resourceDomainIn` &rarr; `namespaceIn`
- [x] `p_i1292_2_`: `resourcePathIn` &rarr; `pathIn`
