### ISSUE TITLE
Various mcNames

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#527]
* `Minecraft`:
  * `field_110451_am`: `mcResourceManager` -> `resourceManager`
  * `field_71424_I`: `mcProfiler` -> `profiler`
  * `field_71412_D`: `mcDataDir` -> `gameDir` ?
  * `field_110450_ap`: `mcDefaultResourcePack` -> `defaultResourcePack`
  * `field_110448_aq`: `mcResourcePackRepository` -> `resourcePackRepository`
  * `field_135017_as`: `mcLanguageManager` -> `languageManager`
  * `field_147127_av`: `mcSoundHandler` -> `soundHandler`
  * `field_147126_aw`: `mcMusicTicker` -> `musicTicker`
  * `field_152352_aC`: `mcThread` -> `clientThread` ?
  * `field_147124_at`: `framebufferMc` -> `framebuffer`
  * `field_71453_ak`: `myNetworkManager` -> `networkManager`

* `SoundHandler.field_147695_g`: `mcResourceManager` -> `resourceManager`
* `GameConfiguration$FolderInformation.field_178760_a`: `mcDataDir` -> `gameDir` ?

* `mcServer` -> `server`:
  * `WorldServer.field_73061_a`
  * `ServerWorldEventHandler.field_72783_a`
  * `NetworkSystem.field_151273_d`
  * `StatisticsManagerServer.field_150890_c`
  * `EntityPlayerMP.field_71133_b`
  * `PlayerList.field_72400_f`
  * `NetHandlerHandshakeMemory.field_147385_a`

**Comment by williewillus** [comment]
mcDataDir -> dotMinecraft? workingDirectory?

**Comment by Pokechu22** [comment]
The name used in `Main` and passed from the launcher is `gameDir`.  That's probably the ideal name.

**Comment by kashike** [comment]
- [x] `field_73061_a`: `mcServer` -> `server`
- [x] `field_72783_a`: `mcServer` -> `server`
- [x] `field_151273_d`: `mcServer` -> `server`
- [x] `field_150890_c`: `mcServer` -> `server`
- [x] `field_71133_b`: `mcServer` -> `server`
- [x] `field_72400_f`: `mcServer` -> `server`
- [x] `field_147385_a`: `mcServer` -> `server`

**Comment by kashike** [comment]
- [x] `field_110451_am`: `mcResourceManager` -> `resourceManager`
- [x] `field_71424_I`: `mcProfiler` -> `profiler`
- [x] `field_71412_D`: `mcDataDir` -> `gameDir`
- [x] `field_110450_ap`: `mcDefaultResourcePack` -> `defaultResourcePack`
- [x] `field_110448_aq`: `mcResourcePackRepository` -> `resourcePackRepository`
- [x] `field_135017_as`: `mcLanguageManager` -> `languageManager`
- [x] `field_147127_av`: `mcSoundHandler` -> `soundHandler`
- [x] `field_147126_aw`: `mcMusicTicker` -> `musicTicker`
- [x] `field_152352_aC`: `mcThread` -> `thread`
- [x] `field_147124_at`: `framebufferMc` -> `framebuffer`
- [x] `field_71453_ak`: `myNetworkManager` -> `networkManager`
- [x] `field_147695_g`: `mcResourceManager` -> `resourceManager`
- [x] `field_178760_a`: `mcDataDir` -> `gameDir`
