### ISSUE TITLE
Minecraft.textureMapBlocks (+ getter)

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#528]
- [ ] `field_147128_au`: `textureMapBlocks` -> `textureMap`
- [ ] `func_147117_R`: `getTextureMapBlocks` -> `getTextureMap`

There isn't a seperate texture map for blocks and items now, so this should have a more generic name.

**Comment by kashike** [comment]
- [x] `field_147128_au`: `textureMapBlocks` -> `textureMap`
- [x] `func_147117_R`: `getTextureMapBlocks` -> `getTextureMap`

**Comment by InsomniaKitten** [comment]
The field name was not updated
