### ISSUE TITLE
IThreadListener.func_152345_ab: isCallingFromMinecraftThread -> ???

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#529]
This is implemented by both `Minecraft` and `MinecraftServer`, so the name is confusing - there's no one "Minecraft" thread, it could be either the client or server thread, depending on the situation.

It's generally used to establish if the calling thread is the same as the one used to run the scheduled tasks, although sometimes it's called for a specific implementation.

Any thoughts/suggestions for improvement?

**Comment by kashike** [comment]
This is a hard one.
- [ ] `isSameThread`-ish

**Comment by bs2609** [comment]
`isRunningOnSameThread` ?

Still a bit verbose, but clearer.

**Comment by Pokechu22** [comment]
`isRunningOnTickThread`?  Or something like that?

"same" probably isn't ideal (same as what?) - the intention is whether a task can be performed directly rather than being queued.

**Comment by bs2609** [comment]
"same" as the thread invoking the method.

**Comment by williewillus** [comment]
IsOnMainThread?

**Comment by bs2609** [comment]
The problem with those names is that this is an instance method on `IThreadListener`, but none of those properties apply to the `IthreadListener` instance, they apply to the caller.

**Comment by Pokechu22** [comment]
That's a good point.  The original name used "calling", which is probably better - `isCallingFromTickThread` is OK but not great; there's also `isCallingFromSameThread` (but the same problem of "same")

**Comment by bs2609** [comment]
"calling" still has the problem that it's _us_ doing the calling, `wasCalled` would have the 'action' sense correct, but then it's a bit too meta, the method is talking about itself, not the underlying object.

As for the "same" issue, I'd say pretend there was an overload that took a `Thread` parameter - this is the version that defaults that param to `Thread.currentThread()`

**Comment by bs2609** [comment]
I think we can all agree that `isRunningOnTheSameThreadAsTheOneCallingThisMethod` is a bit much, anyway.

**Comment by liach** [comment]
`isOnListenedThread`

**Comment by Pokechu22** [comment]
This method lost its name in 1.14 (it got a new SRG id `func_213162_bc`), and was given the name `isOnExecutionThread` by @williewillus.  I think that name's fine.
