### ISSUE TITLE
IWorldAccess -> IWorldEventHandler

### ISSUE THREAD

**Issue by purpleposeidon** [ModCoderPack/MCPBot-Issues#53]
IWorldAccess suggests some kind of symmetry with IBlockAccess, and is also easy to confusingly put IWA when IBA is meant.

**Comment by LexManos** [comment]
1.9:
net/minecraft/world/IWorldAccess -> IWorldEventListener
Handler is usually for actually being responsible for the function of something, Listener is more along the lines of 'stuff happened do whatever you want' So I went with Listener over Handler.

**Comment by purpleposeidon** [comment]
Sounds good. Thanks!
