### ISSUE TITLE
Profiler cleanup

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#530]
* Methods:
  - [ ] `func_76317_a`: `clearProfiling` -> `reset`
  - [ ] `func_76321_b`: `getProfilingData` -> `getResults`
  - [ ] `func_76318_c`: `endStartSection` -> `nextSection` ?
  - [ ] `func_76322_c`: `getNameOfLastSection` -> `getCurrentSection`

* Fields:
  - [ ] `field_76325_b`: `sectionList` -> `sections`
  - [ ] `field_76326_c`: `timestampList` -> `timestamps`
  - [ ] `field_76327_a`: `profilingEnabled` -> `enabled`
  - [ ] `field_76323_d`: `profilingSection` -> `currentSection`
  - [ ] `field_76324_e`: `profilingMap` -> `sectionTimes`

- [ ] `Profiler$Result.field_76331_c`: `profilerName` -> `section`

**Comment by PaleoCrafter** [comment]
I'm not so sure about `nextSection`. It's just a single noun phrase, there's no verb that'd imply some side effect. I don't have any better suggestion, to be honest, but while sounding a little weird, `endStartSection` captured the method's purpose better.

**Comment by liach** [comment]
`goToSection`

**Comment by kashike** [comment]
I think `endStart` is fine, it accurately describes what it does.
