### ISSUE TITLE
Snooper cleanup

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#531]
* `Snooper`:
  - [x] `func_76463_a`: `startSnooper` -> `start`
  - [ ] `func_76467_g`: `addJvmArgsToSnooper` -> `collectJvmArgs` ?
  - [ ] `func_76471_b`: `addMemoryStatsToSnooper` -> `addMemoryStats`
  - [ ] `func_152768_a`: `addClientStat` -> ??? (see notes)
  - [ ] `func_152767_b`: `addStatToSnooper` -> ??? (see notes)
  - [ ] `func_76468_d`: `isSnooperRunning` -> `isRunning`
  - [x] `func_76470_e`: `stopSnooper` -> `stop`
  - [ ] `field_152773_a`: `snooperStats` -> ??? (see notes)
  - [ ] `field_152774_b`: `clientStats` -> ??? (see notes)
  - [ ] `field_76478_d`: `playerStatsCollector` -> ???
  - [x] `field_76479_e`: `threadTrigger` -> `timer`
  - [ ] `field_76483_h`: `selfCounter` -> `uploadCount` ?

* `ISnooperInfo`:
  - [ ] `func_70000_a`: `addServerStatsToSnooper` -> ??? (see notes, only calls `func_152768_a`)
  - [ ] `func_70001_b`: `addServerTypeToSnooper` -> ??? (see notes, only calls `func_152767_b`)

About 'client' stats:
Nothing to do with clients at all, they exist even for the dedicated server.
The timer task posts the collected data for the "client" stats always, but the "other" stats are only sent the first time.

**Comment by bs2609** [comment]
Also:

* `Minecraft`:
  * `field_71427_U`: `usageSnooper` -> `snooper`
  * `func_71378_E`: `getPlayerUsageSnooper` -> `getSnooper`

* `MinecraftServer`:
  * `field_71307_n`: `usageSnooper` -> `snooper`
  * `func_80003_ah`: `getPlayerUsageSnooper` -> `getSnooper`

**Comment by kashike** [comment]
- [x] `field_71427_U`: `usageSnooper` -> `snooper`
- [x] `func_71378_E`: `getPlayerUsageSnooper` -> `getSnooper`
- [x] `field_71307_n`: `usageSnooper` -> `snooper`
- [x] `func_80003_ah`: `getPlayerUsageSnooper` -> `getSnooper`
- [x] `func_76463_a`: `startSnooper` -> `start`
- [x] `func_76470_e`: `stopSnooper` -> `stop`
- [x] `field_76479_e`: `threadTrigger` -> `timer`
