### ISSUE TITLE
Inventory cleanup

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#533]
* `IInventory`:
  - [ ] `func_70302_i_`: `getSizeInventory` -> `getSize`
  - [ ] `func_70299_a`: `setInventorySlotContents` -> `setSlotContents` / `putStack`
  - [ ] `func_70297_j_`: `getInventoryStackLimit` -> `getMaxStackSize`
  - [ ] `func_174889_b`: `openInventory` -> `onOpen`
  - [ ] `func_174886_c`: `closeInventory` -> `onClose`

* `InventoryBasic:`
  - [ ] `field_70483_a`: `inventoryTitle` -> `title`
  - [ ] `field_70481_b`: `slotsCount` -> `size`
  - [ ] `field_70482_c`: `inventoryContents` -> `contents`
  - [x] `field_70480_d`: `changeListeners` -> `listeners`
  - [x] `func_110134_a`: `addInventoryChangeListener` -> `addListener`
  - [x] `func_110132_b`: `removeInventoryChangeListener` -> `removeListener`

* `InventoryCrafting`:
  - [ ] `field_70466_a`: `stackList` -> `contents`
  - [x] `field_70464_b`: `inventoryWidth` -> `width`
  - [x] `field_174924_c`: `inventoryHeight` -> `height`

- [ ] `InventoryCraftResult.field_70467_a`: `stackResult` -> `result`

* `InventoryEnderChest`:
  - [x] `func_70486_a`: `loadInventoryFromNBT` -> `loadFromNBT` / `readFromNBT`
  - [x] `func_70487_g`: `saveInventoryToNBT` -> `saveToNBT` / `writeToNBT`

- [ ] `InventoryMerchant.field_70474_b`: `slots` -> `contents`

* `Container`:
  - [ ] `field_75153_a`: `inventoryItemStacks` -> `contents`
  - [ ] `field_75151_b`: `inventorySlots` -> `slots`
  - [ ] `field_94537_h`: `dragSlots` -> `draggedSlots`
  - [ ] `field_75148_f`: `playerList` -> `players`
  - [x] `func_75146_a`: `addSlotToContainer` -> `addSlot`
  - [ ] `func_75134_a`: `onContainerClosed` -> `onClose`
  - [ ] `func_193327_a`: `clearContainer` -> `clear`
  - [ ] `func_75129_b`: `getCanCraft` -> `canCraft` ?

* `Slot`:
  - [ ] `func_75220_a`: `onSlotChange` -> ???
  - [ ] `func_75216_d`: `getHasStack` -> `hasStack`
  - [ ] `func_178171_c`: `getSlotTexture` -> `getTextureName`
  - [ ] `func_75218_e`: `onSlotChanged` -> ???
  - [ ] `func_75219_a`: `getSlotStackLimit` -> `getMaxStackSize`
  - [ ] `func_178170_b`: `getItemStackLimit` -> `getMaxStackSize` (#524)

**Comment by InsomniaKitten** [comment]
**`net.minecraft.inventory.IInventory`**

**Further suggestions for name adaptions:**

To follow the existing pattern of `getStackInSlot`:
- [ ] `func_70298_a`: `decrStackSize` -> `removeStackFromSlot`
- [ ] `func_70299_a`: `setInventorySlotContents` -> `setStackInSlot`

What are currently labelled as height and width actually represent the rows and columns of the inventory grid, as seen by its usages in craft matrix inventories, and recipe matching:

- [ ] `func_174923_h`: `getHeight` -> `getRows`/`getSlotRows`
- [ ] `func_174922_i`: `getWidth` -> `getColumns`/`getSlotColumns`

**Comment by williewillus** [comment]
why not get rid of the `stackInSlot` from those? The signature already makes it clear we're dealing with stacks.

as for the second, it'll need changing in many other places as well.

**Comment by InsomniaKitten** [comment]
I'd agree on removing `InSlot`/`FromSlot`, but removing the context of the return type will result in a lot of ambiguity, considering this is an interface that is implemented on other objects. `aTileEntity.get(4)` isn't really ideal, imo.

**Comment by williewillus** [comment]
ah yeah, agreed. the `stack` should stay then

**Comment by Runemoro** [comment]
- [ ] `func_70297_j_`: `getInventoryStackLimit()` -> `getStackSizeLimit()` (this limits the stack **size**, not number of stacks)

Simplify names:
- [ ] `func_70300_a`: `isUsableByPlayer(EntityPlayer player)` -> `isUsableBy(EntityPlayer player)`
- [ ] `func_70301_a`: `getStackInSlot(int index)` -> `getStack(int slot)`
- [ ] `func_94041_b`: `isItemValidForSlot(int index, ItemStack stack)` -> `canAddItems(int slot, ItemStack stack)`
- [ ] `func_70299_a`: `setInventorySlotContents(int index, ItemStack stack)` -> `setSlotContents(int slot, ItemStack stack)`
- [ ] `func_75209_a`: `decrStackSize(int index, int count)` -> `takeStack(int slot, int count)`
- [ ] `func_70304_b`: `removeStackFromSlot(int index)` -> `takeStack(int slot)`
- [ ] `func_70300_a`: `isUsableByPlayer(EntityPlayer player)` -> `isUsableBy(EntityPlayer player)`

**Comment by gegy1000** [comment]
Should `setSlotContents` not follow the same pattern as `getStack` and go with `setStack`? Or could possible go with `putStack` as the inventory is essentially a `Map<int, ItemStack>`

**Comment by kashike** [comment]
- [x] `field_70480_d`: `changeListeners` &rarr; `listeners`
- [x] `func_110134_a`: `addInventoryChangeListener` &rarr; `addListener`
- [x] `func_110132_b`: `removeInventoryChangeListener` &rarr; `removeListener`
- [x] `field_70464_b`: `inventoryWidth` &rarr; `width`
- [x] `field_174924_c`: `inventoryHeight` &rarr; `height`
