### ISSUE TITLE
[MCP // Minecraft Forge] [1.12.x] Recent MCP Snapshots causing Build Errors - 20170918, 20170919, 20170925, 20170926

### ISSUE THREAD

**Issue by CDAGaming** [ModCoderPack/MCPBot-Issues#534]
### Important
Before Submitting this Issue, I have done the required steps towards updating the MCP snapshot for Forge (genPatches, Refreshing Dependencies, cleaning/clearing Cache, and doing full clean build)

## Issue Info:
With the 3 Most recent MCP Snapshots, 0918, 0919, and 0925, Some errors have raised within forge that prevent it from being built. These issues are defined below:

### Snapshot 20170918
`:Forge:compileJavaE:\Forked Repos\Minecraft Repos\CoreFiles\MinecraftForge\src\main\java\net\minecraftforge\common\ForgeHooks.java:783: error: cannot find symbol
        if (gameType.isAdventure())
                    ^
  symbol:   method isAdventure()
  location: variable gameType of type GameType
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
 FAILED`

### Snapshot 20170919
`:Forge:compileJavaE:\Forked Repos\Minecraft Repos\CoreFiles\MinecraftForge\src\main\java\net\minecraftforge\common\ForgeHooks.java:783: error: cannot find symbol
        if (gameType.isAdventure())
                    ^
  symbol:   method isAdventure()
  location: variable gameType of type GameType
E:\Forked Repos\Minecraft Repos\CoreFiles\MinecraftForge\src\main\java\net\minecraftforge\registries\GameData.java:426: error: method does not override or implement a method from a supertype
            @Override public boolean isHidden() { return true; }
            ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
 FAILED`

### Snapshot 20170925
`:Forge:compileJavaE:\Forked Repos\Minecraft Repos\CoreFiles\MinecraftForge\src\main\java\net\minecraftforge\client\ForgeHooksClient.java:274: error: cannot find symbol
                int colour = biome.getSkyColorByTemp(biome.getFloatTemperature(pos));
                                                          ^
  symbol:   method getFloatTemperature(BlockPos)
  location: variable biome of type Biome
E:\Forked Repos\Minecraft Repos\CoreFiles\MinecraftForge\src\main\java\net\minecraftforge\common\BiomeDictionary.java:258: error: method getTemperature in class Biome cannot be applied to given types;
            if (biome.isHighHumidity() && biome.getTemperature() >= 0.9F)
                                               ^
  required: BlockPos
  found: no arguments
  reason: actual and formal argument lists differ in length
E:\Forked Repos\Minecraft Repos\CoreFiles\MinecraftForge\src\main\java\net\minecraftforge\common\BiomeDictionary.java:266: error: method getTemperature in class Biome cannot be applied to given types;
                if (biome.getTemperature() <= 0.2f)
                         ^
  required: BlockPos
  found: no arguments
  reason: actual and formal argument lists differ in length
E:\Forked Repos\Minecraft Repos\CoreFiles\MinecraftForge\src\main\java\net\minecraftforge\common\BiomeDictionary.java:290: error: method getTemperature in class Biome cannot be applied to given types;
        if (biome.getTemperature() > 0.85f)
                 ^
  required: BlockPos
  found: no arguments
  reason: actual and formal argument lists differ in length
E:\Forked Repos\Minecraft Repos\CoreFiles\MinecraftForge\src\main\java\net\minecraftforge\common\BiomeDictionary.java:295: error: method getTemperature in class Biome cannot be applied to given types;
        if (biome.getTemperature() < 0.15f)
                 ^
  required: BlockPos
  found: no arguments
  reason: actual and formal argument lists differ in length
E:\Forked Repos\Minecraft Repos\CoreFiles\MinecraftForge\src\main\java\net\minecraftforge\common\BiomeDictionary.java:341: error: method getTemperature in class Biome cannot be applied to given types;
        if (biome.topBlock != Blocks.SAND && biome.getTemperature() >= 1.0f && biome.getRainfall() < 0.2f)
                                                  ^
  required: BlockPos
  found: no arguments
  reason: actual and formal argument lists differ in length
E:\Forked Repos\Minecraft Repos\CoreFiles\MinecraftForge\src\main\java\net\minecraftforge\common\ForgeHooks.java:783: error: cannot find symbol
        if (gameType.isAdventure())
                    ^
  symbol:   method isAdventure()
  location: variable gameType of type GameType
E:\Forked Repos\Minecraft Repos\CoreFiles\MinecraftForge\src\main\java\net\minecraftforge\registries\GameData.java:426: error: method does not override or implement a method from a supertype
            @Override public boolean isHidden() { return true; }
            ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
8 errors
 FAILED`

## Snapshot 20170926
Same as Snapshot 20170925

If i can get some help in resolving these (If what i mentioned above isn't sufficient for updating MCP within Forge), or if i generally just missed something simple, I'd really appreciate it

PS if this isn't known already, i am very new to working on forge but even still this is the only time ive had major issues with MCP

**Comment by kashike** [comment]
It doesn't look like you've updated your fork of MinecraftForge. Do so.

**Comment by CDAGaming** [comment]
https://github.com/CDAGaming/MinecraftForge/commit/7b03fa03881e2ae64c9a949a33893a63955c7768
Fixed Now, found what i needed to do
