### ISSUE TITLE
Potion cleanup

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#538]
* `Potion`:
  - [ ] `field_111188_I`: `attributeModifierMap` -> `attributeModifiers`
  - [ ] `func_188412_a`: `getPotionById` -> `fromID` / `byID` / `get` ?
  - [ ] `func_188409_a`: `getIdFromPotion` -> `toID` / `getID` ?
  - [ ] `func_180142_b`: `getPotionFromResourceLocation` -> `byName` / `get` ?
  - [ ] `func_76390_b`: `setPotionName` -> `setName`
  - [ ] `func_188410_a`: `getPotionDurationString` -> `getFormattedDuration` / `formatDuration` ?
  - [ ] `func_111184_a`: `registerPotionAttributeModifier` -> `registerAttributeModifier`
  - [ ] `func_111187_a`: `removeAttributesModifiersFromEntity` -> `removeAttributeModifiers`
  - [ ] `func_111186_k`: `getAttributeModifierMap` -> `getAttributeModifiers`
  - [ ] `func_111185_a`: `applyAttributesModifiersToEntity` -> `applyAttributeModifiers`

* `PotionEffect`:
  - [ ] `field_100013_f`: `isPotionDurationMax` -> `isMaxDuration`
  - [ ] `func_82720_e`: `getIsAmbient` -> `isAmbient`
  - [ ] `func_188418_e`: `doesShowParticles` -> `showsParticles`
  - [ ] `func_76454_e`: `deincrementDuration` -> `decrementDuration`
  - [ ] `func_76453_d`: `getEffectName` -> `getName`
  - [ ] `func_82719_a`: `writeCustomPotionEffectToNBT` -> `writeToNBT`
  - [ ] `func_82722_b`: `readCustomPotionEffectFromNBT` -> `readFromNBT`
  - [ ] `func_100012_b`: `setPotionDurationMax` -> `markMaxDuration` ?
  - [ ] `func_100011_g`: `getIsPotionDurationMax` -> `isMaxDuration`

* `PotionType`:
  - [ ] `field_185178_c`: `nextPotionTypeId` -> `nextAvailableID` / `nextID`
  - [ ] `func_185168_a`: `getPotionTypeForName` -> `byName` / `get` ?
  - [ ] `func_185174_b`: `getNamePrefixed` -> `getPrefixedName` / `prefixName` ?

* `SPacketEntityEffect`:
  - [ ] `func_186984_g`: `getIsAmbient` -> `isAmbient`
  - [ ] `func_179707_f`: `doesShowParticles` -> `showsParticles`

**Comment by williewillus** [comment]
getPotionById/getIdFromPotion and co. should not be changed without associated changes in Blocks/Items/all other registry entry classes. The pattern is pretty clear and consistent.

**Comment by PaleoCrafter** [comment]
I'll see about collecting these sorts of changes in a single (meta) issue then, maybe? I've already suggested changing the item/block ones in #524/#521.

**Comment by kashike** [comment]
- [x] `func_82720_e`: `getIsAmbient` &rarr; `isAmbient`
- [x] `func_82719_a`: `writeCustomPotionEffectToNBT` &rarr; `write`
- [x] `func_82722_b`: `readCustomPotionEffectFromNBT` &rarr; `read`
- [x] `field_82724_e`: `isAmbient` &rarr; `ambient`

**Comment by yrsegal** [comment]
`removeAttributeModifiers and `applyAttributeModifiers` are more accurately described as `endEffect` and `beginEffect`, since they aren't solely used for attributes.

**Comment by InsomniaKitten** [comment]
- [ ] `func_193076_bZ`: `getActivePotionMap` -> `getActivePotions`
