### ISSUE TITLE
Material cleanup

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#543]
* `Material`:
  - [x] `field_76235_G`: `canBurn` -> `flammable`
  - [ ] `field_76240_I`: `isTranslucent` -> `translucent`
  - [x] `field_76234_F`: `materialMapColor` -> `mapColor`
  - [ ] `field_76241_J`: `requiresNoTool` -> ???
  - [x] `field_76242_K`: `mobilityFlag` -> `pushBehavior` ?
  - [x] `func_76226_g`: `setBurning` -> `setFlammable`
  - [x] `func_76217_h`: `getCanBurn` -> `isFlammable`
  - [ ] `func_76229_l`: `isToolNotRequired` -> ???
  - [x] `func_186274_m`: `getMobilityFlag` -> `getPushBehavior` ?
  - [ ] `func_76219_n`: `setNoPushMobility` -> `setPushingDestroys` ?
  - [ ] `func_76225_o`: `setImmovableMobility` -> `setPushingBlocked` ?
  - [x] `func_151565_r`: `getMaterialMapColor` -> `getMapColor`

* `Block`:
  - [x] `func_149656_h`: `getMobilityFlag` -> `getPushBehavior` ?

* `IBlockProperties`:
  - [x] `func_185905_o`: `getMobilityFlag` -> `getPushBehavior` ?

Notes:
* `requiresNoTool` and `isToolNotRequired` do work to a degree, but any clearer names would be welcome. (`setRequiresTool` works better, but could also be updated to fit in)
* The comment on `mobilityFlag` also needs updating.

**Comment by kashike** [comment]
- [x] `field_76242_K`: `mobilityFlag` -> `pushReaction`
- [x] `func_186274_m`: `getMobilityFlag` -> `getPushReaction`
- [x] `func_149656_h`: `getMobilityFlag` -> `getPushReaction`
- [x] `func_185905_o`: `getMobilityFlag` -> `getPushReaction`

**Comment by chylex** [comment]
If still needed, idea:   
`requiresNoTool` -> `canDropWithoutTool`

**Comment by kashike** [comment]
- [x] `field_76234_F`: `materialMapColor` -> `color`
- [x] `func_151565_r`: `getMaterialMapColor` -> `getColor`
