### ISSUE TITLE
Colour class cleanup

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#544]
* `MapColor`:
  - [ ] `field_76281_a`: `COLORS` -> `PALETTE` ?
  - [ ] `field_193575_b`: `BLOCK_COLORS` -> `DYE_LOOKUP` ?
  - [ ] `field_76291_p`: `colorValue` -> `color`
  - [ ] `field_76290_q`: `colorIndex` -> `index`
  - [ ] `func_151643_b`: `getMapColor` -> `getVariant` ?
  - [ ] `func_193558_a`: `getBlockColor` -> `fromDyeColor` ?

* `EnumDyeColor`:
  - [ ] `field_193351_w`: `colorValue` -> `color`
  - [ ] `field_193352_x`: `colorComponentValues` -> `colorComponents`
  - [ ] `func_192396_c`: `getDyeColorName` -> `getResourceName` ?
  - [ ] `func_193350_e`: `getColorValue` -> `getColor`
  - [ ] `func_193349_f`: `getColorComponentValues` -> `getColorComponents`

**Comment by liach** [comment]
Is `field_193351_w` a java awt color?

**Comment by Pokechu22** [comment]
It's an int, probably in RGB or ARGB form.

**Comment by liach** [comment]
I'd like an specification on if that field is rgb or argb, either in the field name or javadocs.

**Comment by Pokechu22** [comment]
Done for EnumDyeColor (only javadocs; I can't rename things):

<dl>
<dt><code>field_193351_w</code></dt>
<dd>An int containing the corresponding RGB color for this dye color.</dd>
<dt><code>field_193352_x</code></dt>
<dd>An array containing 3 floats ranging from 0.0 to 1.0: the red, green, and blue components of the corresponding color.</dd>
<dt><code>func_193350_e</code></dt>
<dd>Gets the RGB color corresponding to this dye color.</dd>
<dt><code>func_193349_f</code></dt>
<dd>Gets an array containing 3 floats ranging from 0.0 to 1.0: the red, green, and blue components of the corresponding color.</dd>
</dl>

**Comment by liach** [comment]
Thanks!

**Comment by kashike** [comment]
- [x] `field_193560_ab`: `BLACK_STAINED_HARDENED_CLAY` &rarr; `BLACK_TERRACOTTA`
- [x] `field_193572_X`: `BLUE_STAINED_HARDENED_CLAY` &rarr; `BLUE_TERRACOTTA`
- [x] `field_193573_Y`: `BROWN_STAINED_HARDENED_CLAY` &rarr; `BROWN_TERRACOTTA`
- [x] `field_193570_V`: `CYAN_STAINED_HARDENED_CLAY` &rarr; `CYAN_TERRACOTTA`
- [x] `field_193568_T`: `GRAY_STAINED_HARDENED_CLAY` &rarr; `GRAY_TERRACOTTA`
- [x] `field_193574_Z`: `GREEN_STAINED_HARDENED_CLAY` &rarr; `GREEN_TERRACOTTA`
- [x] `field_193564_P`: `LIGHT_BLUE_STAINED_HARDENED_CLAY` &rarr; `LIGHT_BLUE_TERRACOTTA`
- [x] `field_197655_T`: `LIGHT_GRAY_STAINED_HARDENED_CLAY` &rarr; `LIGHT_GRAY_TERRACOTTA`
- [x] `field_193566_R`: `LIME_STAINED_HARDENED_CLAY` &rarr; `LIME_TERRACOTTA`
- [x] `field_193563_O`: `MAGENTA_STAINED_HARDENED_CLAY` &rarr; `MAGENTA_TERRACOTTA`
- [x] `field_193562_N`: `ORANGE_STAINED_HARDENED_CLAY` &rarr; `ORANGE_TERRACOTTA`
- [x] `field_193567_S`: `PINK_STAINED_HARDENED_CLAY` &rarr; `PINK_TERRACOTTA`
- [x] `field_193571_W`: `PURPLE_STAINED_HARDENED_CLAY` &rarr; `PURPLE_TERRACOTTA`
- [x] `field_193559_aa`: `RED_STAINED_HARDENED_CLAY` &rarr; `RED_TERRACOTTA`
- [x] `field_193561_M`: `WHITE_STAINED_HARDENED_CLAY` &rarr; `WHITE_TERRACOTTA`
- [x] `field_193565_Q`: `YELLOW_STAINED_HARDENED_CLAY` &rarr; `YELLOW_TERRACOTTA`
- [x] `field_151659_e`: `CLOTH` &rarr; `WOOL`

**Comment by bs2609** [comment]
On that note:

- [ ] `field_151654_J`: `OBSIDIAN` -> `SPRUCE` ?

I'll let this excerpt from the vanilla wiki speak for itself here:

![image](https://user-images.githubusercontent.com/1447117/52103100-f03b6280-25db-11e9-9f87-9e81b7ddb812.png)
