### ISSUE TITLE
Entity package changes?

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#545]
1. These entity classes don't implement `IMob`, and aren't really hostile.
 Requesting a move from `entity.monster` to `entity.passive` for the following:
 
   * `EntityGolem`
   * `EntityIronGolem`
   * `EntityPolarBear`
   * `EntitySnowman`

2. These could do with a move from `entity` to `entity.item`:

   * `EntityHanging`
   * `EntityLeashKnot`

   Conversely, `EntityXpOrb` could do with moving from `entity.item` to `entity`.

3. The following could go in a new `entity.npc` package.

   * `EntityVillager`
   * `IMerchant`
   * `INpc`
   * `NpcMerchant`

4. Possibly having a `entity.item.minecart` sub-package for all the minecart classes ?

5. `IProjectile` seems to fit better in `entity.projectile` rather than just `entity`.

**Comment by liach** [comment]
Be careful that such package moves might hurt code compiles, for some of the package private methods may be broken in such renames.
