### ISSUE TITLE
ChatAllowedCharacters -> SharedConstants ?

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#547]
It's used for more text than just chat.

Possibly just `AllowedCharacters` would be better, although the references to Netty's `ResourceLeakDetector` make me feel like I'm still missing something here.

**Comment by kashike** [comment]
I'd consider this to be the non-realms `SharedConstants` - everything else is just inlined so they aren't in here (protocol version, game version string, etc).

**Comment by Pokechu22** [comment]
Good point.  The line number table indicates a lot of blank space for other constants.

* Line 30: `NETTY_LEAK_DETECTION`
* Line 57: Body of `isAllowedCharacter` (actual method would presumably occupy lines 56-58)
* Line 60: `ILLEGAL_STRUCTURE_CHARACTERS`
* Line 64: `ILLEGAL_FILE_CHARACTERS`
* Lines 73, 75, 76, 77, and 81: Body of `filterAllowedCharacters` (actual method would presumably occupy lines 72-82)
* Line 85: `static` block applied to `ResourceLeakDetector` (actual block would presumably occupy lines 84-86)

**Comment by kashike** [comment]
Further backed up by: `public static char[] ILLEGAL_FILE_CHARACTERS = ChatAllowedCharacters.ILLEGAL_FILE_CHARACTERS;`.

My guess is that `RealmsSharedConstants` exists so that the un-obfuscated fields can be used in the realms lib, just like the rest of the `net.minecraft.realms` package.

**Comment by kashike** [comment]
- [x] `net/minecraft/util/ChatAllowedCharacters` → `net/minecraft/util/SharedConstants`
