### ISSUE TITLE
WorldClient.showBarrierParticles / doVoidFogParticles

### ISSUE THREAD

**Issue by tterrag1098** [ModCoderPack/MCPBot-Issues#551]
These method names are much too specific, they have almost nothing to do with void/barrier particles other than that there is a bit of hardcode in them to spawn those. Their main purpose is to spawn all randomDisplayTick particles.

- [ ] `func_184153` in `WorldClient`: `showBarrierParticles` -> `spawnRandomParticlesInRange`

This may be a bit verbose, but it is the more specific version of

- [ ] `func_73029_E ` in `WorldClient`: `doVoidFogParticles` -> `spawnRandomParticles`

These are just off the top of my head, I'm aware they aren't perfect. So, suggestions?

**Comment by tterrag1098** [comment]
Additionally, I think `p_184153_4_` should be renamed from "offset" to "range", as it controls the range of the random value chosen to spawn particles at.

- [ ] `p_184153_4_` in `WorldClient.showBarrierParticles`: `offset` -> `range`

**Comment by kashike** [comment]
#703
