### ISSUE TITLE
Item.hasSubtypes (field_77787_bX) and related

### ISSUE THREAD

**Issue by PaleoCrafter** [ModCoderPack/MCPBot-Issues#553]
This suggestion is somewhat subjective, but I've encountered devs setting this to `true` without actually utilizing metadata, which could lead to errors (recipe JSONS requiring a `data` property, for instance). Their reasoning for using it was that they declared 'subtypes' via NBT data. If you look at the field's/methods' usages, you can clearly see that it was intended by Mojang to be used in conjunction with metadata only.

- [ ] `field_77787_bX` in `net.minecraft.item.Item`: `hasSubtypes` -> `usesMetadata`/`hasMetadata`
- [ ] `func_77627_a` in `net.minecraft.item.Item`: `setHasSubtypes` -> `setUsesMetadata`/`setHasMetadata`/`useMetadata`
- [ ] `func_77614_k` in `net.minecraft.item.Item`: `getHasSubtypes` -> `usesMetadata`/`hasMetadata`
- [ ] `func_77981_g` in `net.minecraft.item.ItemStack`: `getHasSubtypes` -> `usesMetadata`/`hasMetadata`

**Comment by bs2609** [comment]
#519 is somewhat related, as is the point that this will also likely change in 1.13.

**Comment by kashike** [comment]
No longer valid.
