### ISSUE TITLE
Move EntityTracker to server.management?

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#554]
It's a bit out of place in the `entity` package, although it is entity-related.
`PlayerChunkMap` is probably most similar in function, so perhaps it should live in `server.management`?

Any thoughts on the following?

* `entity.EntityTracker` -> `server.management.EntityTracker`
* `entity.EntityTrackerEntry` -> `server.management.EntityTrackerEntry`

**Comment by kashike** [comment]
I think it should be moved to the `world` package somewhere - it's used by worlds, not the server directly.

**Comment by bs2609** [comment]
In any case, I think it should be located alongside `PlayerChunkMap`, the classes have similar functionality and are used in generally the same way.
