### ISSUE TITLE
World.getChunkFrom(Block/Chunk)Coords

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#557]
As these methods are distinguishable by their signature, we don't need the extra "From..." in the names to tell them apart.

* `func_175726_f`: `getChunkFromBlockCoords` -> `getChunk`
* `func_72964_e`: `getChunkFromChunkCoords` -> `getChunk`

**Comment by kashike** [comment]
- [x] `func_175726_f`: `getChunkFromBlockCoords` -> `getChunk`
- [x] `func_72964_e`: `getChunkFromChunkCoords` -> `getChunk`

**Comment by asiekierka** [comment]
I'm not sure if I'm a fan of this change. One of those operates on block positions, the other on chunk positions. I have a (possibly unfounded) fear this might get a bit more confusing now?

**Comment by bs2609** [comment]
We're not completely there yet, but I think `getChunk(BlockPos)` and `getChunk(ChunkPos)` would make that pretty clear.
