### ISSUE TITLE
typo Peice (instead of Piece)

### ISSUE THREAD

**Issue by NeunEinser** [ModCoderPack/MCPBot-Issues#559]
The inner class "Peice" of StructureMineshaftPieces is probably a typo and should be called Piece

`net/minecraft/world/gen/structure/StructureMineshaftPieces$Peice` -> `net/minecraft/world/gen/structure/StructureMineshaftPieces$Piece`

**Comment by kashike** [comment]
- [x] `net/minecraft/world/gen/structure/StructureMineshaftPieces$Peice`→ `net/minecraft/world/gen/structure/StructureMineshaftPieces$Piece`
