### ISSUE TITLE
Shader and ShaderManager class names are confusing

### ISSUE THREAD

**Issue by Barteks2x** [ModCoderPack/MCPBot-Issues#560]
`ShaderManager` seems to actually be the shader itself, and contains all the data relevant to shader. And `Shader` class seems to be something that allows to render a framebuffer using shader.

So my proposed name changes are:
 * `Shader` -> `ShaderFramebufferRenderer`
 * `ShaderManager` -> `Shader`

**Comment by kashike** [comment]
@williewillus https://github.com/ModCoderPack/MCPBot-Issues/issues/378#issue-214253186 anything you want to suggest?

**Comment by williewillus** [comment]
Barteks's renames look good

I also propose `ShaderLoader` -> `ShaderFile`. It represents a loaded FSH or VSH file (with an enum field distinguishing which it is) and manages the int gl id associated with it. It's owned by `ShaderManager` instances which is really a `Shader`, which makes sense to own `ShaderFile`s.

I also propose `ShaderLinkHelper` -> `ShaderHelper`. It doesn't just do linking it does creating and deleting too. Also the horrible singleton field/method names in that class need to be renamed: 

* `field_148079_b`: `staticShaderLinkHelper` -> `INSTANCE`
* `func_148076_a`: `setNewStaticShaderLinkHelper` -> `recreateInstance`
* `func_148074_b`: `getStaticShaderLinkHelper` -> `getInstance`

**Comment by williewillus** [comment]
I just ran across this again, so bumping.
I think `Shader` can more succintly be called `ShaderPass`. It holds two framebuffers and performs some graphical operation on it. `ShaderManager` has a list of these, and they're parsed from json with the key `pass`.

So:
* `Shader` -> `ShaderPass`
* `ShaderManager` -> `Shader`

plus the two in the previous comment

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
