### ISSUE TITLE
PropertyHelper -> AbstractProperty

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#562]
This is an abstract implementation of a block state property, not a block state property helper.

`net.minecraft.block.properties.PropertyHelper` -> `net.minecraft.block.properties.AbstractProperty`

**Comment by bs2609** [comment]
I'd be happy with `AbstractProperty`, but I think `PropertyBase` fits more with the naming of similar other classes.

**Comment by kashike** [comment]
- [x] `net/minecraft/block/properties/PropertyHelper` → `net/minecraft/block/properties/AbstractProperty`
