### ISSUE TITLE
NetHandlerPlayServer Keepalive fields

### ISSUE THREAD

**Issue by zachbr** [ModCoderPack/MCPBot-Issues#563]
- [ ] `net.minecraft.network.NetHandlerPlayServer` `field_194402_f` -> `lastKeepAliveTime`
- [ ] `net.minecraft.network.NetHandlerPlayServer` `field_194403_g` -> `pendingKeepAlive`
- [ ] `net.minecraft.network.NetHandlerPlayServer` `field_194404_h` -> `keepAliveId`

Edit: I've updated the suggested name for `field_194402_f` to the one suggested by williewillus, it's a better fit

**Comment by williewillus** [comment]
`lastKeepAliveTime` for field_194402_f? `keepAliveLastSent` implies it's the last ID sent to the client but it's actually the last timestamp the client successfully replied to the server's keepalive.

**Comment by kashike** [comment]
These will be available to name when the bot is updated to 1.12.2 - @bspkrs?
