### ISSUE TITLE
p_77475_2_ : t > y

### ISSUE THREAD

**Issue by TechnicianLP** [ModCoderPack/MCPBot-Issues#564]
- [ ] `p_77475_2_` in `OpenGlHelper.setLightmapTextureCoords`: `t` -> `y`

**Comment by kashike** [comment]
https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glMultiTexCoord.xml

**Comment by bs2609** [comment]
In that case:
* `p_77475_1_`: `x` -> `s`

**Comment by kashike** [comment]
nope.
> ERROR: New parameter name is reserved for use by the JAD-style local field renaming process (p_77475_1_ => s).

**Comment by bs2609** [comment]
If we can't have `s, t`, I'd rather have `x, y` than `x, t`.

**Comment by kashike** [comment]
done.
