### ISSUE TITLE
CreativeTabs cleanup

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#565]
* Fields:
  - [x] `field_78033_n`: `tabIndex` -> `index`
  - [ ] `field_78034_o`: `tabLabel` -> `name`
  - [x] `field_151245_t`: `iconItemStack` -> `icon`

* Methods:
  - [x] `func_78021_a`: `getTabIndex` -> `getIndex`
  - [ ] `func_78013_b`: `getTabLabel` -> `getName` ?
  - [x] `func_78024_c`: `getTranslatedTabLabel` -> `getTranslationKey`
  - [x] `func_151244_d`: `getIconItemStack` -> `getIcon`
  - [x] `func_78016_d`: `getTabIconItem` -> `createIcon`
  - [ ] `func_78019_g`: `drawInForegroundOfTab` -> `drawTitle` ?
  - [x] `func_78017_i`: `shouldHidePlayerInventory` -> `hasScrollbar`
  - [x] `func_78020_k`: `getTabColumn` -> `getColumn`
  - [x] `func_78023_l`: `isTabInFirstRow` -> `isOnTopRow`
  - [ ] `func_78018_a`: `displayAllRelevantItems` -> `getRelevantItems`

**Comment by bs2609** [comment]
Also, following #444:
* `field_78032_a`: `CREATIVE_TAB_ARRAY` -> `ITEM_GROUPS`

**Comment by kashike** [comment]
- [x] `field_78033_n`: `tabIndex` -> `index`
- [x] `field_151245_t`: `iconItemStack` -> `icon`
- [x] `func_78021_a`: `getTabIndex` -> `getIndex`
- [x] `func_78024_c`: `getTranslatedTabLabel` -> `getTranslationKey`
- [x] `func_151244_d`: `getIconItemStack` -> `getIcon`
- [x] `func_78016_d`: `getTabIconItem` -> `createIcon`
- [x] `func_78020_k`: `getTabColumn` -> `getColumn`
- [x] `func_78017_i`: `shouldHidePlayerInventory` -> `hasScrollbar`
- [x] `func_78023_l`: `isTabInFirstRow` -> `isOnTopRow`

**Comment by kashike** [comment]
`name` vs `title` vs `label`?

**Comment by combusterf** [comment]
One preference for label
