### ISSUE TITLE
CrashReport cleanup

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#566]
* `CrashReport`:
  - [ ] `field_85061_c`: `systemDetailsCategory` -> `systemDetails`
  - [ ] `field_71512_c`: `crashReportSections` -> `categories`
  - [ ] `field_71510_d`: `crashReportFile` -> `file`
  - [ ] `field_85059_f`: `firstCategoryInCrashReport` -> ???
  - [ ] `func_71505_b`: `getCrashCause` -> `getCause`
  - [ ] `func_71506_a`: `getSectionsInStringBuilder` -> `appendTo`
  - [ ] `func_71498_d`: `getCauseStackTraceOrString` -> `getCauseAsString` ?
  - [ ] `func_147149_a`: `saveToFile` -> `save`

* `CrashReportCategory`:
  - [x] `func_71507_a`: `addCrashSection` -> `addEntry` ?
  - [ ] `func_71499_a`: `addCrashSectionThrowable` -> `addEntry` ?
  - [ ] `func_85073_a`: `getPrunedStackTrace` -> ???
  - [ ] `func_85069_a`: `firstTwoElementsOfStackTraceMatch` -> `stackTraceStartsWith`
  - [ ] `func_85070_b`: `trimStackTraceEntriesFromBottom` -> `trimStackTrace`
  - [ ] `func_85072_a`: `appendToStringBuilder` -> `appendTo`

**Comment by sokratis12GR** [comment]
what about `field_85059_f`: `firstCategoryInCrashReport` -> `firstCategoryReported` or just `firstCategory` ?

**Comment by bs2609** [comment]
The problem with that name is that it applies to the crash report as a whole - talking about a category doesn't make sense. It also can still be true if the report already contains categories, so it's not about anything being "first".

Something like `updateStackTraces`/`checkStackTraces` would be more correct, although it would be nice to have a name that also covered the "why" a bit.

**Comment by kashike** [comment]
- [x] `func_71507_a`: `addCrashSection` &rarr; `addDetail`
