### ISSUE TITLE
BlockChest inventory methods

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#568]
The names of these `BlockChest` methods and parameters are suboptimal:

- [ ] `func_180676_d`: `getLockableContainer` &rarr; `getInventory`

     Method takes the position and gets the chest inventory, following blocked checks.  Yes, it returns an `ILockableContainer`, but that's an `IInventory`, not a `Container` (these classes will need a cleanup at some point, but that'll be later)
- [ ] `func_189418_a`: `getContainer` &rarr; `getInventory`

     Does the same thing as above, but has an additional Boolean parameter controlling if blocked checks should run.
- [ ] `p_189418_3_`: `allowBlocking` &rarr; `ignoreBlocking`

    The current name is the inverse of the actual purpose.  The method contains this code:

    ```java
    if (!allowBlocking && this.isBlocked(worldIn, pos)) {
        return null;
    } else {
        // ...
    }
    ```

    If the parameter is true, then the check is skipped - the opposite of its current name.

    Note that there is a bug with this parameter and it isn't checked in both cases - see [MC-99321](https://bugs.mojang.com/browse/MC-99321).

I have already updated the javadocs.

**Comment by ryantheleach** [comment]
ILockableContainer => ILockableInventory ?

**Comment by Pokechu22** [comment]
Renaming that would make sense, but I recall there being a few other things (e.g. `ContainerHorseChest`) that are named incorrectly in a similar way which I'd like to bundle into a different report.

**Comment by Pokechu22** [comment]
[MC-99321](https://bugs.mojang.com/browse/MC-99321) has been marked as fixed, so just a reminder to myself to update the Javadoc for `p_189418_3_` once 1.13 comes out.
