### ISSUE TITLE
Minecart interpolation fields

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#569]
These aren't redundant position/rotation fields, but rather used for interpolation clientside.

Rename them to match their counterparts in `EntityLivingBase` (they're used in the exact same manner for interpolation in minecart.onUpdate/elb.onLivingUpdate)

- [ ] `field_70511_i` in `net.minecraft.entity.item.EntityMinecart`: `minecartX` -> `interpTargetX`
- [ ] `field_70509_j` in `net.minecraft.entity.item.EntityMinecart`: `minecartY` -> `interpTargetY`
- [ ] `field_70514_an` in `net.minecraft.entity.item.EntityMinecart`: `minecartZ` -> `interpTargetZ`
- [ ] `field_70513_ap` in `net.minecraft.entity.item.EntityMinecart`: `minecartPitch` -> `interpTargetPitch`
- [ ] `field_70512_ao` in `net.minecraft.entity.item.EntityMinecart`: `minecartYaw` -> `interpTargetYaw`

The minecart version of elb.newPosRotationIncrements is called `turnProgress`, which I think is a better name, so it's not included here.

**Comment by bs2609** [comment]
From #427, `interpTicks` instead of `turnProgress`?
