### ISSUE TITLE
Unexpected NetHandlerPlayClient behaviour

### ISSUE THREAD

**Issue by Vonr** [ModCoderPack/MCPBot-Issues#570]
![2017-11-17](https://user-images.githubusercontent.com/24369412/32939383-3dffb336-cbba-11e7-96df-c1439b5261c2.png)
![2017-11-17 5](https://user-images.githubusercontent.com/24369412/32939354-2c1c4418-cbba-11e7-8e06-df73cd3dbde2.png)
![2017-11-17 1](https://user-images.githubusercontent.com/24369412/32939356-2f67c17e-cbba-11e7-9fd7-140ed5b04578.png)
![2017-11-17 2](https://user-images.githubusercontent.com/24369412/32939360-3358ca58-cbba-11e7-9633-61dcbc895336.png)
![2017-11-17 3](https://user-images.githubusercontent.com/24369412/32939366-35b8b362-cbba-11e7-9743-7630f426f690.png)
![2017-11-17 4](https://user-images.githubusercontent.com/24369412/32939370-37ca9f94-cbba-11e7-82e7-b6fe0aa8ee2d.png)

**Comment by diesieben07** [comment]
How is this an issue with MCP?
This is you not being able to program Java.
