### ISSUE TITLE
func_191824_a in GuiAdvancement: getAdvancementProgress -> setAdvancementProgress

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#571]
- [ ] `func_191824_a` in `GuiAdvancement`: `getAdvancementProgress` -> `setAdvancementProgress`

... [yeah](https://i.gyazo.com/e88029e5e952236269b1b26849b494ce.png)

**Comment by kashike** [comment]
- [x] `func_191824_a`: `getAdvancementProgress` → `setAdvancementProgress`
