### ISSUE TITLE
NetworkManager$InboundHandlerTuplePacketListener -> NetworkManager$QueuedPacket

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#577]
Not sure why this mouthful of words exists when the class is simply a Packet + listeners that fire when sending is complete. Its only reason for existing is storage on a queue before it gets sent.

so 
`NetworkManager$InboundHandlerTuplePacketListener` -> `NetworkManager$QueuedPacket`

**Comment by bs2609** [comment]
Could this be added to #514?

**Comment by kashike** [comment]
https://github.com/MinecraftForge/MCPConfig/commit/193437679055c44272076c6ddf94b6f65178d57d
