### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by zdv1g** [ModCoderPack/MCPBot-Issues#578]
![screenshot_4](https://user-images.githubusercontent.com/8127249/33613231-20e2b54e-d9e5-11e7-8391-20dba9b3d196.png)
![screenshot_3](https://user-images.githubusercontent.com/8127249/33613244-2a259f4a-d9e5-11e7-9797-a366ac117de8.png)

**Comment by kashike** [comment]
It's up here.

**Comment by zdv1g** [comment]
![screenshot_5](https://user-images.githubusercontent.com/8127249/33613410-9cf8fa30-d9e5-11e7-9f54-1127380a4a18.png)
DNS?

**Comment by zdv1g** [comment]
![screenshot_6](https://user-images.githubusercontent.com/8127249/33613695-51428696-d9e6-11e7-9b19-3027c6f3083c.png)
!?!??!?!!?

**Comment by covers1624** [comment]
Fine over here in AU..
![](http://ss.covers1624.net/tao43vq.png)

**Comment by liach** [comment]
Use a vpn.

**Comment by bspkrs** [comment]
As best I can tell it seems that your ISP is jacking up the DNS lookup.

**Comment by zdv1g** [comment]
104.28.20.72 is banned
![screenshot_1](https://user-images.githubusercontent.com/8127249/33769370-09b392e6-dc3b-11e7-8aeb-62faa9dd3b98.png)
