### ISSUE TITLE
World skylightSubtracted field/methods

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#580]
- [ ] `field_73008_k`: `skylightSubtracted` -> `skylightReduction`
- [ ] `func_175657_ab`: `getSkylightSubtracted` -> `getSkylightReduction`
- [ ] `func_175692_b`: `setSkylightSubtracted` -> `setSkylightReduction`
- [ ] `func_72967_a`: `calculateSkylightSubtracted` -> `calculateSkylightReduction`

Think `skylightReduction` is a bit clearer than `skylightSubtracted` here.

**Comment by gabizou** [comment]
Considering we're in ripe age for changing this in 1.13, thoughts on s/subtracted/reduction ? I'd be ok with it, since the methods would be clearer to read.
