### ISSUE TITLE
ItemCloth -> ItemDyed/ItemDyeable ?

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#582]
Not "cloth", an `ItemBlock` subclass used for any dyeable items:
```java
registerItemBlock(Blocks.CONCRETE, (new ItemCloth(Blocks.CONCRETE)).setUnlocalizedName("concrete"));
```

`ItemColored` is taken, currently used more in the sense of having a colour multiplier (used by grass, tallgrass, vines, and extended by lily pads), though it could also be changed.

Any thoughts?

**Comment by kashike** [comment]
This is no longer a class in 1.13.
