### ISSUE TITLE
Minecraft.field_110452_an: metadataSerializer_ -> metadataSerializer

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#583]
As title.

**Comment by Pokechu22** [comment]
Just saw this too, :+1:

No idea why it's like that; it's been like that since 1.6 (which was when the class was added with resource packs, as far as I can tell).

**Comment by kashike** [comment]
- [x] `field_110452_an`: `metadataSerializer_` -> `metadataSerializer`
