### ISSUE TITLE
BlockContainer -> ???

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#585]
Used as a base class for most vanilla blocks with tile entities.

The "container" name doesn't do much good here, can we come up with something better?

Perhaps `BlockTEBase`?

**Comment by williewillus** [comment]
Naming it that would encourage it's use as a TE base class though, a role it doesn't serve very well for modded

**Comment by liach** [comment]
`BlockInventory`. It is blocks with tile entities that support inventories, not necessarily all tile entities.

**Comment by bs2609** [comment]
It isn't just used for blocks with inventories, though.

**Comment by liach** [comment]
Then we can name it `TileEntityCarrierBlock` or `TileBlock` (based on 1.13 new naming scheme)

**Comment by AlexIIL** [comment]
Perhaps ````BlockSimpleTile```` or ````BlockVanillaTileEntity````?

@liach From what I can tell from #584 block names aren't changing. (Unless #576 was resolved differently somewhere I haven't seen yet).

**Comment by covers1624** [comment]
+1 on `BlockVanillaTileEntity`

**Comment by liach** [comment]
I'd support `BlockTEBase` then. This name is the shortest. Including `Vanilla` in the class name sounds a little bit weird.

**Comment by bs2609** [comment]
See also #83.

**Comment by liach** [comment]
Given we use suffix now, do we say `TileEntityBlock` or just `EntityBlock`

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
