### ISSUE TITLE
IWorldNameable → INameable, and the related methods in IWorldNameable and ICommandSender

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#588]
The first change:

- [ ] `IWorldNameable` &rarr; `INameable`.  This has no relation to worlds, and is used for e.g. inventories (`IInventory`), which don't even have a reference to the world (excluding block entities).  More specifically, this applies to:

    * `EntityMinecart` (likely this inheritance is leftover from the days when there was a single minecart class so that `EntityMinecartContainer` (chests and hoppers) could be named &mdash; however, `IWorldNameable` didn't exist in 1.5 when this change was done so that's odd)
        * This probably explains issues like [MC-41893](https://bugs.mojang.com/browse/MC-41893 "[MC-41893] Breaking a Minecart with Command Block in creative drops a Minecart after reloading the world.")
    * `TileEntityBanner` for [its (useless) custom name](https://minecraft.gamepedia.com/Banner#Renaming)
    * `IInteractionObject` for inventory titles (this interface is something I'll want to clean up later)
    * `IInventory` for inventory titles (also to clean up)

    Another name that I thought of might be `INamableInventory`, but due to banners and some of the other stuff that seems like a bad name to me (plus `interface IInventory extends INameableInventory` seems like a horrible idea).

    This should also be repackaged into `net.minecraft.inventory` or `net.minecraft.tileentity` (or perhaps somewhere else).

That change looks nice and innocuous.  Unfortunately, I'd also like to request some cleanup for the methods.  _This_ is actually a pain, because of #14 &mdash; <code>func_70005_c_</code> is both `IWorldNameable.getName()` and `ICommandSender.getName()`... which means that it's also `Entity.getName()`.  Same deal with the other methods in ICommandSender.  (Maybe the `_` on the end of the method's SRG id/obf name signifies that, I'm not 100% sure).  Oh, and these methods are awful and inconsistent.

Anyways, here are some proposed javadocs which I'd like feedback on (both the source and a formatted version; note that the links in the formatted version do not go anywhere and are just provided to show where valid links will be):

- [ ] `func_70005_c_`: `IWorldNameable.getName()`, `ICommandSender.getName()`, `Entity.getName()`:

    ```
    Gets the name of this thing.  This method has slightly different behavior depending on the interface (for <a href="https://github.com/ModCoderPack/MCPBot-Issues/issues/14">technical reasons</a> the same method is used for both IWorldNameable and ICommandSender):

    <dl>
    <dt>{@link net.minecraft.inventory.INameable#getName() INameable.getName()}</dt>
    <dd>Returns the name of this inventory.  If this {@linkplain net.minecraft.inventory#hasCustomName() has a custom name} then this <em>should</em> be a direct string; otherwise it <em>should</em> be a valid translation string.</dd>
    <dd>However, note that <strong>the translation string may be invalid</strong>, as is the case for {@link net.minecraft.tileentity.TileEntityBanner TileEntityBanner} (always returns nonexistent translation code <code>banner</code> without a custom name), {@link net.minecraft.block.BlockAnvil.Anvil BlockAnvil$Anvil} (always returns <code>anvil</code>), {@link net.minecraft.block.BlockWorkbench.InterfaceCraftingTable BlockWorkbench$InterfaceCraftingTable} (always returns <code>crafting_table</code>), {@link net.minecraft.inventory.InventoryCraftResult InventoryCraftResult} (always returns <code>Result</code>) and the {@link net.minecraft.entity.item.EntityMinecart EntityMinecart} family (uses the entity definition).  This is not an exaustive list.</dd>
    <dd>In general, this method should be safe to use on tile entities that implement IInventory.</dd>
    <dt>{@link net.minecraft.command.ICommandSender#getName() ICommandSender.getName()} and {@link net.minecraft.entity.Entity#getName() Entity.getName()}</dt>
    <dd>Returns a valid, displayable name (which may be localized).  For most entities, this is the translated version of its translation string (obtained via {@link net.minecraft.entity.EntityList#getEntityString EntityList.getEntityString}).</dd>
    <dd>If this entity has a custom name set, this will return that name.</dd>
    <dd>For some entities, this will attempt to translate a nonexistent translation string; see <a href="https://bugs.mojang.com/browse/MC-68446">MC-68446</a>.  For {@linkplain net.minecraft.entity.player.EntityPlayer#getName() players} this returns the player's name.  For {@linkplain net.minecraft.entity.passive.EntityOcelot ocelots} this may return the translation of <code>entity.Cat.name</code> if it is tamed.  For {@linkplain net.minecraft.entity.item.EntityItem#getName() item entities}, this will attempt to return the name of the item in that item entity.  In all cases other than players, the custom name will overrule this.</dd>
    <dd>For non-entity command senders, this will return some arbitrary name, such as "Rcon" or "Server".</dd>
    </dl>
    ```

    <blockquote>
    Gets the name of this thing.  This method has slightly different behavior depending on the interface (for <a href="https://github.com/ModCoderPack/MCPBot-Issues/issues/14">technical reasons</a> the same method is used for both IWorldNameable and ICommandSender):

    <dl>
    <dt><a href="#">INameable.getName()</a></dt>
    <dd>Returns the name of this inventory.  If this <a href="#">has a custom name</a> then this <em>should</em> be a direct string; otherwise it <em>should</em> be a valid translation string.</dd>
    <dd>However, note that <strong>the translation string may be invalid</strong>, as is the case for <a href="#">TileEntityBanner</a> (always returns nonexistent translation code <code>banner</code> without a custom name), <a href="#">BlockAnvil$Anvil</a> (always returns <code>anvil</code>), <a href="#">BlockWorkbench$InterfaceCraftingTable</a> (always returns <code>crafting_table</code>), <a href="#">InventoryCraftResult</a> (always returns <code>Result</code>) and the <a href="#">EntityMinecart</a> family (uses the entity definition).  This is not an exaustive list.</dd>
    <dd>In general, this method should be safe to use on tile entities that implement IInventory.</dd>
    <dt><a href="#">ICommandSender.getName()</a> and <a href="#">Entity.getName()</a></dt>
    <dd>Returns a valid, displayable name (which may be localized).  For most entities, this is the translated version of its translation string (obtained via <a href="#">EntityList.getEntityString</a>).</dd>
    <dd>If this entity has a custom name set, this will return that name.</dd>
    <dd>For some entities, this will attempt to translate a nonexistent translation string; see <a href="https://bugs.mojang.com/browse/MC-68446">MC-68446</a>.  For <a href="#">players</a> this returns the player's name.  For <a href="#">ocelots</a> this may return the translation of <code>entity.Cat.name</code> if it is tamed.  For <a href="#">item entities</a>, this will attempt to return the name of the item in that item entity.  In all cases other than players, the custom name will overrule this.</dd>
    <dd>For non-entity command senders, this will return some arbitrary name, such as "Rcon" or "Server".</dd>
    </dl>
    </blockquote>

- [ ] `func_145818_k_`: `IWorldNameable.hasCustomName()`, `Entity.hasCustomName()`

    ```
    Checks if this thing has a custom name.  This method has slightly different behavior depending on the interface (for <a href="https://github.com/ModCoderPack/MCPBot-Issues/issues/14">technical reasons</a> the same method is used for both IWorldNameable and Entity):

    <dl>
    <dt>{@link net.minecraft.inventory.INameable#hasCustomName() INameable.hasCustomName()}</dt>
    <dd>If true, then {@link #getName()} probably returns a preformatted name; otherwise, it probably returns a translation string.  However, exact behavior varies.</dd>
    <dt>{@link net.minecraft.entity.Entity#hasCustomName() Entity.hasCustomName()}</dt>
    <dd>If true, then {@link net.minecraft.entity.Entity#getCustomNameTag() Entity.getCustomNameTag()} will return a non-empty string, which will be used by {@link #getName()}.</dd>
    </dl>
    ```

    <blockquote>
    Checks if this thing has a custom name.  This method has slightly different behavior depending on the interface (for <a href="https://github.com/ModCoderPack/MCPBot-Issues/issues/14">technical reasons</a> the same method is used for both IWorldNameable and Entity):

    <dl>
    <dt><a href="#">INameable.hasCustomName()</a></dt>
    <dd>If true, then <a href="#">getName()</a> probably returns a preformatted name; otherwise, it probably returns a translation string.  However, exact behavior varies.</dd>
    <dt><a href="#">Entity.hasCustomName()</a></dt>
    <dd>If true, then <a href="#">Entity.getCustomNameTag()</a> will return a non-empty string, which will be used by <a href="#">getName()</a>.</dd>
    </dl>
    </blockquote>

- [ ] `func_145748_c_`: `IWorldNameable.getDisplayName()`, `ICommandSender.getDisplayName()`, `Entity.getDisplayName()`:

    This maybe could use a rename, but I don't know what it should be named &mdash; something like `getNameComponent`.

    ```
    Returns a displayable component representing this thing's name.  This method should be implemented slightly differently depending on the interface (for <a href="https://github.com/ModCoderPack/MCPBot-Issues/issues/14">technical reasons</a> the same method is used for both IWorldNameable and ICommandSender), but unlike {@link #getName()} this method will generally behave sanely.

    <dl>
    <dt>{@link net.minecraft.inventory.INameable#getDisplayName() INameable.getDisplayName()}</dt>
    <dd>A normal component.  Might be a translation component or a text component depending on the context.  Usually implemented as:</dd>
    <dd><pre><code>return this.{@link net.minecraft.inventory.INameable#hasCustomName() hasCustomName()} ? new TextComponentString(this.{@link #getName()}) : new TextComponentTranslation(this.{@link #getName()});</code></pre></dd>
    <dt>{@link net.minecraft.command.ICommandSender#getDisplayName() ICommandSender.getDisplayName()} and {@link net.minecraft.entity.Entity#getDisplayName() Entity.getDisplayName()}</dt>
    <dd>For most entities, this returns the result of {@link #getName()}, with {@linkplain net.minecraft.scoreboard.ScorePlayerTeam#formatPlayerName scoreboard formatting} and a {@linkplain net.minecraft.entity.Entity#getHoverEvent special hover event}.</dd>
    <dd>For non-entity command senders, this will return the result of {@link #getName()} in a text component.</dd>
    </dl>
    ```

    <blockquote>
    Returns a displayable component representing this thing's name.  This method should be implemented slightly differently depending on the interface (for <a href="https://github.com/ModCoderPack/MCPBot-Issues/issues/14">technical reasons</a> the same method is used for both IWorldNameable and ICommandSender), but unlike <a href="#">getName</a> this method will generally behave sanely.

    <dl>
    <dt><a href="#">INameable.getDisplayName()</a></dt>
    <dd>A normal component.  Might be a translation component or a text component depending on the context.  Usually implemented as:</dd>
    <dd><pre><code>return this.<a href="#">hasCustomName()</a> ? new TextComponentString(this.<a href="#">getName()</a>) : new TextComponentTranslation(this.<a href="#">getName()</a>);</code></pre></dd>
    <dt><a href="#">ICommandSender.getDisplayName()</a> and <a href="#">Entity.getDisplayName()</a></dt>
    <dd>For most entities, this returns the result of <a href="#">getName()</a>, with <a href="#">scoreboard formatting</a> and a <a href="#">special hover event</a>.</dd>
    <dd>For non-entity command senders, this will return the result of <a href="#">getName()</a> in a text component.</dd>
    </dl>
    </blockquote>

Note that to find declarations of these methods, it's easiest to use `findallm`, for instance `findallm func_70005_c_` or `findallm ^Entity\.func_70005_c_`

**Comment by kashike** [comment]
https://github.com/MinecraftForge/MCPConfig/commit/193437679055c44272076c6ddf94b6f65178d57d

**Comment by Pokechu22** [comment]
I've updated the javadocs for this too.
