### ISSUE TITLE
field_82483_a should be renamed to 'DEFAULT_BEHAVIOR'

### ISSUE THREAD

**Issue by Techcable** [ModCoderPack/MCPBot-Issues#59]
The current name is 'itemDispenseBehaviorProvider', which isn't  appropriate since it doesn't provide anything and its real purpose is as the default behavior.

**Comment by matthewprenger** [comment]
Confirmed and fixed:
`field_82483_a`: `itemDispenseBehaviorProvider` -> `DEFAULT_BEHAVIOR`
