### ISSUE TITLE
Entity tracking: updateFrequency -> updateInterval

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#591]
This is the interval in ticks, not the frequency.

See `EntityTracker.track`:
```java
crashreportcategory.addDetail("Update interval", new ICrashReportDetail<String>()
{
	public String call() throws Exception
	{
		String s = "Once per " + updateFrequency + " ticks";

		if (updateFrequency == Integer.MAX_VALUE)
		{
			s = "Maximum (" + s + ")";
		}

		return s;
	}
});
```

Proposing the following name changes:

* `EntityTrackerEntry`:
  - [ ] `field_73131_c`: `updateFrequency` -> `updateInterval`
  - [ ] `p_i46837_4_`: `updateFrequencyIn` -> `updateInterval`

* `EntityTracker`:
  - [ ] `p_72791_3_`: `updateFrequency` -> `updateInterval`
  - [ ] `p_72785_3_`: `updateFrequency` -> `updateInterval`

**Comment by Pokechu22** [comment]
:+1:

To make units clear, frequency is measured in actions per time units, and interval is measured in time units per actions.  That message makes it clear that actions is 1 and that value is the time units, so it should be interval.

**Comment by combusterf** [comment]
It was mentioned that shadowing causes issues with the decompiler; consider 
`updateFrequencyIn -> updateIntervalIn`
instead

**Comment by Pokechu22** [comment]
I'm not sure whether it's shadowing fields causes problems (I think it won't cause issues since the decompiler can be explicit with `this`).  Naming something that matches a class does cause issues because of local variables, though...

**Comment by kashike** [comment]
- [x] `field_73131_c`: `updateFrequency` -> `updateInterval`
- [x] `p_i46837_4_`: `updateFrequencyIn` -> `updateInterval`
- [x] `p_72791_3_`: `updateFrequency` -> `updateInterval`
- [x] `p_72785_3_`: `updateFrequency` -> `updateInterval`
