### ISSUE TITLE
___Controller field cleanup

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#592]
The suffix doesn't really add anything here.
- [ ] `NetHandlerPlayClient.field_147299_f`: `gameController` -> `client`
- [ ] `NetHandlerPlayClient.field_147300_g`: `clientWorldController` -> `world`
- [ ] `NetHandlerPlayServer.field_147367_d`: `serverController` -> `server`

**Comment by Pokechu22** [comment]
Perhaps `field_147299_f` would be better as `mc` or `minecraft`; I'm not sure if we're moving away from that convention or not.

**Comment by kashike** [comment]
done.
- [x] `field_147299_f`: `gameController` -> `client`
- [x] `field_147300_g`: `clientWorldController` -> `world`
- [x] `field_147367_d`: `serverController` -> `server`
