### ISSUE TITLE
Chunk light checking names

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#593]
More slightly confusing lighting names.

* `queuedLightChecks` is somewhat backwards, if it's >= 4096 no checks are done, and checks are queued by setting it to 0. It acts as a counter of checks completed, as well as determining the location to check.

* `resetRelightChecks` might be okay as is, as it sets the counter to 0, but it could perhaps be made clearer that this is what causes these checks to be run at all (initial value is set to 4096 in the chunk constructor).

* `enqueueRelightChecks` doesn't queue anything, it just performs the checks. 8 sets of locations are checked at a time, provided there are checks outstanding. It's called once a tick.

Name suggestions, though I'm not completely sure what's best here:

- [ ] `field_76649_t`: `queuedLightChecks` → `lightCheckIndex` / `completedLightChecks` ?
- [ ] `func_76613_n`: `resetRelightChecks` → `queueLightChecks` / `redoLightChecks` ?
- [ ] `func_76594_o`: `enqueueRelightChecks` → `nextLightCheck` / `performLightChecks` ?

**Comment by williewillus** [comment]
1. `completedLightChecks` ("index" unclear)
2. no change, just add a comment
3. `performLightChecks` ("next" unclear)
