### ISSUE TITLE
World.func_147467_a: playMoodSoundAndCheckLight -> updateChunk ?

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#594]
Called client-side each tick from `updateBlocks` for up to 10 chunks at a time.

Does do what it says on the tin, but could have a cleaner name - the method description should cover the rest.

**Comment by kashike** [comment]
Seems like it's the client-only version of `World.updateBlocks`, as that's where it's called from. Why it's defined in `World` instead of `WorldClient` is... a mystery.

**Comment by bs2609** [comment]
`updateBlocks` isn't really the best name here too, tbh.
