### ISSUE TITLE
More chunk light-checking names

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#595]
More lighting-related names that could do with some clarification. These are for skylight checks, whereas #593 is more to do with block lighting.

Overview:

* `updateSkylightColumns` (`field_76639_c`) - boolean array used to mark columns in the chunk for skylight updates.

* `isGapLightingUpdated` (`field_76650_s`) - if this is true, then `recheckGaps` is called when ticking the chunk. `recheckGaps` checks if the surrounding chunks are loaded, and if so, calls `checkSkylightNeighborHeight` on all columns that are flagged as needing an update by `updateSkylightColumns`, then sets `isGapLightingUpdated` to false.

* `propagateSkylightOcclusion` (`func_76595_e`) - sets the corresponding (x, z) entry in `updateSkylightColumns` to true, as well as `isGapLightingUpdated`.

Issues:

* `updateSkylightColumns` isn't too bad, as it has a comment explaining it's use. The name still sounds more like a method than an array of flags though, so it could still possibly be improved.

* `propagateSkylightOcclusion` doesn't actually do the updates, it just marks things. The actual updating is done via `checkSkylightNeighborHeight` called from `recheckGaps` on tick.

* `isGapLightingUpdated` isn't clear - it marks that something has changed which means that checking (and potentially updating) the skylight is needed.

I'll have a go at coming up with some suggestions here - other ideas also welcome.

**Comment by thiakil** [comment]
`isGapLightingUpdated` -> `gapLightingDirty` to keep inline with stuff like `markDirty()`?

or `lightingGapsChecked`?

**Comment by williewillus** [comment]
`updateSkylightColumns` -> `dirtySkylightColumns`
`propagateSkylightOcclusion` -> `markSkylightDirty`
` isGapLightingUpdated` -> `skylightDirty`
