### ISSUE TITLE
Cleanup of all of the inventory fields/methods/parameters within containers

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#596]
A cleanup of all of the inventory fields/methods/parameters within containers.

Some containers (and their GUIs) refer to their inventory as if it were a tile entity, which is incorrect.  While it _is_ a tile entity on the server's side, it isn't for the client (see <ruby><rb><code>EntityPlayerSP.displayGUIChest</code></rb><rp> (</rp><rt><code>func_71007_a</code><rp>)</rp></ruby> and <ruby><rb><code>NetHandlerPlayClient.handleOpenWindow</code></rb><rp> (</rp><rt><code>func_147265_a</code></rt><rp>)</rp></ruby>).  Instead it is an `InventoryBasic`.  As such the name should be generalized.

These things do need a more complete cleanup of most of their methods, which I'm working on (one step at a time).  However, just improving the consistency of these fields cleaned up helps a lot, along with a few changes to the base container:

- [ ] `Container.getInventory` (`func_75138_a`) &rarr; `getContents` &mdash; Does not return an `IInventory` instance; instead returns a `NonNullList<ItemStack>`

    We need this change to free up that name for more "correct" uses below.

- [ ] `GuiContainer.inventorySlots` (`field_147002_h`) &rarr; `container` &mdash; typing (not super important)

See also: #533.

------

- [ ] Beacons:
    - [ ] `ContainerBeacon.tileBeacon` (`field_82866_e`) &rarr; `inventory`
    - [ ] `ContainerBeacon() playerInventory` (`p_i45804_2_`) &rarr; `playerInventoryIn`
    - [ ] `ContainerBeacon() tileBeaconIn` (`p_i45804_2_`) &rarr; `inventoryIn`
    - [ ] `ContainerBeacon.getTileEntity()` (`func_180611_e`) &rarr; `getInventory`
    - [ ] `GuiBeacon.tileBeacon` (`field_147024_w`) &rarr; `inventory`
    - [ ] `GuiBeacon() playerInventory` (`p_i45507_1_`) &rarr; `playerInventoryIn`
    - [ ] `GuiBeacon() tileBeaconIn` (`p_i45507_2_`) &rarr; `inventoryIn`
- [ ] Brewing stands:
    - [ ] `ContainerBrewingStand.tileBrewingStand` (`field_75188_e`) &rarr; `inventory`
    - [ ] `ContainerBrewingStand() playerInventory` (`p_i45802_1_`) &rarr; `playerInventoryIn`
    - [ ] `ContainerBrewingStand() tileBrewingStandIn` (`p_i45802_2_`) &rarr; `inventoryIn`
    - [ ] `GuiBrewingStand.tileBrewingStand` (`field_147013_v`) &rarr; `inventory`
    - [ ] `GuiBrewingStand() playerInv` (`p_i45506_2_`) &rarr; `playerInventoryIn`
    - [x] `GuiBrewingStand() p_i45506_2_` &rarr; `inventoryIn` &mdash; was unnamed
- [ ] Chests:

    These have some names that are already definitely incorrect beyond just the tile/inventory issue (in fact they actually already use inventory):

    - [ ] `ContainerChest.lowerChestInventory` (`field_75155_e`) &rarr; `inventory` &mdash; I've already added documentation stating: "`On the server, this may be a {@link net.minecraft.tileentity.TileEntityChest} (corresponding to a single chest block) or an {@link net.minecraft.inventory.InventoryLargeChest} (corresponding to a large chest); chests larger than 2 chest blocks are represented by several nested InventoryLargeChests.  See {@link net.minecraft.block.BlockChest#getContainer()} for more information.  On the client, this is an InventoryBasic.`"
    - [ ] `ContainerChest() playerInventory` (`p_i45801_1_`) &rarr; `playerInventoryIn`
    - [ ] `ContainerChest() chestInventory` (`p_i45801_2_`) &rarr; `inventoryIn`
    - [ ] `ContainerChest.getLowerChestInventory()` (`func_85151_d`) &rarr; `getInventory` &mdash; Also documented.
    - [ ] `GuiChest.upperChestInventory` (`field_147016_v`) &rarr; `playerInventory`
    - [ ] `GuiChest.lowerChestInventory` (`field_147015_w`) &rarr; `inventory`
    - [ ] `GuiChest() upperInv` (`p_i46315_1_`) &rarr; `playerInventoryIn`
    - [ ] `GuiChest() lowerInv` (`p_i46315_2_`) &rarr; `inventoryIn`

- [ ] Dispensers
    - [ ] `ContainerDispenser.dispenserInventory` (`field_178146_a`) &rarr; `inventory`
    - [ ] `ContainerDispenser() playerInventory` (`p_i45799_1_`) &rarr; `playerInventoryIn`
    - [ ] `ContainerDispenser() dispenserInventoryIn` (`p_i45799_2_`) &rarr; `inventoryIn`
    - [ ] `GuiDispenser.dispenserInventory` (`field_175377_u`) &rarr; `inventory` &mdash; note that this field is public
    - [ ] `GuiDispenser() playerInv` (`p_i45503_1_`) &rarr; `playerInventoryIn`
    - [ ] `GuiDispenser() dispenserInv` (`p_i45503_2_`) &rarr; `inventoryIn`

- [ ] Enchantment tables
    - [ ] `ContainerEnchantment.tableInventory` (`field_75168_e`) &rarr; `inventory` &mdash; extra docs have been added as this is not a parameter
    - [ ] `ContainerEnchantment() playerInv` (`p_i45797_1_` and `p_i45798_1_`) &rarr; `playerInventoryIn`
    - [ ] `GuiEnchantment.container` (`field_147075_G`) &rarr; `enchantmentContainer` (**The original name conflicts with my proposed change to `GuiContainer.inventorySlots`**; that field is simply a downcasted copy of the other field)
    - [ ] `GuiEnchantment() inventory` (`p_i45502_1_`) &rarr; `playerInventoryIn`

    -----

    There's also these, which I'm not entirely sure what to do with (see also #588):

    - [ ] `GuiEnchantment.nameable` (`field_175380_I`)
    - [ ] `GuiEnchantment() nameable` (`p_i45502_3_`)

    This is an instance of <code>I<del>World</del>Nameable</code>, more specifically the `IInteractionObject` passed to `EntityPlayerSP.displayGui`; it's specifically used to get the display name of the enchantment table.  But it feels weird to specifically call the field `nameable`.

- [ ] Furni (furnaces)
    - [ ] `ContainerFurance.tileFurnace` (`field_75158_e`) &rarr; `inventory`
    - [ ] `ContainerFurance() playerInventory` (`p_i45794_1_`) &rarr; `playerInventoryIn`
    - [ ] `ContainerFurnace() furnaceInventory` (`p_i45794_2_`) &rarr; `inventoryIn`
    - [ ] `GuiFurnace.tileFurnace` (`field_147086_v`) &rarr; `inventory`
    - [ ] `GuiFurnace() playerInv` (`p_i45501_1_`) &rarr; `playerInventoryIn`
    - [ ] `GuiFurnace() furnaceInv` (`p_i45501_2_`) &rarr; `inventoryIn`

- [ ] Hoppers
    - [ ] `ContainerHopper.hopperInventory` (`field_94538_a`) &rarr; `inventory`
    - [ ] `ContainerHopper() playerInventory` (`p_i45792_1_`) &rarr; `playerInventoryIn`
    - [ ] `ContainerHopper() hopperInventoryIn` (`p_i45792_2_`) &rarr; `inventoryIn`
    - [ ] `GuiHopper.hopperInventory` (`field_147083_w`) &rarr; `inventory`
    - [ ] `GuiHopper() playerInv` (`p_i1092_1_`) &rarr; `playerInventoryIn`
    - [ ] `GuiHopper() hopperInv` (`p_i1092_2_`) &rarr; `inventoryIn`

- [ ] Horses (and other equine beings)
    - [ ] `ContainerHorseInventory.horseInventory` (`field_111243_a`) &rarr; `inventory`
    - [ ] `ContainerHorseInventory() playerInventory` (`p_i45791_1_`) &rarr; `playerInventoryIn`
    - [ ] `ContainerHorseInventory() horseInventoryIn` (`p_i45791_2_`) &rarr; `inventoryIn`
    - [ ] `GuiScreenHorseInventory.horseInventory` (`field_147029_w`) &rarr; `inventory`
    - [ ] `GuiScreenHorseInventory() playerInv` (`p_i1093_2_`) &rarr; `playerInventoryIn`
    - [ ] `GuiScreenHorseInventory() horseInv` (`p_i1093_2_`) &rarr; `inventoryIn`

- [ ] Merchants
    - [ ] `ContainerMerchant.merchantInventory` (`field_75176_f`) &rarr; `inventory`
    - [ ] `ContainerMerchant() playerInventory` (`p_i1821_1_`) &rarr; `playerInventoryIn`
    - [ ] `ContainerMerchant.getMerchantInventory()` (`func_75174_d`) &rarr; `getInventory`
    - [x] `GuiMerchant() p_i45500_1_` &rarr; `playerInventoryIn` &mdash; was unnamed.

- [ ] Anvils
    - [ ] `ContainerRepair() playerInventory` (`p_i45806_1_` and `p_i45807_1_`) &rarr; `playerInventoryIn`
    - [ ] `GuiRepair.anvil` (`field_147092_v`) &rarr; `anvilContainer`
    - [ ] `GuiRepair() inventoryIn` (`p_i45508_1_`) &rarr; `playerInventoryIn`

- [x] Shulker Boxes &mdash; these were all unnamed
    - [x] `ContainerShulkerBox() p_i47266_1_` &rarr; `playerInventoryIn`
    - [x] `ContainerShulkerBox() p_i47266_2_` &rarr; `inventoryIn`
    - [x] `GuiShulkerBox() p_i47233_1_` &rarr; `playerInventoryIn`
    - [x] `GuiShulkerBox() p_i47233_2_` &rarr; `inventoryIn`

- [ ] Crafting tables (workbenches)
    - [ ] `ContainerWorkbench() playerInventory` (`p_i45800_1_`) &rarr; `playerInventoryIn`
    - [ ] `GuiCrafting() playerInv` (`p_i45504_1_` and `p_i45505_1_`) &rarr; `playerInventoryIn`

------

Here are the same things in command form:

###### Prerequisites to ensure names are valid

```
sm func_75138_a getContents
sf field_147075_G enchantmentContainer
sf field_147092_v anvilContainer
sf field_147002_h container
```

###### Names referring to tile entities

```
sf field_82866_e inventory
sp p_i45804_2_ inventoryIn
sm func_180611_e getInventory
sf field_147024_w inventory
sp p_i45507_2_ inventoryIn
sf field_75188_e inventory
sp p_i45802_2_ inventoryIn
sf field_147013_v inventory
sf field_75158_e inventory
sf field_147086_v inventory
```

###### Other incorrect/misleading names

```
sf field_75155_e inventory
sm func_85151_d getInventory
sf field_147016_v playerInventory
sf field_147015_w inventory
sp p_i46315_1_ playerInventoryIn
sp p_i46315_2_ inventoryIn
sp p_i45502_1_ playerInventoryIn
sp p_i45508_1_ playerInventoryIn
```

###### Names including the type of inventory

```
sp p_i45801_2_ inventoryIn
sf field_178146_a inventory
sp p_i45799_2_ inventoryIn
sf field_175377_u inventory
sp p_i45503_2_ inventoryIn
sp field_75168_e inventory
sp p_i45794_2_ inventoryIn
sp p_i45501_2_ inventoryIn
sf field_94538_a inventory
sp p_i45792_2_ inventoryIn
sf field_147083_w inventory
sp p_i1092_2_ inventoryIn
sf field_111243_a inventory
sp p_i45791_2_ inventoryIn
sf field_147029_w inventory
sp p_i1093_2_ inventoryIn
sf field_75176_f inventory
sm func_75174_d getInventory
```

###### Player inventory parameters

```
sp p_i45804_2_ playerInventoryIn
sp p_i45507_1_ playerInventoryIn
sp p_i45802_1_ playerInventoryIn
sp p_i45506_2_ playerInventoryIn
sp p_i45801_1_ playerInventoryIn
sp p_i45799_1_ playerInventoryIn
sp p_i45503_1_ playerInventoryIn
sp p_i45797_1_ playerInventoryIn
sp p_i45798_1_ playerInventoryIn
sp p_i45794_1_ playerInventoryIn
sp p_i45501_1_ playerInventoryIn
sp p_i45792_1_ playerInventoryIn
sp p_i1092_1_ playerInventoryIn
sp p_i45791_1_ playerInventoryIn
sp p_i1093_2_ playerInventoryIn
sp p_i1821_1_ playerInventoryIn
sp p_i45806_1_ playerInventoryIn
sp p_i45807_1_ playerInventoryIn
sp p_i45800_1_ playerInventoryIn
sp p_i45504_1_ playerInventoryIn
sp p_i45505_1_ playerInventoryIn
```

###### Undecided

- `GuiEnchantment.nameable` (`field_175380_I`)
- `GuiEnchantment() nameable` (`p_i45502_3_`)

**Comment by Zidane** [comment]
@Pokechu22 

Not sure I see the value in the `in` monikers above. Otherwise, no real complains.

**Comment by kashike** [comment]
@Zidane `In` is required when not being force-set.
