### ISSUE TITLE
ExtendedBlockStorage -> ChunkSection

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#597]
* What is "Extended" about it?
* It's not storage, it's an in-memory representation.
* "Chunk section" is a well-understood name for the 16x16x16 cubes that make up a full chunk column

Also see #418.

**Comment by bs2609** [comment]
Related `Chunk` renames:

* Fields:
  - [ ] `field_186036_a`: `NULL_BLOCK_STORAGE` -> `NULL_SECTION` / `EMPTY_SECTION` ?
  - [ ] `field_76652_q`: `storageArrays` -> `sections`

* Methods:
  - [ ] `func_76602_a`: `setStorageArrays(newStorageArrays)` -> `setSections(newSections)`
  - [ ] `func_76587_i`: `getBlockStorageArray()` -> `getSections()`
  - [ ] `func_186031_y`: `getLastExtendedBlockStorage()` -> `getTopSection()`
  - [ ] `func_76625_h`: `getTopFilledSegment()` -> `getTopSectionBase()` ?

**Comment by bs2609** [comment]
Also see this log message in `Chunk.setStorageArrays`:
```java
LOGGER.warn("Could not set level chunk sections, array length is {} instead of {}", Integer.valueOf(newStorageArrays.length), Integer.valueOf(this.storageArrays.length));
```

**Comment by bs2609** [comment]
Could this be added to #514?

**Comment by tterrag1098** [comment]
I think `getTopSectionBase` could use some javadocs to explain that it's the top section *with any blocks*, but otherwise these names seem good.

**Comment by kashike** [comment]
- [x] `field_76652_q`: `storageArrays` &rarr; `sections`
- [x] `field_186036_a`: `NULL_BLOCK_STORAGE` &rarr; `EMPTY_SECTION`
- [x] `func_76602_a`: `setStorageArrays` &rarr; `setSections`
