### ISSUE TITLE
Duplicate EntityFlying

### ISSUE THREAD

**Issue by gabizou** [ModCoderPack/MCPBot-Issues#600]
- [ ] `net.minecraft.entity.passive.EntityFlying` -> `net.minecraft.entity.passive.IFlying`
- [ ] `net.minecraft.entity.EntityFlying` -> `net.minecraft.entity.EntityLivingFlying`

The reasoning is as follows:
`passive.EntityFlyging` is an interface that is extended by `EntityParrot`. `entity.EntityFlying` is an abstract class with AI to be extended by `EntityGhast`. For lack of better names for `entity.EntityFlying`, it should likely be even something similar to `EntityLiving` since that has all the AI additions.

**Comment by liach** [comment]
`EntityAIFlying` sounds somewhat like an ai class

**Comment by kashike** [comment]
- [x] `net/minecraft/entity/passive/EntityFlying` → `net/minecraft/entity/passive/IFlyingAnimal`
