### ISSUE TITLE
setPositionAndRotationDirect -> setInterpolationTarget

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#601]
`func_180426_a`: `setPositionAndRotationDirect` -> `setInterpolationTarget`

The original is named as such because of `Entity`'s default implementation, but upon inspection of all subclass implementations (particularly, `EntityLivingBase` and `EntityMinecart` (see #569)), it's evident that the purpose of this method is not to set the position and rotation directly, but rather a target position and rotation for the client to interpolate towards over the next few ticks.

Supporting this is the fact that the method is client only and only used in packet handlers for entity motion packets.

Better name suggestions welcome.

**Comment by bs2609** [comment]
Related: #429
