### ISSUE TITLE
DragonFightManager.respawnDragon() → tryRespawnDragon()

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#602]
- [ ] `func_186106_e`: `respawnDragon` &rarr; `tryRespawnDragon`

This method checks for whether there are enough crystals to spawn the dragon, but if there aren't doesn't actually do anything.  The other <ruby><rb>`respawnDragon(List<EntityEnderCrystal>)`</rb><rp> (</rp><rt>`func_186093_a`</rt><rp>)</rp></ruby> is what actually handles respawning it, or at least adjusting the portal and setting `respawnState` to `START`.  (I don't know enough about the dragon code to change that, just that the first method's wrong).

**Comment by kashike** [comment]
- [x] `func_186106_e`: `respawnDragon` &rarr; `tryRespawnDragon`
