### ISSUE TITLE
ChunkRenderDispatcher.func_188247_f: hasChunkUpdates -> hasNoChunkUpdates

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#603]
- [ ] `func_188247_f` in `ChunkRenderDispatcher`: `hasChunkUpdates` -> `hasNoChunkUpdates`

and people wonder why I get anxious about bad naming

![](https://i.gyazo.com/0b5c3863c3dca0253089eb54a2a3e598.png)

**Comment by kashike** [comment]
- [x] `func_188247_f`: `hasChunkUpdates` -> `hasNoChunkUpdates`
