### ISSUE TITLE
EnumFacing names, in particular EnumFacing.getFront → EnumFacing.byIndex

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#608]
- [ ] func_82600_a: `getFront` &rarr; `byIndex`

This name is upsetting.  "Named getFront for legacy reasons."  Wonderful.  It's been this way since 1.5, perhaps earlier.

The only issue with this change is that there's a _lot_ of references to this method, so it might break mods.  As such it might make sense to delay this change for 1.13.

Alternatively, perhaps `forIndex` would work better; in that case `byName` should also be changed for consistency.

Some other names that aren't as horrible but just would be nice for readability:

- [ ] func_176731_b: `getHorizontal` &rarr; `byHorizontalIndex`
- [ ] func_82601_c: `getFrontOffsetX` &rarr; `getXOffset`
- [ ] func_96559_d: `getFrontOffsetY` &rarr; `getYOffset`
- [ ] func_82599_e: `getFrontOffsetZ` &rarr; `getZOffset`

**Comment by kashike** [comment]
- [x] `func_82600_a`: `getFront` -> `byIndex`
- [x] `func_176731_b`: `getHorizontal` -> `byHorizontalIndex`
- [x] `func_82601_c`: `getFrontOffsetX` -> `getXOffset`
- [x] `func_96559_d`: `getFrontOffsetY` -> `getYOffset`
- [x] `func_82599_e`: `getFrontOffsetZ` -> `getZOffset`
