### ISSUE TITLE
ModelRotation.field_177544_s: matrix4d -> matrix

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#609]
Currently:
```java
private final Matrix4f matrix4d;
```

**Comment by bs2609** [comment]
Also:
`func_177525_a`: `getMatrix4d` -> `getMatrix`

**Comment by gegy1000** [comment]
What about `transformationMatrix` or even `rotationMatrix`?

**Comment by covers1624** [comment]
I think `matrix` is good enough, adding `transformation` is redundant and `rotation` is not accurate. Matrices can do translation, rotation and scale, so just `matrix` is fine imo.

**Comment by kashike** [comment]
- [x] `field_177544_s`: `matrix4d` -> `matrix`
- [x] `func_177525_a`: `getMatrix4d` -> `matrix` - enums have `name` and `ordinal` methods, so I left off the `get` prefix here (to prevent the collision as mentioned by @bs2609)
