### ISSUE TITLE
WorldSettings setWorldName and similar are completely wrong

### ISSUE THREAD

**Issue by simon816** [ModCoderPack/MCPBot-Issues#61]
`WorldSettings.setWorldName()` should be `setGeneratorOptions()`
`WorldSettings.worldName` should be `generatorOptions`
`WorldSettings.getWorldName()` should be `getGeneratorOptions()`

Edit: changed from `generatorSettings` to `generatorOptions`

**Comment by simon816** [comment]
This is marked as "needs research", can anybody else confirm?

**Comment by kashike** [comment]
I can confirm, along with `p_71247_6_` being incorrectly named `worldNameIn` instead of `generatorOptions`.

**Comment by matthewprenger** [comment]
Confirmed and Fixed:
`p_71247_6_`: `worldNameIn2` -> `generatorOptions`
`p_82750_1_`: `name` -> `options`
`func_82750_a`: `setWorldName` -> `setGeneratorOptions`
`func_82749_j`: `getWorldName` -> `getGeneratorOptions`
`field_82751_h`: `worldName` -> `generatorOptions`
