### ISSUE TITLE
Containers that actually aren't (ContainerHorseChest, ILockableContainer, EntityMinecartContainer, ContainerLocalMenu)

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#611]
See also #585 

* [ ] `ContainerHorseChest`: this should be `InventoryHorseChest` or similar.  It extends InventoryBasic, and isn't a container (there's `ContainerHorseInventory` for that)
* [ ] `ILockableContainer`: this should be `ILockableInventory` as it's a subinterface of `IInventory`.  Mentioned in #568.

and more tentatively:

* [ ] `EntityMinecartContainer`: could go either way, but it might be better as something like `EntityStorageMinecart`.  There _isn't_ a unique container class for minecart variants, so this isn't that big of a deal.
* [ ] `ContainerLocalMenu`: black magic.  Frankly I don't want to think about this (and the related `LocalBlockIntercommunication`).  But, it's not a container, so it should maybe be `LocalInventory` or something...

**Comment by williewillus** [comment]
These are barely any better but maybe:
`LocalBlockIntercommunication` -> `SlotlessInteractionObject`. This class is used as a dummy clientside IInteractionObject when the serverside container has no storage slots (for example, anvils and workbenches).

`ContainerLocalMenu` -> `DummyInventory`. Is an `InventoryBasic`, but also just used as a dummy clientside IInteractionObject when the serverside container has storage slots.

see: http://wiki.vg/Protocol#Open_Window

there's other clues and hints about the container system I see, but I'll leave that for another ticket

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
