### ISSUE TITLE
isBlockIndirectlyGettingPowered -> getRedstonePowerFromNeighbors

### ISSUE THREAD

**Issue by quat1024** [ModCoderPack/MCPBot-Issues#612]
- [ ] `func_175687_A` in `net.minecraft.world.World`: `isBlockIndirectlyGettingPowered` -> `getRedstonePowerFromNeighbors`

isBlockIndirectlyGettingPowered *sounds* like it returns a boolean value (hence the prefix "is"), but actually returns an integer value 0-15. Additionally, it returns a non-zero value when the block is arguably "directly" receiving power (e.x. when a repeater/comparator points directly into my block,), as well as when it feels "indirectly" powered (e.x. repeater pointing into a stone block adjacent to my block, redstone dust on top of adjacent block)

So basically this name sucks.

I'm not entirely sure about a good alternative name, though. The use-case seems to be "get the redstone power level for purposes when a user expects a block to be analog-ly powered in an intuitive manner, e.x. taking the largest power level if powered from multiple sides, and responding to weak power-through-blocks". It's like an analog form of `isBlockPowered`.

I use it for analog lamps in Dazzle, and it works great - behaves exactly like a vanilla redstone lamp (which uses `isBlockPowered`), just... analogly.

Best I can think of is something like `getAnalogPower`???

**Comment by williewillus** [comment]
`getRedstonePowerFromNeighbors` ?

that's the simplest explanation for what it does, and the method is not limited to analog uses, really

**Comment by kashike** [comment]
- [x] `func_175687_A`: `isBlockIndirectlyGettingPowered` -> `getRedstonePowerFromNeighbors`
