### ISSUE TITLE
EntityArrow -> EntityProjectile (?)

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#613]
I don't know what the convention is for making issues for non-released versions, but whatever.

the new trident class extends EntityArrow in 1.13 (alongside spectral arrows and tipped arrows), making it evident that this is no longer an "arrow" class. I propose `EntityProjectile`.

Might be confused with `IProjectile` or `EntityThrowable` though.

**Comment by Pokechu22** [comment]
Especially beneficial as the `minecraft:arrow` entity (which is both regular and tipped arrows) isn't actually implemented by `EntityArrow`, but instead `EntityTippedArrow`, so the name is just more confusing.

**Comment by kashike** [comment]
This isn't something we're going to do at this time.
