### ISSUE TITLE
ItemRenderer.func_178108_a: renderBlockInHand -> renderSuffocationOverlay

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#614]
`ItemRenderer.func_1787108_a`: `renderBlockInHand` -> `renderSuffocationOverlay`

Just takes a TAS from the main atlas and renders it over the player's view. Used for suffocation overlay.

**Comment by Pokechu22** [comment]
How about `renderSuffocationOverlay` or `renderInBlockOverlay`?  I don't think `renderOverlay` is specific enough.

**Comment by kashike** [comment]
- [x] `func_178108_a`: `renderBlockInHand` -> `renderSuffocationOverlay`
