### ISSUE TITLE
renderEngine -> textureManager

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#615]
All `TextureManager` instances. Comments also need updating/clearing in some cases.

- [ ] `TileEntityRendererDispatcher.field_147553_e`
- [ ] `RenderGlobal.field_72770_i`
- [ ] `FontRenderer.field_78298_i`
- [ ] `Minecraft.field_71446_o`
- [ ] `RenderManager.field_78724_e`

**Comment by kashike** [comment]
- [x] `field_147553_e`: `renderEngine` -> `textureManager`
- [x] `field_72770_i`: `renderEngine` -> `textureManager`
- [x] `field_78298_i`: `renderEngine` -> `textureManager`
- [x] `field_71446_o`: `renderEngine` -> `textureManager`
- [x] `field_78724_e`: `renderEngine` -> `textureManager`
