### ISSUE TITLE
RenderGlobal.ContainerLocalRenderInformation -> ???

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#616]
Contains a `RenderChunk`, plus some extra info used when propagating visibility.

Outside of that usage, is only used to get visible `RenderChunk` instances, by iterating over the `renderInfos` list.

Any suggestions for a better name here?

Also suggesting a field rename:
* `RenderGlobal.field_72755_R`: `renderInfos` -> `visibleChunks`

The comment on this field also needs changing.

**Comment by bs2609** [comment]
Also, on a somewhat related note, this is how the class constructor currently appears:
```java
private ContainerLocalRenderInformation(RenderChunk renderChunkIn, EnumFacing facingIn, @Nullable int counterIn)
```

The `EnumFacing` is supposed to be the nullable parameter, but the annotation is shown on the `int` instead.

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
