### ISSUE TITLE
RegistryNamespaced -> RegistryIntegerBacked (+1)

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#617]
`net.minecraft.util.registry.RegistryNamespaced` -> `net.minecraft.util.registry.RegistryIntegerBacked`
`net.minecraft.util.registry.RegistryNamespacedDefaultedByKey` -> `net.minecraft.util.registry.RegistryIntegerBackedDefaulted`

Nothing about this registry says anything about namespacing (ResourceLocation isn't even used here, the key type is generic). What actually distinguishes it from its superclass is that this registry allocates integer ID's for its entries.

better name suggestions welcome

**Comment by bs2609** [comment]
The vanilla names appear to be `DefaultedMappedRegistry` (and probably `MappedRegistry`) - see this line in `RegistryNamespacedDefaultedByKey.validateKey`:

```java
Validate.notNull(this.defaultValue, "Missing default of DefaultedMappedRegistry: " + this.defaultValueKey);
```
