### ISSUE TITLE
net.minecraft.entity.ai.EntityAIWatchClosest2 -> EntityAIWatchClosestWithoutMoving

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#618]
better names welcome

`net.minecraft.entity.ai.EntityAIWatchClosest2` -> `EntityAIWatchClosestWithoutMoving`

Same as `EntityAIWatchClosest`, but sets the mutex bits to `2 | 1` instead of 2. The `2` bit states that this AI task should not run along with others that modify the entity's head/look. The `1` bit states that this AI task should not run along with others that move the entity's position.

So this subclass is just a watch task that also prevents the entity from walking around. This makes sense, since `EntityAIVillagerInteract` (the villager-throw-food-to-one-another task) extends from this `EntityAIWatchClosest2`

**Comment by bs2609** [comment]
`EntityAIWatchClosestWithoutMoving`?
