### ISSUE TITLE
Potion and Enchantment setName/getName

### ISSUE THREAD

**Issue by Terrails** [ModCoderPack/MCPBot-Issues#619]
- [ ] `func_76390_b` in `net.minecraft.potion.Potion`: `setPotionName` -> `setUnlocalizedName`
- [ ] `func_76393_a` in `net.minecraft.potion.Potion`: `getName` -> `getUnlocalizedName`
- [ ] `func_77322_b` in `net.minecraft.enchantment.Enchantment`: `setName` -> `setUnlocalizedName`
- [ ] `func_77320_a` in `net.minecraft.enchantment.Enchantment`: `getName` -> `getUnlocalizedName`
- [ ] `func_77316_c` in `net.minecraft.enchantment.Enchantment`: `getTranslatedName` -> `getLocalizedName`

Current names are not consistent with the names from Block and Item. So this is only for consistency.

**Comment by JamiesWhiteShirt** [comment]
This should be updated if #632 goes through.
