### ISSUE TITLE
EntityLiving.equipment -> .activeEquipment

### ISSUE THREAD

**Issue by mcrafty50** [ModCoderPack/MCPBot-Issues#62]
`activeEquipment` would clarify that the equipment is not just "in the inventory", but active: either "equipped" or "held".

This is relevant, as these items are used in calculating attackModifiers, exp-point drops, potion-damage-calculations, etc... where only 'equipped' or 'held' equipment should be considered.

An entity could have other equipment in inventory; for (a contrived) example, a horse with a chest might be carrying horse armor, but not have it equipped (note that this is contrived - horse inventory is implemented completely independent of EntityLiving.equipment... but the semantics relate).

Relates to #63.

**Comment by mezz** [comment]
Same as #63, this is fixed in 1.9. There are `inventoryHands` and `inventoryArmor` fields.
