### ISSUE TITLE
EntityItemFrame.removeFrameFromMap → removeItem

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#620]
- [ ] `func_110131_b` in `EntityItemFrame`: `removeFrameFromMap ` &rarr; `removeItem`

This method is used to do more things than just remove from a map, although it does do that.

Current comment is "Removes the dot representing this frame's position from the map when the item frame is broken." and it should be changed to "Called when the given item is removed from this frame.  Used to update the stack's status and remove icons from maps."

**Comment by kashike** [comment]
- [x] `func_110131_b`: `removeFrameFromMap` -> `removeItem`
