### ISSUE TITLE
TextureMap texture location names

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#622]
- [ ] `field_174945_f`: `LOCATION_MISSING_TEXTURE` -> `MISSING_TEXTURE_LOCATION`
- [ ] `field_110575_b`: `LOCATION_BLOCKS_TEXTURE` -> `TEXTURE_ATLAS_LOCATION`

**Comment by bs2609** [comment]
Also:
- [ ] `ModelBakery.field_177602_b`: `LOCATIONS_BUILTIN_TEXTURES` -> `BUILTIN_TEXTURE_LOCATIONS`

**Comment by InsomniaKitten** [comment]
Just `ATLAS_LOCATION` would be fine, imo, when accessed as `TextureMap.ATLAS_LOCATION`.
