### ISSUE TITLE
net.minecraft.world.MinecraftException -> SavingException

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#625]
- [ ] `net.minecraft.world.MinecraftException` -> `net.minecraft.world.storage.SavingException`

This exception is only thrown from `SaveHandler.checkSessionLock()`, which only has to do with saving worlds to disk. `MinecraftException` is too general. Perhaps `SessionLockException`

**Comment by kashike** [comment]
Already renamed for 1.13.

- [x] `net.minecraft.world.MinecraftException` -> `net.minecraft.world.storage.SessionLockException`
