### ISSUE TITLE
Vec3d#addVector -> Vec3d#add

### ISSUE THREAD

**Issue by InsomniaKitten** [ModCoderPack/MCPBot-Issues#627]
It'd be nice to see this changed, as currently it is inconsistent with the other addition/subtraction methods in the class.
- [ ] `func_72441_c` in `net.minecraft.util.math.Vec3d`: `addVector` -> `add`

**Comment by bs2609** [comment]
Also:
- [ ] `func_72433_c`: `lengthVector` -> `length`
- [ ] `func_189984_a`: `fromPitchYawVector` -> `fromPitchYaw`

**Comment by kashike** [comment]
- [x] `func_72441_c`: `addVector` -> `add`
- [x] `func_72433_c`: `lengthVector` -> `length`
- [x] `func_189984_a`: `fromPitchYawVector` -> `fromPitchYaw`
