### ISSUE TITLE
ChunkProvider field names

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#628]
* `ChunkProviderServer`:
  - [ ] `field_73248_b`: `droppedChunksSet` ->`droppedChunks`
  - [ ] `field_73244_f`: `id2ChunkMap` ->`loadedChunks`

* `ChunkProviderClient`:
  - [ ] `field_73236_b`: `chunkMapping` -> `loadedChunks`

**Comment by kashike** [comment]
- [x] `field_73248_b`: `droppedChunksSet` -> `droppedChunks`
- [x] `field_73244_f`: `id2ChunkMap` -> `loadedChunks`
- [x] `field_73236_b`: `chunkMapping` -> `loadedChunks`
