### ISSUE TITLE
Entity.getInventory() -> .getActiveEquipment()

### ISSUE THREAD

**Issue by mcrafty50** [ModCoderPack/MCPBot-Issues#63]
getActiveEquipment() would clarify that the equipment is not just "in the inventory", but active: either "equipped" or "held". This is directly related, and potentially more important than #62.

This is relevant, as these items are used in calculating attackModifiers, exp-point drops, potion-damage-calculations, etc... where only 'equipped' or 'held' equipment should be considered.

An entity could have other equipment in inventory; for (a contrived) example, a horse with a chest might be carrying horse armor, but not have it equipped (note that this is contrived - horse inventory is implemented completely independent of EntityLiving.equipment... but the semantics relate).

**Comment by mezz** [comment]
It looks like this has been clarified in 1.9. There is `getArmorInventoryList()` (4 armor inventory) and `getHeldEquipment()` (2 hands), which seems pretty clear.
