### ISSUE TITLE
unlocalizedName -> translationKey

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#632]
Putting this up for debate.
Trying to emphasise that these are **only** supposed to be used for translation.

* `unlocalizedName` -> `translationKey`:
  - [x] `ItemFishFood$FishType.field_150981_g`
  - [x] `BlockDoublePlant$EnumPlantType.field_176947_j`
  - [x] `BlockPrismarine$EnumType.field_176812_g`
  - [x] `BlockSand$EnumType.field_176691_g`
  - [x] `BlockQuartz$EnumType.field_176806_i`
  - [x] `Block.field_149770_b`
  - [x] `BlockPlanks$EnumType.field_176848_j`
  - [x] `BaseAttribute.field_111115_a`
  - [x] `BlockDirt$DirtType.field_176929_g`
  - [x] `BlockRedSandstone$EnumType.field_176830_g`
  - [x] `BlockStoneSlab$EnumType.field_176635_l`
  - [x] `BlockStoneBrick$EnumType.field_176622_h`
  - [x] `Item.field_77774_bZ`
  - [x] `BlockFlower$EnumFlowerType.field_176977_o`
  - [x] `EnumDyeColor.field_176785_v`
  - [x] `BlockSilverfish$EnumType.field_176891_j`
  - [x] `BlockWall$EnumType.field_176661_f`
  - [x] `BlockSandStone$EnumType.field_176678_g`
  - [x] `BlockStone$EnumType.field_176654_k`

* `getUnlocalizedName` -> `getTranslationKey`:
  - [x] `ItemFishFood$FishType.func_150972_b`
  - [x] `BlockDoublePlant$EnumPlantType.func_176939_c`
  - [x] `BlockPrismarine$EnumType.func_176809_c`
  - [x] `BlockSand$EnumType.func_176685_d`
  - [x] `Block.func_149739_a`
  - [x] `ItemStack.func_77977_a`
  - [x] `BlockPlanks$EnumType.func_176840_c`
  - [x] `BlockDirt$DirtType.func_176927_c`
  - [x] `BlockRedSandstone$EnumType.func_176828_c`
  - [x] `BlockSlab.func_150002_b`
  - [x] `BlockStoneSlab$EnumType.func_176627_c`
  - [x] `BlockStoneBrick$EnumType.func_176614_c`
  - [x] `Item.func_77667_c`
  - [x] `Item.func_77658_a`
  - [x] `BlockFlower$EnumFlowerType.func_176963_d`
  - [x] `BlockStoneSlabNew$EnumType.func_176918_c`
  - [x] `EnumDyeColor.func_176762_d`
  - [x] `BlockSilverfish$EnumType.func_176882_c`
  - [x] `BlockWall$EnumType.func_176659_c`
  - [x] `BlockSandStone$EnumType.func_176676_c`
  - [x] `BlockStone$EnumType.func_176644_c`

* `setUnlocalizedName` -> `setTranslationKey`:
  - [ ] `Block.func_149663_c`
  - [ ] `Item.func_77655_b`

**Comment by Pokechu22** [comment]
Things are changing a bit in 1.13; `getUnlocalizedName` for most things becomes lazy and there is no setter (for either blocks or items).  Instead a default name is created based off of the thing's ID (e.g. `block.minecraft.tnt` or `item.minecraft.apple`), although many things still override `getUnlocalizedName`.  Still, :+1: this would be a good change to make then.

**Comment by kashike** [comment]
- [x] `field_150981_g`: `unlocalizedName` -> `translationKey`
- [x] `field_176947_j`: `unlocalizedName` -> `translationKey`
- [x] `field_176812_g`: `unlocalizedName` -> `translationKey`
- [x] `field_176691_g`: `unlocalizedName` -> `translationKey`
- [x] `field_176806_i`: `unlocalizedName` -> `translationKey`
- [x] `field_149770_b`: `unlocalizedName` -> `translationKey`
- [x] `field_176848_j`: `unlocalizedName` -> `translationKey`
- [x] `field_111115_a`: `unlocalizedName` -> `translationKey`
- [x] `field_176929_g`: `unlocalizedName` -> `translationKey`
- [x] `field_176830_g`: `unlocalizedName` -> `translationKey`
- [x] `field_176635_l`: `unlocalizedName` -> `translationKey`
- [x] `field_176622_h`: `unlocalizedName` -> `translationKey`
- [x] `field_77774_bZ`: `unlocalizedName` -> `translationKey`
- [x] `field_176977_o`: `unlocalizedName` -> `translationKey`
- [x] `field_176785_v`: `unlocalizedName` -> `translationKey`
- [x] `field_176891_j`: `unlocalizedName` -> `translationKey`
- [x] `field_176661_f`: `unlocalizedName` -> `translationKey`
- [x] `field_176678_g`: `unlocalizedName` -> `translationKey`
- [x] `field_176654_k`: `unlocalizedName` -> `translationKey`
- [x] `func_150972_b`: `getUnlocalizedName` -> `getTranslationKey`
- [x] `func_176939_c`: `getUnlocalizedName` -> `getTranslationKey`
- [x] `func_176809_c`: `getUnlocalizedName` -> `getTranslationKey`
- [x] `func_176685_d`: `getUnlocalizedName` -> `getTranslationKey`
- [x] `func_149739_a`: `getUnlocalizedName` -> `getTranslationKey`
- [x] `func_77977_a`: `getUnlocalizedName` -> `getTranslationKey`
- [x] `func_176840_c`: `getUnlocalizedName` -> `getTranslationKey`
- [x] `func_176927_c`: `getUnlocalizedName` -> `getTranslationKey`
- [x] `func_176828_c`: `getUnlocalizedName` -> `getTranslationKey`
- [x] `func_150002_b`: `getUnlocalizedName` -> `getTranslationKey`
- [x] `func_176627_c`: `getUnlocalizedName` -> `getTranslationKey`
- [x] `func_176614_c`: `getUnlocalizedName` -> `getTranslationKey`
- [x] `func_77667_c`: `getUnlocalizedName` -> `getTranslationKey`
- [x] `func_77658_a`: `getUnlocalizedName` -> `getTranslationKey`
- [x] `func_176963_d`: `getUnlocalizedName` -> `getTranslationKey`
- [x] `func_176918_c`: `getUnlocalizedName` -> `getTranslationKey`
- [x] `func_176762_d`: `getUnlocalizedName` -> `getTranslationKey`
- [x] `func_176882_c`: `getUnlocalizedName` -> `getTranslationKey`
- [x] `func_176659_c`: `getUnlocalizedName` -> `getTranslationKey`
- [x] `func_176676_c`: `getUnlocalizedName` -> `getTranslationKey`
- [x] `func_176644_c`: `getUnlocalizedName` -> `getTranslationKey`
- [ ] `func_149663_c`: `setUnlocalizedName` -> `setTranslationKey`
- [ ] `func_77655_b`: `setUnlocalizedName` -> `setTranslationKey`

**Comment by bs2609** [comment]
Bonus:
* `Item.func_77657_g`: `getUnlocalizedNameInefficiently` -> `getTranslationKeyInefficiently` ?

Also, params for the two setter methods could do with updating.

**Comment by kashike** [comment]
- [x] `p_77655_1_`: `unlocalizedName` -> `key`
- [x] `p_149663_1_`: `name` -> `key`
