### ISSUE TITLE
1.13 INBTBase Method And Parameter Changes

### ISSUE THREAD

**Issue by InsomniaKitten** [ModCoderPack/MCPBot-Issues#634]
- [ ] `???` in `net.minecraft.nbt.INBTBase`: `getTagTypeName` -> `getTypeById`
- [ ] `p_193581_0_` in `net.minecraft.nbt.INBTBase#getTagTypeName`: `p_193581_0_` -> `id`

Returns a String value from `INBTBase#NBT_TYPES` for the given int ordinal. It does not take a "name".

---
- [ ] `???` in `net.minecraft.nbt.INBTBase`: `createNewByType` -> `createFromId`

Returns a new INBTBase object based on the given type id.

**Comment by InsomniaKitten** [comment]
These changes could be applied to 1.12 as well, along with the following additional change

- [ ] `p_equals_1_` in `net.minecraft.nbt.NBTBase#equals`: `p_equals_1_` -> `obj`

**Comment by kashike** [comment]
- [x] `func_193581_j`: `getTagTypeName` -> `getTypeName`
- [x] `func_150284_a`: `createNewByType` -> `create`

`p_equals_1_` cannot be changed.
