### ISSUE TITLE
Inconsistent EntityTrackerEntry field names

### ISSUE THREAD

**Issue by Nessiesson** [ModCoderPack/MCPBot-Issues#635]
In EntityTrackerEntry there are three fields with inconsistent naming: `lastTrackedEntityMotionX`, `lastTrackedEntityMotionY`, `motionZ`.

I propose changing `motionZ` to follow the naming scheme of the other two:
- [ ] `field_73135_l` in `net.minecraft.entity.EntityTrackerEntry`: `motionZ` -> `lastTrackedEntityMotionZ`

**Comment by bs2609** [comment]
I would suggest possibly dropping the `_TrackedEntity_` part from all those names, it doesn't really add anything as there's only the one entity it could really refer to.

The class itself could even be called `TrackedEntity`, rather than `EntityTrackerEntry`.
