### ISSUE TITLE
SearchTree field names are mismatched

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#636]
Relevant fields:
* `field_194044_a` (`byId`)
* `field_194045_b` (`byName`)
* `field_194046_c` (`nameFunc`)
* `field_194047_d` (`idFunc`)

According to the current comments, these names should correspond:
```java
/** A {@link SuffixArray} that contains values keyed by the ID (as produced by {@link #idFunc}). */
protected SuffixArray<T> byId = new SuffixArray<T>();
/** A {@link SuffixArray} that contains values keyed by the name (as produced by {@link #nameFunc}). */
protected SuffixArray<T> byName = new SuffixArray<T>();
```

However, currently we have this:
```java
private void index(T element)
{
    (this.idFunc.apply(element)).forEach((p_194039_2_) ->
    {
        this.byName.add(element, p_194039_2_.toString().toLowerCase(Locale.ROOT));
    });
    (this.nameFunc.apply(element)).forEach((p_194041_2_) ->
    {
        this.byId.add(element, p_194041_2_.toLowerCase(Locale.ROOT));
    });
}
```

As the functions are identifiable by the return value type ("id" returns `Iterable<ResourceLocation>`, "name" returns `Iterable<String>`), this would suggest the `SuffixArray` fields should have their names switched to match the function naming, like so:

- [ ] `field_194044_a`: `byId` -> `byName`
- [ ] `field_194045_b`: `byName` -> `byId`

**Comment by kashike** [comment]
- [x] `field_194044_a`: `byId` -> `byName`
- [x] `field_194045_b`: `byName` -> `byId`
