### ISSUE TITLE
1.13 BlockRedstoneLight -> BlockRedstoneLamp

### ISSUE THREAD

**Issue by InsomniaKitten** [ModCoderPack/MCPBot-Issues#637]
A simple enough change request, not sure if additional detail is needed. Reasoning is that it fits better with the registry name and localized name of the registered instance; `minecraft:redstone_lamp` and `Redstone Lamp` respectively. I am aware than the translation key refers to it as `redstoneLight` in 1.12, however as of 1.13, this has been replaced with `redstone_lamp`.

- [ ] `net.minecraft.block.BlockRedstoneLight` -> `BlockRedstoneLamp`

**Comment by Pokechu22** [comment]
Note that those weird old translation keys are being removed in 1.13 (in favor of using keys based on the ID), so there really is no reason to keep it as light.

**Comment by kashike** [comment]
https://github.com/MinecraftForge/MCPConfig/commit/193437679055c44272076c6ddf94b6f65178d57d
