### ISSUE TITLE
CompressedStreamTools → NbtIo

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#638]
`net.minecraft.nbt.CompressedStreamTools` is a bad name; it doesn't just work with compressed streams but instead handles writing NBT to both compressed and uncompressed streams (and in fact directly to files too).

This class already has a name in Mojang's [anvil converter](https://www.mojang.com/2012/02/new-minecraft-map-format-anvil/): `com.mojang.nbt.NbtIo`.  (That actually appears to be the exact same code, other than the changes that accumulated over the past 5 years).  I'm not 100% sure I like `NbtIo` just because it's _two_ acronyms (so it could be `NBTIO` but that's just awful), but given that Mojang was fine with that name I think it's acceptable here.

**Comment by kashike** [comment]
Do you have any other name suggestions for the class? @LexManos isn't a fan of `NbtIo`.

**Comment by PaleoCrafter** [comment]
I'm not sure we should discard `NbtIo` based on the opinion of a single person (especially given the public opinion as indicated by the upvotes on this issue). If it really is not an option, maybe we should go with something like `NBTStreams`/`NbtStreams`? The utilities are not limited to streams, but you could argue that the file case is just a special instance of streams.

**Comment by Pokechu22** [comment]
Yeah, if `Io` is the problem then even `NbtStreamTools` or anything like that whatever is fine.  The compressed part definitely has to go though.

**Comment by phase** [comment]
If it's still a class that contains tools for modifying/using NBT streams, `NbtStreamTools` makes sense.

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
