### ISSUE TITLE
Block.onEntityCollidedWithBlock(World, BlockPos, Entity) incorrectly remapped in 1.8+

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#64]
I know this has and will bite a lot of people, but in Block there are actually *two* overloads of onEntityCollidedWithBlock: one that takes (World, BlockPos, Entity), and another that takes (World, BlockPos, IBlockState, Entity).

The dangerous part is that mods porting from 1.7.x will automatically choose the first overload, since it's a straight conversion from World, x, y, z, Entity. However, it is actually the second (state-aware) one that inherits the old functionality of 1.7's onEntityCollidedWithBlock.

If we look at the state-less overload in 1.8.x, only stairs, slime blocks, and Redstone ore use it, with redstone ore using it to trigger active state. Looking at vanilla code, the state-less overload is called only when the entity is walking over the block, and its uses exactly matches the old 1.7 Block.onEntityWalking.

Since this overload is confusing and potentially may introduce hidden issues (still compiles, behavior broken) into mods porting from 1.7 I propose this state-less overload be renamed back to its 1.7 name, onEntityWalking.

**Comment by williewillus** [comment]
bump on this as I think lots of people are getting bitten/getting hidden bugs introduced, especially as they start porting to 1.8+

**Comment by matthewprenger** [comment]
Fixed:
`func_176199_a`: `onEntityCollidedWithBlock` -> `onEntityWalk`
