### ISSUE TITLE
Main: isNullOrEmpty → isNotEmpty

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#642]
\*facepalm\*

- [ ] `func_110121_a` in `net.minecraft.client.main.Main`: `isNullOrEmpty` &rarr; `isNotEmpty`

```java
	private static boolean isNullOrEmpty(String str) {
		return str != null && !str.isEmpty();
	}
```

The new name is the same as Apache Commons StringUtils.isNotEmpty.  It could be `isNotNullOrEmpty`, but I think the (newly-revised) javadoc is enough to clarify that it also checks for null.

Note that <ruby><rb>`StringUtils.isNullOrEmpty`</rb><rp> (</rp><rt>func_151246_b</rt><rp>)</rp></ruby> _is_ correctly named and does not need to be changed.

**Comment by kashike** [comment]
- [x] `func_110121_a`: `isNullOrEmpty` → `isNotEmpty`
