### ISSUE TITLE
Keep structure classes in separate package

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#643]
I'm not a fan of these being thrown in `world.gen.feature` along with all the other feature decoration classes - there's plenty of classes in that package already, and there's a clear grouping that's otherwise lost.

Can we keep `world.gen.structure`, or at least have a separate `structure` subpackage?

**Comment by kashike** [comment]
https://github.com/MinecraftForge/MCPConfig/pull/14
