### ISSUE TITLE
class name: BlockModelShapes → ?

### ISSUE THREAD

**Issue by quat1024** [ModCoderPack/MCPBot-Issues#645]
I have no idea if this class exists in 1.13 yet... On the off chance that it still does...

`net.minecraft.client.renderer.BlockModelShapes → ???`

Heard there was a last call for 1.13 class name changes so, hi :wave:

Honestly this class is a bit of a mess, so it's tricky to put a name to it. It seems to be doing two things at once. The main attraction is the big pile of block statemappers at the bottom, in `registerAllBlocks()`. Forge hooks this to add custom block state mapper functionality and I referenced this class a lot when writing my first statemappers.

But there's also `getTexture`, used to determine the texture of nether portal particles, digging particles, and the suffocation overlay. The point of that method seems to be to smooth out statemapper edge cases; every single block special-cased in there uses a TESR and has an empty statemapper. There's also a few more helper functions dumped in there, like `getModelForState`, which returns a missing model for blockstates that don't have a model instead of `null`.

So of course this makes the name `BlockModelShapes` a bit of a mystery. Whatever this class wants to be, it has nothing to do with block models, and certainly nothing to do with their *shapes*, only statemappers. It might be a holdover from 1.7 days, but I don't know, I wasn't modding then.

Possibly `StateMapperHelpers`?

**Comment by tterrag1098** [comment]
It does more than statemappers, it also holds a state->model cache. Maybe keeping it simple is the best, just `BlockModelHelper`? Naming it with "StateMapper" seems misleading as it's slightly more than that.

**Comment by PaleoCrafter** [comment]
In fact, in 1.13, there will be no more state mappers (to my awareness). Maybe something like `BlockModelStore` (somewhat according to the `bakedModelStore` field) would be good? `Helper` to me signifies a pure utility class (i.e. mostly static methods, stateless methods), which this class obviously isn't.

**Comment by InsomniaKitten** [comment]
I think `StateModelCache` might be a more appropriate name, given that it holds `IBlockState` keys not `Block` keys, and the values in the implementation are just references to existing values in the model registry. The class essentially works as a cache to avoid recreation of a `ModelResourceLocation` instance every time a model is queried for an `IBlockState`.

**Comment by williewillus** [comment]
`ItemModelMesher`'s name should follow this one, since that's the respective baked model cache for items (custom meshers are gone in 1.13 so all IMM does is cache)

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
