### ISSUE TITLE
Broken parent SRG mappings

### ISSUE THREAD

**Issue by jamierocks** [ModCoderPack/MCPBot-Issues#646]
`net/minecraft/entity/monster/EntityDrowned` inherits from both `net/minecraft/entity/monster/EntityZombie` and `net/minecraft/entity/IRangedAttackMob`. Both of which define a method of identical signature (`s (Z)V` in 1.13-pre3). However they are given different SRG names, `func_184733_a` and `func_184724_a`.

**Comment by LexManos** [comment]
Alright I looked into the issue, and its a interesting case I didn't think about.
I have updated MappingVerifier to detect these cases. https://github.com/MinecraftForge/MappingVerifier/commit/5deac372ebee4e507d882c571a3aafd2478333f0
I have also updated MCPConfig to fix all these issues. https://github.com/MinecraftForge/MCPConfig/commit/67807bae30c6027890092203220e982d376f34bb
There was more then Just EntityDrowned, There was also an issue with net/minecraft/util/datafix/optics/Lens/func_206191_a
