### ISSUE TITLE
[1.13] net.minecraft.world.chunk.ChunkPrimerWrapper -> ChunkPrimerView

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#647]
Delegates reads to another `IChunk` and satisfies the interface of a `ChunkPrimer`, but silently drops all mutations

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
