### ISSUE TITLE
A new name for func_184222_aU

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#649]
`func_184222_aU` (`isNonBoss`) is, obviously, incorrectly named, as shown in 1.13 by `EntityFishHook` overriding this method to `false`.

This method seems to be whether the entity can change dimensions/use portals, as seen by the usages:
- `net.minecraft.block.BlockEndPortal#func_196262_a`
- `net.minecraft.block.BlockPortal#func_196262_a`

**Comment by marcelelements** [comment]
Suggestion:
- [ ] isNonBoss -> canLeaveDimension

**Comment by williewillus** [comment]
how about `canUsePortals`

`canLeaveDimension` sounds like the entity in question *can't* be teleported from a technical perspective, whereas `canUsePortals` implies it's just a gameplay restriction (e.g. nothing prevents withers from using portals besides mojang not wanting them to)

**Comment by bs2609** [comment]
Does that apply to fish hooks though?
