### ISSUE TITLE
Block.blockRegistry (field_149771_c) -> Block.REGISTRY

### ISSUE THREAD

**Issue by SoniEx2** [ModCoderPack/MCPBot-Issues#65]
For the next Minecraft update, Block.blockRegistry aka field_149771_c, should be renamted to Block.REGISTRY. It is a `public static final` field, after all.

Also, RegistryNamespacedDefaultedByKey.getObject() should be renamed RegistryNamespacedDefaultedByKey.byKey() (and I think the class name should be changed because damn that's an ugly name. I hope that's not the name used by mojang.)

**Comment by diesieben07** [comment]
Just because the field is `static final` means it's a constant.
`static final String FOO = "foo"` is a constant.
`static final String[] bar = { "foo" }` is _not_ a constant, because arrays are mutable.

Why `byKey`? Why not `get` to conform with the standard `java.util.Map` interface?

**Comment by SoniEx2** [comment]
`<Grum> if you want to do it by RL; Block.REGISTRY.byKey(...)`. That says some things.

**Comment by SoniEx2** [comment]
@diesieben07 Also I think you might be confusing the concept of "constant" and the concept of "immutable". "Constant" is a variable that never changes, "immutable" is a value that never changes.

**Comment by diesieben07** [comment]
Well, I am certainly not [the only one who thinks like this](https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names).
And just because Mojang names it this internally is no excuse.

**Comment by SoniEx2** [comment]
@diesieben07 Then name it "registry" instead. There's no conflict there. Same thing should be done for Items. (Sorry if you don't like me trying to make the deobfuscated names align closer to Mojang's names)

**Comment by diesieben07** [comment]
I am fine with `registry`. Very fine actually. Also very fine with aligning names with Mojang's names. But `byKey` is awful.

**Comment by SoniEx2** [comment]
It also makes sense. Registry.byKey(keyObject) Registry.byValue(valueObject) etc.

**Comment by diesieben07** [comment]
`get` and `getKey` would be much better. `byKey` tells you nothing about what the method returns / what it does.

**Comment by SoniEx2** [comment]
It tells you how you're accessing the registry. byKey means you're trying to access it with a key, byValue means you're trying to access it with a value.

**Comment by diesieben07** [comment]
But you _know_ what you are giving it. You do _not_ know what the method will give you in return.

**Comment by SoniEx2** [comment]
It's a registry.

**Comment by diesieben07** [comment]
Sure. Let's call the method `zonk` then. It's a registry.

**Comment by liach** [comment]
@SoniEx2 Please stop giving such suggestions. If you want everything to match "Mojang name" then ask MCP to rename all entity AIs, `BlockState` (Grum called it `BlockStateDefinition`), and even `EntityPlayer` as they are not in such "Mojang name"s.

**Comment by SoniEx2** [comment]
@liach I think it's implied that that's what I want. I want to be able to compile mods both in MCP's codebase and Mojang's codebase.

**Comment by bspkrs** [comment]
We (the MCP devs) already HAVE the _ability_ to use Mojang's names... we get a full obfuscation map for every release. We are not _allowed_ to just use them, otherwise we will stop receiving them altogether. That's the explanation I was given when I asked why we don't just use them already.

**Comment by matthewprenger** [comment]
#134
