### ISSUE TITLE
[1.13] NextTickListEntry changes

### ISSUE THREAD

**Issue by ZeroMemes** [ModCoderPack/MCPBot-Issues#654]
In 1.12, ``pendingTickListEntriesThisTick`` is assigned to a field typed ``List<NextTickListEntry>``, however in 1.13 it has been reassigned to a field typed ``ServerTickList<Block>`` along with the addition of another field typed ``ServerTickList<Fluid>``. Here are my proposed names:

- [ ] `field_94579_S` in `WorldServer`: `pendingTickListEntriesThisTick` -> `pendingTickListBlocks`
- [ ] `field_205342_P` in `WorldServer`: `pendingTickListFluids`
- [ ] ``func_151351_a`` in ``NextTickListEntry``: ``getBlock`` -> ``getObject``
- [ ] ``field_151352_g`` in ``NextTickListEntry``: ``block`` -> ``object``

**Comment by ZeroMemes** [comment]
Sounds much better than my names

**Comment by ZeroMemes** [comment]
Another relevant change.

- [ ] ``func_151351_a`` in ``NextTickListEntry``: ``getBlock`` -> ``getObject``

**Comment by gabizou** [comment]
- [ ] `func_151351_a` : `getBlock` -> `getTarget`?

I'm tempted to name it source because it's the targeted type for the scheduled entry, and the implementation checks if the type is still valid for that position, otherwise if the block/fluid has changed it doesn't do anything.

**Comment by williewillus** [comment]
I like target more than source, personally

**Comment by gabizou** [comment]
I'd be fine with `getTarget`, it makes sense that the entry *targets* an object, whether or not it ticks the target is dependent if the target still is valid for the entry's context.

**Comment by kashike** [comment]
- [x] `field_151352_g`: `block` &rarr; `target`
- [x] `func_151351_a`: `getBlock` &rarr; `getTarget`
