### ISSUE TITLE
World.isRemote -> World.isClient

### ISSUE THREAD

**Issue by Runemoro** [ModCoderPack/MCPBot-Issues#655]
- [ ] `field_72995_K ` in `net.minecraft.world.World`: `isRemote` -> `isClient`

The field is set from only two places, the constructors of the `WorldClient` and `WorldServer` subclasses:

![isRemote](https://user-images.githubusercontent.com/2412762/43480787-46cecc68-94d2-11e8-919b-d63dab547240.png)

Also, the name `isRemote` is simply wrong. If I understand correctly, the word "remote" means "on the other side" (so client-side in server-side code, and server-side from client-side code). That would mean that the field should always be false, since `WorldServer`s are only used server-side and `WorldClient`s are only used client-side.

**Comment by ZeroMemes** [comment]
I would recommend taking a look at #42. lol

**Comment by tterrag1098** [comment]
`isClient` would be inaccurate, as most would consider the integrated server to be on the "client"

Plus, as said, the name is never going to be changed, as was lengthily discussed in #42

**Comment by Runemoro** [comment]
No, `Minecraft.world.isRemote` is true even when called on the client thread, despite the client thread not being remote to itself.

**Comment by tterrag1098** [comment]
That makes no sense at all. Again the server is in control, the data is always *relative* to the server. The client world needs to be able to introspectively know if it is remote to the server. The client world is NOT in control so it is remote. End of discussion.
