### ISSUE TITLE
Comment corrections

### ISSUE THREAD

**Issue by Gamebuster19901** [ModCoderPack/MCPBot-Issues#656]
- [ ] `func_186254_a` in `net.minecraft.world.gen.structure.template.Template`:
- [ ] `func_186255_a` in `net.minecraft.world.gen.structure.template.Template`:

func_186254_a should have it's comment changed to the below example because it doesn't just save the blocks, it also saves entities.
  

```
/**
 	* takes blocks from the world and puts their data into this template
	
	* also takes entities from the world and puts their data into this template, if takeEntities is true
*/
```

func_186255_a should have it's comment changed to the below example because the current comment is completely incorrect as it doesn't save blocks at all, it saves entities.

```
/**
	* takes entities from the world and puts their data into this template
*/
```

**Comment by Pokechu22** [comment]
You can freely rename comments using the bot, no need to report it here; just use `sm <method> <existingName> <comment>` (as long as the name matches the current name, you're free to set a new comment; similarly, if a method has no existing name you can add a new one)
