### ISSUE TITLE
FallbackResourceManager -> NamespaceResourceManager

### ISSUE THREAD

**Issue by Runemoro** [ModCoderPack/MCPBot-Issues#657]
- [ ] `net.minecraft.resources.FallbackResourceManager` -> `net.minecraft.resources.NamespaceResourceManager`
- [ ] ~~`net.minecraft.resources.SimpleReloadableResourceManager` -> ?~~

The name `FallbackResourceManager` is inaccurate. It implies that it is a fallback that's only used when the main resource manager fails. Instead, one instance of the class is created for each resource namespace and stored in a map, allowing to efficiently find resources by searching in only the packs providing those namespaces.

~~There is also nothing "simple" about the `SimpleReloadableResourceManager`. A better name would be `NamespacedResourceManager` (though that's too similar to `NamespaceResourceManager`), `CompositeResourceManager`, `RootResourceManager`. or just `ResourceManager`.~~

Here are the methods from `SimpleReloadableResourceManager` showing how it works.
```java
    private final Map<String, FallbackResourceManager> namespaceResourceManagers;

    public void addResourcePack(IResourcePack resourcePack) {
        for (String namespace : resourcePack.getResourceNamespaces(type)) {
            resourceDomains.add(namespace);
            FallbackResourceManager resourceManager = namespaceResourceManagers.get(namespace);
            if (resourceManager == null) {
                resourceManager = new FallbackResourceManager(type);
                namespaceResourceManagers.put(namespace, resourceManager);
            }
            resourceManager.addResourcePack(resourcePack);
        }
    }

    @Override
    public IResource getResource(ResourceLocation resourceLocation) throws IOException {
        FallbackResourceManager resourceManager = namespaceResourceManagers.get(resourceLocation.getNamespace());
        if (resourceManager != null) {
            return resourceManager.getResource(resourceLocation);
        }
        throw new FileNotFoundException(resourceLocation.toString());
    }
```

Here are fully deobfuscated versions of [SimpleReloadableResourceManager](https://paste.dimdev.org/kiququsido.java) and [FallbackResourceManager](https://paste.dimdev.org/uveqorepam.java)

**Comment by kashike** [comment]
:+1: for `FallbackResourceManager` -> `NamespaceResourceManager`.

`SimpleReloadableResourceManager` has an appropriate name - `Simple` is a common prefix for implementations of interfaces (`IReloadableResourceManager` in this case), just like `Impl` is a common suffix (`ReloadableResourceManagerImpl` would be the name in that case).

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
