### ISSUE TITLE
"EntityCreature", "EntityLiving", and "EntityAINearestAttackableTarget"

### ISSUE THREAD

**Issue by Runemoro** [ModCoderPack/MCPBot-Issues#658]
The following string reveals the mojang names for "EntityCreature", "EntityLiving", "EntityAINearestAttackableTarget".
```java
    public EntityAIFindEntityNearestPlayer(final EntityLiving entityLivingIn) {
        this.entityLiving = entityLivingIn;
        if (entityLivingIn instanceof EntityCreature) {
            LOGGER.warn("Use NearestAttackableTargetGoal.class for PathfinerMob mobs!");
        }
```
We can also see that entities do not have an "Entity" prefix in the vanilla code, but that might not be worth changing in MCP.

- [ ] EntityLiving -> EntityMob

This is a more accurate name which would make it clear that EntityPlayer is not a subclass of it. Someone may think think that EntityPlayer extends EntityLiving since a player is living, but not that EntityPlayer extends EntityMob since a player is not a mob.

- [ ] EntityMob -> EntityHostileMob

"Mob" refers to both hostile and non-hostile creatures in Minecraft. This change would make it clear that this subclass of EntityLiving is intended for hostile mobs only. The change would be necessary if EntityLiving is renamed to EntityMob.

- [ ] EntityCreature -> EntityPathfinderMob

The current name doesn't describe how EntityCreature is different from EntityMob or EntityLiving. Changing to the vanilla name (but with the `Entity` prefix) would help clear up this confusion.

- [ ] EntityLivingBase -> EntityLiving

If EntityLiving is renamed to EntityMob, the "Base" suffix becomes unnecessary. EntityLiving makes sense as a superclass for both EntityMob and EntityPlayer as they are obviously both living.

**Comment by kashike** [comment]
https://github.com/ModCoderPack/MCPBot-Issues/issues/92

**Comment by kashike** [comment]
Please open a separate issue for the goals.

**Comment by Runemoro** [comment]
Done: https://github.com/ModCoderPack/MCPBot-Issues/issues/659

**Comment by bs2609** [comment]
> EntityLiving makes sense as a superclass for both EntityMob and EntityPlayer as they are obviously both living.

The issue here is `EntityArmorStand` which is very obviously not living, but also inherits from `EntityLivingBase`.

**Comment by Pokechu22** [comment]
[wiki.vg's entity metadata page](https://wiki.vg/Entity_metadata) uses a different set of names, for reference.  I'm not completely happy with them but they're useful for comparison.

* `EntityLivingBase` = `Living`
    * Armor stands subclass this.
* `EntityLiving` = `Insentient`
* `EntityAmbientCreature` = `Ambient`
    * Bats subclass this; not in the current report
* `EntityWaterMob` = `WaterMob`
    * Subclasses Creature in 1.13, but Insentient in 1.12.  The entity metadata article currently targets 1.12.
* `EntityMob` = `Monster`
* `EntityAnimal` = `Animal` (and ageable also matches; these aren't included here)
* `EntityCreature` is not listed as it does not provide metadata.

**Comment by kashike** [comment]
`EntityLiving` = `Mob`

**Comment by liach** [comment]
mob means mobile not monster, so i agree with kashike

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
