### ISSUE TITLE
EntityAI -> Goal

### ISSUE THREAD

**Issue by Runemoro** [ModCoderPack/MCPBot-Issues#659]
We can see that the vanilla name for "EntityAI" is "Goal":

    public EntityAIFindEntityNearestPlayer(final EntityLiving entityLivingIn) {
        this.entityLiving = entityLivingIn;
        if (entityLivingIn instanceof EntityCreature) {
            LOGGER.warn("Use NearestAttackableTargetGoal.class for PathfinerMob mobs!");
        }

An "entity AI" would better describe the set of all goals and their priorities. Changing to the mojang name would make is clearer that an entity can have more than one goal.

**Comment by kashike** [comment]
`goalSelector` and `targetSelector`, as the profiler steps show, most likely.

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
