### ISSUE TITLE
IChunk.func_201591_a: addBlockEntity -> addTileEntity

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#660]
`IChunk.func_201591_a`: `addBlockEntity` -> `addTileEntity`

The other overload is `addTileEntity`, and we've been through the discussion about blockentity vs tileentity. So it should be named as the old ones.

cc @Runemoro

**Comment by Runemoro** [comment]
I changed the name to `addTileEntity`.

**Comment by Runemoro** [comment]
I changed it to `addTileEntity`.
