### ISSUE TITLE
ChunkStatus.field_202133_m: chunkDistanceAroundForTask -> taskRadius

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#661]
`ChunkStatus.field_202133_m`: `chunkDistanceAroundForTask` -> `taskRadius`

too long

cc @Runemoro

**Comment by Runemoro** [comment]
The value of that field is `(length in side of square in chunks - 1)/2`.

`taskRadius` doesn't make it clear that the center chunk is excluded, and isn't completely accurate since the radius is measured from the center to a corner in a square (this would be the [apothem](https://en.wikipedia.org/wiki/Apothem)). It can also give the impression that a task with a higher "task radius" will affect more chunks than just the center chunk, but in reality only the center chunk is affected by the task, and the chunks around it are only read.

**Comment by Runemoro** [comment]
I changed the name of the field and getter to `taskMargin` with the following comment: `Distance in chunks between the edge of the center chunk and the edge of the chunk region needed for the task. The task will only affect the center chunk, only reading from the chunks in the margin.` for the following reasons:

 - The word "radius" in MinecraftServer.getSpawnRadius (and in general) includes the center. A radius of 1 is a 1x1 square. In this case, a radius of 1 would be a 3x3 square, so it wouldn't make sense to reuse the same word. If we really wanted to use the word "radius", the correct name would be `taskRadiusMinusOne`
 - The word "margin" makes it clear that the surrounding chunks won't be affected by the tasks, the same way you don't write in the margin of the sheet of paper.
 - The word "margin" gives a better mental image of what it represents: a square region around the area that's affected by the chunk
 - It's only a coincidence that the name taskRadius is not completely inaccurate. If the affected area was a 2x2 square of chunks, the word "radius" would be completely false, and if the area was a 2x1 square of chunks, then "radius" would not even make sense at all.

However, feel free to change the name to something else if you disagree.

**Comment by kashike** [comment]
How about `range`?

**Comment by Runemoro** [comment]
The problem with `range` is that it doesn't accurately represent the meaning of the field. The field's value is a measurement of how much extra information the task needs about the surrounding chunks. It's the width (outer radius - inner radius) of the ring surrounding the center chunk, not the total size of the task. 

In other words, if Mojang increased the base size of chunk tasks to 2x2, the values of that field would stay the same. The word "range" implies that it should increase as the base area of tasks increases.

**Comment by williewillus** [comment]
resolved to `range` via discord discussion
