### ISSUE TITLE
IBlockState.func_196947_b: onBlockBreak -> onReplaced

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#662]
`IBlockState.func_196947_b`: `onBlockBreak` -> `onReplaced`
`Block.func_196243_a`: `onBlockBreak` -> `onReplaced`

This name is easily confused with onBlockHarvested/onPlayerDestroyed. The 1.12 name is `breakBlock`, which is also not accurate. This method is called whenever the block is replaced in the chunk by another block. Vanilla uses it to cleanup TE's, break multiblocks, etc.

cc @Runemoro

**Comment by Runemoro** [comment]
Changed both of these.

**Comment by williewillus** [comment]
looks like the block one didn't get changed (func_196243_a)

**Comment by kashike** [comment]
done
