### ISSUE TITLE
ChunkPrimer.func_201579_g: getTileEntityNBT -> getDeferredTileEntity

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#663]
`ChunkPrimer.func_201579_g`: `getTileEntityNBT` -> `getDeferredTileEntity`

The reason why this class has maps for both TE objects and NBT compounds is that the NBT compounds are supposed to be deserialized only when the chunk is post processed. Therefore, I've named the related fields and methods in Chunk and ChunkPrimer after "deferred tile entity". Rename this one to follow suit.

cc @Runemoro

**Comment by Runemoro** [comment]
Changed it to `getDeferredTileEntity`.
