### ISSUE TITLE
IBlockState.func_200015_d: isFullBlock -> isOpaqueCube

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#664]
IBlockState.func_200015_d: isFullBlock -> isOpaqueCube

Change this match its old name, since there could be confusion as `Block.isFullBlock` is also a field in 1.12 that was removed in 1.13.

isOpaqueCube sucks, but it maintains consistency with 1.12 till we find a better name

Compare usage in RenderChunk.rebuildChunk between 1.12 and 1.13 to see that this is accurate

cc @Runemoro

**Comment by Runemoro** [comment]
Changed this too.
