### ISSUE TITLE
CustomBossEvent -> CustomBossBar, CustomBossInfo, BossInfoCustom

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#666]
The parent class represents a custom boss bar added through the new /bossbar commands, and thus should have similar naming to its parent class.

Also rename `CustomBossEvents` to be the plural form of whatever we decide here.

**Comment by kashike** [comment]
The name of these is `BossEvent`, as shown by the NBT tag `CustomBossEvents`.

**Comment by kashike** [comment]
- [ ] `BossInfo` -> `BossEvent`
- [ ] `BossInfoClient` -> `ClientBossEvent`
- [ ] `BossInfoServer` -> `ServerBossEvent`

**Comment by Runemoro** [comment]
The correct name is for CustomBossEvent is CustomBossbar, as shown by the BossBarCommand:

```java
    private static int func_201414_a(CommandSource source, CustomBossEvent p_201414_1_) {
        source.sendFeedback(new TextComponentTranslation("commands.bossbar.get.value", p_201414_1_.func_201369_e(), p_201414_1_.getValue()), true);
        return p_201414_1_.getValue();
    }
```
`"commands.bossbar.get.value": "Custom bossbar %s has a value of %s",`

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
