### ISSUE TITLE
IBucketPickupHandler.func_204508_a: getFluid -> pickupFluid

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#667]
IBucketPickupHandler.func_204508_a: getFluid -> pickupFluid

When you see this method in a subclass without seeing the interface, it looks like a getter, so I was confused when I saw it performing mutations to the world (setBlockState air). Rename so it makes clearer that the fluid is being taken out of the world.

alternatives like extractFluid or whatever are also fine by me, as long as it shows mutation occurring.

cc @runemoro

**Comment by kashike** [comment]
`takeFluid`?

**Comment by Runemoro** [comment]
Renamed it to pickupFluid for now since it's at least better than getFluid, but you can change it to takeFluid if you prefer.

**Comment by williewillus** [comment]
I'm fine with pickupFluid
