### ISSUE TITLE
Block.func_196262_a: onCollisionWithEntity -> onEntityCollidedWithBlock

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#668]
`Block.func_196262_a`: `onCollisionWithEntity` -> `onEntityCollidedWithBlock`
Rename to match old name, and the IBlockState name which didn't change

cc @runemoro

**Comment by kashike** [comment]
This was changed to `onEntityCollision` in 1.12.

**Comment by Runemoro** [comment]
Renamed to `onEntityCollision`.
