### ISSUE TITLE
BlockHorizontal.FACING -> HORIZONTAL_FACING

### ISSUE THREAD

**Issue by Runemoro** [ModCoderPack/MCPBot-Issues#670]
In BlockHorizontal: `public static final DirectionProperty FACING = BlockStateProperties.HORIZONTAL_FACING;`

This should be renamed to `HORIZONTAL_FACING`, such that the `field_196359_a` in its subclass `BlockCarvedPumpkin` can be renamed to `FACING`: `public static final DirectionProperty field_196359_a = BlockHorizontal.FACING;`

- [ ] `field_185512_D` in `net.minecraft.block.BlockHorizontal`: `FACING` -> `HORIZONTAL_FACING`
- [ ] `field_196359_a` in `net.minecraft.block.BlockCarvedPumpkin`: `field_196359_a` -> `FACING`

**Comment by kashike** [comment]
- [x] `field_185512_D`: `FACING` -> `HORIZONTAL_FACING`
- [x] `field_196359_a`: `field_196359_a` -> `FACING`
