### ISSUE TITLE
ShapeUtils -> VoxelShapes

### ISSUE THREAD

**Issue by InsomniaKitten** [ModCoderPack/MCPBot-Issues#671]
Suggested rename of `ShapeUtils` to `VoxelShapes`. This follows Guava's factory class design, which has long been proven to be fluent and readable approach to object factories and utility classes - see: [Strings](https://github.com/google/guava/blob/master/guava/src/com/google/common/base/Strings.java), [Objects](https://github.com/google/guava/blob/master/guava/src/com/google/common/base/Objects.java), [Lists](https://github.com/google/guava/blob/master/guava/src/com/google/common/collect/Lists.java), etc.

**Comment by kashike** [comment]
https://github.com/MinecraftForge/MCPConfig/commit/3292260f68f664e93f44bcaa346299b76e8c1d83

- [x] `net/minecraft/util/math/shapes/ShapeUtils` &rarr; `net/minecraft/util/math/shapes/VoxelShapes`
