### ISSUE TITLE
ParticleManager

### ISSUE THREAD

**Issue by Runemoro** [ModCoderPack/MCPBot-Issues#675]
- [ ] `func_178930_c` in `net.minecraft.client.particle.ParticleManager`: `registerVanillaParticles` -> `registerParticleFactories`
- [ ] `field_178932_g` in `net.minecraft.client.particle.ParticleManager`: `particleTypes` -> `particleFactories`

The `registerVanillaParticles` method actually registers particle *factories* for each particle type. The particles themselves are registered in `ParticleType`. The `Map<ParticleType, IParticleFactory> particleTypes` is actually used to get the particle factory by particle type, so it should be renamed to `particleFactories`.

**Comment by kashike** [comment]
- [x] `field_178932_g`: `particleTypes` -> `factories`
- [x] `func_178930_c`: `registerVanillaParticles` -> `registerFactories`
- [x] `func_199283_a`: `registerParticleFactory` -> `registerFactory`
