### ISSUE TITLE
func_203096_a to causeTridentDamage

### ISSUE THREAD

**Issue by strikerrocker** [ModCoderPack/MCPBot-Issues#676]
`func_203096_a -> causeTridentDamage`
 Named similar to other damage functions in DamageSource apparent from the string in method signature 

`public static DamageSource func_203096_a(Entity p_203096_0_, @Nullable Entity p_203096_1_) {
        return (new EntityDamageSourceIndirect("trident", p_203096_0_, p_203096_1_)).setProjectile();
}`

**Comment by kashike** [comment]
This was an unnamed method - you could have set it yourself. I've gone ahead and set it to `causeTridentDamage`.
