### ISSUE TITLE
OpenGlHelper.func_77474_a: initializeTextures -> init / readCapabilities ?

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#678]
Called from `Minecraft.init()`, this is mostly about setting up `OpenGlHelper` state based on querying `GLContext.getCapabilities()`. Not at all limited to textures, needs a better name.

Any other ideas?

**Comment by kashike** [comment]
- [x] `func_77474_a`: `initializeTextures` -> `init`
