### ISSUE TITLE
p_148544_2_ has an incorrect name

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#68]
`p_148544_2_` is currently named `isChat`, but should be `isSystem` (currently the reverse) to describe what it actually is.
`func_148916_d` is currently named `isChat`, but should be `isSystem` (currently the reverse) to describe what it actually is.

**Comment by matthewprenger** [comment]
Fixed:
func_148916_d: isChat -> isSystem
p_148544_2_: isChat -> isSystem
