### ISSUE TITLE
The troubling trio of Block.getActualState replacements

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#680]
We had lengthy discussions on discord about this, which partially resolved one of the three methods here, but after some thinking I'm still quite uncomfortable about the other two. Here we go.

### validateNeighborBlocks (IBlockState.func_196946_a, Block.func_196242_c)
* When is it called?
  * Called on the newly arriving block in setBlockState if flag 16 is off
* What does it do?
  * Loop through all 6 neighbors, calling `updatePostPlacement` on them, and setting that result into the world.
  * Example: Fences return a state connecting to the original block, observers schedule their pulse if the original block was put in front of their "observing side"
* Why is this weird?
  * It's not *just* validation (though a block could return AIR if it wanted to break), it's performing things `getActualState` used to do like making connections, as well as core gameplay mechanics like observer pulses, scheduling fluid ticks, and solidifying concrete powder. "Validate" is too light of a name.
* Suggested naming
  * Unsure, probably something that implies its relationship with `updatePostPlacement` and has a more powerful tone than "validate". Perhaps "react" or also "update".

---

### updatePostPlacement (IBlockState.func_196956_a, Block.func_196271_a)
* When is it called?
  * By `validateNeighborBlocks` on its 6 neighbors
* What does it do?
  * Examine the passed in side and the caller/neighbor on that side, and returning a new blockstate with the block's reactions to the caller. For example, fences and walls form connections to the caller, concrete powder returns real concrete if wet, etc...
  * But, can also perform side effects like scheduling fluid ticks (waterlogged blocks), scheduling block ticks (observers), etc.
* I think this name is acceptable; the name can be improved, but not sure to what. Whatever its name is, needs to strongly show its connection to the above method

---

### validatePlacement (IBlockState.func_196948_b, Block.func_196248_b)
* When is it called?
  * Called on the departing block in setBlockState when flag 16 is off
  * Called on the newly arriving block in setBlockState when flag 16 is off
* What does it do?
  * The existing comment on this method was blatantly wrong, stating that redstone dust uses it to break itself. I've updated the comment correcting this
  * The only current usage it has is for redstone dust to update its visual connection states (something formerly done in getActualState). It does not break itself.
* Why is this confusing?
  * There's no validating being done, just redstone dust changing its visual connection state 
  * Why does dust implement both this *and* `updatePostPlacement`, what's it do?
  * Why is it called on the departing block?
* Suggested names
  * Unsure. Anything except the existing one, which is wrong. It's not validating, it's definitely *doing* things

**Comment by williewillus** [comment]
cc @gabizou

**Comment by williewillus** [comment]
How about, respectively

`updateNeighbors` + keep existing comment (For all neighbors, have them react to this block's existence, potentially updating their states as needed. For example, fences make their connections to this block if possible and observers pulse if this block was placed in front of their detector)

`updateForNeighbor` + keep existing comment (Update the provided state given the provided neighbor facing and neighbor state, returning a new state. For example, fences make their connections to the passed in state if possible, and wet concrete powder immediately returns its solidified counterpart. Note that this method should ideally consider only the specific face passed in.)

`updateNeighborsAuxiliary` + clarify in a comment

**Comment by williewillus** [comment]
also, update the methods for "old-style" block updates (flag 1/neighborChanged) noting this system

**Comment by gabizou** [comment]
I’d make the changes myself, but I can’t get longer descriptions without my irc client trimming messages.

**Comment by Pokechu22** [comment]
@gabizou You should be able to set longer ones when connected via DCC; it at least works for me over weechat.  Just as an FYI.

**Comment by gabizou** [comment]
Just changed them. Can't close the issue, but could use discussion for what the comments should be. Finally figured out how to get DCC working hahah

**Comment by williewillus** [comment]
this is resolved now
