### ISSUE TITLE
Block.blockState -> blockStateContainer

### ISSUE THREAD

**Issue by Runemoro** [ModCoderPack/MCPBot-Issues#682]
- [ ] `field_176227_L` in `net.minecraft.block.Block`: `blockState` -> `stateContainer`
- [ ] `func_176194_O` in `net.minecraft.block.Block`: `getBlockState` -> `getStateContainer`

It seems like that field and its getter were never renamed [when BlockState was changed to BlockStateContainer](https://github.com/ModCoderPack/MCPBot-Issues/issues/127).

**Comment by kashike** [comment]
- [x] `field_176227_L`: `blockState` -> `stateContainer`
- [x] `func_176194_O`: `getBlockState` -> `getStateContainer`
