### ISSUE TITLE
IWorldWriter.setBlockToAir -> removePhysicalBlock?

### ISSUE THREAD

**Issue by gabizou** [ModCoderPack/MCPBot-Issues#684]
- [ ] `func_175698_g ` in `IWorldWriter`: `setBlockToAir` -> `removeBlock`

Reasoning being: the `World` implementation does not actually remove air, it does this:
```java
    public boolean setBlockToAir(BlockPos pos) {
        IFluidState ifluidstate = this.getFluidState(pos);
        return this.setBlockState(pos, ifluidstate.getBlockState(), 3);
    }
```

It's not really setting to air, since there can be water or lava existing at that position, and it would just fill that position with the full fluid state for that block. 

Of course, this does have some changes for `WorldGenRegion` doing the opposite, but that's more or less due to world generation needing to ensure that the block is safely removed, if not scheduled for an update by the chunk primer.

Granted, this method has been called `setBlockToAir` since 2014, but the target method no longer does what it was originally doing. I personally believe the intent is to simply "remove the block".

**Comment by kashike** [comment]
- [x] `func_175698_g`: `setBlockToAir` -> `removeBlock`
