### ISSUE TITLE
GuiSlot.getEventListeners → getEntries

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#685]
While this returns a `List<? extends IGuiEventListener>` in `GuiSlot`, the (newly generic) `GuiListExtended<E>` has it return a `List<E>`, more specifically its <ruby><rb>entries</rb><rp> (</rp><rt>field_195087_v</rt><rp>)</rp></ruby>.  `getEventListeners` is, as such, not a discoverable name for its actual purpose.

 - [ ] func_195074_b in `GuiSlot`: `getEventListeners` &rarr; `getEntries`

**Comment by Pokechu22** [comment]
On further looking, it turns out that the method isn't specified in `GuiSlot`, but rather `GuiEventHandler`, and thus applies to `GuiScreen` as well.  In that case, `getEntries` does not make sense; however, `getChildren` or something like that seems more general and probably would work.

**Comment by kashike** [comment]
- [x] `func_195074_b`: `getEventListeners` &rarr; `getChildren`
