### ISSUE TITLE
Block.isOpaque -> Block.doesShapeFillCube

### ISSUE THREAD

**Issue by Runemoro** [ModCoderPack/MCPBot-Issues#689]
The name `isOpaque` is completely wrong. The method is not at all related to opacity. It's used in the Block.isOpaqueCube method but also many other places like movement checks and `doesSideFillSquare`. It should be renamed to `doesShapeFillCube`.

```java
    public static boolean doesSideFillSquare(VoxelShape shape, EnumFacing side) {
        VoxelShape voxelshape = ShapeUtils.makeShapeFromSide(shape, side);
        return isOpaque(voxelshape);
    }

    public static boolean isOpaque(VoxelShape shape) {
        return !ShapeUtils.compare(ShapeUtils.fullCube(), shape, IBooleanFunction.ONLY_FIRST);
    }
```

Note that something like `isFullCube` would not work. This method returns true if the method fills the entire cube even if part of it exceeds the cube.

@gabizou

**Comment by liach** [comment]
Moreover, the block should not be hollow; it allows sides of blocks surrounding it not be stitched in rendering.
