### ISSUE TITLE
BreakingFour is a misnomer

### ISSUE THREAD

**Issue by tterrag1098** [ModCoderPack/MCPBot-Issues#69]
This class has nothing to do with the breaking texture specifically. It seems to just be a class which takes the verts of one baked quad, but replaces the UVs with that of another TextureAtlasSprite. I'd suggest maybe `RetexturedQuad`?

**Comment by LexManos** [comment]
1.9:
net/minecraft/client/renderer/block/model/BreakingFour -> BakedQuadTextured

**Comment by tterrag1098** [comment]
Sounds good to me :) Thanks!
