### ISSUE TITLE
Chunk generator names

### ISSUE THREAD

**Issue by Runemoro** [ModCoderPack/MCPBot-Issues#690]
The ChunkGeneratorType class (and also the names in the Buffet GUI) gives us names for the chunk generator classes:

```java
static {
    SURFACE = registerChunkGenerator("surface", ChunkGeneratorOverworld::new, Settings.SURFACE, true);
    CAVES = registerChunkGenerator("caves", ChunkGeneratorNether::new, Settings.CAVES, true);
    FLOATING_ISLANDS = registerChunkGenerator("floating_islands", ChunkGeneratorEnd::new, Settings.FLOATING_ISLANDS, true);
    DEBUG = registerChunkGenerator("debug", ChunkGeneratorDebug::new, Settings.DEBUG, false);
    FLAT = registerChunkGenerator("flat", ChunkGeneratorFlat::new, Settings.FLAT, false);
}
```

- ChunkGeneratorOverworld-> ChunkGeneratorSurface
- ChunkGeneratorEnd -> ChunkGeneratorFloatingIslands
- ChunkGeneratorNether -> ChunkGeneratorCaves

Until 1.12, these were used only to generate the overworld/end/nether, but they should be renamed now that they've become more flexible in 1.13.

An advantage of this would be that modders know they can use the "caves" chunk generator to generate a cave world instead of thinking it can only be used for the nether.

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
