### ISSUE TITLE
GlowStoneFeature -> GlowstoneFeature

### ISSUE THREAD

**Issue by Runemoro** [ModCoderPack/MCPBot-Issues#691]
The block is named "Glowstone", not "Glow Stone". The other two classes with "glowstone" in their name are correctly named `BlockGlowstone` and `NetherGlowstone`.

**Comment by kashike** [comment]
https://github.com/MinecraftForge/MCPConfig/commit/3292260f68f664e93f44bcaa346299b76e8c1d83

- [x] `net/minecraft/world/gen/feature/GlowStoneFeature` &rarr; `net/minecraft/world/gen/feature/GlowstoneFeature`
