### ISSUE TITLE
ChunkCache -> Region

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#692]
Revealed by logging in the class:
```
throw new RuntimeException("This method should never be called here. No entity logic inside Region");
```

**Comment by kashike** [comment]
https://github.com/MinecraftForge/MCPConfig/commit/3292260f68f664e93f44bcaa346299b76e8c1d83

- [x] `net/minecraft/world/ChunkCache` &rarr; `net/minecraft/world/Region`
