### ISSUE TITLE
New names for text components

### ISSUE THREAD

**Issue by sjx233** [ModCoderPack/MCPBot-Issues#694]
As shown in their `toString` methods:

- [ ] `TextComponentBase` → `BaseComponent`
- [ ] `TextComponentString` → `TextComponent`
- [ ] `TextComponentTranslation` → `TranslatableComponent`
- [ ] `TextComponentScore` → `ScoreComponent`
- [ ] `TextComponentSelector` → `SelectorComponent`
- [ ] `TextComponentKeybind` → `KeybindComponent`

These names should be changed as well, to match the names above:

- [ ] `ITextComponent` → `IComponent`
- [ ] `TextComponentUtils` → `Components`
- [ ] `TextComponentTranslationFormatException` → `TranslatableComponentFormatException`

**Comment by Zidane** [comment]
Not sure I would rename ITextComponent to IComponent, it becomes too general and at first glance I'd never think IComponent would be for the Text framework.

That said, I was thinking to not do the bottom three changes and instead keep the stuff at the top with one change

`TextComponentBase` → `AbstractTextComponent`

Just my thoughts.

**Comment by Leviathan143** [comment]
Why not go halfway? MCP is trying to use vanilla names where we know them, but I agree that `TextComponent` is clearer than `Component `. So we would have

- [ ] `TextComponentBase` → `BaseTextComponent`
- [ ] `TextComponentString` → `TextTextComponent`
- [ ] `TextComponentTranslation` → `TranslatableTextComponent`
- [ ] `TextComponentScore` → `ScoreTextComponent`
- [ ] `TextComponentSelector` → `SelectorTextComponent`
- [ ] `TextComponentKeybind` → `KeybindTextComponent`
- [ ] `TextComponentUtils` → `TextComponents`
- [ ] `TextComponentTranslationFormatException` → `TranslatableTextComponentFormatException`

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
