### ISSUE TITLE
Simplication of IBlockState#withRotation/withMirror

### ISSUE THREAD

**Issue by InsomniaKitten** [ModCoderPack/MCPBot-Issues#695]
As an extension of https://github.com/ModCoderPack/MCPBot-Issues/issues/687

---
**`IBlockState`**
- [ ] `func_185907_a`: `withRotation` -> `rotate`
- [ ] `func_185902_a`: `withMirror` -> `mirror`

**`Block`**
- [ ] `func_185499_a`: `withRotation` -> `rotate`
- [ ] `func_185471_a`: `withMirror` -> `mirror`

---
Example applications:
- `state.rotate(Rotation.CLOCKWISE_180);`
- `state.mirror(Mirror.FRONT_BACK);`

I understand these suggestions could be considered controversial, but it doesn't hurt for them to be suggested. I personally feel the simplification still implies the semantics of the method call just as much as the current names do.

**Comment by phase** [comment]
Do they make a copy of the object _with_ the new attribute? If they do, `withX` would make more sense here. If not, throw them out!

**Comment by gabizou** [comment]
I can understand why there would be the side to keep `with`, because you're implying it's going to have the block state with the desired rotation/mirror, but you're avoiding the implication that it's a new instance.

I do understand wanting to keep it in line with the method `withProperty`. I'd wager to keep it as is.

**Comment by Leviathan143** [comment]
I think we should stick with the "with" prefix for these methods, as it implies that the method returns the [flyweight](https://en.wikipedia.org/wiki/Flyweight_pattern) with the attributes of the callee plus the rotation/mirroring. `rotate` and `mirror` imply that the callee is mutated.

**Comment by Zidane** [comment]
If those methods do perform a mutation of the callee then the `with` moniker gives the wrong implication, somewhat. If so, I would remove them myself.

`withProperty` is a different case as the state is not mutated.

**Comment by InsomniaKitten** [comment]
The rotation and mirroring should never cause mutations. Block states are immutable singletons. The logic executed by `withRotation` and `withMirror` are handled on a per-block basis, and it is expected for the block to return a block state instance that reflects the given rotation or mirror, if at all possible. Think of it like `cycleProperty`, but with the Block having control over the return value.

**Comment by Zidane** [comment]
@InsomniaKitten Right which I think gives more weight to the current names. If I see...

`x.rotate`

To me that implies that after that call `x` will be rotated and therefore mutated. Sure the result is different (a different blockstate if successful in this instance) but the callee remains the same.

**Comment by kashike** [comment]
It doesn't imply mutation at all:
```java
    @Deprecated
    public IBlockState withRotation(IBlockState state, Rotation rot) {
        return state;
    }
```
It takes `state` in, which is immutable, and returns another state (or the same one) with `Rotation` applied.

**Comment by Leviathan143** [comment]
@kashike I'm saying the name `rotate` implies mutation, and the name `withRotation` doesn't. This is about naming reflecting what the method actually does, and it doesn't mutate.

**Comment by PaleoCrafter** [comment]
It's an established contract that block states are immutable, hence I'm fine with the names without `with`. The argument that just `rotate` or `mirror` implies mutability is moot, imo, considering that we also have immutable vector type that have methods like `add` that don't mutate, either.

As for the method on `Block`, names without `with` make a lot more sense there because you're telling the flyweight to rotate something and give you back the result. `with` would signify to me that the `Block` instance is affected in some way.

**Comment by InsomniaKitten** [comment]
Generalizing both to `with` would lead to very vague methods required for implementation within `Block`, and very ambiguous stack traces if one or the other were to throw an exception during executing. And arguing that the methods in `Block` could have more verbose names to counteract the generalized use of `with` would just lead to confusion with regard to Mojang's delegation design from state to block calls. Both `rotate` and `mirror` directly imply the intent with no need for parameter context, and would be perfectly applicable as overriden methods in a `Block`.

**Comment by covers1624** [comment]
Makes sense, i vote for `rotate` and `mirror` then.

**Comment by kashike** [comment]
- [x] `func_185907_a`: `withRotation` &rarr; `rotate`
- [x] `func_185902_a`: `withMirror` &rarr; `mirror`
- [x] `func_185499_a`: `withRotation` &rarr; `rotate`
- [x] `func_185471_a`: `withMirror` &rarr; `mirror`
