### ISSUE TITLE
SoundEvents.BLOCK_ -> FLUID_ For Fluids

### ISSUE THREAD

**Issue by InsomniaKitten** [ModCoderPack/MCPBot-Issues#696]
- [ ] `field_187917_gq`: `BLOCK_WATER_AMBIENT` -> `FLUID_WATER_AMBIENT`
- [ ] `field_187656_cX`: `BLOCK_LAVA_AMBIENT` -> `FLUID_LAVA_AMBIENT`
- [ ] `field_187659_cY`: `BLOCK_LAVA_EXTINGUISH` -> `FLUID_LAVA_EXTINGUISH`
- [ ] `field_187662_cZ`: `BLOCK_LAVA_POP` -> `FLUID_LAVA_POP`

**Comment by kashike** [comment]
Nope. The fields are using the proper names.
