### ISSUE TITLE
Rename EntityPotion.potionDamage to EntityPotion.potionItem

### ISSUE THREAD

**Issue by gabizou** [ModCoderPack/MCPBot-Issues#70]
Since a while now, the field isn't just for the damage value of the potion to retrieve, but rather the `ItemStack` to retrieve the list of `PotionEffect`s to use on impact. Suggesting a field rename for a more proper name as it is used.

**Comment by matthewprenger** [comment]
This field appears to have been removed in 1.9

**Comment by gabizou** [comment]
@matthewprenger yep, seems like 1.9 moved the ItemStack to an `Optional` within a `DataParameter`.
