### ISSUE TITLE
ItemStack.field_77990_d: stackTagCompound -> ???

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#701]
Related methods:
* `func_77942_o` (`hasTagCompound`)
* `func_77978_p` (`getTagCompound`)
* `func_77982_d` (`setTagCompound`)

(possibly also `func_77983_a` (`setTagInfo`))

Is (de)serialised as "tag":
```java
this.stackTagCompound = compound.getCompoundTag("tag");
```

Could be `tag`, or alternatively `nbt`. Should lose the redundant "stack" prefix at least.

Thoughts/opinions?

**Comment by kashike** [comment]
`tag`, `getTag`, `setTag`

**Comment by kashike** [comment]
- [x] `field_77990_d`: `stackTagCompound` -> `tag`
- [x] `func_77942_o`: `hasTagCompound` -> `hasTag`
- [x] `func_77978_p`: `getTagCompound` -> `getTag`
- [x] `func_196082_o`: `getOrCreateTagCompound` -> `getOrCreateTag`
- [x] `func_77982_d`: `setTagCompound` -> `setTag`
- [x] `func_190925_c`: `getOrCreateSubCompound` -> `getOrCreateChildTag`
- [x] `func_179543_a`: `getSubCompound` -> `getChildTag`
- [x] `func_196083_e`: `removeSubCompound` -> `removeChildTag`
