### ISSUE TITLE
EntityWitherSkull "invulnerable" names

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#702]
These names are used to determine if the skull is a "blue" wither skull. From the wiki:

>The main head controls the Wither's movement, and has a 0.1% chance to shoot a blue wither skull instead of the default black one.

> There are two types of wither skulls: a fast-moving black one, and a slower blue one. Black wither skulls explode with a blast radius of 1, the same as a ghast's fireball, and cannot break blocks with a blast resistance above 20. The blue wither skull has the same explosion strength, but moves slower and treats most blocks as having a blast resistance of no more than 4, making it more destructive to the terrain.

Taking suggestions for the following:

- [ ]  `field_184565_e`: `INVULNERABLE` -> ???
- [ ]  `func_82342_d`: `isInvulnerable` -> ???
- [ ]  `func_82343_e`: `setInvulnerable(invulnerable)` -> ???

Also from `EntityWither.launchWitherSkullToCoords`: 
- [ ] `p_82209_8_`: `invulnerable` -> ???

**Comment by TheCodedOne** [comment]
I'd suggest empowered or charged to replace invulnerable

**Comment by kashike** [comment]
- [x] `func_82342_d`: `isInvulnerable` &rarr; `isSkullInvulnerable`
- [x] `func_82343_e`: `setInvulnerable` &rarr; `setSkullInvulnerable`
These have been changed to allow #522 to proceed. Other names for the two methods above can be discussed and picked if necessary.
