### ISSUE TITLE
Global "update" -> "tick"

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#703]
We have lots of methods named `update*` when they should be `tick*` - they're being ticked by the client/server.

**Comment by kashike** [comment]
- [x] `func_180655_c`: `randomDisplayTick` &rarr; `animateTick`
- [x] `func_186059_r`: `onWorldUpdateEntities` &rarr; `tick`
- [x] `func_70071_h_`: `onUpdate` &rarr; `tick`
- [x] `func_75774_a`: `onUpdateTasks` &rarr; `tick`
- [x] `func_75641_c`: `onUpdateMoveHelper` &rarr; `tick`
- [x] `func_75649_a`: `onUpdateLook` &rarr; `tick`
- [x] `func_75661_b`: `doJump` &rarr; `tick`
- [x] `func_78464_a`: `updateRenderer` &rarr; `tick`
- [x] `func_75523_a`: `clearSensingCache` &rarr; `tick`
- [x] `func_204522_a`: `randomDisplayTick` &rarr; `animateTick`
- [x] `func_73831_a`: `updateTick` &rarr; `tick`
- [x] `func_206881_a`: `randomDisplayTick` &rarr; `animateTick`
- [x] `func_73660_a`: `update` &rarr; `tick`
- [x] `func_204870_b`: `update` &rarr; `tick`
- [x] `func_74428_b`: `processReceivedPackets` &rarr; `tick`
- [x] `func_151269_c`: `networkTick` &rarr; `tick`
- [x] `func_189213_a`: `onUpdate` &rarr; `tick`
- [x] `func_78868_a`: `updateEffects` &rarr; `tick`
- [x] `func_75501_e`: `onUpdateNavigation` &rarr; `tick`
- [x] `func_78765_e`: `updateController` &rarr; `tick`
- [x] `func_72374_b`: `onTick` &rarr; `tick`
- [x] `func_193303_d`: `update` &rarr; `tick`
- [x] `func_72870_g`: `updateEntity` &rarr; `tickEntity`
- [x] `func_72939_s`: `updateEntities` &rarr; `tickEntities`
- [x] `func_147456_g`: `updateBlocks` &rarr; `tickBlocks`
- [x] `func_72979_l`: `updateWeather` &rarr; `tickWeather`
- [x] `func_73029_E`: `doVoidFogParticles` &rarr; `animateTick`
- [x] `func_184153_a`: `showBarrierParticles` &rarr; `animateTick`
- [x] `func_72955_a`: `tickUpdates` &rarr; `tickPending`

**Comment by tterrag1098** [comment]
Not sure I agree with `animateTick`, it doesn't convey the correct behavior to me.

**Comment by kashike** [comment]
I'm up for an alternative name - that one is pulled from the profiler (`this.profiler.endStartSection("animateTick");`) and matches `randomTick` in `Block`.
