### ISSUE TITLE
RAS syndrome with NBTTag* classes

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#704]
Namely, these:
* `NBTTagByteArray`
* `NBTTagByte`
* `NBTTagCompound`
* `NBTTagDouble`
* `NBTTagEnd`
* `NBTTagFloat`
* `NBTTagIntArray`
* `NBTTagInt`
* `NBTTagList`
* `NBTTagLongArray`
* `NBTTagLong`
* `NBTTagShort`
* `NBTTagString`

Given that we have `NBTBase` and `NBTPrimitive` already, I'd suggest dropping the surplus `_Tag_` from the others.
An alternative would be going with just `Tag_`, and dropping the `NBT_` prefix instead.

What do people think?

**Comment by kashike** [comment]
Mojang calls these `<type>Tag`:
`ByteArrayTag`
`ByteTag`
`CompoundTag`
`DoubleTag`
`EndTag`
`FloatTag`
`IntArrayTag`
`IntTag`
`ListTag`
`LongArrayTag`
`LongTag`
`ShortTag`
`StringTag`

**Comment by bs2609** [comment]
That goes into the whole prefix/suffix debate, though.

**Comment by kashike** [comment]
We've converted biomes to be `*Biome` already.

**Comment by bs2609** [comment]
Then go ahead and change the others? IMO, indefinite inconsistency is the worst option.

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
