### ISSUE TITLE
AbstractFish.field_203710_a: getPackSize -> literally anything else

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#706]
AbstractFish.field_203710_a: getPackSize -> literally anything else

who thinks it's a good idea to name fields like getters? no one!

cc @strikerrocker

**Comment by PaleoCrafter** [comment]
I feel like this should be `schoolSize`. Groups of fish are called schools, not packs >.> If we want to keep the terminology generic, go with `groupSize`, considering that's what `EntityAIFollowGroupLeader` uses.

**Comment by williewillus** [comment]
` func_203704_dv`  (getMaxPackSize) should follow whatever we set here then

**Comment by strikerrocker** [comment]
Reverted the name myself. Guess you can close this now and set yourself a good name
