### ISSUE TITLE
ISaveHandler -> IWorldStorage

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#708]
We have `WorldSavedDataStorage` for a world's saved data storage.

`net/minecraft/world/storage/ISaveHandler` -> `net/minecraft/world/storage/IWorldStorage`

**Comment by bs2609** [comment]
Some method names:
- [ ] `func_75758_b`: `getMapFileFromName` -> `getSavedDataFile` ?
- [ ] `func_75756_e`: `getPlayerNBTManager` -> `getPlayerFileData`

**Comment by bs2609** [comment]
Would need renaming:
* `ISaveFormat.getSaveLoader` (`func_197715_a`)
* `World.getSaveHandler` (`func_72860_G`)
* `World.saveHandler` (`field_73019_z`)
* `WorldSavedDataStorage.saveHandler` (`field_75751_a`)
