### ISSUE TITLE
Noise Generator Mappings

### ISSUE THREAD

**Issue by gegy1000** [ModCoderPack/MCPBot-Issues#709]
The `NoiseGenerator` subclass names seem to not match their function correctly:

- [ ] `NoiseGeneratorPerlin` -> `NoiseGeneratorSimplexOctaves`
    -  Holds an array of simplex noise generators that it samples from.
- [ ] `NoiseGeneratorImproved` -> `NoiseGeneratorPerlin`
    - Looks like the improved Perlin noise algorithm. As this is the only Perlin noise supported by MC, it being Perlin noise is more relevant than it being Improved. Could also be `NoiseGeneratorPerlinImproved`
- [ ] `NoiseGeneratorOctaves` -> `NoiseGeneratorPerlinOctaves`
    - Need to be more specific as now there'd be two octave noise generators.

Another option is to go with just a `Noise` prefix instead of `NoiseGenerator`, or even do it as a suffix like biome subclasses. Thoughts?

**Comment by Pokechu22** [comment]
See [this comment](https://github.com/ModCoderPack/MCPBot-Issues/issues/712#issuecomment-417793734).  Note in particular that "NoiseGeneratorImproved" actually matches the mojang name (as of 9 years ago, though).  :+1: to `NoiseGeneratorPerlin` &rarr; `NoiseGeneratorSimplexOctaves` or `NoiseSimplexOctaves` in particular; the rest also make sense but don't completely match the original names (not that that matters too much).

**Comment by gegy1000** [comment]
Following that,
`NoiseGeneratorPerlin` vs `NoiseGeneratorPerlinImproved` vs `NoiseGeneratorImproved`?
`NoiseGenerator` vs `Synth`? (base class)
`NoiseGenerator*` vs `Noise*` vs `*Noise`?

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
