### ISSUE TITLE
Proposal for method signature search

### ISSUE THREAD

**Issue by chylex** [ModCoderPack/MCPBot-Issues#71]
Okay, here's the proposal for a command to search method signatures, I would like to get some input on this from other people first, but I think I have most of it figured out.

It would be added as a new command (**!finds**/**findalls** for find signature, those are unique to methods so there will not be any confusion). The reason is that method signature search is rarely ever needed, and separation is convenient to avoid confusion in command descriptions<sup>[1]</sup>. Since it's also specialized, you can have a special case to avoid escaping the parentheses.
## Syntax Description

```
!finds [<class>] (<argument-types>)<return-type> [version]
!findalls [<class>] (<argument-types>)<return-type> [version]
```

The regex search would be split and accept <argument-types> and <return-type> as regex strings. This means the outside () do not need to be escaped, and unless you actually need regex, you won't have to think about escaping since (almost) no other characters inside the java type description would need escaping.

The optional class and version arguments work the same as in **!gc**.
## Parsing Argument and Return Types

One rule is that there cannot be any spaces, since it would cause confusion with the [version] argument.
### Primitive Types

All primitive types allow their short signatures, but also their actual names separated with semicolons. There is no ambiguity as class names are neither all lowercase nor all uppercase. Here is an example, the ones on top are converted into the one on the bottom:

```
(int;long;boolean;)void
(int;long;boolean)void
(I;long;Z)void
(IJZ)V
```

The semicolon before the ending parenthesis is discarded. Full names are always separated from the letters with semicolons. This is an optional feature and might not be worth implementing, since you can just link to [VM type signature list](http://journals.ecs.soton.ac.uk/java/tutorial/native1.1/implementing/method.html), but it would be convenient.
### Classes

Classes can be written using their signature name, or MCP names surrounded by semicolons. Notch names are not supported. The ones on top are converted into the one on the bottom.

```
(D;EnumSkyBlock;int;int;int;)void
(D;EnumSkyBlock;III)Z
(D;Lnet/minecraft/world/EnumSkyBlock;III)Z
(DLnet/minecraft/world/EnumSkyBlock;III)Z
```

Unnecessary semicolons (including the one before the ending parenthesis) are discarded. If two classes have the same MCP name, either the first one (!finds) or all of them (!findalls) will be returned.
### Arrays

Since arrays use [ character which needs to be escaped, there could be a conversion to find all unclosed brackets and escape them, but it is not needed. If interested though, it would work like this:

```
([IZD)Z
 ^-- unclosed, convert into: (\[IZD)Z

([IZ])Z
 ^--^-- closed, keep as is

([[IZ])Z
  ^--^-- closed, keep as is
 ^-- unclosed, convert into: (\[[IZ])Z
```
### Return Type

If the return type is missing, it is replaced with an end wildcard regex:

```
(.*?)$
```
## Search Target

Since !gm uses this as the signature:

```
Descriptor : (Lahn;III)Z => (Lnet/minecraft/world/EnumSkyBlock;III)Z
```

I would propose that only _(Lnet/minecraft/world/EnumSkyBlock;III)Z_ is searched with the final regular expression, since obfuscated class name handling would increase ambiguity and I don't think handling them is necessary.
## Notes

[1] Current !findm/findallm should have "_Returns method entries with names matching a regex pattern._", !finds/findalls would then have "_Returns method entries with signatures matching regex patterns for argument and return types._"
## Feedback

Let me know if there's anything that I missed, or anything you find unintuitive and would want me to improve it.

**Comment by bspkrs** [comment]
Non-bytecode primitive type names and non-fully qualified object types are stretch goals... they will require lookups to be done before even starting the search.

**Comment by bspkrs** [comment]
Also, I'm pretty sure that the parentheses will still have to be escaped, otherwise it's not a regex search. I /won't cook up some half-assed semi-regex syntax just so that people don't have to type \ before special regex characters.

**Comment by bspkrs** [comment]
What optional class argument are you referring to? In !gc the class argument is required, and in !gm/!gf the class portion is not separated by a space.

**Comment by bspkrs** [comment]
In the interest of actually getting this done in a timely manner, I think I'll probably just ignore the array handling bit as well. Square brackets will have to be escaped just like any other special character.

**Comment by chylex** [comment]
The parentheses are a part of the command syntax (which was a bit messy, I fixed it here):

```
!finds [<class>] (<argument-types>)[<return-type>] [<version>]
```

For example, *!finds (abc)d* means there are two regexes, *abc* and *d*; it's done like that for the sake of convenience, since the parens are always required in the signature.

The optional class argument is in the !finds, I was just pointing out the lookup should behave the same way as how !gc handles its own class argument.

I've started with Python recently, but I think I can make the primitive type and class conversion work, so you can just connect it with the database lookup - I'd have it convert the (<argument-types>)[<return-type>] into a single escaped regex, assuming that's what you would need for the database.

**Comment by chylex** [comment]
Apparently this issue exists, I have no/minimal recollection of what's going on here; is this still of interest to anyone?
