### ISSUE TITLE
EntityLiving.func_175456_n: applyEntityAI -> resetSoundTimer (or other)

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#711]
`EntityLiving.func_175456_n`: `applyEntityAI` -> `resetSoundTimer` (or other)

Only serves to reset a counter controlling the entity's ambient sounds. Holdover from legacy/old AI probably.

**Comment by bs2609** [comment]
Not quite correct - see #522.

**Comment by williewillus** [comment]
@bs2609 not sure what part of that ticket contradicts this? It's clearly a sound method and has nothing to do with AI anymore. This ticket only deals with the living one, not the zombie one.

**Comment by bs2609** [comment]
> Holdover from legacy/old AI probably.
It's not a holdover, it's taking the name from the zombie method.

It can't be named differently to that until it gets a unique SRG name.
