### ISSUE TITLE
NoiseGenerator sampling function inconsistency

### ISSUE THREAD

**Issue by Gegy** [ModCoderPack/MCPBot-Issues#712]
(Following on from #709)
There is currently a lack of consistency between sampling function mapping on noise generators. Many include the term "populate", which implies filling an uninitialised buffer. However, all implementations rather add the sampled noise to the current value allowing for it to be layered in octaves. I think `sample` feels like a more appropriate term.

- [ ] `NoiseGeneratorImproved#func_76308_a` -> `sampleArea`
- [ ] `NoiseGeneratorSimplex#func_151605_a` -> `samplePoint`
- [ ] `NoiseGeneratorSimplex#func_151606_a` -> `sampleArea`
- [ ] `NoiseGeneratorOctaves#func_76304_a` -> `sampleArea`
- [ ] `NoiseGeneratorOctaves#func_76305_a` -> `sampleArea`
- [ ] `NoiseGeneratorPerlin#func_151601_a` -> `samplePoint`
- [ ] `NoiseGeneratorPerlin#func_151599_a` -> `sampleArea`
- [ ] `NoiseGeneratorPerlin#func_151600_a` -> `sampleArea`

**Comment by Pokechu22** [comment]
Time for another case of giving information from ~~stupid~~ interesting sources (last time I did this I proved that you [charge a phone with a `BlockCompressedPowered`](https://github.com/ModCoderPack/MCPBot-Issues/issues/537#issuecomment-332567131)).  Version [c0.0.13a](https://launcher.mojang.com/v1/objects/936d575b1ab1a04a341ad43d76e441e88d2cd987/client.jar), dating to 2009, is not obfuscated.  And it has some of these things, although the methods appeared and disappeared over time.  Granted, this code dates back almost 10 years, but it's enough information to start.  Also, I suspect I'm not the first person to look at these...

* `NoiseGeneratorImproved`: This was originally `com.mojang.minecraft.level.levelgen.synth.ImprovedNoise`.
    * <ruby><rb>`permutations`</rb><rp> (</rp><rt>field_76312_d</rt><rp>)</rp></ruby>: `p`
    * <ruby><rb>`xCoord`</rb><rp> (</rp><rt>field_76315_a</rt><rp>)</rp></ruby>, <ruby><rb>`yCoord`</rb><rp> (</rp><rt>field_76313_b</rt><rp>)</rp></ruby>, <ruby><rb>`zCoord`</rb><rp> (</rp><rt>field_76314_c</rt><rp>)</rp></ruby>: No equivalent (probably from fixed-sized maps back then)
    * <ruby><rb>`GRAD_X`</rb><rp> (</rp><rt>field_152381_e</rt><rp>)</rp></ruby>, <ruby><rb>`GRAD_Y`</rb><rp> (</rp><rt>field_152382_f</rt><rp>)</rp></ruby>, <ruby><rb>`GRAD_Z`</rb><rp> (</rp><rt>field_152383_g</rt><rp>)</rp></ruby>: No equivalent; grad calculation happened without an array.
    * <ruby><rb>`GRAD_2X`</rb><rp> (</rp><rt>field_152384_h</rt><rp>)</rp></ruby>, <ruby><rb>`GRAD_2Z`</rb><rp> (</rp><rt>field_152385_i</rt><rp>)</rp></ruby>: No equivalent; also these are duplicates of the regular GRAD arrays so I'm not sure why they're needed.
    * ctor (note that there was originally also one that didn't take a random and just passed a `new Random()` to the other)
        * `p_i45469_1_`: `random`
    * `func_205561_a` ("new" to 1.13): `noise`
        * `p_205561_1_`: `x`
        * `p_205561_3_`: `y`
        * `p_205561_5_`: `z`
    * Inlined code like `d0 * d0 * d0 * (d0 * (d0 * 6.0D - 15.0D) + 10.0D)`: originally `fade`; parameter `t`
    * <ruby><rb>`lerp`</rb><rp> (</rp><rt>func_76311_b</rt><rp>)</rp></ruby>: `lerp`
        * `p_76311_1_`: `t`
        * `p_76311_3_`: `a`
        * `p_76311_5_`: `b`
    * <ruby><rb>`grad2`</rb><rp> (</rp><rt>func_76310_a</rt><rp>)</rp></ruby>: No equivalent, but this is a 2-arg version of regular grad.
    * <ruby><rb>`grad`</rb><rp> (</rp><rt>func_76310_a</rt><rp>)</rp></ruby>: `grad`
        * `p_76310_1_`: `hash`
        * `p_76310_2_`: `x`
        * `p_76310_4_`: `y`
        * `p_76310_6_`: `z`
    * `func_205562_a`: `getValue` (calls `noise` with the third arg as 0.0)
        * `p_205562_1_`: `x`
        * `p_205562_3_`: `y`
    * `func_205560_c`: No equivalent.  Strangely, this just delegates to `noise`.
    * <ruby><rb>`populateNoiseArray`</rb><rp> (</rp><rt>func_76308_a</rt><rp>)</rp></ruby>: No equivalent.  So, `sampleArea` is probably fine.
* `NoiseGeneratorOctaves`: This was originally `com.mojang.minecraft.level.levelgen.synth.PerlinNoise`.
    * <ruby><rb>`noiseLevels`</rb><rp> (</rp><rt>field_151603_a</rt><rp>)</rp></ruby>: `noiseLevels`
    * <ruby><rb>`levels`</rb><rp> (</rp><rt>field_151602_b</rt><rp>)</rp></ruby>: `levels`
    * ctor (note that there was originally also one that didn't take a random and just passed a `new Random()` to the other)
        * <ruby><rb>`seed`</rb><rp> (</rp><rt>p_i45470_1_</rt><rp>)</rp></ruby>: `random`
        * <ruby><rb>`levelsIn`</rb><rp> (</rp><rt>p_i45470_2_</rt><rp>)</rp></ruby>: `levels`
    * <ruby><rb>`getValue`</rb><rp> (</rp><rt>func_151601_a</rt><rp>)</rp></ruby>: `getValue`
        * <ruby><rb>`x`</rb><rp> (</rp><rt>p_151601_1_</rt><rp>)</rp></ruby>: `x`
        * <ruby><rb>`z`</rb><rp> (</rp><rt>p_151601_3_</rt><rp>)</rp></ruby>: `z`
    * <ruby><rb>`generateRegion`</rb><rp> (</rp><rt>func_202645_a, func_202644_a</rt><rp>)</rp></ruby>: No equviilent.  New to 1.13.
* `NoiseGeneratorSimplex`: No equivalent.
* `NoiseGeneratorPerlin`: No equivalent.  **However**: note that the original `PerlinNoise` is actually now `NoiseGeneratorOctaves`, not this.  (This uses octaves of simplex noise, not "improved" noise)
* `NoiseGenerator`: this class is empty currently, but it actually originally acted as an interface, with name `com.mojang.minecraft.level.levelgen.synth.Synth`.
    * (no equivalent remains, but `getValue` as `func_205562_a`, `func_151601_a`, and the equivalents for `NoiseGeneratorSimplex` and `NoiseGeneratorPerlin` _would_ override this): `getValue`
        * No parameter data, as this method is abstract
    * (no equivalent remains): `create` - creates a fixed size array.  Probably gone now that worlds are infinite.  Takes width and height and returns a `double[]`.

I feel like there was a later version that was also released without obfuscation, but I'm not sure which it was.  Also, it seems like most of these haven't actually related too much to this issue, but it's still interesting data, so I'm going to post it anyways (I spent _way_ too long looking all that up).

**Comment by gegy1000** [comment]
@Pokechu22 Wow. So much respect for looking all of that up.

So it seems we don't have any definitive names for the area sampling. Though for sampling a point, should the name stay in line with vanilla as `getValue`? Possibly by extension `getArea`?
