### ISSUE TITLE
IWorldEventListener -> IWorldListener

### ISSUE THREAD

**Issue by ChloeDawn** [ModCoderPack/MCPBot-Issues#714]
The "Event" part is a bit redundant and non-sensical.

- [ ] `net/minecraft/world/IWorldEventListener` -> `IWorldListener`
- [ ] `net/minecraft/world/ServerWorldEventHandler` -> `ServerWorldHandler`/`ServerWorldListener?`

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
