### ISSUE TITLE
MobEffect and Potion

### ISSUE THREAD

**Issue by sjx233** [ModCoderPack/MCPBot-Issues#715]
Also see #538 and #694.

- [ ] `PotionTypes` → `Potions`
  - [ ] `func_185217_a`: `getRegisteredPotionType` → `getRegisteredPotion`
- [ ] `PotionType` → `Potion`
  - [ ] `func_185175_b`: `registerPotionTypes` → `registerPotions`
  - [ ] `func_185173_a`: `registerPotionType` → `registerPotion`
- [ ] `Potion` → `MobEffect`
  - [ ] `func_199286_c`: `(none)` → `makeTranslatableComponent`

## Reason
In `PotionTypes."<clinit>"`:

```java
throw new RuntimeException("Accessed Potions before Bootstrap!");
```

In `PotionTypes.getRegisteredPotionType`:

```java
throw new IllegalStateException("Invalid Potion requested: " + p_getRegisteredPotionType_0_);
```

In `MobEffects.getRegisteredMobEffect`:

```java
throw new IllegalStateException("Invalid MobEffect requested: " + p_getRegisteredMobEffect_0_);
```

**Comment by pau101** [comment]
@Shadows-of-Fire It is true we don't have `Mob` as apart of entity hierarchy as it actually is, but developers knows what mobs are in the context of the game, and there are many locations where we do actually reference "mob" in code.

`Potions`, as named currently is wildly inaccurate. Our `PotionTypes` are the actual potions and the `Potion` we have is not about potions, but instead merely the representation of an effect applied to mobs, and only some are for potions, others are applied by other game mechanics. These class renames are certainly warranted.

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
