### ISSUE TITLE
EnumFacing & EnumDirection8

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#718]
`net.minecraft/util/EnumFacing` -> `net.minecraft/util/Direction`
`net.minecraft/util/EnumDirection8` -> `net.minecraft/util/Direction8`

**Comment by williewillus** [comment]
but `Compass` doesn't imply 8 either, for all I know it could just be the 4 cardinal directions

**Comment by tterrag1098** [comment]
There is no good word to imply all 8 cardinal and ordinal directions, I think "compass" is as close as you can get. It's not hard to just look at the class and see what constants are defined, nor is it a stretch to think that a compass direction enum would include ordinal directions.

**Comment by williewillus** [comment]
hmm, I'd almost say I prefer `CompassDirection` over `CompassPoint`, Direction is more accurate than Point imo (I'd have to see usages though)

**Comment by Pokechu22** [comment]
Wiktionary has an article for [compass point](https://en.wiktionary.org/wiki/compass_point), but not for compass direction.  But, I feel direction is a bit more obvious... so, no strong opinion between the two.

**Comment by pau101** [comment]
@williewillus "Point" is used explicitly for the avoidance of "Direction", as comment argued.
