### ISSUE TITLE
Sound Cleanup

### ISSUE THREAD

**Issue by ChloeDawn** [ModCoderPack/MCPBot-Issues#719]
**`net.minecraft.client.audio.ISound`**

- [ ] `func_184366_a`: `createAccessor` -> `init`
- [ ] `func_147650_b`: `getSoundLocation` -> `getName`
- [ ] *`func_147656_j`: `getAttenuationType` -> `getAttenuationModel`/`getModel`*
- [x] `func_147649_g`: `getXPosF` -> `getX`
- [x] `func_147654_h`: `getYPosF` -> `getY`
- [x] `func_147651_i`: `getZPosF` -> `getZ`

**`net.minecraft.client.audio.ISound$AttenuationType`**
- [ ] *`dfm$a`: `ISound$AttenuationType` -> `ISound$AttenuationModel`*
- [ ] `field_148589_c`: `type` -> `id`
- [ ] ` p_i45110_3_`: `typeIn` -> `idIn`
- [ ] `func_148586_a`: `getTypeInt` -> `getId`

**`net.minecraft.client.audio.PositionedSound`**

- [ ] `field_184369_l`: `soundEvent` -> `accessor`
- [ ] *`field_147666_i`: `attenuationType` -> `attenuationModel`/`model`*
- [ ] `p_i46534_1_`: `soundId` -> `nameIn`
- [x] `field_147660_d`: `xPosF` -> `x`
- [x] `field_147661_e`: `yPosF` -> `y`
- [x] `field_147658_f`: `zPosF` -> `z`

**`net.minecraft.client.audio.Sound`**

- [ ] `func_188719_a`: `getSoundLocation` -> `getName`
- [ ] `func_188721_b`: `getSoundAsOggLocation` -> `getFileLocation`

**`net.minecraft.client.audio.SoundList`**

- [ ] `p_i46525_2_`: `replceIn` -> `replaceIn`

**`net.minecraft.client.audio.SoundHandler`**

- [ ] `field_147694_f`: `sndManager` -> `soundManager`
- [ ] `func_186712_a`: `setSoundLevel` -> `setVolume`
- [ ] `func_147693_a`: `loadSoundResource` -> `load`
- [ ] `func_184401_a`: `validateSoundResource` -> `validate`
- [ ] `func_175085_a`: `getSoundMap` -> `getSoundsFromJson`/`fromJson`
- [x] `func_147682_a`: `playSound` -> `play`
- [x] `func_147681_a`: `playDelayedSound` -> `play`/`playWithDelay`
- [x] `func_147689_b`: `pauseSounds` -> `pause`/`pauseAll`
- [x] `func_147690_c`: `stopSounds` -> `stop`/`stopAll`
- [x] `func_147687_e`: `resumeSounds` -> `resume`/`resumeAll`
- [x] `func_147683_b`: `stopSound` -> `stop`
- [x] `func_147692_c`: `isSoundPlaying` -> `isPlaying`

**`net.minecraft.client.audio.SoundManager`**

- [x] `func_148596_a`: `reloadSoundSystem` -> `reload`
- [s] `func_148608_i`: `loadSoundSystem` -> `load`
- [x] `func_148613_b`: `unloadSoundSystem` -> `unload`
- [ ] `func_148614_c`: `stopAllSounds` -> `stop`/`stopAll`
- [x] `func_195855_a`: `stopAllSounds` -> `stop`/`stopAll`
- [x] `func_148597_a`: `isSoundPlaying` -> `isPlaying`
- [x] `func_148602_b`: `stopSound` -> `stop`
- [x] `func_148611_c`: `playSound` -> `play`
- [x] `func_148610_e`: `pauseAllSounds` -> `pause`/`pauseAll`
- [x] `func_148604_f`: `resumeAllSounds` -> `resume`/`resumeAll`
- [ ] `func_188772_d`: `getClampedPitch` -> `getPitch`/`getActualPitch`
- [ ] `func_188770_e`: `getClampedVolume` -> `getVolume`/`getActualVolume`
- [x] `func_148599_a`: `playDelayedSound` -> `play`/`playWithDelay`
- [ ] `func_204259_a`: `enqueuePreload` -> `enqueue`
- [ ] `func_148612_a`: `getURLForSoundResource` -> `getURL`

**`net.minecraft.client.audio.PositionedSoundRecord`**

- [ ] `func_184371_a`: `getMasterRecord` -> `create`
- [ ] `func_194007_a`: `getRecord` -> `create`
- [ ] `func_184370_a`: `getMusicRecord` -> `createMusic`
- [ ] `func_184372_a`: `getRecordSoundRecord` -> `createRecord`

**`net.minecraft.client.audio.MusicTicker`**

- [x] `func_181558_a`: `playMusic` -> `play`
- [x] `func_209200_a`: `stopMusic` -> `stop`
- [x] `p_181558_1_`: `requestedMusicType` -> `type`

**`net.minecraft.client.audio.MusicTicker$MusicType`**

- [x] `p_i47050_3_`: `musicLocationIn` -> `soundEventIn`
- [x] `field_148645_h`: `musicLocation` -> `soundEvent`
- [x] `func_188768_a`: `getMusicLocation` -> `getSoundEvent`

**`net.minecraft.client.audio.ISoundEventListener`**

- [x] `func_184067_a`: `soundPlay` -> `onPlaySound`

**`net.minecraft.client.audio.SoundRegistry`**

- [x] `func_148763_c`: `clearMap` -> `clear`

**Comment by bs2609** [comment]
Still some unneeded parts to the names:
* `getSoundName` -> `getName`
* `getPosX` -> `getX`
* `getPosY` -> `getY`
* `getPosZ` -> `getZ`
* `posX` -> `x`
* `posY` -> `y`
* `posZ` -> `z`

No need to specify "pos" for x/y/z unless there's also something else with directional components.

Also `ISound.AttenuationType`:
* `func_148586_a`: `getTypeInt` -> `getType` ?

The `_Int` can be removed at least, but something better than "type" for this would also be nice. Maybe "id"? `field_148589_c` (`type`) would also need changing in this case.

The class name would also posssibly be better as `AttenuationModel`, based on the sound library javadocs (description of the "type" int passed as a parameter).
```java
@param attmodel Attenuation model to use.
```

**Comment by pau101** [comment]
The purpose of `ISound#createAccessor` is not to get an accessor for the sound, but instead to prepare the sound object to be subsequently played, which happens to have the result `SoundEventAccessor`. This is indicated by `SoundManager#playSound` requiring `ISound#getSound` to return non-null in subsequent code following `createAccessor` and `PositionedSound` performing initialization of its nullable `sound` field (returned by `getSound`) in this function.

Therefore I propose the following:
- [ ] `func_184366_a`: `createAccessor` -> `init`

**Comment by InsomniaKitten** [comment]
@bs2609 @pau101 The ticket has been updated accordingly

**Comment by kashike** [comment]
- [x] `func_147649_g`: `getXPosF` &rarr; `getX`
- [x] `func_147654_h`: `getYPosF` &rarr; `getY`
- [x] `func_147651_i`: `getZPosF` &rarr; `getZ`
- [x] `field_147660_d`: `xPosF` &rarr; `x`
- [x] `field_147661_e`: `yPosF` &rarr; `y`
- [x] `field_147658_f`: `zPosF` &rarr; `z`
- [x] `func_147682_a`: `playSound` &rarr; `play`
- [x] `func_147681_a`: `playDelayedSound` &rarr; `playDelayed`
- [x] `func_147689_b`: `pauseSounds` &rarr; `pause`
- [x] `func_147690_c`: `stopSounds` &rarr; `stop`
- [x] `func_147687_e`: `resumeSounds` &rarr; `resume`
- [x] `func_147683_b`: `stopSound` &rarr; `stop`
- [x] `func_147692_c`: `isSoundPlaying` &rarr; `isPlaying`
- [x] `func_195855_a`: `stopAllSounds` &rarr; `stop`
- [x] `func_148610_e`: `pauseAllSounds` &rarr; `pause`
- [x] `func_148604_f`: `resumeAllSounds` &rarr; `resume`
