### ISSUE TITLE
Chunk$EnumCreateEntityType -> Chunk$RequestType

### ISSUE THREAD

**Issue by ChloeDawn** [ModCoderPack/MCPBot-Issues#722]
- [ ] `net/minecraft/world/chunk/Chunk$EnumCreateEntityType` -> `Chunk$RequestType`

It makes no sense for an enum class to imply creation semantics when a constant of `CHECK` exists. The enum is used as more of a request type, to determine how a requested object is processed (currently only implemented for TileEntity lookups in Chunk).

- `RequestType.IMMEDIATE` would imply the requested object will be immediately processed.
- `RequestType.QUEUED` would imply the requested object will be queued for processing.
- `RequestType.CHECK` would imply you're checking for the presence of a requested object.

See also: #717

**Comment by LexManos** [comment]
It has been open for over a year and no comments. Closing due to nobody caring.
