### ISSUE TITLE
GuiTextField.updateCursorCounter → tick

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#723]
See #703.  This is also shown to be the Mojang name in #503.

While the default implementation's behavior is to just update the cursor counter, subclasses can use it for other purposes, and it's always called in `GuiScreen.tick` (né `updateScreen`).  For example, see `GuiWorldEdit.tick`.  (Note that each GUI that uses a text field needs to manually call the method, though)

- [ ] `func_146178_a` in `GuiTextField`: `updateCursorCounter` &rarr; `tick`

**Comment by kashike** [comment]
- [x] `func_146178_a`: `updateCursorCounter` &rarr; `tick`
