### ISSUE TITLE
TextureAtlasSprite Cleanup

### ISSUE THREAD

**Issue by ChloeDawn** [ModCoderPack/MCPBot-Issues#724]
- [ ] `field_110983_h`: `tickCounter` -> `currentTick`
- [ ] `field_110973_g`: `frameCounter` -> `currentFrame`/`currentFrameIndex`
- [ ] `field_110984_i`: `iconName` -> `location`
- [x] `field_110975_c`: `originX` -> `x`
- [x] `field_110974_d`: `originY` -> `y`
- [ ] `field_176605_b`: `interpolatedFrameData` -> `interpolatedFrames`
- [x] `func_94211_a`: `getIconWidth` -> `getWidth`
- [x] `func_94216_b`: `getIconHeight` -> `getHeight`
- [ ] `func_195668_m`: `func_195668_m` -> `getLocation`*
- [ ] `func_94219_l`: `updateAnimation` -> `tick`
- [ ] `func_180599_n`: `updateAnimationInterpolated` -> `tickInterpolated`
- [ ] `func_130098_m`: `hasAnimationMetadata` -> `isAnimated`
- [ ] `func_195664_a`: `loadSpriteFrames` -> `loadFrames`
- [ ] `func_130103_l`: `clearFramesTextureData` -> `clearFrameData`

###### *Requires `MissingAtlasSprite.getLocation` to be renamed.

**Comment by kashike** [comment]
- [x] `field_110975_c`: `originX` &rarr; `x`
- [x] `field_110974_d`: `originY` &rarr; `y`
