### ISSUE TITLE
EnumFacing Cleanup

### ISSUE THREAD

**Issue by ChloeDawn** [ModCoderPack/MCPBot-Issues#727]
- [ ] `field_199792_n`: `FACING_VALUES` -> `VALUES`
- [x] `field_82609_l`: `VALUES` -> `BY_INDEX`
- [x] `field_176754_o`: `HORIZONTALS` -> `BY_HORIZONTAL_INDEX`
- [ ] `p_i46016_9_`: `directionVecIn` -> `vectorIn`
- [ ] `field_176756_m`: `directionVec` -> `vector`
- [ ] `func_196054_a`: `getFacingDirections` -> `orderedByEntity`?
- [ ] `func_176737_a`: `getFacingFromVector` -> `fromVector`
- [ ] `func_210769_a`: `getFacingFromVector` -> `fromVector`
- [ ] `func_181076_a`: `getFacingFromAxis` -> `fromAxis`
- [ ] `func_176730_m`: `getDirectionVec` -> `getVector`/`asVector`
---
- [ ] `func_176742_j`: `getName2` -> `getKey`? (Used only for `NAME_LOOKUP` keys)
- [ ] `func_176719_a`: `getName2` -> `getKey`? (Used only for `NAME_LOOKUP` keys)

```java
// field_176761_p | EnumFacing.NAME_LOOKUP
private static final Map<String, EnumFacing> NAME_LOOKUP = (Map)Arrays.stream(FACING_VALUES).collect(Collectors.toMap(EnumFacing::getName2, (p_199787_0_) -> {
	return p_199787_0_;
}));

// field_176725_d | EnumFacing$Axis.NAME_LOOKUP
private static final Map<String, EnumFacing.Axis> NAME_LOOKUP = (Map)Arrays.stream(values()).collect(Collectors.toMap(EnumFacing.Axis::getName2, (p_199785_0_) -> {
	return p_199785_0_;
}));
```

See also: #718

**Comment by Barteks2x** [comment]
The VALUES and FACING_VALUES rename is very likely to silently break mod code that relies on the order for modders that are unaware of this change.

**Comment by bs2609** [comment]
See https://github.com/ModCoderPack/MCPBot-Issues/issues/302#issuecomment-327595091.

**Comment by InsomniaKitten** [comment]
Both fields are private in vanilla, and if Forge were to port their access transformer line to 1.13, it would be applied to `SORTED_VALUES`, making `VALUES` references an error, as the field would now be private. It would not cause a silent issue in this case.

**Comment by kashike** [comment]
- [x] `field_82609_l`: `VALUES` &rarr; `BY_INDEX`
- [x] `field_176754_o`: `HORIZONTALS` &rarr; `BY_HORIZONTAL_INDEX`
