### ISSUE TITLE
IChatComponent method names

### ISSUE THREAD

**Issue by Minecrell** [ModCoderPack/MCPBot-Issues#73]
##### Updated method/field renames:

- `func_150256_b` (`getChatStyle`) -> `getStyle` (Class name was changed to `Style`)
- `func_150255_a` (`setChatStyle`) -> `setStyle`
- `func_150261_e` (`getUnformattedTextForChat`) -> `getUnformattedComponentText` (Only returns the unformatted text of the component itself, doesn't include the siblings)
- `func_150265_g` (`getChatComponentText_TextValue`) -> `getText` (Simple getter for the `text` field)
- `field_150251_h` (`chatClickEvent`) -> `clickEvent` (Not directly related to chat)
- `field_150252_i` (`chatHoverEvent`) -> `hoverEvent`
- `func_150235_h` (`getChatClickEvent`) -> `getClickEvent`
- `func_150210_i` (`getChatHoverEvent`) -> `getHoverEvent`
- `func_150241_a` (`setChatClickEvent`) -> `setClickEvent`
- `func_150209_a` (`setChatHoverEvent`) -> `setHoverEvent`

---

`IChatComponent` uses some (in my opinion) rather confusing method names that should be changed to better reflect what they're actually doing. I'm bad at naming things so feel free to choose a better name that fits what the method actually does.

- (`getUnformattedText` (`func_150260_c`) is properly named and returns the unformatted text of the component itself and all children components.)
- `getUnformattedTextForChat` (`func_150261_e`) should be named something like `getUnformattedComponentText` because it only returns the unformatted text of the **component itself** and does NOT include the children components.
- `getChatComponentText_TextValue` (`func_150265_g`) is a simple getter for the text field in `ChatComponentText` and should be probably simply named `getText` or `getContent` or something like that.

**Comment by Minecrell** [comment]
The method name changes from #110 haven't been applied yet, so I'll also include them here:

- `func_150256_b` (`getChatStyle`) -> `getStyle` (Class name was changed to `Style`)
- `func_150255_a` (`setChatStyle`) -> `setStyle`
- `func_150261_e` (`getUnformattedTextForChat`) -> `getUnformattedComponentText` (Only returns the unformatted text of the component itself, doesn't include the siblings)
- `func_150265_g` (`getChatComponentText_TextValue`) -> `getText` (Simple getter for the `text` field)
- `field_150251_h` (`chatClickEvent`) -> `clickEvent` (Not directly related to chat)
- `field_150252_i` (`chatHoverEvent`) -> `hoverEvent`
- `func_150235_h` (`getChatClickEvent`) -> `getClickEvent`
- `func_150210_i` (`getChatHoverEvent`) -> `getHoverEvent`
- `func_150241_a` (`setChatClickEvent`) -> `setClickEvent`
- `func_150209_a` (`setChatHoverEvent`) -> `setHoverEvent`

**Comment by matthewprenger** [comment]
Fixed:
`func_150256_b`: `getChatStyle` -> `getStyle`
`func_150255_a`: `setChatStyle` -> `setStyle`
`func_150261_e`: `getUnformattedTextForChat` -> `getUnformattedComponentText`
`func_150265_g`: `getChatComponentText_TextValue` -> `getText`
`field_150251_h`: `chatClickEvent` -> `clickEvent`
`field_150252_i`: `chatHoverEvent` -> `hoverEvent`
`func_150235_h`: `getChatClickEvent` -> `getClickEvent`
`func_150210_i`: `getChatHoverEvent` -> `getHoverEvent`
`func_150241_a`: `setChatClickEvent` -> `setClickEvent`
`func_150209_a`: `setChatHoverEvent` -> `setHoverEvent`
