### ISSUE TITLE
BlockModelShapes Cleanup

### ISSUE THREAD

**Issue by ChloeDawn** [ModCoderPack/MCPBot-Issues#730]
**`net.minecraft.client.renderer.BlockModelShapes`**

- [ ] `field_178129_a`: `bakedModelStore` -> `models`
- [ ] `func_178122_a`: `getTexture` -> `getParticleTexture`
- [x] `func_178125_b`: `getModelForState` -> `getModel`
- [ ] `func_178124_c`: `reloadModels` -> `reload`
- [ ] `func_209552_a`: `getPropertyMapString` -> `getVariantString`
- [ ] `func_209555_a`: `getPropertyValueString` -> `getValueName`

**Comment by kashike** [comment]
- [x] `func_178125_b`: `getModelForState` &rarr; `getModel`
