### ISSUE TITLE
BlockPos inner class renames

### ISSUE THREAD

**Issue by gegy1000** [ModCoderPack/MCPBot-Issues#731]
The `BlockPos` in the inner class names are redundant.

- [ ] `BlockPos$MutableBlockPos` -> `BlockPos$Mutable`
- [ ] `BlockPos$PooledMutableBlockPos` -> `BlockPos$PooledMutable`

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
