### ISSUE TITLE
TutorialSteps.getTutorial -> byName

### ISSUE THREAD

**Issue by InsomniaKitten** [ModCoderPack/MCPBot-Issues#732]
**`net.minecraft.client.tutorial.TutorialSteps`**

- [ ] `func_193307_a`: `getTutorial` -> `byName`
- [ ] `p_193307_0_`: `tutorialName` -> `name`

Better consistency with `EnumFacing.byName`

**Comment by kashike** [comment]
- [x] `func_193307_a`: `getTutorial` -> `byName`
- [x] `p_193307_0_`: `tutorialName` -> `name`
