### ISSUE TITLE
Minecraft ItemRenderer/RenderItem Cleanup

### ISSUE THREAD

**Issue by InsomniaKitten** [ModCoderPack/MCPBot-Issues#734]
**`net.minecraft.client.Minecraft`**

- [ ] `field_175621_X`: `renderItem` -> `itemRenderer`
- [ ] `field_175620_Y`: `itemRenderer` -> `firstPersonRenderer`
- [ ] `func_175599_af`: `getRenderItem` -> `getItemRenderer`
- [ ] `func_175597_ag`: `getItemRenderer` -> `getFirstPersonRenderer`

There is no argument that this would cause silent bugs, as the methods within each class differ entirely, and would produce errors at every call site post-change.

Relevant ticket: #514

**Comment by bs2609** [comment]
Original ticket is #78, for reference.

**Comment by kashike** [comment]
- [x] `field_175621_X`: `renderItem` &rarr; `itemRenderer`
- [x] `field_175620_Y`: `itemRenderer` &rarr; `firstPersonRenderer`
- [x] `func_175599_af`: `getRenderItem` &rarr; `getItemRenderer`
- [x] `func_175597_ag`: `getItemRenderer` &rarr; `getFirstPersonRenderer`
