### ISSUE TITLE
IInventory names

### ISSUE THREAD

**Issue by Runemoro** [ModCoderPack/MCPBot-Issues#736]
Simplify names:
- [ ] `getSizeInventory()` -> `getInventorySize()`
- [ ] `getStackInSlot(int index)` -> `getStack(int slot)`
- [ ] `isItemValidForSlot(int index, ItemStack stack)` -> `canAddItems(int slot, ItemStack stack)`
- [ ] `setInventorySlotContents(int index, ItemStack stack)` -> `setSlotContents(int slot, ItemStack stack)`
- [ ] `decrStackSize(int index, int count)` -> `takeItems(int slot, int count)`
- [ ] `removeStackFromSlot(int index)` -> `ItemStack takeAllItems(int slot)`
- [ ] `isUsableByPlayer(EntityPlayer player)` -> `isUsableBy(EntityPlayer player)`

Fix incorrect name:
- [ ] `getInventoryStackLimit()` -> `getStackSizeLimit()` (limits the stack *size*, not number of stacks)

Add "Inventory" in method names since IInventory is implemented by tile entities so it should be clear the methods refer to the inventory rather than the tile entity itself:
- [ ] `getHeight()` -> `getInventoryHeight()`
- [ ] `getWidth()` -> `getInventoryWidth()`

**Comment by InsomniaKitten** [comment]
Please add SRG name references

**Comment by Pokechu22** [comment]
I'm not sure whether those should be plural or singular and whether they're the best choice ("canAddItems" sounds odd, and "takeItems"/"takeAllItems" feel like they'd be applying to the entire inventory and not a specific slot).  Also, "canUsableBy" just sounds wrong; "isUsableBy" would be better (or alternatively "canBeUsedBy").

**Comment by kashike** [comment]
#533
