### ISSUE TITLE
BlockModelShapes/ItemModelMesher Rename

### ISSUE THREAD

**Issue by ChloeDawn** [ModCoderPack/MCPBot-Issues#737]
Request ticket for #645 

- [ ] `net.minecraft.client.renderer.BlockModelShapes` -> `BlockModelCache`
- [ ] `net.minecraft.client.renderer.ItemModelMesher` -> `ItemModelCache`

`StateModelCache` had originally been suggested - however on second thought, with the addition of fluid states in 1.13, "state" could be seen as fairly ambiguous in this case. `Block` also pairs with `Item` better.

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
