### ISSUE TITLE
CreativeSettings -> HotbarSnapshots

### ISSUE THREAD

**Issue by InsomniaKitten** [ModCoderPack/MCPBot-Issues#738]
- [ ] **`net/minecraft/client/settings/CreativeSettings` -> `HotbarSnapshots`**
---
- [ ] `func_192563_a`: `getHotbarSnapshot` -> `get`
- [ ] `field_191950_u`: `creativeSettings` -> `hotbarSnapshots`
- [ ] `func_199403_al`: `getCreativeSettings` -> `getHotbarSnapshots`
---
Although this class' logger describes it as "creative mode options", the general implementation is specifically for hotbar snapshots. The getter itself that pulls from the `HotbarSnapshot[]` now handles the lazy loading, implying this class will only ever be loaded in the context of accessing a hotbar snapshot, with no other intention of loading for future settings.

**Comment by bs2609** [comment]
> The getter itself that pulls from the HotbarSnapshot[] now handles the lazy loading, implying this class will only ever be loaded in the context of accessing a hotbar snapshot, with no other intention of loading for future settings.

Not really - why wouldn't they just add a lazy `load` call to any other settings accessor?

**Comment by InsomniaKitten** [comment]
Okay well that point wasn't very strong, I'll admit that. But if you look at the constructor, it's body and parameters are specific to loading hotbar snapshot data. Either way, I don't see anything other than the logger messages that imply this class is more than just storage for hotbar snapshots. Possibly the logger messages are legacy code?

**Comment by bs2609** [comment]
We've been trying not to hardcode names to current usage too much, and there's no real benefit to changing this that isn't purely based on conjecture.

> Possibly the logger messages are legacy code?

The class was introduced in 1.12.

**Comment by InsomniaKitten** [comment]
Closing for now then, we can review the status of the class in 1.14.
