### ISSUE TITLE
Renderer Class Renames

### ISSUE THREAD

**Issue by InsomniaKitten** [ModCoderPack/MCPBot-Issues#740]
- [ ] `net/minecraft/client/renderer/entity/RenderManager` -> `EntityRenderer`?
- [ ] `net/minecraft/client/renderer/EntityRenderer` -> `GameRenderer`
- [ ] `net/minecraft/client/renderer/RenderGlobal` -> `WorldRenderer`

**Comment by kashike** [comment]
https://github.com/MinecraftForge/MCPConfig/commit/3292260f68f664e93f44bcaa346299b76e8c1d83

- [x] `net/minecraft/client/renderer/EntityRenderer` &rarr; `net/minecraft/client/renderer/GameRenderer`
- [x] `net/minecraft/client/renderer/RenderGlobal` &rarr; `net/minecraft/client/renderer/WorldRenderer`
