### ISSUE TITLE
EntityTracker(Entry) names

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#743]
See also #621, #635.

* `EntityTracker`:
  - [ ] `field_72794_c`: `trackedEntityHashTable` -> `trackedEntities`
  - [ ] `field_72792_d`: `maxTrackingDistanceThreshold` -> `maxTrackingDistance` ? (see #621)
  - [ ] `func_187253_a`: `getPositionLong` -> `encodePosition` ?
  - [ ] `func_72787_a`: `removePlayerFromTrackers` -> `removePlayer`
  - [ ] `func_85172_a`: `sendLeashedEntitiesInChunk` -> ???

* `EntityTrackerEntry`:
  - [x] `func_73122_a`: `updatePlayerList` -> `tick`
  - [ ] `func_111190_b`: `sendMetadata` -> ???
  - [ ] `func_151259_a`: `sendPacketToTrackedPlayers` -> `sendToTracking`
  - [ ] `func_73119_a`: `sendDestroyEntityPacketToTrackedPlayers` -> `removeEntity` / `onRemoval` ?
  - [ ] `func_73118_a`: `removeFromTrackedPlayers` -> ???
  - [ ] `func_73117_b`: `updatePlayerEntity` -> `updatePlayer`
  - [ ] `func_73121_d`: `isPlayerWatchingThisChunk` -> `isWatchingChunk` / `isChunkWatched` ?
  - [x] `func_73125_b`: `updatePlayerEntities` -> `updatePlayers`
  - [ ] `func_73123_c`: `removeTrackedPlayerSymmetric` -> ???

* Notes:
  * `sendLeashedEntitiesInChunk`: as per the method comment, sends both leashed entities (`SPacketEntityAttach`) and entities with passengers (`SPacketSetPassengers`). The distinguishing feature here is that this is done directly after the chunk data packet is sent.
  * `removeFromTrackedPlayers` / `removeTrackedPlayerSymmetric`: annoyingly similar in use and function (see https://github.com/ModCoderPack/MCPBot-Issues/issues/743#issuecomment-418887717).
  * `sendMetadata`: sends (if needed) datamanager entries (`SPacketEntityMetadata`) and synchronised attribute values (`SPacketEntityProperties`).
  * `sendDestroyEntityPacketToTrackedPlayers`: called on tracker entries when they are removed from the tracker (from `EntityTracker.untrack`).

**Comment by bs2609** [comment]
Further context:

```java
// called from tracker.untrack(player)
public void removeFromTrackedPlayers(EntityPlayerMP playerMP)
{
    if (this.trackingPlayers.contains(playerMP))
    {
        this.trackedEntity.removeTrackingPlayer(playerMP);
        playerMP.removeEntity(this.trackedEntity);
        this.trackingPlayers.remove(playerMP);
    }
}
```

```java
// called from tracker.removePlayer(player)
public void removeTrackedPlayerSymmetric(EntityPlayerMP playerMP)
{
    if (this.trackingPlayers.contains(playerMP))
    {
        this.trackingPlayers.remove(playerMP);
        this.trackedEntity.removeTrackingPlayer(playerMP);
        playerMP.removeEntity(this.trackedEntity);
    }
}
```

**Comment by kashike** [comment]
- [x] `func_73122_a`: `updatePlayerList` &rarr; `tick`
- [x] `func_73125_b`: `updatePlayerEntities` &rarr; `updatePlayers`
