### ISSUE TITLE
Item/Block$Builder -> Item/Block$Properties

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#744]
This isn't a builder, it's a set of properties.

`net/minecraft/block/Block$Builder` -> `net/minecraft/block/Block$Properties`
`net/minecraft/item/Item$Builder` -> `net/minecraft/item/Item$Properties`

**Comment by gegy1000** [comment]
Should `Biome$BiomeBuilder` be renamed similarly?

**Comment by liach** [comment]
I strongly agree with this change. They are an argument for block constructors, not objects for creating blocks.

**Comment by kashike** [comment]
`BiomeBuilder` is special-cased: the `toString` has `BiomeBuilder`

**Comment by kashike** [comment]
https://github.com/MinecraftForge/MCPConfig/commit/3292260f68f664e93f44bcaa346299b76e8c1d83

- [x] `net/minecraft/block/Block$Builder` &rarr; `net/minecraft/block/Block$Properties`
- [x] `net/minecraft/item/Item$Builder` &rarr; `net/minecraft/item/Item$Properties`
