### ISSUE TITLE
EnumCreatureType names

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#745]
* Fields:
  - [x] `field_75605_d`: `creatureClass` -> `baseClass` ?
  - [ ] `field_75606_e`: `maxNumberOfCreature` -> `spawnCap`
  - [ ] `field_75604_g`: `isPeacefulCreature` -> `isPeaceful`

* Methods:
  - [x] `func_75598_a`: `getCreatureClass` -> `getBaseClass` ?
  - [ ] `func_75601_b`: `getMaxNumberOfCreature` -> `getSpawnCap`
  - [ ] `func_75599_d`: `getPeacefulCreature` -> `isPeaceful`
  - [ ] `func_82705_e`: `getAnimal` -> `isAnimal`

**Comment by kashike** [comment]
- [x] `field_75605_d`: `creatureClass` &rarr; `baseClass`
- [x] `func_75598_a`: `getCreatureClass` &rarr; `getBaseClass`
