### ISSUE TITLE
ItemFood. func_77845_h  : isWolfsFavoriteMeat -> isWolfFood 

### ISSUE THREAD

**Issue by strikerrocker** [ModCoderPack/MCPBot-Issues#748]
`isWolfsFavoriteMeat `is too verbose so `isWolfFood` perfectly fits the method usages in EntityWolf and 
shorter

**Comment by kashike** [comment]
How about something more generic, such as `isMeat`? It's only `true` for meat foods (porkchop, beef, chicken, rotten flesh, rabbit, mutton).

**Comment by Pokechu22** [comment]
`isMeat` sounds good to me.  field_77856_bY should also be renamed (it's the stored field for it).  p_i48492_3_ was unnamed but is now `isWolfFood`; it might also be changed or might not.

**Comment by kashike** [comment]
- [x] `field_77856_bY`: `isWolfsFavoriteMeat` &rarr; `meat`
- [x] `p_i48492_3_`: `isWolfFood` &rarr; `meat`
- [x] `func_77845_h`: `isWolfsFavoriteMeat` &rarr; `isMeat`
