### ISSUE TITLE
BiomeColorHelper Cleanup

### ISSUE THREAD

**Issue by InsomniaKitten** [ModCoderPack/MCPBot-Issues#749]
**`net.minecraft.world.biome.BiomeColorHelper`**

- [ ] `func_180285_a`: `getColorAtPos` -> `getColor`
- [ ] `func_180286_a`: `getGrassColorAtPos` -> `getGrassColor`
- [ ] `func_180287_b`: `getFoliageColorAtPos` -> `getFoliageColor`
- [ ] `func_180288_c`: `getWaterColorAtPos` -> `getWaterColor`
- [ ] `p_180285_2_`: `colorResolver` -> `resolver`
- [ ] `p_180285_0_`: `blockAccess` -> `reader`
- [ ] `p_180286_0_`: `blockAccess` -> `reader`
- [ ] `p_180287_0_`: `blockAccess` -> `reader`
- [ ] `p_180288_0_`: `blockAccess` -> `reader`

**Comment by InsomniaKitten** [comment]
Related naming patterns within the `Biome` class:

**`net.minecraft.world.biome.Biome`**

- [ ] `func_180627_b`: `getGrassColorAtPos` -> `getGrassColor`
- [ ] `func_180625_c`: `getFoliageColorAtPos` -> `getFoliageColor`

**Comment by kashike** [comment]
- [x] `func_180285_a`: `getColorAtPos` &rarr; `getColor`
- [x] `func_180286_a`: `getGrassColorAtPos` &rarr; `getGrassColor`
- [x] `func_180287_b`: `getFoliageColorAtPos` &rarr; `getFoliageColor`
- [x] `func_180288_c`: `getWaterColorAtPos` &rarr; `getWaterColor`
- [x] `p_180285_2_`: `colorResolver` &rarr; `resolver`
- [x] `p_180285_0_`: `blockAccess` &rarr; `worldIn`
- [x] `p_180286_0_`: `blockAccess` &rarr; `worldIn`
- [x] `p_180287_0_`: `blockAccess` &rarr; `worldIn`
- [x] `p_180288_0_`: `blockAccess` &rarr; `worldIn`
