### ISSUE TITLE
Typo for isChristmas in TileEntityChestRenderer

### ISSUE THREAD

**Issue by VikeStep** [ModCoderPack/MCPBot-Issues#75]
`field_147509_j` in `net.minecraft.client.renderer.tileentity.TileEntityChestRenderer` is currently `isChristams`, but it should be `isChristmas`.

Version: 1.7.2 - 1.8.9

It was spelled correctly in 1.6.4

**Comment by iChun** [comment]
I've corrected the typo on the bot.
