### ISSUE TITLE
BiomeColorHelper -> BiomeColors

### ISSUE THREAD

**Issue by InsomniaKitten** [ModCoderPack/MCPBot-Issues#750]
- [ ] `net/minecraft/world/biome/BiomeColorHelper` -> `BiomeColors`

```java
BiomeColors.getFoliageColor(world, pos);
```
See also: #749

**Comment by kashike** [comment]
https://github.com/MinecraftForge/MCPConfig/commit/3292260f68f664e93f44bcaa346299b76e8c1d83

- [x] `net/minecraft/world/biome/BiomeColorHelper` &rarr; `net/minecraft/world/biome/BiomeColors`
