### ISSUE TITLE
ColorizerFoliage/ColorizerGrass Cleanup

### ISSUE THREAD

**Issue by ChloeDawn** [ModCoderPack/MCPBot-Issues#751]
**`net.minecraft.world.ColorizerFoliage`**

- [ ] `field_77471_a`: `foliageBuffer` -> `map`
- [ ] `func_77467_a`: `setFoliageBiomeColorizer` -> `setMap`/`setColorMap`
- [ ] `p_77467_0_`: `foliageBufferIn` -> `mapIn`
- [x] `func_77470_a`: `getFoliageColor` -> `get`/`getColor`
- [x] `func_77466_a`: `getFoliageColorPine` -> `getSpruce`/`getSpruceColor`
- [x] `func_77469_b`: `getFoliageColorBirch` -> `getBirch`/`getBirchColor`
- [x] `func_77468_c`: `getFoliageColorBasic` -> `getDefault`/`getDefaultColor`

**`net.minecraft.world.ColorizerGrass`**

- [ ] `field_77481_a`: `grassBuffer` -> `map`
- [ ] `func_77479_a`: `setGrassBiomeColorizer` -> `setMap`/`setColorMap`
- [ ] `p_77479_0_`: `grassBufferIn` -> `mapIn`
- [x] `func_77480_a`: `getGrassColor` -> `get`/`getColor`

```java
ColorizerFoliage.getSpruceColor();
ColorizerFoliage.setColorMap(...);
ColorizerGrass.getColor(0.5, 1.0);
```

**Comment by kashike** [comment]
- [x] `func_77466_a`: `getFoliageColorPine` &rarr; `getSpruceColor`
- [x] `func_77469_b`: `getBirchFoliageColor` &rarr; `getBirchColor`
- [x] `func_77468_c`: `getFoliageColorBasic` &rarr; `getDefaultColor`
