### ISSUE TITLE
FoliageColorizer/GrassColorizer -> FoliageColors/GrassColors

### ISSUE THREAD

**Issue by InsomniaKitten** [ModCoderPack/MCPBot-Issues#752]
- [ ] `net/minecraft/world/ColorizerFoliage` -> `FoliageColors`
- [ ] `net/minecraft/world/ColorizerGrass` -> `GrassColors`

**Comment by kashike** [comment]
https://github.com/MinecraftForge/MCPConfig/commit/3292260f68f664e93f44bcaa346299b76e8c1d83

- [x] `net/minecraft/world/ColorizerFoliage` &rarr; `net/minecraft/world/FoliageColors`
- [x] `net/minecraft/world/ColorizerGrass` &rarr; `net/minecraft/world/GrassColors`
