### ISSUE TITLE
*ColorReloadListener Cleanup

### ISSUE THREAD

**Issue by InsomniaKitten** [ModCoderPack/MCPBot-Issues#753]
**`net.minecraft.client.resources.FoliageColorReloadListener`**

- [ ] `field_130079_a`: `LOC_FOLIAGE_PNG` -> `FOLIAGE_COLOR_MAP`

**`net.minecraft.client.resources.GrassColorReloadListener`**

- [ ] `field_130078_a`: `LOC_GRASS_PNG` -> `GRASS_COLOR_MAP`

**Comment by kashike** [comment]
- [x] `field_130079_a`: `LOC_FOLIAGE_PNG` &rarr; `FOLIAGE_LOCATION`
- [x] `field_130078_a`: `LOC_GRASS_PNG` &rarr; `GRASS_LOCATION`
