### ISSUE TITLE
JsonUtils Cleanup

### ISSUE THREAD

**Issue by ChloeDawn** [ModCoderPack/MCPBot-Issues#755]
- [ ] `func_188174_a` in `deserializeClass` -> `fromJsonElement`
- [ ] `func_188179_a` in `deserializeClass` -> `fromJsonElement`
- [ ] `func_188177_a` in `deserializeClass` -> `fromJsonElement`
- [x] `func_193840_a` in `gsonDeserialize` -> `fromJson`
- [x] `func_188176_a` in `gsonDeserialize` -> `fromJson`
- [x] `func_188178_a` in `gsonDeserialize` -> `fromJson`
- [x] `func_188173_a` in `gsonDeserialize` -> `fromJson`
---
- [ ] ~~`...`: `memberName` -> `key`~~

**Comment by kashike** [comment]
- [x] `func_193840_a`: `gsonDeserialize` &rarr; `fromJson`
- [x] `func_188176_a`: `gsonDeserialize` &rarr; `fromJson`
- [x] `func_188178_a`: `gsonDeserialize` &rarr; `fromJson`
- [x] `func_188173_a`: `gsonDeserialize` &rarr; `fromJson`

**Comment by kashike** [comment]
I'm not going to be changing `memberName` &rarr; `key` &middot; `memberName` is what Gson uses as their parameter name in their methods.

**Comment by liach** [comment]
Some of the getXxx methods can be renamed to requireXxx as they cast a json element to xxx or throw error

**Comment by liach** [comment]
The `checkNotNull` actually does something not much different from `getXxx`. See:
```java
public static boolean getBoolean(JsonElement json, String memberName) {
    if (json.isJsonPrimitive()) {
        return json.getAsBoolean();
    } else {
        throw new JsonSyntaxException("Expected " + memberName + " to be a Boolean, was " + toString(json));
    }
}
```
compare to 
```java
public static <T> T checkNotNull(T reference, @Nullable Object errorMessage) {
    if (reference == null) {
      throw new NullPointerException(String.valueOf(errorMessage));
    }
    return reference;
}
```

`getOrThrow`, `get` are definitely not informative. See this snippet:
```java
    /**
     * Gets the boolean value of the given JsonElement.  Expects the second parameter to be the name of the element's
     * field if an error message needs to be thrown.
     */
    public static boolean getBoolean(JsonElement json, String memberName) {
        if (json.isJsonPrimitive()) {
            return json.getAsBoolean();
        } else {
            throw new JsonSyntaxException("Expected " + memberName + " to be a Boolean, was " + toString(json));
        }
    }

    /**
     * Gets the boolean value of the field on the JsonObject with the given name.
     */
    public static boolean getBoolean(JsonObject json, String memberName) {
        if (json.has(memberName)) {
            return getBoolean(json.get(memberName), memberName);
        } else {
            throw new JsonSyntaxException("Missing " + memberName + ", expected to find a Boolean");
        }
    }

    /**
     * Gets the boolean value of the field on the JsonObject with the given name, or the given default value if the
     * field is missing.
     */
    public static boolean getBoolean(JsonObject json, String memberName, boolean fallback) {
        return json.has(memberName) ? getBoolean(json.get(memberName), memberName) : fallback;
}
```
All three methods are called `getBoolean`, but the first method is definitely doing something drastically different than other methods (the two below calls the first one). After some comparison, a name like `asBoolean` for the first method is better.
