### ISSUE TITLE
MathHelper -> Mth

### ISSUE THREAD

**Issue by InsomniaKitten** [ModCoderPack/MCPBot-Issues#756]
- [ ] `net/minecraft/util/math/MathHelper` -> `Mth`

A more concise class name for static math operations, that does not conflict with `java.lang.Math`

```java
public Vec3i(double xIn, double yIn, double zIn) {
    this(Mth.floor(xIn), Mth.floor(yIn), Mth.floor(zIn));
}
```

**Comment by gegy1000** [comment]
Iirc this was confirmed somewhere in Mojang code / a Mojang snippet

**Comment by kashike** [comment]
Going off of Guava's naming, `Math2`?

**Comment by Runemoro** [comment]
> Iirc this was confirmed somewhere in Mojang code / a Mojang snippet

Yes, there's a class called `RealmsMth` in the `net.minecraft.realms` package that proxies methods to `MathHelper`.

**Comment by InsomniaKitten** [comment]
Any changes to the class name would likely result in a similar response to my initial suggestion, so I'll just close this. Any other suggestions could be done in a separate ticket if there is a desire for change from anyone else.

**Comment by Barteks2x** [comment]
This seems to confirm that Mojang internally uses `Mth` as the name: https://pastebin.com/XBLdGqXQ (link from https://www.reddit.com/r/Minecraft/comments/1m97cw/while_you_are_all_crying_over_the_name_change_of/cc7f8s5/)
