### ISSUE TITLE
BlockStateHelper -> BlockStateMatcher

### ISSUE THREAD

**Issue by Lunatrius** [ModCoderPack/MCPBot-Issues#76]
`net.minecraft.block.state.pattern.BlockStateHelper` should be renamed to `BlockStateMatcher`. It's a predicate that is meant for block state matching and nothing else.

**Comment by LexManos** [comment]
1.9:
net/minecraft/block/state/pattern/BlockHelper -> BlockMatcher
net/minecraft/block/state/pattern/BlockStateHelper -> BlockStateMatcher
