### ISSUE TITLE
SPacketUpdateRecipesPacket → SPacketUpdateRecipes

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#760]
`net/minecraft/network/play/server/SPacketUpdateRecipesPacket` → `net/minecraft/network/play/server/SPacketUpdateRecipes`

For some reason `Packet` is on there twice...

**Comment by kashike** [comment]
https://github.com/MinecraftForge/MCPConfig/commit/3292260f68f664e93f44bcaa346299b76e8c1d83

- [x] `net/minecraft/network/play/server/SPacketUpdateRecipesPacket` &rarr; `net/minecraft/network/play/server/SPacketUpdateRecipes`
