### ISSUE TITLE
RayTraceResult Cleanup

### ISSUE THREAD

**Issue by ChloeDawn** [ModCoderPack/MCPBot-Issues#761]
- [x] `field_72313_a`: `typeOfHit` -> `type`
- [ ] `field_178784_b`: `sideHit` -> `face`
- [ ] `field_72307_f`: `hitVec` -> `pos`
- [x] `field_72308_g`: `entityHit` -> `entity`

**Comment by kashike** [comment]
- [x] `field_72313_a`: `typeOfHit` &rarr; `type`
- [x] `field_72308_g`: `entityHit` &rarr; `entity`
