### ISSUE TITLE
EntityPlayer.func_71007_a: displayGUIChest -> openInventory (+ more)

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#765]
EntityPlayer.func_71007_a: displayGUIChest -> displayInventory, displayGuiInventory

Not just chests, it's used for all vanilla `IInventory`s

**Comment by williewillus** [comment]
on a further note, I think all the various `display` methods in EntityPlayer should be changed to perhaps `open`. These `display` methods are also responsible for opening the container serverside, and nothing is being "displayed" in that case.

**Comment by kashike** [comment]
:+1: for `open`

**Comment by williewillus** [comment]
alright so (all on `EntityPlayer`)

func_184809_a: displayGuiEditCommandCart -> openCommandCart
func_184824_a : displayGuiCommandBlock -> openCommandBlock
func_180472_a: displayVillagerTradeGui -> openVillagerTrade
func_71007_a: displayGUIChest -> openInventory
func_180468_a: displayGui -> openContainer (this one is a bit special, the IInteractionObject has 1. a method to create the serverside container and 2. a string ID to identify which clientside gui to make)

**Comment by kashike** [comment]
- [x] `func_184824_a`: `displayGuiCommandBlock` &rarr; `openCommandBlock`
- [x] `func_184826_a`: `openGuiHorseInventory` &rarr; `openHorseInventory`
