### ISSUE TITLE
EntityPlayerMP.func_71123_m: mountEntityAndWakeUp -> onDisconnected

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#767]
`EntityPlayerMP.func_71123_m`: `mountEntityAndWakeUp` -> `onDisconnected`

Only called by NHPS when disconnecting. Perhaps `disconnect` will also work instead of `onDisconnected`.

**Comment by kashike** [comment]
- [x] `func_71123_m`: `mountEntityAndWakeUp` &rarr; `disconnect`
