### ISSUE TITLE
RendererLivingEntity -> RenderLivingEntity

### ISSUE THREAD

**Issue by RainWarrior** [ModCoderPack/MCPBot-Issues#77]
this one class stands out from the rest of entity renderers

**Comment by LexManos** [comment]
Chose LivingBase because it follows the same patterns as all the other classes, and RenderLiving already existed for '<T extends EntityLiving>' and this one is '<T extends EntityLivingBase>'
1.9:
net/minecraft/client/renderer/entity/RendererLivingEntity -> RenderLivingBase
