### ISSUE TITLE
ChunkStatus.comesAfter → isAtLeast

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#772]
- [ ] `func_209003_a` in `ChunkStatus`: `comesAfter` → `isAtLeast`

The implementation is this (note `>=`, not `>`):

```java
	public boolean comesAfter(ChunkStatus status) {
		return this.ordinal() >= status.ordinal();
	}
```

The only use is <ruby><rb>`Chunk.isPopulated`</rb><rp> (</rp><rt>func_150802_k</rt><rp>)</rp></ruby>:

```java
	public boolean isPopulated() {
		return this.status.comesAfter(ChunkStatus.POSTPROCESSED);
	}
```

This doesn't make sense, since `POSTPROCESSED` is the last value in `ChunkStatus`.  `comesAfter` implies that it would only be true for `FULLCHUNK` or similar (i.e. `>`).

**Comment by kashike** [comment]
- [x] `func_209003_a`: `comesAfter` &rarr; `isAtLeast`
