### ISSUE TITLE
PathNavigate -> EntityNavigator

### ISSUE THREAD

**Issue by gegy1000** [ModCoderPack/MCPBot-Issues#774]
- [ ] `net.minecraft.pathfinding.PathNavigate` -> `net.minecraft.pathfinding.EntityNavigator`

**Comment by gegy1000** [comment]
Alternatively `PathNavigator` works too and is more readable.

**Comment by kashike** [comment]
`PathNavigation` is another option.

**Comment by liach** [comment]
Just curious, shouldn't `net.minecraft.pathfinding` package be moved to `net.minecraft.entity.ai.pathfinding` instead?

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
