### ISSUE TITLE
PathNavigate Cleanup

### ISSUE THREAD

**Issue by gegy1000** [ModCoderPack/MCPBot-Issues#775]
Proposal for less verbose and more accurate PathNavigate field and method names. Goes along with #774.

#### Fields
- [ ] `field_75514_c` (`currentPath`) -> `activePath`
- [ ] `field_188563_q` (`lastTimeUpdated`) -> `lastCalculateTime`
- [ ] `field_188562_p` (`tryUpdatePath`) -> `shouldRecalculate`
- [ ] `field_75520_h` (`ticksAtLastPos`) -> `lastStuckCheckTicks`

#### Methods
- [ ] `func_188554_j ` (`updatePath`) -> `recalculatePath`
- [ ] `func_75488_a` (`getPathToXYZ`) -> `findPath`
- [ ] `func_179680_a` (`getPathToPos`) -> `findPath`
- [ ] `func_75494_a` (`getPathToEntityLiving`) -> `findPath`
- [ ] `func_75492_a` (`tryMoveToXYZ`) -> `navigateTo`
- [ ] `func_75497_a` (`tryMoveToEntityLiving`) -> `navigateTo`
- [ ] `func_75484_a` (`setPath`) -> `followPath`
- [ ] `func_75505_d` (`getPath`) -> `getActivePath`
- [ ] `func_75508_h` (`pathFollow`) -> `followPath`
- [ ] `func_179677_a` (`checkForStuck`) -> `checkStuck`
- [ ] `func_75500_f` (`noPath`) -> `isInactive`
- [ ] `func_75499_g` (`clearPath`) -> `stop`
- [ ] `func_188553_i` (`canUpdatePathOnTimeout`) -> `shouldRecalculate`

**Comment by bs2609** [comment]
Maybe add this to #510?

**Comment by gegy1000** [comment]
Oops, moved all of this over there.
