### ISSUE TITLE
IBlockStatePalette and implementers are no longer associated with blockstates

### ISSUE THREAD

**Issue by tterrag1098** [ModCoderPack/MCPBot-Issues#777]
### Classes
- [ ] `net.minecraft.world.chunk.IBlockStatePalette` -> `net.minecraft.util.palette.IPalette`
- [ ] `net.minecraft.world.chunk.BlockStatePaletteHashMap` -> `net.minecraft.util.palette.PaletteHashMap`
- [ ] `net.minecraft.world.chunk.BlockStatePaletteLinear` -> `net.minecraft.util.palette.PaletteArray`
- [ ] `net.minecraft.world.chunk.BlockStatePaletteRegistry` -> `net.minecraft.util.palette.PaletteIdentity`
- [ ] `net.minecraft.world.chunk.BlockStateContainer` -> `net.minecraft.util.palette.PalettedContainer` (Mojang name, see `lock()`)
- [ ] `net.minecraft.world.chunk.IBlockStatePaletteResizer` -> `net.minecraft.util.palette.ResizeCallback`

### Methods
- [x] `net.minecraft.world.chunk.IBlockStatePalette func_186039_a`: `getBlockState` -> `get`

**Comment by Pokechu22** [comment]
IMO it would be best to still include "state" in the name: `IStatePalette`, `StatePaletteHashMap`, etc.  Even though they _technically_ don't have any requirements to refer to a state, I think making the name more general would just be confusing (in the same vein as `IRegistry` is just a specialized `Map`, so it could totally be renamed to `IMap` but that doesn't make sense).

**Comment by tterrag1098** [comment]
They don't have any relations to states. We don't call it registries `IItemRegistry` for the same reason. There's nothing else in the game called a "palette" so this generic name is perfectly applicable.

**Comment by Pokechu22** [comment]
Hm, I thought they did have some references directly to states in it, but it doesn't seem like that's the case.

However, it doesn't make sense to rename this unless `IBlockStatePaletteResizer` and `BlockStateContainer` are also renamed.  `BlockStateContainer` actually has a message, `"Writing into PalettedContainer from multiple threads"`, that indicates it should be `PalettedContainer`.

I also don't think these should be in the `world.chunk` package anymore if they are to be considered generalized.

**Comment by tterrag1098** [comment]
Good point on the package.

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
