### ISSUE TITLE
RenderItem: move out of renderer.entity package

### ISSUE THREAD

**Issue by RainWarrior** [ModCoderPack/MCPBot-Issues#78]
it's not an entity renderer (that's RenderEntityItem), but a general item-rendering-related class.

**Comment by LexManos** [comment]
RenderItem and ItemRenderer are two cloosly linked classes, Yes this one needs to be moved out of entity however they should both be renamed to something better.
Please suggest names here guys.

**Comment by kashike** [comment]
`ItemRenderer` seems to handle items in a player's hands/arms

**Comment by mezz** [comment]
Name  change suggestions:
`net.minecraft.client.renderer.ItemRenderer` --> `FirstPersonRenderer`
`net.minecraft.client.renderer.RenderItem` --> `ItemRenderer`

The current `ItemRenderer` even has a field called `itemRenderer` which is a `RenderItem` heh

**Comment by bs2609** [comment]
re: #514, any update on @mezz's suggestions here?

**Comment by kashike** [comment]
Yes - added.

**Comment by kashike** [comment]
- [x] `net/minecraft/client/renderer/RenderItem` → `net/minecraft/client/renderer/ItemRenderer`
