### ISSUE TITLE
PlayerCapabilities -> PlayerAbilities

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#781]
NBT tag is `abilities`, not `capabilities`.

Additionally removes confusion with [Forge capabilities](https://mcforge.readthedocs.io/en/latest/datastorage/capabilities/).

`net/minecraft/entity/player/PlayerCapabilities` &rarr; `net/minecraft/entity/player/PlayerAbilities`

**Comment by Pokechu22** [comment]
This also would make it match the name for the packet (`SPacketPlayerAbilities`/`CPacketPlayerAbilities`, and also "Player Abilities" on wiki.vg).

**Comment by liach** [comment]
aren't capabilities and abilities the same?

**Comment by liach** [comment]
For my last comment: These two words are almost identical in English. https://www.dictionary.com/browse/capabilities

Naming it qualities or abilities is indeed better because the new names are shorter.
