### ISSUE TITLE
IWorldEventListener.onEntityRemoved

### ISSUE THREAD

**Issue by liach** [ModCoderPack/MCPBot-Issues#784]
See #430

- [ ] `func_72709_b` in `IWorldEventListener`: `onEntityRemoved` -> `onEntityUnloaded`

When the method is called, the entity might be just unloaded as a part of a chunk instead of when it is `removed`.

**Comment by liach** [comment]
Note: `field_70128_L` is only set to `true` only if the entity will never be added back to the world.

**Comment by kashike** [comment]
I think we'll keep the current name.

**Comment by tterrag1098** [comment]
Anyone can update javadocs.
