### ISSUE TITLE
ITextureObject -> ITexture

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#785]
Also `ITickableTextureObject` -> `ITickableTexture`.

All the existing implementing classes are named as such already: `AbstractTexture`, `SimpleTexture`, `DynamicTexture`, etc.

**Comment by gegy1000** [comment]
If this change is made, the names from #786 should probably be changed to match this.

**Comment by bs2609** [comment]
Yes, I was going to mention that somewhere, but then forgot.

After this, `field_110585_a` should go from `textureObjects` to just `textures`.

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
