### ISSUE TITLE
More miscellaneous texture names

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#787]
* `DynamicTexture`:
  - [ ] `field_110566_b`: `dynamicTextureData` -> ???
  - [ ] `func_110564_a`: `updateDynamicTexture` -> `update` ?
  - [ ] `func_195414_e`: `getTextureData` -> ???

* `LayeredColorMaskTexture`:
  - [ ] `field_174948_g`: `textureLocation` -> `location` ?
  - [ ] `field_174949_h`: `listTextures` -> `layerNames` / `layers` ?
  - [ ] `field_174950_i`: `listDyeColors` -> `layerColors` ?

* `LayeredTexture`:
  - [ ] `field_110567_b`: `layeredTextureNames` -> `layerNames` / `layers` ?

* `SimpleTexture`:
  - [ ] `field_110568_b`: `textureLocation` -> `location` ?

**Comment by gegy1000** [comment]
What about `updateDynamicTexture` -> `upload`? Might be more descriptive.
Regarding `dynamicTextureData`, it could be something similar to `imageBuffer` or `colorBuffer`?
