### ISSUE TITLE
"TEX_2S" is really lightmap

### ISSUE THREAD

**Issue by Cadiboo** [ModCoderPack/MCPBot-Issues#788]
`field_181715_o` in `net.minecraft.client.renderer.vertex.DefaultVertexFormats` : `TEX_2F` -> `TEX_2`

`field_181716_p` in `net.minecraft.client.renderer.vertex.DefaultVertexFormats` : `TEX_2S` -> `LIGHTMAP_2`

**Comment by bs2609** [comment]
Covered in #648.
