### ISSUE TITLE
ILocationArgument, LocationInput, and LocalLocationArgument consistency

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#790]
`ILocationArgument` does not actually implement `Argument`.  It's just a location (that can be either a position or a rotation, hackilly).  I think the name used for `LocationInput` is probably good to extend to all of them, although it does seem a bit awkward for the interface:

- [ ] `net/minecraft/command/arguments/ILocationArgument` &rarr; `net/minecraft/command/arguments/ILocationInput`
- [x] `net/minecraft/command/arguments/LocationInput`
- [ ] `net/minecraft/command/arguments/LocalLocationArgument` &rarr; `net/minecraft/command/arguments/LocalLocationInput`

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
