### ISSUE TITLE
IRegistry.field_212617_f: REGISTRY -> REGISTRIES

### ISSUE THREAD

**Issue by Earthcomputer** [ModCoderPack/MCPBot-Issues#793]
I know this breaks the convention of all the other names in the class, but I think this change is necessary since the current name could imply "singleton" or "the registry" rather than "the registry of registries".
 Currently my initial reaction when I look at `IRegistry.REGISTRY` is "what registry?"

**Comment by Earthcomputer** [comment]
Perhaps it would hurt if this were done for the other registries too, just to keep it consistent?

**Comment by kashike** [comment]
I'd prefer for this to stay as `REGISTRY` - 99.99999999% of the time nobody will even be touching this field.
