### ISSUE TITLE
Canyon → Ravine

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#794]
"Ravine" has been the term since these were added [in beta 1.8](https://mcupdate.tumblr.com/post/10199253666/minecraft-beta-18).  (See 5th bullet)

Fields:

- [ ] `field_201909_d` in `Biome`: `CANYON_WORLD_CARVER` &rarr; `RAVINE_WORLD_CARVER`
- [ ] `field_203612_e` in `Biome`: `UNDERWATER_CANYON_WORLD_CARVER` &rarr; `UNDERWATER_RAVINE_WORLD_CARVER`

Classes:

- [ ] `net/minecraft/world/gen/carver/CanyonWorldCarver` &rarr; `net/minecraft/world/gen/carver/RavineWorldCarver`
- [ ] `net/minecraft/world/gen/carver/UnderwaterCanyonWorldCarver` &rarr; `net/minecraft/world/gen/carver/UnderwaterRavineWorldCarver`

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
