### ISSUE TITLE
EntityPlayer.isNormalCube

### ISSUE THREAD

**Issue by ichttt** [ModCoderPack/MCPBot-Issues#795]
It is actually the exact opposite, as the result from `IBlockState#isNormalCube` is inverted before returning the value

- [ ] `func_207401_g` in `EntityPlayer`: `isNormalCube` -> ???

**Comment by williewillus** [comment]
I think this has something to do with "crawl-swimming" in 1x1 spaces. The places that use this are the mechanics that check if you can stand back up, and the mechanics to push you towards a 2 high spot if one exists nearby

**Comment by williewillus** [comment]
I'd rather it get renamed something sematnically relevant to that instead of what it forwards to
