### ISSUE TITLE
Missed UNMAPPED SRG names in net.minecraft.item.ItemSign

### ISSUE THREAD

**Issue by ahmed605** [ModCoderPack/MCPBot-Issues#798]
- [x] `p_195943_1_` in `net.minecraft.item.ItemSign`: `p_195943_1_` -> `pos`
- [x] `p_195943_2_` in `net.minecraft.item.ItemSign`: `p_195943_2_` -> `worldIn`
- [x] `p_195943_3_` in `net.minecraft.item.ItemSign`: `p_195943_3_` -> `player`
- [x] `p_195943_4_` in `net.minecraft.item.ItemSign`: `p_195943_4_` -> `stack`
- [x] `p_195943_5_` in `net.minecraft.item.ItemSign`: `p_195943_5_` -> `state`

**Comment by Pokechu22** [comment]
If it's not mapped, you can just set the names yourself using MCPBot; you don't need to create a report.  See [the help page](http://mcpbot.bspk.rs/help).

I've done these for you.  The commands I ran:

```
!sp p_195943_1_ pos
!sp p_195943_2_ worldIn
!sp p_195943_3_ player
!sp p_195943_4_ stack
!sp p_195943_5_ state
```

But, again, for future reference, you can do these yourself.
