### ISSUE TITLE
LightEmittingMatcher → TransparentMatcher or something

### ISSUE THREAD

**Issue by Pokechu22** [ModCoderPack/MCPBot-Issues#799]
`net.minecraft.block.state.pattern.LightEmittingMatcher` has nothing to do with whether a block emits light, but rather whether or not it is opaque.  The relevant heightmap is called `LIGHT_BLOCKING`, but the matcher actually tests for blocks with an opacity of 0, so I think the right name is something like `TransparentMatcher`.  (However, I haven't fully wrapped my head around the lightmap code so this might not be the best name for it)

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
