### ISSUE TITLE
Two ITickable's

### ISSUE THREAD

**Issue by modmuss50** [ModCoderPack/MCPBot-Issues#80]
Im not too sure what to suggest, but having two classes with the same name, that at a glance appear the same. Im talking about:

`net.minecraft.client.renderer.texture.ITickable`
and
`net.minecraft.util.ITickable`

Its only a small thing and just a suggestion.

**Comment by GirafiStudios** [comment]
What about changing the ITickable in:
net.minecraft.client.renderer.texture.ITickable
to ITickableTexture , would fit the naming of the other interfaces in that package.

**Comment by diesieben07** [comment]
Except there is already `ITickableTextureObject`, which extends the `ITickable` in that package.

**Comment by GirafiStudios** [comment]
I see what you mean - got any better ideas for another name for that interface?

**Comment by tterrag1098** [comment]
Why they are separate interfaces is the real question. Forge could potentially unify their use, but that's not a concern here. Maybe the one used on TEs should be `IUpdatable`, since its method is `update()` not `tick()`

**Comment by LexManos** [comment]
Forge does not merge vanilla structure like that.
They are separate because vanilla has them separate.
What is the problem with having two interfaces named the same? They do the exact same thing.
This is what packages are for.

**Comment by modmuss50** [comment]
One is client side only, so crashes the server if you import the wrong one. Its not a major issue, just a small thing.

**Comment by LexManos** [comment]
Thats bad modder, nothing to do with the mappings.

**Comment by GirafiStudios** [comment]
It's not like this is a huge problem or anything, I just see it as an annoyance if you accidently import the wrong interface.

**Comment by Unh0lyTigg** [comment]
I'd like to suggest `net.minecraft.client.renderer.texture.IRenderTickable` for the Client-only `ITickable`

**Comment by kashike** [comment]
I think it's `net.minecraft.client.renderer.texture.ITickableTextureObject` that needs a rename - if so, `net.minecraft.client.renderer.texture.ITickable` -> `ITickableTexture`

**Comment by gabizou** [comment]
*cough* smurfnaming *cough*

**Comment by LexManos** [comment]
It's staying the same in 1.9.

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
