### ISSUE TITLE
ModelBiped$ArmPose -> ModelBiped$HandState

### ISSUE THREAD

**Issue by ChloeDawn** [ModCoderPack/MCPBot-Issues#800]
Used to determine the state of the contents of the player's hands, the enumeration has nothing to do with arm posing.

- [ ]  `ModelBiped$ArmPose` -> `ModelBiped$HandState`

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
