### ISSUE TITLE
"Side" numbers

### ISSUE THREAD

**Issue by staj-d** [ModCoderPack/MCPBot-Issues#802]
In the MCP Mappings what sides do the numbers represent?
What is 0, 1 and 2 for side/what side do they represent?

**Comment by Pokechu22** [comment]
Which side it's on, with the same meaning as `SideOnly` in joined code you'd see with forge.  0 is client-only, 1 is server-only, and 2 is both server and client.

The value is generally not used in practice, and is completely ignored by forgegradle (it looks like the MCP python scripts do check it, but it doesn't seem strictly necessary).

**Comment by staj-d** [comment]
Ok thanks.

**Comment by staj-d** [comment]
Wait, but net.minecraft.command.arguments.EntityArgument.func_197094_d() is labeled as both client and server side in the mappings "mcp_snapshot-20180921-1.13" but when I run the method on the server side (unstable 1.13 forge) it returns a java.lang.NoSuchMethodError.

**Comment by LexManos** [comment]
It is a leggacy value used for some verificaiton before the client and server merged. There were actually some SRG values that existed in both the client and the server, that had different numbers for the same field. Or different fields with the same number.

In today world, it doesn't mean anything.

You should look for the annotations in code for what side things are in not the csv files.
