### ISSUE TITLE
IUnbakedModel.func_187965_e: getOverrideLocations -> getModels

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#804]
IUnbakedModel.func_187965_e: getOverrideLocations -> getModels

This is not just the override locations for items, this is all model paths that `this` IUnbakedModel depends on itself.

Why:
* In vanilla `ModelBlock`, not only are override locations added, but also the parent model
* In vanilla `VariantList`, which represents a model that dispatches between several weighted random submodels, it returns all of its submodels for this method.
* When baking models, `ModelBakery` loads everything returned from this method

Suggesting getModels to match getTextures, but personally i think getDependencies is better.

**Comment by kashike** [comment]
- [x] `func_187965_e`: `getOverrideLocations` -> `getDependencies`
