### ISSUE TITLE
Rename Enchantment Classes

### ISSUE THREAD

**Issue by Shadows-of-Fire** [ModCoderPack/MCPBot-Issues#805]
Enchantment class names may be better served if the names of non-reused classes matched the English name of the enchantment they represented.  Newer enchantment classes already do this (curse classes, frost walker, etc), but the older ones have names that are less than obvious.

All classes mentioned below are in the `net.minecraft.enchantment` package.

- [ ] `EnchantmentArrowDamage` -> `EnchantmentPower`
- [ ] `EnchantmentArrowFire` -> `EnchantmentFlame`
- [ ] `EnchantmentArrowKnockback` -> `EnchantmentPunch`
- [ ] `EnchantmentArrowInfinite` -> `EnchantmentInfinity`
- [ ] `EnchantmentDigging` -> `EnchantmentEfficiency`
- [ ] `EnchantmentDurability` -> `EnchantmentUnbreaking`
- [ ] `EnchantmentOxygen` -> `EnchantmentRespiration`
- [ ] `EnchantmentWaterWorker` -> `EnchantmentAquaAffinity`
- [ ] `EnchantmentWaterWalker` -> `EnchantmentDepthStrider`
- [ ] `EnchantmentUntouching` -> `EnchantmentSilkTouch`
- [ ] `EnchantmentFishingSpeed` -> `EnchantmentLure`

**Comment by liach** [comment]
Should they be named in suffix style as some less frequently used classes (e.g. commands) are now named in suffixes?

**Comment by Shadows-of-Fire** [comment]
I don't think so, they are game objects, and should follow class name conventions as all other registry-based objects.  This is just for consistency, as the newer enchantment classes are all `EnchantmentName`, unlike these older ones.

**Comment by liach** [comment]
ah, only commands were changed to use suffix, so the enchantments can stay on prefix.

**Comment by LexManos** [comment]
https://gist.github.com/LexManos/cab8cd55ff508e67d092e38452377e09#file-3_suffixes-tsrg-L636
