### ISSUE TITLE
BanList & IPBanEntry

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#81]
`BanList` -> `UserListIPBans`
`IPBanEntry` -> `UserListIPBansEntry`

**Comment by LexManos** [comment]
1.9:
net/minecraft/server/management/BanList -> UserListIPBans
net/minecraft/server/management/IPBanEntry -> UserListIPBansEntry
net/minecraft/server/management/BanEntry -> UserListEntryBan
