### ISSUE TITLE
Various unmapped World-related methods

### ISSUE THREAD

**Issue by HellFirePvP** [ModCoderPack/MCPBot-Issues#811]
1.13.2 missing mappings in `net.minecraft.world.World` and `net.minecraft.world.ForcedChunksSaveData`:
Seemingly this replaces the need for a forge chunk manager to keep certain chunks loaded at first glance. It prevents the specified chunk at that position from being unloaded and saves it into the WorldSavedData for persistence.

- [ ] Method in `net.minecraft.world.World`: `func_212412_ag` -> `getForcedChunkSet`
- [ ] Method in `net.minecraft.world.World`: `func_212416_f` -> `isChunkForceLoaded`
- [ ] 1st Parameter to `func_212416_f`: `p_212416_1_` -> `chunkX`
- [ ] 2nd Parameter to `func_212416_f`: `p_212416_2_` -> `chunkZ`
- [ ] Method in `net.minecraft.world.World`: `func_212414_b` -> `setChunkForceLoaded`
- [ ] 1st Parameter to `func_212414_b`: `p_212414_1_` -> `chunkX`
- [ ] 2nd Parameter to `func_212414_b`: `p_212414_2_` -> `chunkZ`
- [ ] 3rd Parameter to `func_212414_b`: `p_212414_3_` -> `setLoaded`
- [ ] Method in `net.minecraft.world.ForcedChunksSaveData`: `func_212438_a` -> `getForcedChunkSet`
- [ ] Field in `net.minecraft.world.ForcedChunksSaveData`: `field_212439_a` -> `forcedChunkSet`

`setLoaded` might be debateable. It's basically the flag that decides if the operation `setChunkForceLoaded`, in my suggestion, actually adds the specified position to the forced-chunk-list or removes it. Passing "true" tries to add that chunk to that list, passing "false" tries to remove it from said list.

**Comment by williewillus** [comment]
if they have no mcp name, you can go ahead and name the ones you feel confident about with MCPBot
