### ISSUE TITLE
ScoreDummyCriteria

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#82]
`ScoreBaseCriteria`
`ScoreGenericCriteria`

**Comment by LexManos** [comment]
1.9:
net/minecraft/scoreboard/IScoreObjectiveCriteria -> IScoreCriteria
net/minecraft/scoreboard/ScoreDummyCriteria -> ScoreCriteria
net/minecraft/scoreboard/ScoreHealthCriteria -> ScoreCriteriaHealth
net/minecraft/scoreboard/ScoreReadOnlyCriteria -> ScoreCriteriaReadOnly
net/minecraft/scoreboard/GoalColor -> ScoreCriteriaColored
net/minecraft/stats/ObjectiveStat -> net/minecraft/scoreboard/ScoreCriteriaStat
