### ISSUE TITLE
[1.14] `ChunkRender` (previously `RenderChunk`) -> `ChunkRenderer`

### ISSUE THREAD

**Issue by Cadiboo** [ModCoderPack/MCPBot-Issues#821]
- [x] `net.minecraft.client.renderer.chunk.IChunkRendererFactory` (previously `net.minecraft.client.renderer.chunk.IRenderChunkFactory`) -> `net.minecraft.client.renderer.chunk.IChunkRendererFactory` (**NO CHANGE HERE, it apparently got renamed to `Renderer` as part of the 1.13 -> 1.14 update**)
- [ ] `net.minecraft.client.renderer.chunk.ListedChunkRender` (previously `net.minecraft.client.renderer.chunk.ListedRenderChunk`) -> `net.minecraft.client.renderer.chunk.ListedChunkRenderer`
- [ ] `net.minecraft.client.renderer.chunk.ChunkRender` (previously `net.minecraft.client.renderer.chunk.RenderChunk`) -> `net.minecraft.client.renderer.chunk.ChunkRenderer`
- [ ] `net.minecraft.client.renderer.chunk.ChunkRenderCache` (previously `net.minecraft.client.renderer.chunk.RenderChunkCache`) -> `net.minecraft.client.renderer.chunk.ChunkRendererCache`

**Comment by Barteks2x** [comment]
Unless something in the code got a significant change in that class since 1.13.2, I don't really agree with RenderChunk being renamed to ChunkRenderer.
It's not actually doing any chunk rendering, it's mostly just holding the state about a given 16x16x16 region to render, and has a method to rebuild the chunk.

**Comment by LexManos** [comment]
@tterrag1098 This is not a valid vote, this is too batched together. 
As well as the fact that the original post had no explanation or call for a vote. 
So this has not passed for the 1.14.x lifecycle.
