### ISSUE TITLE
please add CORS headers for zips.

### ISSUE THREAD

**Issue by anatawa12** [ModCoderPack/MCPBot-Issues#822]
I want to load the MCP mappings from javascript. But the server returns without CORS headers so I can't load MCP mappings from javascript. 
Please add [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) headers.

**Comment by bspkrs** [comment]
This sounds like something that needs to be upgraded within the django web code... ugh.

**Comment by anatawa12** [comment]
I found a django app to add CORS headers. Could you use this? I didn't use django so I may have mistakes. [django-cors-headers](https://github.com/ottoyiu/django-cors-headers)

**Comment by anatawa12** [comment]
Sorry. I mistaked.
