### ISSUE TITLE
ICommandSource -> ICommandExecutor

### ISSUE THREAD

**Issue by tterrag1098** [ModCoderPack/MCPBot-Issues#824]
- [ ] `net.minecraft.command.ICommandSource` (`bt`): `ICommandSource` -> `ICommandExecutor`

This is a clearer name as to the purpose of the class, something that can execute commands. The nomenclature matches that of the `/execute [as]` command, and unties it from `net.minecraft.command.CommandSource` which is unrelated (and in fact wraps an `ICommandSource`).

**Comment by LexManos** [comment]
With a vote of 2 to 1 on 05/21/19 This passes and will be applied to 1.14.1.
