### ISSUE TITLE
NonNullList factory methods

### ISSUE THREAD

**Issue by ChloeDawn** [ModCoderPack/MCPBot-Issues#827]
**`net.minecraft.util.NonNullList`**
~~- [ ] `func_191196_a`: `create` -> `of`~~ TBC
~~- [ ] `func_191197_a`: `withSize` -> `ofSize`~~ TBC
~~- [ ] `func_193580_a`: `from` -> `copyOf`~~ TBC
- [ ] `p_191197_1_`: `fill` -> `defaultElementIn`
- [ ] `p_i47327_2_`: `listType` -> `defaultElementIn`

**Comment by bs2609** [comment]
I prefer `create` to `of`, which I've only really seen used for immutable collections. Having a list 'of' something is pretty meaningless if it then immediately becomes a list 'of' something else.

**Comment by InsomniaKitten** [comment]
`EnumSet` and `Optional` both use `of`. The former being mutable, the latter being transformable.

**Comment by InsomniaKitten** [comment]
On second thoughts... with the introduction of `List.of`/`List.copyOf` in J9, maybe you are right that this naming would be poor. The factory methods introduced by the JDK return immutable collections, and having `NonNullList.of` alongside `List.of` would imply equivalent semantics. Personally, I'm not a fan of `create`, but I'm unsure what a better name would be that isn't `of`.

**Comment by bs2609** [comment]
`EnumSet.of` is a good mutable example, although `noneOf` is the method to create an empty set there, all `of` methods require elements.

I still prefer `create` in any case.

I would also note that `from` does not copy, so `copyOf` is misleading.

**Comment by InsomniaKitten** [comment]
I'd be okay with leaving the names as-is if there are no better alternatives that don't coincide with naming patterns of immutable collections.
