### ISSUE TITLE
Changes to the Settings classes

### ISSUE THREAD

**Issue by ChloeDawn** [ModCoderPack/MCPBot-Issues#829]
Migrations relative to `net.minecraft.client`:
- [ ] `~.GameSettings` -> `~.options.Options`
There is no conflicting options class, and Mojang explicitly refers to them as options both in logging and the external file name. I considered a Client prefix to clarify that this options class is a client-only implementation, but I think the package it resides in implies that enough - and another problem was that if this class were to be prefixed, then the creative options class really should be too... but "ClientCreativeOptions" or "CreativeClientOptions" sound messy, IMO.

- [ ] `~.settings.CreativeSettings` -> `~.options.CreativeOptions`
Technically Mojang refers to the creative options as "creative mode options" but I feel that "mode" is redundant verbosity in the class name.

- [ ] `~.settings.HotbarSnapshot` -> `~.options.SavedHotbar`
The "SavedHotbar" class represents... well... a saved hotbar. They are not "snapshots". Mojang actually describes them in localization as "saved toolbars" but I feel that is a bit too controversial for a state that can hold more than just tools.

---
Related member migrations:
- [ ] `field_199424_a` in `HotbarSnapshot`: `hotbarItems` -> `items`
- [ ] `field_192568_d` in `CreativeSettings`: `hotbarSnapshots` -> `savedHotbars`
- [ ] `func_192563_a` in `CreativeSettings`: `getHotbarSnapshot` -> `getSavedHotbar`
- [ ] `func_199403_al` in `Minecraft`: `getCreativeSettings` -> `getCreativeOptions`
- [ ] `func_192044_a` in `CreativeScreen`: `handleHotbarSnapshots` -> `handleSavedHotbars`

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
