### ISSUE TITLE
BlockContainer -> BlockVanillaTE or similar

### ISSUE THREAD

**Issue by tterrag1098** [ModCoderPack/MCPBot-Issues#83]
This class is used by modders (especially newbies) way too often, and as of 1.8 its behavior is even more confusing. It gives the -1 render type by default, as well as having some weird code in it concerning cacti. There is just no reason for mods to use it, and the name should make that clear.

**Comment by smbarbour** [comment]
You seem to be seeing different source than I am seeing.  I see an abstract class defining default behavior for blocks that have a TileEntity (like removing the TE when the block is broken) and I see no code concerning cacti.

**Comment by LexManos** [comment]
It has two functions that default check for cactus yes.
However those functions are more along the lines of 'isInvalidNeighbor' and 'hasInvalidNeighbor' 
They are only used for placement by the banner and sign classes.
Possibly to expand more.

However, i think we should keep this class named Container because thats what everyone uses it for.
As it's existed seince way before ITileEntityProvider existed it's the defactor 'Base TileEntity block' for modded minecraft.

**Comment by tterrag1098** [comment]
But no one *should* be using it. There's no good reason to, when ITEP exists. It also has nothing to do with Containers.

**Comment by smbarbour** [comment]
I would argue that it is better to extend BlockContainer than incorrectly implement ITEP (such as failing to properly remove the TileEntity when the block is removed)

**Comment by tterrag1098** [comment]
Um, what? Block takes care of that, BlockContainer is NOT necessary.

**Comment by smbarbour** [comment]
If Block has that code, why would BlockContainer, which extends Block, have it as well?

**Comment by LexManos** [comment]
Block does NOT have this code.
Forge adds it: https://github.com/MinecraftForge/MinecraftForge/blob/master/patches/minecraft/net/minecraft/block/Block.java.patch#L83
It also does sorta adhere to a container because it has:
```
    public boolean onBlockEventReceived(World worldIn, BlockPos pos, IBlockState state, int eventID, int eventParam)
    {
        super.onBlockEventReceived(worldIn, pos, state, eventID, eventParam);
        TileEntity tileentity = worldIn.getTileEntity(pos);
        return tileentity == null ? false : tileentity.receiveClientEvent(eventID, eventParam);
    }

Which is just a fundamental way of dispatching things. I';m not seeing a strong need to rename this as there isn't an issue with people using it. And A LOT of people use it as it's the defacto 'Extend this if you have a TE'
