### ISSUE TITLE
Missing Mappings in BipedModel and EntityModel

### ISSUE THREAD

**Issue by itsmeow** [ModCoderPack/MCPBot-Issues#830]
These two are fairly obvious if you look at the cube sizes that get assigned to them
- [x] `field_78116_c` in `net.minecraft.client.renderer.entity.model.BipedModel`: `field_78116_c` -> `bipedBody`
- [x] `field_78115_e` in `net.minecraft.client.renderer.entity.model.BipedModel`: `field_78115_e` -> `bipedHead`

This last one I was hoping someone could confirm, this is what it looks like (see this code in BipedModel):

- [x] `field_217113_d` in `net.minecraft.client.renderer.entity.model.EntityModel`: `field_217113_d` -> `isRiding`

```java
if (this.field_217113_d) {
         this.bipedRightArm.rotateAngleX += (-(float)Math.PI / 5F);
         this.bipedLeftArm.rotateAngleX += (-(float)Math.PI / 5F);
         this.bipedRightLeg.rotateAngleX = -1.4137167F;
         this.bipedRightLeg.rotateAngleY = ((float)Math.PI / 10F);
         this.bipedRightLeg.rotateAngleZ = 0.07853982F;
         this.bipedLeftLeg.rotateAngleX = -1.4137167F;
         this.bipedLeftLeg.rotateAngleY = (-(float)Math.PI / 10F);
         this.bipedLeftLeg.rotateAngleZ = -0.07853982F;
}
```

**Comment by williewillus** [comment]
these have been named now I think

**Comment by GirafiStudios** [comment]
They are indeed all named now.
Proof: https://i.imgur.com/q1gibp1.png
