### ISSUE TITLE
Rename ItemEntity.getItem()

### ISSUE THREAD

**Issue by itsmeow** [ModCoderPack/MCPBot-Issues#831]
This one really hurts to read sometimes when trying to get the item instance `entityitem.getItem().getItem()` and I think everyone agrees that this change would make FAR more sense.
- [ ] `func_92059_d` in `net.minecraft.entity.item.ItemEntity`: `getItem` -> `getItemStack`
- [ ] `func_92058_a` in `net.minecraft.entity.item.ItemEntity`: `setItem` -> `setItemStack`

This was addressed and introduced in #338, but it doesn't make sense given that it's a stack and not an actual item instance. I understand it's based off the tag, but the tag is still what we call an `ItemStack`, and not an `Item`. For all we know Mojang could call `ItemStack` `Item` and `Item` `ItemType`. But for our purposes I think this makes much more sense and is much more readable.

`entityitem.getItemStack().getItem()` vs `entityitem.getItem().getItem()`

**Comment by DarkGuardsman** [comment]
Can I make an alt suggestion of 

func_92059_d in net.minecraft.entity.item.ItemEntity: getItem -> getHeldItemStack
func_92058_a in net.minecraft.entity.item.ItemEntity: setItem -> setHeldItemStack

or 

func_92059_d in net.minecraft.entity.item.ItemEntity: getItem -> getHeldItem
func_92058_a in net.minecraft.entity.item.ItemEntity: setItem -> setHeldItem

or 

func_92059_d in net.minecraft.entity.item.ItemEntity: getItem -> getContainedItem
func_92058_a in net.minecraft.entity.item.ItemEntity: setItem -> setContainedItem

These options would better convey the idea that the entity is containing or holding the item.

**Comment by juliand665** [comment]
The problem I see with `held` is that it may be confused with one held in the hand.

Additionally, all suggestions without `Stack` at the end don't convey that they actually return `ItemStack`s, resulting in weird code like @itsmeow pointed out to start with: `itemEntity.getFooItem().getItem()` (specifically the `…Item().getItem()`

**Comment by DarkGuardsman** [comment]
Depends if you think of the entity as the item or as an entity holding the item.

**Comment by juliand665** [comment]
The confusion between held meaning "containing" and it meaning "held in a hand" is independent of what you think of `ItemEntity` as.

I'm not debating whether or not adding a qualifier like that to mean "containing" is a good idea, I'm merely pointing out the fact that the exact wording "held" has a potential for confusion, which is important to consider when naming things.

**Comment by DarkGuardsman** [comment]
Yep but it is better than getItem() though getItemStack() might be better

**Comment by Alpvax** [comment]
I would vote for either getItemStack, or just getStack.
The itemstack IS the entity, and everyone knows exactly which item is being talked about, so I think the held/contained qualifier is meaningless and just adds confusion

**Comment by liach** [comment]
I support the `getStack` name.

**Comment by DarkGuardsman** [comment]
> The itemstack IS the entity

This can be argued in any direction, I personally see EntityItem as a holder rather than the item. However, this is not really the point of the matter as we could be here all day arguing semantics. 

> I would vote for either getItemStack, or just getStack.

Honestly I say we just got with getItemStack() in the end. Its the easiest change over and provides just enough improvement to be useful.
