### ISSUE TITLE
Changes regarding Food / Food.Builder class

### ISSUE THREAD

**Issue by MrTroble** [ModCoderPack/MCPBot-Issues#833]
See comment below

**Comment by williewillus** [comment]
it's not *only* healing. That code you snipped is probably from the wolf code I bet. There it uses the food value to heal the wolf directly, but for players the food value....goes into their food bar (which you didn't screenshot, so this is slightly misleading). It's used for two things, so the lowest common denominator name is `value`.

This is the classic "I saw it used in one place so the name must come from its meaning in that one context" mistake, without considering all contexts where the variable is used.

**Comment by MrTroble** [comment]
Well we need to do give this other names ... what about taking
`foodLevel`

as in

`field_221470_a in net.minecraft.item.Food: value -> foodLevel`
`field_221458_a in net.minecraft.item.Food.Builder: value -> foodLevel`
`p_221456_1_ in net.minecraft.item.Food.Builder: hungerIn -> foodLevelIn`
`func_221456_a in net.minecraft.item.Food.Builder: hunger -> level`

This would conform with the rest of the players food code and would also describe all of the cases (e.g. Cat and Wolf healing)
![alt](https://image.prntscr.com/image/_tqJdSR-TN6lbpD7LDxgEQ.png)

**Comment by williewillus** [comment]
sure, that works too
