### ISSUE TITLE
Consistent names for TicketManager register and release methods (func_219356_a, func_219345_b, func_219331_c, func_219362_d)

### ISSUE THREAD

**Issue by Niko-sk2x** [ModCoderPack/MCPBot-Issues#834]
For the last few days I've been looking at and trying to understand 1.14 chunk management code and deobfuscate some of it. I have ideas for naming `func_219356_a`, `func_219345_b`, `func_219331_c` and `func_219362_d` but one of them (`func_219356_a`, named `register`) is already named in a way that would be inconsistent (and conflicting) with the names I want to propose.

`func_219356_a` and `func_219331_c` are both "register" methods, with the same method signature, but slightly different function. In the same way, both `func_219345_b` and `func_219362_d` are "release".

Since they have the same signatures they can't have the same names, so here is what I wanted to name them:
 * `func_219356_a` -> `registerWithLevel`
    This method interprets the third (int) argument as level that goes into the `ChunkDistanceGraph`. It's not easy to interpret what this "level" actually means. As far as I could understand, lower level is "higher radius" here, except some of the higher level values are also used to represent different chunk status values (which actually directly translate into radius anyway). I think the "base value" of 33 is there so that render distance values up to 32 can be supported without ever going into negative level values.
 * `func_219345_b` -> `releaseWithLevel` (same as above)
 * `func_219331_c` -> `register`
   Here the third argument is interpreted as load distance/radius (in a square around the center). 
 * `func_219362_d` -> `release` (same as above)

**Comment by williewillus** [comment]
I just removed my names for `register` and `release`, feel free to use your naming scheme instead
