### ISSUE TITLE
Left/Right issue in AbstractList (1.14.3)

### ISSUE THREAD

**Issue by skyecodes** [ModCoderPack/MCPBot-Issues#839]
There's a mismatch between the getLeft and the getRight method : they respectively return the right position and the left position.

- method in `net.minecraft.client.gui.widget.list.AbstractList`: `getLeft` -> `getRight`
- method in `net.minecraft.client.gui.widget.list.AbstractList`: `getRight` -> `getLeft`

To avoid this confusion :
- field in `net.minecraft.client.gui.widget.list.AbstractList`: `x0` -> `left`
- field in `net.minecraft.client.gui.widget.list.AbstractList`: `x1` -> `right`
- field in `net.minecraft.client.gui.widget.list.AbstractList`: `y0` -> `top`
- field in `net.minecraft.client.gui.widget.list.AbstractList`: `y1` -> `bottom`

**Comment by kashike** [comment]
These names are provided by Mojang.
