### ISSUE TITLE
ServerConfigurationManager -> PlayerList

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#84]
We have `DedicatedPlayerList` and `IntegratedPlayerList`.

`serverConfigManager` -> `playerList`
`getConfigurationManager` -> `getPlayerList`
`setConfigManager` -> `setPlayerList`

**Comment by LexManos** [comment]
Something i've wanted to change for a while.

1.9:
net/minecraft/server/management/ServerConfigurationManager -> PlayerList
