### ISSUE TITLE
[MCPBot Issue] Lambda parameter names are not mappable

### ISSUE THREAD

**Issue by psoftware** [ModCoderPack/MCPBot-Issues#841]
Hi, I'm new to MCPBot and this contribution mechanism and I'm happy to contribute.
I tried to suggest to the bot some lambda parameter mappings but without success.  I didn't find any past issue here or info on the main website.

Is it possible to submit this type of mapping? I hope so, because part of chunk loading code would remain unreadable due to some lambdas used with the CompletableFuture methods.

Thank you

**Comment by williewillus** [comment]
IMO this is crucially needed, Mojang is using lambdas more and more since the recent(-ish) move to Java 8 and if we can't get sane names for the lambda parameters, then it just becomes parameter soup and impossible to navigate.
