### ISSUE TITLE
20190705-1.14.3 Duplicate method name and signatures in RegionSectionCache

### ISSUE THREAD

**Issue by lehjr** [ModCoderPack/MCPBot-Issues#842]
These appear to have been added for net.minecraft.world.chunk.storage.RegionSectionCache
```
func_219108_a,serialize,2,
func_219112_a,save,2, 
func_219116_a,markDirty,2,
func_219117_c,save,2,
```
However, both "save" methods have the same signature: 
save(ChunkPos)

**Comment by kashike** [comment]
- [x] `func_219112_a`: `save` &rarr; `saveIfDirty`
