### ISSUE TITLE
SelectionContext -> EntityContext

### ISSUE THREAD

**Issue by Cadiboo** [ModCoderPack/MCPBot-Issues#844]
- [ ] `net.minecraft.util.math.shapes.ISelectionContext` -> `net.minecraft.util.math.shapes.IEntityContext`
- [ ] `net.minecraft.util.math.shapes.EntitySelectionContext` -> `net.minecraft.util.math.shapes.EntityContext`

This class is used in many more places than just selection including in `Block#getCollisionShape` and entity movement calculations.

**Comment by kashike** [comment]
:-1: for  `net.minecraft.util.math.shapes.ISelectionContext` &rarr; `net.minecraft.util.math.shapes.IEntityContext` - there's nothing limiting implementations to just `Entity`. `EntitySelectionContext` is the `Entity`-specific implementation.

**Comment by Cadiboo** [comment]
`ISelectionContext` contains the method `isSneaking` and the factory method `forEntity`. I don't think its really applicable to anything except entities. However, my main problem is with it being called `Selection` when its used for much more than just selection

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
