### ISSUE TITLE
ChickenModel fields

### ISSUE THREAD

**Issue by ghost** [ModCoderPack/MCPBot-Issues#846]
- [ ] `field_78137_g` in `net.minecraft.client.renderer.entity.model.ChickenModel`: `field_78137_g` -> `bill`
- [ ] `field_78143_h` in `net.minecraft.client.renderer.entity.model.ChickenModel`: `field_78143_h` -> `chin`
- [ ] `field_78140_b` in `net.minecraft.client.renderer.entity.model.ChickenModel`: `bill` -> `body`
- [ ] `field_78141_c` in `net.minecraft.client.renderer.entity.model.ChickenModel`: `chin` -> `rightLeg`
- [ ] `field_78138_d` in `net.minecraft.client.renderer.entity.model.ChickenModel`: `body` -> `leftLeg`

**Comment by williewillus** [comment]
You can name these yourself if they have no mcp name, this repo is for disputing existing mcp names
