### ISSUE TITLE
MCP | Source code is full of yellow errors.

### ISSUE THREAD

**Issue by JavasPichu** [ModCoderPack/MCPBot-Issues#854]
I don't know the name for the errors that are yellow, but the thing is. From the block to the world and down, it has yellow errors.

Is there anyway I can fix this? If you want to private message me and assist me on Discord please contact me there. objectDaniel#3408

**Comment by JoJoDeveloping** [comment]
A 'yellow error' is a warning. They aren't errors. They don't inhibit compilation. They exist because your IDE does not like the code that much. So won'tfix since it's intended or at least expected.

**Comment by JavasPichu** [comment]
> A 'yellow error' is a warning. They aren't errors. They don't inhibit compilation. They exist because your IDE does not like the code that much. So won'tfix since it's intended or at least expected.

So I don't need to really worry about them right now?

**Comment by JoJoDeveloping** [comment]
No...
Why did you even ask if they aren't causing problems?

**Comment by JavasPichu** [comment]
> No...
> Why did you even ask if they aren't causing problems?

I was just worried about them, sorry if it was kinda unnecessary. I didn't know at first to be honest.
