### ISSUE TITLE
Rename SpawnerAnimals to WorldSpawner

### ISSUE THREAD

**Issue by gabizou** [ModCoderPack/MCPBot-Issues#86]
SpawnerAnimals is currently used for spawning mobs in chunks during population and chunks for normal world spawning. This should be accurately named as opposed to how it's currently named for "animals".

**Comment by LexManos** [comment]
WorldMobSpaner?

**Comment by gabizou** [comment]
But the animals aren't extending `EntityMob` either. Maybe `WorldCreatureSpawner`?

**Comment by kashike** [comment]
```java
        addMapping(EntityLiving.class, "Mob", 48);
        addMapping(EntityMob.class, "Monster", 49);
```

Maybe now is a good time to:
`EntityLivingBase` -> `EntityLiving`
`EntityLiving` -> `EntityMob`
`EntityMob` -> `EntityMonster`
?

**Comment by LexManos** [comment]
For this class itself, Mob just refers to the generic programming/gaming term Mob not specifically anything.

**Comment by gabizou** [comment]
right, which would make sense though for anyone looking at it "Oh, this is capable of spawning all creatures, not just mobs." Remember, there's some certain level of intuition when it comes to names like this. Previously, the uninitiated would think `SpawnerAnimals` would just spawn animals, and not monsters as well.

**Comment by LexManos** [comment]
WorldEntitySpawner?

**Comment by Zidane** [comment]
WorldEntitySpawner would be fine to me.

**Comment by kashike** [comment]
`WorldEntitySpawner` works

**Comment by LexManos** [comment]
1.9:
net/minecraft/world/SpawnerAnimals - > WorldEntitySpawner
