### ISSUE TITLE
MovingObjectPosition & MovingObjectType

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#87]
`MovingObjectPosition` -> `RayTraceHit`
`MovingObjectPosition.MovingObjectType` -> `Type`, `TraceType`

**Comment by LexManos** [comment]
1.9:
net/minecraft/util/MovingObjectPosition -> RayTraceResult
net/minecraft/util/MovingObjectPosition$MovingObjectType -> RayTraceResult$Type
