### ISSUE TITLE
"Use in forge gradle" button on website shows incorrect settings

### ISSUE THREAD

**Issue by saviski** [ModCoderPack/MCPBot-Issues#870]
Foe example, for *mcp_snapshot-20200207-1.15.1.zip* the website suggests you to do the following:

Add or edit this info in your build.gradle file:
```
minecraft {
    mappings = 'snapshot_20200207'
}
```

I have added it as 

```
mappings channel: 'snapshot', version: '20200207'
``` 

because the format is different

![image](https://user-images.githubusercontent.com/1424721/74075914-db19c080-49f3-11ea-96bd-d3f8005deb2d.png)

but it does not work, I was able to make it work by changing it to:

```
minecraft {
    mappings channel: 'snapshot', version: '20200207-1.15.1'
}
```

![image](https://user-images.githubusercontent.com/1424721/74075860-99891580-49f3-11ea-9e4d-de5641643b6b.png)

**Comment by naqaden** [comment]
This threw me off for a while. It seems as of MC 1.13, the MC version has to be appended to the MCP version to be found on Forge's Maven.
