### ISSUE TITLE
ItemInWorldManager rename

### ISSUE THREAD

**Issue by gabizou** [ModCoderPack/MCPBot-Issues#88]
I'm sure that the original name made sense, but at this point, it doesn't really quite make sense for what purpose it serves. It manages an `EntityPlayerMP`'s state for game mode and various other utility methods.
Suggested Names:
- `PlayerInteractionManager`
- `PlayerInteractManager`

**Comment by Unh0lyTigg** [comment]
I vote for PlayerInteractionManager

**Comment by kashike** [comment]
Another for `PlayerInteractionManager`, it manages a players interaction.

**Comment by LexManos** [comment]
1.9:
net/minecraft/server/management/ItemInWorldManager -> PlayerInteractionManager
