### ISSUE TITLE
https://bitbucket.org/ProfMobius/mcpbot

### ISSUE THREAD

**Issue by Zaxar163** [ModCoderPack/MCPBot-Issues#888]
This is inaccessible...

**Comment by simon816** [comment]
>Bitbucket no longer supports Mercurial repositories.

Luckily [ArchiveTeam](https://archiveteam.org/index.php?title=Bitbucket) were there to save us.

Source code zip: https://web.archive.org/web/20200703031830/https://bitbucket.org/ProfMobius/mcpbot/get/14dda266aaba.zip

(part of this collection: https://archive.org/details/archiveteam_bitbucket_20200703055015_7bdfe8da)

**Comment by simon816** [comment]
>Bitbucket no longer supports Mercurial repositories.

Luckily [ArchiveTeam](https://archiveteam.org/index.php?title=Bitbucket) were there to save us.

Source code zip: https://web.archive.org/web/20200703031830/https://bitbucket.org/ProfMobius/mcpbot/get/14dda266aaba.zip

(part of this collection: https://archive.org/details/archiveteam_bitbucket_20200703055015_7bdfe8da)

**Comment by bspkrs** [comment]
https://github.com/ModCoderPack/mcpbot
