### ISSUE TITLE
Pls make 1.16.3-1.16.4 support!

### ISSUE THREAD

**Issue by MrScautHD** [ModCoderPack/MCPBot-Issues#890]
Pls make 1.16.3-1.16.4 support!

**Comment by FinnT730** [comment]
The person doing the bot has no time on their hands. And they are the only ones knowing how to put in new names.

Therenis another project called MMMS in the works, which will replace the mcpbot

**Comment by MrScautHD** [comment]
@FinnT730 can you pls send me a link to MMMS?

**Comment by FinnT730** [comment]
It so still in the works, and not done yet.
It is an project made by one person (mainly 1 person, for now) and when it is done, it will be used.
