### ISSUE TITLE
MCP Won’t Decompile 

### ISSUE THREAD

**Issue by Pixchure** [ModCoderPack/MCPBot-Issues#891]
So I was trying to decompile MCP to make a mod and I came across an issue. MCP just wouldn’t decompile I tried the decompile.bat script in MCP 918 then nothing happened. It’s been decompiling for about a day at this point. No error messages or anything. Does it normally take this long or did I break something?

**Comment by FinnT730** [comment]
Mcp is dead. Has been for the last 4 years.
Use Forge.

**Comment by Pixchure** [comment]
> Mcp is dead. Has been for the last 4 years.
> 
> Use Forge.

Oh wait what. Sorry I didn't know it was dead
