### ISSUE TITLE
MCPBot down?

### ISSUE THREAD

**Issue by dxxxxy** [ModCoderPack/MCPBot-Issues#893]
`Etag download for http://export.mcpbot.bspk.rs/versions.json failed with code 500`
MCPBot appears to be down. 500 Internal Server Error.

**Comment by ghost** [comment]
yep its down for me too

**Comment by bspkrs** [comment]
Most likely related to a python2 update I did earlier this week. I’ll look into it tomorrow.

**Comment by rsmeowry** [comment]
any ideas when it will be back up?

**Comment by bspkrs** [comment]
Well, there is good news and bad news. The good news is that versions.json will work again because luckily I started generating the static file a while back. The bad news is that the rest of the site which is non-static will continue to be broken. This will not be resolved any time soon.
