### ISSUE TITLE
MCP Not Working!

### ISSUE THREAD

**Issue by AwesomeKids652** [ModCoderPack/MCPBot-Issues#894]
**MCP Not Working!**
this has been a issue for me in ubuntu, not in windows! i even downloaded the natives but still its saying 'Couldn't find lwjgl.so in <path censcored>'
i don't know why it is happening.

**Comment by FinnT730** [comment]
MCP is dead.
Use something like Forge.
If you want to make a hacked client, then that is not supported by TOS, and no one will help.
