### ISSUE TITLE
I need to know a thing

### ISSUE THREAD

**Issue by LilNiffer** [ModCoderPack/MCPBot-Issues#897]
I just wanna know if the non-static site is ever going to be fixed because I'm trying to backport a mod and I need the website to use the method I'm learning because no one wants to teach me or help me learn anything.

**Comment by bspkrs** [comment]
Fixed? The VM that backed mcpbot.bspk.rs (and consequently the dynamic website) was decommissioned back in November 2021 when it was determined that MCPBot had been surpassed by a more modern and sustainable process for mapping from obfustated names to human-readable names (that I’m pretty sure means the mappings from Mojang are what we use now). I’m not sure what you could possibly need from the website that you can’t get via the artifacts that still exist in the Forge nexus repository, and also in the MCP Mapping Archive, another git repo under this same github group that contains an archive of all the artifacts that were ever uploaded to the Forge nexus repository. 

If I’m somehow wrong and you need something that the website provided that is not the mappings archive or some other artifact that used to be provided by the website, please elaborate.

**Comment by LilNiffer** [comment]
I just saw this so sorry. there aren't too many tutorials for backporting and the only one I could find involved this. I'm not the greatest at this whole code thing, but there are people who only play up to 1.12.2 and I really want them to be able to enjoy this one mod that the devs don't feel like backporting. Honestly I don't believe this port is even possible but I try nonetheless.

**Comment by LilNiffer** [comment]
hours of time went down the drain when I found this obstacle.

**Comment by Pokechu22** [comment]
If your goal is to just specify a version of the mappings, they're just based on the date and you should be able to figure out the pattern fairly quickly.  You can also try an [archived copy of the site](https://web.archive.org/web/20200328074516/http://export.mcpbot.bspk.rs/).

1.12.2 is still quite old and most people aren't supporting it anymore.  If you want to try to backport something to it, you certainly can attempt it, but most people have given up on it so there's not much help available.
