### ISSUE TITLE
Redstone methods in Block are weird

### ISSUE THREAD

**Issue by Wuerfel21** [ModCoderPack/MCPBot-Issues#9]
in particular func_180656_a(isProvidingWeakPower) and func_176211_b(isProvidingStrongPower).
They have a is infront of them, but return the strength(int), which is confusing.
My proposal:
func_180656_a>getWeakPower
func_176211_b>getStrongPower

**Comment by jk-5** [comment]
I wanted to change these already but did not do that because the current names are well known. I do agree on changing them

**Comment by bspkrs** [comment]
Will be fixed in 1.8.8
