### ISSUE TITLE
WorldProvider -> Dimension

### ISSUE THREAD

**Issue by Zidane** [ModCoderPack/MCPBot-Issues#90]

**Comment by mcsnetworks** [comment]
No description needed...

**Comment by Zidane** [comment]
```WorldProvider``` -> ```Dimension```
```WorldProviderSurface``` -> ```DimensionOverworld```
```WorldProviderHell``` -> ```DimensionNether```
```WorldProviderEnd``` -> ```DimensionEnd```

OR

```WorldProvider``` -> ```Dimension```
```WorldProviderSurface``` -> ```DimensionSurface```
```WorldProviderHell``` -> ```DimensionHell```
```WorldProviderEnd``` -> ```DimensionEnd```

**Comment by LexManos** [comment]
Maybe in 1.10... This is a core concept/name in much of modding.

**Comment by kashike** [comment]
- [x] `net/minecraft/world/DimensionType` → `net/minecraft/world/dimension/DimensionType`
- [x] `net/minecraft/world/WorldProvider` → `net/minecraft/world/dimension/Dimension`
- [x] `net/minecraft/world/WorldProviderEnd` → `net/minecraft/world/dimension/EndDimension`
- [x] `net/minecraft/world/WorldProviderNether` → `net/minecraft/world/dimension/NetherDimension`
- [x] `net/minecraft/world/WorldProviderOverworld` → `net/minecraft/world/dimension/OverworldDimension`
