### ISSUE TITLE
Entities

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#92]
Maybe now is a good time to rename some entity classes?
`EntityLivingBase` -> `EntityLiving`
`EntityLiving` -> `EntityMob`
`EntityMob` -> `EntityMonster`

**Comment by gabizou** [comment]
Just saying, this is likely to wreck havoc with mods extending either or and expecting different outcomes.

**Comment by kashike** [comment]
Yeah, I'm aware - I'm just throwing this out here because it's a good time

**Comment by LemADEC** [comment]
Mob is short for Monster, I'm not keen on replacing a confusion with another.

**Comment by ThomasRules2000** [comment]
What about `EntityMob` -> `EntityHostile`
