### ISSUE TITLE
Snooper

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#95]
`IPlayerUsage` -> `ISnoopable`?
`PlayerUsageSnooper` -> `Snooper`

Perhaps its own package, unless it counts as "profiling".

**Comment by darkevilmac** [comment]
Sounds like a good idea to me at least, IPlayerUsage doesn't really match considering it's referred to as snooper in game.

**Comment by Minecrell** [comment]
+1 for a separate package, doesn't really make sense there IMO.

**Comment by LexManos** [comment]
1.9:
net/minecraft/profiler/IPlayerUsage -> ISnooperInfo
net/minecraft/profiler/PlayerUsageSnooper -> Snooper
