### ISSUE TITLE
net/minecraft/command/IAdminCommand

### ISSUE THREAD

**Issue by matthewprenger** [ModCoderPack/MCPBot-Issues#98]
Don't really have a good name for this but IAdminCommand doesn't make a whole lot of sense. Implementations of this interface (currently only one in MC) handle actually notifying operators when certain command events happen.

**Comment by kashike** [comment]
`ICommandListener`
`ICommandNotifier`

**Comment by matthewprenger** [comment]
I don't think ICommandListener makes sense for this class. ICommandNotifier sounds good though.

**Comment by The-Fireplace** [comment]
I like ICommandNotifier

**Comment by LexManos** [comment]
1.9:
net/minecraft/command/IAdminCommand -> ICommandListener
